### ISSUE TITLE
OMEdit crashes when moving a graphical model

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OpenModelica#10004]
### Description

I created a simulation example that crashes, every time I move one particular model in:

[Conveyer_crash.mo.zip](https://github.com/OpenModelica/OpenModelica/files/10344823/Conveyer_crash.mo.zip)

### Steps to Reproduce

- Open file `Conveyer_crash.mo` in OMEdit.
- Move the red machine icon in the Diagrams View

![image](https://user-images.githubusercontent.com/4184218/210573959-25a524a7-8b91-4b1c-9a95-d6b63483066d.png)

=> OMEdit crashes

### Screenshots

![image](https://user-images.githubusercontent.com/4184218/210574262-7c4f9d8a-b2d5-4254-bf75-a329c8841978.png)

### Version and OS

```
Connected to OpenModelica 1.21.0~dev-177-g115eb96 built for Ubuntu 20.04.5 LTS.
The running OS is Linux Mint 20.3 on x86_64.
```

Also install version 3.0.0 of the systems library `ElectroMechanicalDrives`.

**Comment by casella** [comment]
@christiankral thanks for reporting, @adeas31 will look into it ASAP.

**Comment by casella** [comment]
@christiankral this issue is now resolved with the new instance-based GUI. Go to Tool | Options | General and tick Enable Instance API, then restart OMEdit.

Until we release 1.22.0 this autumn, I'd suggest to use the latest nightly build, since this feature is still being actively debugged (20+ issues [resolved](https://github.com/OpenModelica/OpenModelica/issues?q=is%3Aissue+label%3A%22COMP%2FGUI%2FInstBased+Interface%22+milestone%3A1.22.0+is%3Aclosed) since the 1.21.0 release)

**Comment by christiankral** [comment]
@casella Very good. I enabled the new instance-based GUI and double checked this issue. It all works fine now.

**Comment by casella** [comment]
It's still not perfect, so you may experience other (hopefully small) issues. Please post tickets if you do.
