### ISSUE TITLE
Causalization in component-based ScalableTestSuite models scales as O(N^3)

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10131]
Please check the TransmissionLineModelica, OneDHeatTransfer_TI_Modelica, and OneDHeatTransfer_TT_Modelica in the [ScalableTestSuite_NB report](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/ScalableTestSuite_NB.html). The backend time scales as O(N^3) for larger models, due to Causalization times going through the roof.

These methods are implemented in MetaModelica, which is possibly not as efficient as C. However, if you compare the backend performance of the same models in the [ScalableTestSuite_OB](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_OB/ScalableTestSuite_OB.html) report, it is apparent that the scaling is more favourable, even though still superlinear.

Both the OB and NB matching algorithms are written in MetaModelica. Apparently, the NB one has some very serious data handling inefficiency somewhere. This could be easily identified by profiling, then we could ask @perost to have a look and help fixing the inefficient parts of the code.

Alternatively, both methods could be implemented in C, which will for sure provide substantial performance improvement.

**Comment by casella** [comment]
Link to [DistributionSystemModelica_N_10_M_10](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/files/ScalableTestSuite_NB_ScalableTestSuite.Electrical.DistributionSystemDC.ScaledExperiments.DistributionSystemModelica_N_10_M_10.err) heavy-test result.

**Comment by casella** [comment]
@mahge, could you please carry out some profiling analysis similar to what you did in #11302, so that @phannebohm could try to fix this issue as well?

**Comment by mahge** [comment]
This is specifically for the `OneDHeatTransfer_TI_Modelica` models even though it will most probably help in almost every other case.

The translation spends a lot of time in causalization module as you mentioned. Around 90% of the time spent with-in the causalization module is spent in the function `NBSlice.getDependentCrefIndicesPseudoArray`

https://github.com/OpenModelica/OpenModelica/blob/ff6287bb30b3ac8c3a39b7cef31e4aca64107439/OMCompiler/Compiler/NBackEnd/Util/NBSlice.mo#L276

There is a loop at the end of this function 
https://github.com/OpenModelica/OpenModelica/blob/ff6287bb30b3ac8c3a39b7cef31e4aca64107439/OMCompiler/Compiler/NBackEnd/Util/NBSlice.mo#L333-L336

it is this loop that takes all the computation time in the function and is also responsible for **1/3 of the total translation time**. 

The loop operates on list of lists (actually an array of lists but for this discussion it is easier to thing of it as a list of lists). We can refer to them as the main-list and the sub-lists. The loop goes through each sub-list of the main-list, makes each sub-list unique (removes duplicates) and then sorts each sub-list. 

Before considering anything else it is good to have an idea of what inputs the computation gets. The table below shows the name of the model, the size of the main-list (the number of lists), the size of each sub-list, and finally the total number of elements processed by the loop :

<html>
<body>

Model | size of main-list | size of each sub-list | total (main-list * sub-list)
-- | --| -- | -- 
OneDHeatTransfer_TI_Modelica_80 | 79 | 158 | 12,482
OneDHeatTransfer_TI_Modelica_160 | 159 | 318 | 50,562
OneDHeatTransfer_TI_Modelica_320 | 319 | 638 | 203,52
OneDHeatTransfer_TI_Modelica_640 | 639 | 1278 | 816,642
OneDHeatTransfer_TI_Modelica_1280 | 1279 | 2558 | 3,271,682

</body>
</html>

Even if we consider sorting and 'unique'ing the lists takes `O(N)` time (it of course will be higher than that but even if we assume that), the number of elements to be processed grows as `O(M^2)` where M is the number of `nodes` in the Modelica model. 

The models themselves do not seem to grow quadratically however since the NF as well as the old Backend seem to handle them fine. However, this might be general intrinsic issue with the array matching algorithms which the NB implements. If not then it might be something that can be restructured to be processed in some other way. I am not sure what the actual entries in this two-dimensional list of integers represents.  

----------------------------------------------------------------------

Another main but straightforward improvement we can do is reversing the unique -> sort process. From what I can tell our `List.unique` implementation is O(N^2). This is needed because the function does not require that the given input list is sorted already. There is another function `List.sortedUnique` which should operate in O(N) time on a sorted list. I did a quick test with it and it does seem to help. The cahnge is something like this
```diff
    for i in 1:arrayLength(indices) loop
-      indices[i] := List.sort(List.unique(indices[i]), intLt);
+      indices[i] := List.sortedUnique(List.sort(indices[i], intLt), intEq);
    end for;
```` 

In the table below you can see the timing results for the two cases (unique followed by sort VS sort followed by unique). The total translation time is shown but it also shows the time taken in the causalize module separately (Note that the causalize module is run twice, however the second call seems to be more expensive than the first so that is what is shown here. They both show similar improvements though. )

<html>
<body>

Model | unique -> sort translation | unique -> sort causalize | sort -> unique translation | sort -> unique causalize
-- | --| -- | -- | --
OneDHeatTransfer_TI_Modelica_80 | 2.401 | 0.1687 | 0.1418 | 2.329
OneDHeatTransfer_TI_Modelica_160 | 3.588 | 0.8508 | 3.177 | 0.5559
OneDHeatTransfer_TI_Modelica_320 | 10.48 | 5.175 | 6.687 | 3.06
OneDHeatTransfer_TI_Modelica_640 | 51.87 | 32.51 | 20.51 | 12.06
OneDHeatTransfer_TI_Modelica_1280 | 354.7 | 233.6 | 84.14 | 56.74
 
</body>
</html>

This is already a good improvement from one line of change but, of course, the core of the issue still remains and the whole thing seems to scale somewhat quadratically.

**Comment by casella** [comment]
Something was improved between Nov 17 and Dec 13, see [regression report](https://libraries.openmodelica.org/branches/history/newInst-newBackend/2023-11-17%2019:44:19..2023-12-23%2003:15:17.html): three more `TransmissionLineModelica` simulated successfully, most likely due to a reduction in compile time that avoided timeout. Now the Causalize method scales with O(N^2) for `TransmissionLineModelica` models.

**Comment by casella** [comment]
Looking at the latest [LargeTestSuite_NB report](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html), this problem is now definitely solved.
