### ISSUE TITLE
omc generats spurious equations with expandable connectors that contain a connector with a flow variable

### ISSUE THREAD

**Issue by albertoleva** [OpenModelica/OpenModelica#10291]
### Description

In the presence of an expandable connector of type ec containing a connector c that in turn contains a flow variable f, when two connectors of type ec (ec1 and ec2 to name them) are connected together, the two equations

ec1.c.f = 0
ec2.c.f = 0

are generated, which should not happen.

### Steps to reproduce

Run model Examples.Example_01_Gen_pinA_Usr_pinA in the package in the attached zip to trigger the error
Model Examples.Example_01_reworked_by_hand, where the spurious equations were removed by hand, conversely works.

### Expected behavior

As Examples.Example_01_reworked_by_hand.

### Additional files

See below.

### Version and OS

 - OpenModelica 1.20.0
 - MSL 4.0
 - OS ubuntu 22.04 LTS
[Expandable_MWEs.zip](https://github.com/OpenModelica/OpenModelica/files/10861447/Expandable_MWEs.zip)

**Comment by perost** [comment]
This doesn't seem to have anything to do with expandable connectors, you get the same issue if you change the expandable connector to a normal connector:
```Modelica
connector Bus
  Modelica.Electrical.Analog.Interfaces.PositivePin a;    
end Bus;
```
The equations are generated because `G.a` and `U.a` are only connected as outside connectors, but not inside (see [specification](https://specification.modelica.org/master/connectors-and-connections.html#inside-and-outside-connectors). An unconnected inside flow variable will cause a zero-equation to be generated, i.e.:
```Modelica
connector C
  Real e;
  flow Real f;
end C;

model A
  C c1;
  C c2;
equation
  connect(c1, c2);  // Connecting c1 and c2 as outside connectors
end A;

model M
  A a;
end M;
```
will generate the equations:
```Modelica
a.c1.e = a.c2.e;
(-a.c1.f) - a.c2.f = 0.0;
a.c1.f = 0.0;
a.c2.f = 0.0;
```
while
```Modelica
connector C
  Real e;
  flow Real f;
end C;

model A
  C c1;
  C c2;
end A;

model M
  A a;
equation
  connect(a.c1, a.c2);  // Connecting c1 and c2 as inside connectors
end M;
```
gives
```Modelica
a.c1.e = a.c2.e;
a.c2.f + a.c1.f = 0.0;
```
So I'm going to close this since it looks like a modelling issue rather than a compiler issue.
