### ISSUE TITLE
omc should print notifications on stderr

### ISSUE THREAD

**Issue by fedetftpolimi** [OpenModelica/OpenModelica#10327]
### Description

The command ```omc Model.mo``` should produce a flattened Model on standard output. However, some internal debug messages such as
```Notification: Automatically loaded package Modelica 3.2.3 due to uses annotation from HeatsinkBlocks.```
are also printed on standard output, making it difficult to separate from the actual flattened model.
I think omc should print those messages on stderr.

### Steps to Reproduce

Run omc from the command line on a model that contains ```annotation(uses(Modelica(version = "3.2.3")));```

### Version and OS

omc version OpenModelica 1.21.0~dev-268-g59d7f9f
Ubuntu Linux

**Comment by casella** [comment]
MWE:

```modelica
model MWE
  Modelica.Units.SI.Length L = 1;
annotation(uses(Modelica(version = "4.0.0")));
end MWE;
```
running
```
omc MWE.mo
```
produces the following output on stdout
```
class MWE
  Real L(quantity = "Length", unit = "m") = 1.0;
end MWE;
Notification: Automatically loaded package Modelica 4.0.0 due to uses annotation from MWE.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation from Modelica.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation from Modelica.
```
The notifications should be printed on stderr, so that the flat modelica code is only output on stdout, as claimed by the omc documentation.

@perost, can you please fix that? Otherwise our MARCO parser has problems parsing the notifications. Thanks!

**Comment by perost** [comment]
As always things are more difficult than they should be. Printing the messages to stderr is trivial, but anything we print to stderr ends up at the top when redirecting to a file. That's fine if you want to ignore stderr, but it breaks all of our testing. 

I'm not sure why that happens, it doesn't usually do that so we must be messing up the standard streams somewhere in the compiler for some reason. I will see if anyone else has a clue about what's going on, otherwise plan B would be to add a flag to disable the error messages.

**Comment by perost** [comment]
Turns out we had to flush before printing the error messages to sync the streams, now it seems to work as intended.

**Comment by casella** [comment]
Thanks @perost!

**Comment by fedetftpolimi** [comment]
Thanks!
