### ISSUE TITLE
OM does not pass second record to function through the C Interface

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10444]
### Description

Modelica and modelica tools can be useful well beyond the applications for which it is designed for.
I have an application that requires very long and structurally complicated algorithms (it involves electric vehicles running in motorways, which occasionally stop to recharge from the grid).

Unfortunately modelica tools, being modelica language equation oriented, analyse algorithms in terms of equation/variable balance, and in case find imbalance, they issue messages very difficult to interpret: they just list many rows of algorithm code where the imbalance is found.

To solve this I decided to resort to C functions through the C interface. The idea is to put important imperative parts of the code in what is born for imperative programming: C.

Unfortunately, returning multiple values through C-structs (which map into records in Modelica), seems not to work, but this is not critical for me. To overcome the difficulty of returning records/structs, I decided to output the struct/record as a parameter passed to the C function by reference, as proposed also in the MS.

The example TestMdlStruct in the following package
[TestCInterface.mo.txt](https://github.com/OpenModelica/OpenModelica/files/11063994/TestCInterface.mo.txt)
does this, and works very well in Dymola.

Unfortunately it does not compile in OM giving the error message shown in the follwing screenshot:
![image](https://user-images.githubusercontent.com/7373030/227575501-212af98b-6ff4-4534-8e71-b1b60d690312.png)

I.e., it seems that OM "forgets" to add the second struct to the passed parameters.

### Steps to Reproduce
1. download and load TestCInterface.mo
2. download and put somewhere the following C file: [ExtFunStruct.c.txt](https://github.com/OpenModelica/OpenModelica/files/11064210/ExtFunStruct.c.txt)
4. in the annotation of ExtFunStruct inside TesstCInterface.mo change the full pathname of ExtFunStruct.c into the actual pathname where OM will find it
5. open and run TestMdlStruct

### Expected Behavior
The supplied example should compile and run correctly.

### Version and OS

OM 1.20.0
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by mahge** [comment]
```mo
  function ExtFunStruct "two real inputs and outputs"
    record R
      Real x1, x2;
    end R;
    input  R xr;
    output R yr;

    external "C"
    annotation ( Include = "#include \"ExtFunStruct.c\"");
  end ExtFunStruct;
```

The [Modelica specification: 12.9.2 Return Type Mapping](https://specification.modelica.org/maint/3.5/functions.html#return-type-mapping
)  says

> If there is a **single output parameter and no explicit call of the external function**, or if there is an explicit external call in the form of an equation, in which case the LHS must be one of the output parameters, **the external routine is assumed to be a value-returning function**. 

So OpenModelica is correct in assuming that the external function has the form

```c
R ExtFunStruct(R* x);
```

that is, it is a value returning function (non-void) with one input parameter.


If you want to keep the current form of your external C code, you have to explicitly tell the compiler what format to expect:

```mo
  function ExtFunStruct "two real inputs and outputs"
    record R
      Real x1, x2;
    end R;
    input  R xr;
    output R yr;

    external "C" ExtFunStruct(xr,yr);
//               ^^^^^^^^^^^^^^^^^^^
    annotation ( Include = "#include \"ExtFunStruct.c\"");
  end ExtFunStruct;
```

**Comment by mahge** [comment]
> Before writing this ticket I had tried
> 
> ```
>   record R
>     Real x1, x2;
>   end R;
>   input  R xr;
>   output R yr;
>   external "C" yr=ExtFunStruct2(xr);
>     Include = "#include <\"ExtFunStruct2.C\"");
> ```
> 
> with ExtFunStruct2.C being:
> 
> ```
> struct Str{
>   double x1, x2;
> } ;
> 
> 
> struct Str ExtFunStruct2(struct Str *inS){
>     struct {double x1, x2;}outS;
> 	outS.x1=inS->x1*sin(inS->x2);
> 	outS.x2=inS->x1*cos(inS->x2);
>  return outS;
> }
> ```
> 
> but did not work, and I did not understand why.

I just tried this and indeed it does not work. Unfortunately, this is tricky issue and I am not sure how to make it work right now without additional support from Modelica itself. 

The issue is that OpenModelcia does not really know the type of your C struct at compile time (`Str` in this case). What it does is create an equivalent struct in its own code based on the Modelica record declaration. Right now, this record will be called `TestCInterface_ExtFunStruct_R_external` based on its qualified path. It has the same members and layout as your external C struct.  

This is where the problem begins. When a struct is returned from your external function (of type Str), OpenModelica will try to assign it to its own `struct` instance of type `TestCInterface_ExtFunStruct_R_external`. Unfortunately (fortunately?) the C compiler does not allow this because as far as it is concerned these are two different struct types. They have the same members and layout but are two different declarations/types (Modelica would allow this under "plug-compatibility" which is another flexibility that causes issues). 

The reason it works when it is passed as an "output parameter" instead (i.e., the void type, two argument function) is because in that case the records are passed by pointers (unlike the return by value in the previous case). In this case the C compiler allows this with a warning. You probably have seen this warning already. 

So I think, short of tricks (e.g., `memcpy` instead of assignment. Maybe that's what Dymola does but it won't work once you have array members) OR a considerable rewriting of how we copy records around, there is not much we can do about this right now. 

The good news is that there is always the second alternative which is better for readability, consistency, and possibly safer because it avoids returning a local struct (which can potentially have array members and other nested records.) 

> I was unable to find the solution you showed (external "C" ExtFunStruct(xr, yr);), because the documentation somewhow confused me, I don't know whether it is unclear of I was not brilliant enough. Thank you for showing me the correct syntax.

The documentation is definitely confusing and lacks enough examples to show the use cases. You have to read multiple times to understand what it is trying to convey. So the confusion is perfectly understandable.
