### ISSUE TITLE
Instantiation of models failing with no error message

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#10479]
### Description

Some models from our BRSL library can no longer be instantiated.  The error message is:
```
Internal error Instantiation of Rexroth_BRSL_Test.Generic_Test.Hydraulics.DirectionalValves.DirectionalValve42_Easy_TC01 failed with no error message.
```

### Steps to Reproduce
Load the package ```Rexroth_BRSL\package.mo```
Load the package ```Rexroth_BRSL_Test\package.mo```
Simulate the model ```Rexroth_BRSL_Test.Generic_Test.Hydraulics.DirectionalValves.DirectionalValve42_Easy_TC01```

### Version and OS

 - OpenModelica Version:  v1.22.0-dev-3-ga510dec0d6 
 - OS: Windows 10, 64 bit
 - BRSL 2.3.0

**Comment by perost** [comment]
#10486 should fix the issue. However, as assert is now triggered during compilation when evaluating the `calcFlow` function:
```
Warning: assert triggered: Error in Rexroth_BRSL.Generic.Hydraulics.Valves.Internal.calcFlowTableNegative volume flow value detected at element71Value:-0
```
I'm not sure if this is an issue with OMC or with the model, but it only happens when `calcFlow` is called with `OpeningCharacteristic.Circular`. It seems that part of the function wasn't used before since the issue wasn't due to a regression in OMC but rather the library changing, so perhaps there's some issue with it?

**Comment by abuntrock** [comment]
@perost The model `Rexroth_BRSL_Test.Generic_Test.Hydraulics.DirectionalValves.DirectionalValve42_Easy_TC01` now simulates successfully with todays nightly. Thanks a lot.
The warning you mentioned has nothing to do with the OMC but rather our library.
