### ISSUE TITLE
Building with NF does not propagate "protected" to isProtected attribute inside Model_init.xml

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#10578]
### Description

When we build with NF the protected attribute is not propagated to the ScalarVariable inside Model_init.xml. 

### Steps to Reproduce

For example run testsuite/simulation/modelica/others/world.mos with NF and OF and see world_init.xml

NF:
```xml
<ScalarVariable
    name = "world.x_label.cylinders[1].length"
    valueReference = "1151"
    description = "Length of visual object"
    variability = "continuous" isDiscrete = "false"
    causality = "local" isValueChangeable = "false"
    alias = "noAlias"
    classIndex = "151" classType = "rAlg"
    isProtected = "false" hideResult = "false" initNonlinear = "false"
    fileName = "C:/Users/adrpo33/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Utilities/Internal.mo" startLine = "33" startColumn = "5" endLine = "33" endColumn = "74" fileWritable = "true">
    <Real fixed="true" useNominal="false" unit="m" />
  </ScalarVariable>
```
OF:

```xml
  <ScalarVariable
    name = "world.x_label.cylinders[1].length"
    valueReference = "1151"
    description = "Length of visual object"
    variability = "continuous" isDiscrete = "false"
    causality = "local" isValueChangeable = "false"
    alias = "noAlias"
    classIndex = "151" classType = "rAlg"
    isProtected = "true" hideResult = "" initNonlinear = "false"
    fileName = "C:/Users/adrpo33/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Utilities/Internal.mo" startLine = "33" startColumn = "5" endLine = "33" endColumn = "74" fileWritable = "true">
    <Real fixed="true" useNominal="false" unit="m" />
  </ScalarVariable>
```

### Expected Behavior

We should have `isProtected=true` attribute inside `world_init.xml` for protected elements when building with NF.

**Comment by perost** [comment]
The reason is that the `visxml` debug flag is turned on in that test. With the NF this triggers the `VisualXML` module to change protected visualization parameters to public:
https://github.com/OpenModelica/OpenModelica/blob/34856e7d4f39b071d86fa5ab6510d485b6363a82/OMCompiler/Compiler/BackEnd/VisualXML.mo#L225-L236

When using the OF it doesn't find any visualization variables, I guess the OF doesn't add the type information to the element sources that the `VisualXML` module uses to identify them. So I'm not sure what to do in this case, as far as I can see it's actually the OF that doesn't work as intended in this case.

**Comment by adrpo** [comment]
Geez, OK. Then I guess we can close this ticket. We don't care about the old front-end. I changed that test to simulate with OF and add `simflags="-emit_protected -ignoreHideResult"` so is fixed.
