### ISSUE TITLE
Use official ClaRa release for package manager

### ISSUE THREAD

**Issue by HSchatzTLK** [OpenModelica/OpenModelica#10667]
As far as I understand the repository https://github.com/ClaRaLibrary/ClaRa is used for testing compatability of the ClaRa library as well as the OM package manager.

As I've mentioned in [9249](https://github.com/OpenModelica/OpenModelica/issues/9249#issuecomment-1540024979), this repository is maintained by an anonymous person downloading the libraries from the official sites and uploading them to GitHub.

Until there's an official repository for ClaRa I would recommend downloading ClaRa from https://www.claralib.com/. At least for the package manager. Using this source for automated testing might be impossible due to the required user interaction, as already mentioned by @AnHeuermann.

**Comment by rfranke** [comment]
Referring to testing of ClaRa, most examples fail with the C++ runtime due to lack of const qualifiers for array inputs to external functions, see: https://libraries.openmodelica.org/branches/cpp/ClaRa/ClaRa.html
The recently released version 1.8.1 exhibits the same problem.
For example `ClaRa.Components.BoundaryConditions.Check.TestIAPWSboundaries2`
```
./OMCppClaRa_dev_ClaRa.Components.BoundaryConditions.Check.TestIAPWSboundaries2Functions.cpp:244:12: error: no matching function for call to 'TILMedia_VLEFluid_Cached_specificEnthalpy_pTxi'
  h__ext = TILMedia_VLEFluid_Cached_specificEnthalpy_pTxi(p__ext, T__ext, ConstArray(xi_).getData(), vleFluidPointer__ext);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./OMCppClaRa_dev_ClaRa.Components.BoundaryConditions.Check.TestIAPWSboundaries2Functions.cpp:51:8: note: candidate function not viable: 3rd argument ('const double *') would lose const qualifier
double TILMedia_VLEFluid_Cached_specificEnthalpy_pTxi(double, double, double*, void*);
       ^
```
C compilers used by other runtimes just raise a warning -- which works but is not nice either.

This was corrected in [Modelica spec 3.5](https://specification.modelica.org/maint/3.5/functions.html#arrays-1) going back to https://github.com/modelica/ModelicaSpecification/issues/1955.

Could const qualifiers be added? How could we get this into the automated testing then?
