### ISSUE TITLE
Variable Filter option not working

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#10708]
### Description

The Simulation setup -> Output -> Variable filter does not work as expected.

### Steps to Reproduce

Put a filter for variables ending with xx and check results:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/0c8527ab-b155-43d8-b75e-a0fad2b01b43)

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/6031f91f-08fd-4d4e-be20-8873ead95502)

All variables are shown regardless the filter.

### Expected Behavior

Only variables ending on "y" shall be presented (in both OMedit and .mat file)

### Screenshots

see above

### Version and OS

OpenModelica Version: v.1.21.0 (64-bit)
OS: Windows 10 64 bit
Versions of used Modelica libraries if applicable: MSL 3.2.3

### Additional Context

N/A

**Comment by casella** [comment]
As the [User's Guide states](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.22/omedit.html#output)

> only output _variables_ with names fully matching the regular expression

hence _parameters_, which are computed at initialization and only saved once, are always saved in the .mat file.

Additionally, the variable browser will still show all the names of variables and parameters of the model. Of course, for those variables that were not saved, there is no checkbox to display them. If you don't want to see them at all, you can type `.*y` in the Variables Browser filter, that will get rid of all parameters and variable not containing `y` in the browser.

For the record, note that the behaviour of the variable filter in the Variables Browser is slightly different from the variable filter of the simulation output option. 

In the simulation output option, only the variables _exactly_ matching the regexp will be saved. In your case, all variables ending in `y`.

In the Variables Browser, all the variables that _contain_ a string matching the regexp will be displayed. So, not only variables ending in `y`, but also variables that contain further characters after it (or before it, for that). This is handy because typing, e.g., `der` will show all derivatives in the model, such as `der(x)` or `component.der(x)`. Unfortunately, it will not only show `abc.y`, but also `abc.yz`

If you want to display only the variables that end with the regexp, add a trailing $ to it, e.g. `.*y$`. This would avoid showing `abc.yz`

BTW, the leading `.*` in the regexp `*.y` is necessary for the simulation output option, where the regexp is matched exactly, but is not necessary in the Variables Browser, you can just type `y$` there.

Regexp's are complicated 😅

**Comment by casella** [comment]
There is an exhaustive documentation of regexp's for the simulation options [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.22/omedit.html#output), which is also accessible by clicking on the button to the right of the regexp filter string input field.

Unfortunatly, I just recognized that there is no explanation of how the regexp filter works [in the variables browser](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.22/omedit.html#variables-browser), which is slightly different. I'll add it to the user's guide ASAP.

**Comment by BasilioPV** [comment]
Ok, sorry for not understand well the working of the filters, but now I find on the OMedit help the correct description of how works. Thanks!

**Comment by casella** [comment]
Nobody every reads the documentation 😜 

PR #10710 improves the documentation for the Variables Browser filter.
