### ISSUE TITLE
Protected variables are incorrectly written to the result file

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#10707]
### Description

Checking Simulation setup -> Output -> "Protected Variables" does not change properly the .mat file.

### Steps to Reproduce

Currently, the behaviour is (for a given example):

**Protected Variables UNCHECKED:**
(1.6 GB .mat file) 
 
![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/6778dd4f-ddde-43c0-8606-17d68d04407c)

-	On OMEDIT: Not seen protected variables
-	Iniside .mat file: All variables (including protected) are present with all data inside.
(5162 variables, only 4 when conditions, all der() variables)

**Protected Variables CHECKED:**
(2.01 GB .mat file)
 
![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/76b9a45f-2fbf-4681-aa95-f5d86987d725)

-	On OMEDIT: Does not load the results (>2GB file issue??). If I reduce the simulation total time now I can see ALL variables (protected and public).

-	Iniside .mat file: All variables (including protected) are present with all data inside. (6576 variables, including $when conditions in the table and der() variables)

**Conclusions**

Plotting on OMedit, the behaviour is correct but the .mat file still contains the protected variables in both cases. The only difference on both situations is that when UNCHECK "protected variables", a lot of "$when" variables dissapear from the .mat file.

### Expected Behavior

The expected behaviour is that:
- Only variables must appear inside -mat file (not "$when" or "der()" variables) 
- With protected variables UNCHECKED, only public variables shall be present on .mat file

NOTE: reducing the .mat file adress indirectly the issue to load .mat files bigger than 2GB

### Screenshots

N/A

### Version and OS

OpenModelica Version: v.1.21.0 (64-bit)
OS: Windows 10 64 bit
Versions of used Modelica libraries if applicable: MSL 3.2.3

### Additional Context

N/A

**Comment by casella** [comment]
This issue has been fixed in the 1.22.0-dev version, see #10206. Please try with the latest nightly build.

**Comment by casella** [comment]
Sorry, I messed up a bit with my previous comment.

- Regarding protected variables being saved to the .mat file, this issue was indeed fixed in 1.22.0-dev, see #10206. Please try with the latest nightly build.
- `der(x)` is also considered a 'variable' in Modelica, in the sense that it is part of the set of time-varying unknowns of the differential-algebraic equations that describe models, so it is also saved in the result file. It would be odd if it wouldn't, all Modelica tools do that
- OpenModelica adds some auxiliary variables to the problem for efficiency reasons, starting with `$`, e.g., `$cse` variables are used to avoid multiple calls of the same pure function with the same input variable, `$when` variables are used to store the boolean triggering conditions of when clauses. These variables are used in the solution process and are visible in the [equation-based debugger](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#variables-browser), so it can be convenient to see them in the result file

Regarding auxiliary variables, we may actually add one more output option to filter them out, if you need this feature please open a separate ticket for that.
