### ISSUE TITLE
Warnings in .bnd C code

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10702]
Please run the PowerGrids.Examples.IEEE14bus.IEEE14busStaticNetwork in OMEdit. The following warning is generated during C compilation:
```C
IEEE14busStaticNetwork_08bnd.c:19:157: warning: format specifies type 'long' but the argument has type 'modelica_integer' (aka 'long long') [-Wformat]
    infoStreamPrint(LOG_INIT_V, 0, "updated start value: %s(start=%ld)", data->modelData->integerVarsData[4].info /* GEN8.AVR.limiterWithLag.state */.name, (modelica_integer) (data->localData[0]->integerVars[4] /* GEN8.AVR.limiterWithLag.state DISCRETE */));
                                                                  ~~~                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                  %lld
```
I guess that doesn't matter much unless really long integers are used, but I think we should have corrected C code nevertheless.

@mahge I think this was added when you managed to fix the thorny issue with start values bound to parameter expressions, would you mind having a look?

**Comment by mahge** [comment]
This happens because OpenModelica's `modelica_integer` is `long` on Linux and `long long` on Windows. So the warning happens only on Windows now. If we change it to `%lld`, there will be no warning on Windows but we will have one on Linux. 

The most logical thing to do would be to find the code-generation code responsible for this and fix it to generate the correct format specifier for the current OS. Unfortunately, that information about the OS, is not available right at the point where the code-generator generates this code. Making it available there will require some amount of changes because of how Susan works (you would have to pass it through a chain of functions). I remember seeing some global variables being used for some features. Maybe that can help here as well. 

The second, also logical but a bit ugly for the eyes, solution is to not directly print the format specifiers, but to use pre-processor variables in their place. These preprocessor variables can then be defined according to the OS. These approach is already being used in a few places in the runtime system. With this, we change the generated code from:

```c
infoStreamPrint(LOG_INIT_V, 0, "updated start value: %s(start=%ld)", data->modelData->integerVarsData[4].info ....);
```
To
```c
infoStreamPrint(LOG_INIT_V, 0, "updated start value: %s(start=" OMC_INT_FORMAT ")", data->modelData->integerVarsData[4].info ...);
```

Although it might be a bit confusing at first sight, this works fine as well.

**Comment by casella** [comment]
> This happens because OpenModelica's `modelica_integer` is `long` on Linux and `long long` on Windows. 

Ouch. Right.

> The most logical thing to do would be to find the code-generation code responsible for this and fix it to generate the correct format specifier for the current OS. Unfortunately, that information about the OS, is not available right at the point where the code-generator generates this code. Making it available there will require some amount of changes because of how Susan works (you would have to pass it through a chain of functions). I remember seeing some global variables being used for some features. Maybe that can help here as well.
> 
> The second, also logical but a bit ugly for the eyes, solution is to not directly print the format specifiers, but to use pre-processor variables in their place. These preprocessor variables can then be defined according to the OS. These approach is already being used in a few places in the runtime system. With this, we change the generated code from:

I am definitetly in favour of using macros. Seems the most logical thing to do, given the state of the affairs. I hope it's not too much work to fix it.

> ```c
> infoStreamPrint(LOG_INIT_V, 0, "updated start value: %s(start=%ld)", data->modelData->integerVarsData[4].info ....);
> ```
> 
> To
> 
> ```c
> infoStreamPrint(LOG_INIT_V, 0, "updated start value: %s(start=" OMC_INT_FORMAT ")", data->modelData->integerVarsData[4].info ...);
> ```

Shouldn't it be 
```C
infoStreamPrint(LOG_INIT_V, 0, "updated start value: %s(start=OMC_INT_FORMAT)", data->modelData->integerVarsData[4].info ...);
```
?

**Comment by mahge** [comment]
> Shouldn't it be
> 
> ```c
> infoStreamPrint(LOG_INIT_V, 0, "updated start value: %s(start=OMC_INT_FORMAT)", data->modelData->integerVarsData[4].info 
> ```

Unfortunately no. It might be confusing at first sight 🙂 and that is why I hesitated before going ahead and adding it. 

The C-pre-processor (CPP) macro replacement does not work inside literal strings. It ignores string literals completely. So the string (_simplified a bit_)  
```c
"updated start value: start=OMC_INT_FORMAT)"
```

would not be changed by the CPP even when OMC_INT_FORMAT is a macro. 

To get around that, we have to split the string into three parts:
```c
   "updated start value: start=" OMC_INT_FORMAT ")"
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~  ~~~
//               1                     2         3
```

which will be pre-processed to  

```c
   "updated start value: start=" "%ld" ")"
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~  ~~~
//               1                2     3
```

and then concatenated to one string by the C compiler.

**Comment by casella** [comment]
> The C-pre-processor (CPP) macro replacement does not work inside literal strings.

Aha, I was not aware of that. Applied witchcraft 101 😄 

Do you have a PR ready with that?

**Comment by casella** [comment]
I confirm the .bnd file warnings are gone. There are others left, see #10701. @mahge could you please fix them in the same way?

Thanks!
