### ISSUE TITLE
NF fails in models with fixed = false parameters

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10812]
Please run the attached Save Total model [OneBusOneLoadTotal.zip](https://github.com/OpenModelica/OpenModelica/files/11723843/OneBusOneLoadTotal.zip) with the script
```modelica
loadFile("OneBusOneLoadTotal.mo");getErrorString();
simulate(OneBusOneLoad_total);getErrorString();
```
The NF gives this error message:
```
"[C:/dev/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1126:9-1126:67:writable] Error: 
internal error NFCeval.evalBinaryDiv failed to evaluate loadPQ.UStart / 1.732050807568877
```
but then happily treads on and eventually leads to the production of correct simulation code. So, this issue, which affects the development version of PowerGrids, see PowerGrids/PowerGrids#62, is not a blocker, but is nevertheless quite annoying, because the end user sees an error message and has no clue what it implies and what to do with it.

Now, `loadPQ.UStart` is a `final parameter` but also has `fixed = false`, which means it can only be computed by solving the initializazion problem by means of initial equations, which are handled by the backend. The NF has no business trying to constant-evaluate it

### Expected Behavior

The NF should not try to constant-evaluate `loadPQ.UStart`, and leave it to the backend and runtime.

In fact, unless I am missing something, the NF should never try to constant-evaluate parameters with `fixed = false` attribute.

**Comment by casella** [comment]
Adding @AndreaBartolini to the loop

**Comment by perost** [comment]
#10820 fixes the issue in three ways:

1. By hiding any eventual error messages when trying to evaluate record bindings in order to be able to split them (to avoid having to move them to an initial equation), since a failure to evaluate the binding is ok in that case.
2. By making sure that the constant evaluation doesn't try to evaluate non-structural parameters (i.e. parameters that can't be structural, such as fixed parameters), so that we don't even try to evaluate the binding in this case. Not sure why we even allowed that before, I guess we'll see if it breaks anything...
3. By improving the inlining, so that the call in this case is inlined instead of moved to an initial equation.

Each fix makes the previous one redundant in this case, i.e. just improving the inlining is enough, but could of course be important in other cases.
