### ISSUE TITLE
OMEdit does not start command prompt

### ISSUE THREAD

**Issue by FWuellhorst** [OpenModelica/OpenModelica#10852]
### Description

I installed OM on Windows in a different directory (on D:) than the default. 
When clicking on Tools -> OpenModelica Command Prompt, the following error occurs:

```
Das System kann den angegebenen Pfad nicht finden. (path can not be found)
PATH = "C:\Users\...\AppData\Local\Temp\OpenModelica\OMEdit;C:\Users\...\AppData\Local\Temp\OpenModelica\OMEdit\..\..\usr\bin\;D:/05_Programme/OpenModelica\bin;D:/05_Programme/OpenModelica\lib\omc\msvc;D:/05_Programme/OpenModelica\lib\omc\cpp;D:/05_Programme/OpenModelica\lib\omc\cpp\msvc;"
```

### Steps to Reproduce

Install OM 1.21.0 64 bit on different location. Follow description

### Version and OS

 - OpenModelica Version: 1.21.0 64 bit
 - OS:  Windows 10, 64 bit

**Comment by adeas31** [comment]
What is the value of `Tools -> Options -> General -> Working Directory`?
It seems you might have an invalid old value from some old installation.

**Comment by FWuellhorst** [comment]
It is `C:/Users/.../AppData/Local/Temp/OpenModelica/OMEdit`. The directory exists on my device.

**Comment by adeas31** [comment]
I tried to fix this with PR #10872. Let me know if you still have issues.

**Comment by FWuellhorst** [comment]
Thanks! How can I build the .exe for this branch to check it out?

**Comment by adeas31** [comment]
The branch is now merged with the master. You fetch the latest code and compile it.

If you use the nightly builds then this should be available in tomorrow's nightly build.

**Comment by FWuellhorst** [comment]
I does not work with the nightly build. However, knowing which bat is triggered I was able to debug it further: 
On my device, msys is located under tools:
```
set MINGW=%OPENMODELICAHOME%\tools\msys\%OM_PLATFORM%
```
This fixes the PATH not found.

However, I was actually trying to run a .mos script inside OMEdit. What is the correct way to do this? If I run it using the Compiler CLI prompt, libraries are not loaded.

**Comment by adeas31** [comment]
Its because the nightly build failed and the one available is bit old and does not have the fix.
Anyways, my fix also does the same thing what you did yourself https://github.com/OpenModelica/OpenModelica/pull/10872/files

The mos script loads the stuff in a new session and there is no way to inter link OMEdit and mos script. You could try loading stuff in ´Tools->OpenModelica Compiler CLI´. There is no guarantee that the GUI is updated accordingly but there are some cases which works. I recommend not to mix diagram editing and command line scripting.

**Comment by FWuellhorst** [comment]
Ok perfect, thanks! 

Regarding the .mos files: How can I then load different libraries, change working directories etc. upon startup of OMEdit? Or is this not possible?

**Comment by adeas31** [comment]
Just load them one by one in OMEdit via `File->Open Model/Library File(s)`.

You can change the working directory in `Tools->Options->General->Working Directory`. Usually there is no need to change the working directory when loading the libraries. I wonder why you want to change the working directory.

**Comment by FWuellhorst** [comment]
Ok. Well, I often have multiple libraries and models which in different projects. I want to have the result files for these projects separated, thus, the different working directory. Loading everything manually and changing it is tedious and is often error-prone.

**Comment by adeas31** [comment]
You can add uses annotation to the model so that the dependent libraries are automatically loaded when model is loaded. For this to work the dependent libraries should be part of MODELICAPATH. OM doesn't load the libraries from the current model directory. That is a known issue and perhaps there is an open issue about it already.

Regarding the working directory, there is no easy solution. We can use vendor annotation but then you will have hard coded path in the model which is not nice.

**Comment by FWuellhorst** [comment]
I see! Thanks!

For development reasons, I have sometimes different branches of different libraries. Thus, I would have conflicting libraries in my PATH. I don't see why triggering multiple "loadFile" instead of one should be a problem to OMEdit, but then again I am not sure how the front- and backend interact with each other.

**Comment by perost** [comment]
> The mos script loads the stuff in a new session and there is no way to inter link OMEdit and mos script. You could try loading stuff in `Tools->OpenModelica Compiler CLI`. There is no guarantee that the GUI is updated accordingly but there are some cases which works. I recommend not to mix diagram editing and command line scripting.

Can't OMEdit just call `runScript` to run a .mos-script? That shouldn't be any different than just doing individual API calls.
