### ISSUE TITLE
Can't change parameter of a component of an extended model

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10865]
### Steps to Reproduce

- Load the attached [InitBlocks.zip](https://github.com/OpenModelica/OpenModelica/files/11798184/InitBlocks.zip) in OMEdit
- Open `InitBlocks.Examples.Tests.WaterHeater.SteadyStateOnDesignBackward`, which extends `SteadyStateOnDesignForward`
- Double-click on the salmon-hued `outputBlock`
- Try to change any parameter, e.g. type 100 in `y_norm`
- The change is not accepted and the following error message is reported:
```modelica
[3] 11:11:21 Scripting Error
Unable to set the extends modifier value using command setExtendsModifierValue(InitBlocks.Examples.Tests.WaterHeater.SteadyStateOnDesignBackward, 
InitBlocks.Examples.Tests.WaterHeater.BaseTests.BaseTestWaterHeater, outputBlock.y_norm, $Code(=100))
```

@perost, @adeas31, this looks similar to #10864. However, it behaves in the same way also if the Enable instance API flag is switched off and OMEdit restarted, so it probably has a different root cause. Can you please check?

Keeping @matteodepascali in the loop.

**Comment by perost** [comment]
The reason why the `setExtendsModifierValue` fails is because it's asking for the modifier to be put on the `BaseTestWaterHeater` extends clause, but `SteadyStateOnDesignBackward` doesn't directly extend from that class. I.e. the structure looks like:
```Modelica
model BaseTestWaterHeater
  OutputBlock outputBlock;
end BaseTestWaterHeater;

model SteadyStateOnDesignForward
  extends BaseTestWaterHeater;
end SteadyStateOnDesignForward;

model SteadyStateOnDesignBackward
  extends SteadyStateOnDesignForward;
end SteadyStateOnDesignBackward;
```
I'm not sure if that can work with the old API, but with the new it should be possible for OMEdit to follow the extends chain back and ask for the modifier to be put on the `SteadyStateOnDesignForward` extends instead.
