### ISSUE TITLE
Wrong equation count in the NF when using if initial()

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10927]
### Description

Please check the following MWE:
```modelica
model TestInitial
  Real x,y, der_x;
equation 
  der_x = y;
  if initial() then
    der_x = 0;
  else
    der_x = der(x);
  end if;
  y = -2*x + (if time > 0.5 then 1 else 0);
initial equation 
  der(x) = 0;
end TestInitial;
```
The output is:
```
Check of TestInitial completed successfully.
Class TestInitial has 2 equation(s) and 3 variable(s).
1 of these are trivial equation(s).
```
In fact, the model is balanced, and it compiles and simulates just fine.

### Expected Behavior

The checkModel operation should return 3 equations and 3 variables, initial() can be assumed to return false during checking, since the initial equation count is a backend matter.

Keeping @matteodepascali in the loop

**Comment by perost** [comment]
Looks like the `checkModel` implementation was implemented based on a backend implementation a long time ago, and it had a special case for if-equations with `initial()` as condition that couldn't be translated to an if-expression. That doesn't really make any sense for the frontend since it doesn't do such transformations, so I just removed it.

**Comment by casella** [comment]
Fastest ticket ever 😄
