### ISSUE TITLE
libiconv missing when compiling on macOS 

### ISSUE THREAD

**Issue by Mathadon** [OpenModelica/OpenModelica#10944]
### Description

Libiconv is missing when compiling even though it is installed.

### Steps to Reproduce

```
git clone --recurse-submodules https://github.com/OpenModelica/OpenModelica.git && cd OpenModelica
cmake -S . -B build_cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DOM_OMC_ENABLE_FORTRAN=OFF -DOM_OMC_ENABLE_IPOPT=OFF
cmake --build build_cmake --parallel 1 --target install
```

Error message:
```
[ 30%] Linking CXX executable bootstrapped/bin/bomc
ld: warning: dylib (/opt/homebrew/lib/libintl.dylib) was built for newer macOS version (13.0) than being linked (12.3)
Undefined symbols for architecture arm64:
  "_libiconv", referenced from:
      _SystemImpl__iconv in libomcruntime.a(System_omc.c.o)
  "_libiconv_close", referenced from:
      _SystemImpl__iconv in libomcruntime.a(System_omc.c.o)
  "_libiconv_open", referenced from:
      _SystemImpl__iconv in libomcruntime.a(System_omc.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [OMCompiler/Compiler/boot/bootstrapped/bin/bomc] Error 1
make[1]: *** [OMCompiler/Compiler/boot/CMakeFiles/bomc.dir/all] Error 2
make: *** [all] Error 2
```

I have installed libiconv using homebrew and `configure` finds it:

```
-- The following REQUIRED packages have been found:

 * boost_program_options (required version == 1.79.0)
 * boost_atomic (required version == 1.79.0)
 * boost_filesystem (required version == 1.79.0)
 * boost_headers (required version == 1.79.0)
 * boost_graph (required version == 1.79.0)
 * boost_chrono (required version == 1.79.0)
 * Boost
 * CURL
 * Intl
 * Iconv        <-----------
 * Threads
 * BLAS
 * LAPACK
 * Java
 * Qt5Concurrent
 * Readline
 * Qt5PrintSupport
 * Qt5WebKit (required version >= 5.9.2)
 * Qt5WebKitWidgets
 * Qt5Xml
 * Qt5XmlPatterns
 * Qt5OpenGL
 * Qt5Network
 * Qt5Svg
 * OpenSceneGraph
 * OpenGL
 * Qt5Core
 * Qt5Gui
 * Qt5Widgets
 * Qt5
```

Libiconv is installed, including the referenced symbols:
```
 brew ls --verbose libiconv
/opt/homebrew/Cellar/libiconv/1.17/INSTALL_RECEIPT.json
/opt/homebrew/Cellar/libiconv/1.17/bin/iconv
/opt/homebrew/Cellar/libiconv/1.17/.brew/libiconv.rb
/opt/homebrew/Cellar/libiconv/1.17/ChangeLog
/opt/homebrew/Cellar/libiconv/1.17/AUTHORS
/opt/homebrew/Cellar/libiconv/1.17/include/libcharset.h
/opt/homebrew/Cellar/libiconv/1.17/include/localcharset.h
/opt/homebrew/Cellar/libiconv/1.17/include/iconv.h
/opt/homebrew/Cellar/libiconv/1.17/README
/opt/homebrew/Cellar/libiconv/1.17/COPYING.LIB
/opt/homebrew/Cellar/libiconv/1.17/COPYING
/opt/homebrew/Cellar/libiconv/1.17/NOTES
/opt/homebrew/Cellar/libiconv/1.17/NEWS
/opt/homebrew/Cellar/libiconv/1.17/lib/libcharset.a
/opt/homebrew/Cellar/libiconv/1.17/lib/libcharset.1.dylib
/opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.2.dylib
/opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.dylib
/opt/homebrew/Cellar/libiconv/1.17/lib/libcharset.dylib
/opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.a               <-------------------------------
/opt/homebrew/Cellar/libiconv/1.17/share/man/man3/iconv.3
/opt/homebrew/Cellar/libiconv/1.17/share/man/man3/iconv_close.3
/opt/homebrew/Cellar/libiconv/1.17/share/man/man3/iconv_open_into.3
/opt/homebrew/Cellar/libiconv/1.17/share/man/man3/iconv_open.3
/opt/homebrew/Cellar/libiconv/1.17/share/man/man3/iconvctl.3
/opt/homebrew/Cellar/libiconv/1.17/share/man/man1/iconv.1
/opt/homebrew/Cellar/libiconv/1.17/share/doc/libiconv/iconv_close.3.html
/opt/homebrew/Cellar/libiconv/1.17/share/doc/libiconv/iconv.3.html
/opt/homebrew/Cellar/libiconv/1.17/share/doc/libiconv/iconvctl.3.html
/opt/homebrew/Cellar/libiconv/1.17/share/doc/libiconv/iconv_open_into.3.html
/opt/homebrew/Cellar/libiconv/1.17/share/doc/libiconv/iconv_open.3.html
/opt/homebrew/Cellar/libiconv/1.17/share/doc/libiconv/iconv.1.html
``` 

```
nm -gU /opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.a

/opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.a(iconv.o):
0000000000100d08 D __libiconv_version
00000000000020d4 T _iconv_canonicalize
00000000000018d4 T _libiconv                                      <--------------------------
00000000000018f8 T _libiconv_close                            <--------------------------
0000000000000788 T _libiconv_open                           <--------------------------
0000000000001910 T _libiconv_open_into
0000000000001d24 T _libiconvctl
0000000000001e58 T _libiconvlist
000000000000033c T _utf8_decodestr
0000000000000000 T _utf8_encodestr
0000000000100ce8 D _utf_extrabytes

/opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.a(localcharset.o):
0000000000000000 T _locale_charset

/opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.a(relocatable.o):
00000000000000c8 T _libiconv_relocate
00000000000001ac T _libiconv_relocate2
0000000000000000 T _libiconv_set_relocation_prefix
```

It is arm64:
```
lipo -info /opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.a
Non-fat file: /opt/homebrew/Cellar/libiconv/1.17/lib/libiconv.a is architecture: arm64
```

### Version and OS
OM version: 4669298c990fd1301ef241771eeb7dd9a56ab304

OS: macOS 13.0.1

**Comment by mahge** [comment]
I think this is because omc is probably linking to the MacPorts libiconv instead of the hombrew one. I think I remember something like that. The two `iconv` libraries provide different symbols IIRC. For example, one provides `_libiconv_close` while the other provides `_iconv_close`, i.e., one of them does not have the `lib` prefix on the functions. 

If you can run the build once again (no need to clean) and attach the log, we might be able to tell

```
cmake --build build_cmake --parallel 1 --target install - v |& tee build.trace
```

-------------------------------------------------------

In the mean time, you can also try and see if there is a libiconv installed by MacPorts and disable it temporarily. 
```
sudo port -f deactivate libiconv
```

and see if that changes anything.

**Comment by mahge** [comment]
I am adding some notes to the README about this but I am not 100% sure which workaround worked for you. Is it disabling the `MacPorts` `libiconv` OR removing the `.tbd` file? If disabling the `MacPorts` `libiconv` does the trick then that is probably better to suggest for users. Otherwise we can add a note about removing the `.tbd` file as a last resort.

**Comment by mahge** [comment]
> Moving the tbd file is what worked :) Updating Xcode did not create the missing file so I presume otherwise the problem persists (but I did not test it).
> 
> edit: I did not disabled the macports libiconv since I don't think it exists. My macports is broken and needs to be reinstalled so I cannot check.

Ahh I see. I think I confused the MacPorts version with the XCode version. It is the XCode installed version that has the different symbols causing the issue here. 

-----------------------------

When you have time to experiment a bit more, can you please test these and let me know what happens?

First put back the `.tbd` file to its original place and verify the problem pops up again. If it does, reconfigure OpenModelica like this
```
cmake  ... -DCMAKE_PREFIX_PATH=/opt/local
```
this will tell `CMake` to prioritize the `MacPorts` installed libs (in `opt/local`) above others. 

If that does not work 
```
cmake  ... -DCMAKE_PREFIX_PATH=/opt/local;/usr/local/opt/
```

This time adding the homebrew installed libraries to the priority as well. I am not sure which one to prioritize over the two but since it is practically mandatory to use MacPorts for compiling OpenModelica (because of missing `QtWebkit` library in homebrew) anyway, it should probably be search first.

If one of these works, then it is perhaps a better solution.

**Comment by Mathadon** [comment]
Adding `-DCMAKE_PREFIX_PATH=/opt/local` to the configure stage seems to solve the problem 🥰

**Comment by mahge** [comment]
I have updated the readme in #10962 and added the -DCMAKE_PREFIX_PATH= specification to the instructions for bot `MacPorts` and `homebrew` users. I have also added a note about this specific issue just for completeness. Thanks for finding the issue and debugging.

**Comment by ryandesign** [comment]
> That file links to `/usr/lib/libiconv.2.dylib`, which does not exist on my system.

That's right. Apple, in their wisdom, have decided as of macOS 11 that system libraries and frameworks will no longer reside in the filesystem. They are now only in the dyld cache. Therefore, checking whether a file exists on disk is no longer a valid way to discover whether a library or framework exists. The only way to know is to call `dlopen` on it.

**Comment by ryandesign** [comment]
> I think I confused the MacPorts version with the XCode version. It is the XCode installed version that has the different symbols causing the issue here.

libiconv is not provided by Xcode; it's provided by macOS. Xcode does provide the headers and text-based stubs for libiconv and all other system libraries and frameworks, though.

**Comment by thynus** [comment]
more info:
https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx
