### ISSUE TITLE
"Use Static Linking" issue between 1.18.1 and 1.21

### ISSUE THREAD

**Issue by antoine-chupin-jimmy** [OpenModelica/OpenModelica#10957]
### Description
In v1.18.1 when the option "use static linking" is set in options/simulations it is possible to run directly the simulation by double clicking on the .exe file in the working directory.
On v1.21 this action leads to an error with mingw dll

### Steps to reproduce
Compile and run a model using "use static linking" then click on the .exe file on windows

### Expected behavior
Run of .exe file and generation of .mat file

### Screenshots
Not available

### Additional files
Not needed

### Version and OS
 - OpenModelica Version 1.21 64bits
 - Versions of used Modelica libraries if applicable
 - OS: Win11 64 bits

**Comment by antoine-chupin-jimmy** [comment]
Hello again, I have done additional tests following issue [https://github.com/OpenModelica/OpenModelica/issues/7534](url)

I tried with OM 1.22.0beta4 and the same issue is present

I tried adding the Additional Translation Flags: --linkType=static but with no success

And as I understand and as I use it in versions up to 1.18.1 the correct way to use it is by ticking the check box in options/simulation:use static linking

It is annoying since I have issues (for example for using external media) on 1.18.1 that are solved on 1.21 but I cannot use it for this issue. 
Like EDF I am using the .exe files to run simulation batches for sensitivity analysis.

Thanks

**Comment by casella** [comment]
@mahge, @adeas31 can you please help with this?

**Comment by adeas31** [comment]
It seems to be fine from OMEdit side.

I think @mahge broke it with commits https://github.com/OpenModelica/OpenModelica/commit/627bacf54067027b902307a921431848b8b0b4e8 and https://github.com/OpenModelica/OpenModelica/commit/dbf37cf7c3239b72ff57cbff296e166c9e1e36ac.

**Comment by mahge** [comment]
> On v1.21 this action leads to an error with mingw dll

What exactly does the error say?

There is also a `.bat` file generated with the same name as the executable in the same directory. You can run this .bat file in an MSYS terminal and it should set the necessary paths and launch the executable for you. However, the list of paths added does not include the MSYS/MinGW library directories. It will only include the paths which provide the OpenModelica runtime libraries and paths to pre-compiled libraries in Modelica libraries (e.g. DLLs distributed as part of ExternalMedia and used by the simulation. These are taken from paths specified in annotations in the Modelica library itself.) 

Maybe we can add the OpenModelica installation's MSYS libraries path to this list of paths so you can achieve what you are trying to do. Before that, however, we need to know exactly what error messages you are getting.

**Comment by adeas31** [comment]
@mahge the error is, `error while loading shared libraries: libSimulationRuntimeC.dll: cannot open shared object file: No such file or directory`, this is because `libSimulationRuntimeC` is not linked statically.

Of course it will work if we add the OpenModelica installation to PATH but the whole idea of having the option `Use static linking` is to be able to run or distribute executable without dependencies.

**Comment by mahge** [comment]
> @mahge the error is, error while loading shared libraries: libSimulationRuntimeC.dll: cannot open shared object file: No such file or directory, this is because libSimulationRuntimeC is not linked statically.

That should be handled by the `.bat` file. It will set the correct paths and launches the executable for you. There are two more DLL dependencies on OpenModelica libraries. `libOpenModelicaRuntimeC.dll` and `libomcgc.dll` are also required by the simulation executable. The paths to these DLLs and any other Modelica annotation specified libraries are handled by the `.bat` file.

@antoine-chupin-jimmy mentioned that he was getting an error to a `MinGW DLL`. That was what I wanted to see. If it is indeed just missing the OpenModelica DLLs themselves then the `.bat` file should cover that already.

@antoine-chupin-jimmy you can just double click the `.bat` file to get more or less the same behavior as you had before.  If you want to copy/move the executable to some other directory or machine, then copy these three DLLs and put them in the same directory as your executable and it should work fine. It will also save you some memory space if you have many of these simulation executables to handle.

**Comment by adeas31** [comment]
> That should be handled by the .bat file. It will set the correct paths and launches the executable for you. There are two more DLL dependencies on OpenModelica libraries. libOpenModelicaRuntimeC.dll and libomcgc.dll are also required by the simulation executable. The paths to these DLLs and any other Modelica annotation specified libraries are handled by the .bat file.

I agree. I actually prefer it this way with dynamic linking.
The only thing is that we had in the past the option to have static linking which is not possible now which means this is a regression. Perhaps we should remove the static linking option and write somewhere in the our users guide about how to launch the simulation executable.

**Comment by mahge** [comment]
I was thinking about that but wanted to check before I wrote something because I never used the option before.

What I was thinking was that we can keep the option if it affects how the system C libraries are linked. Things like `libgcc` or `libc`. I will check.

**Comment by adeas31** [comment]
There is the old reference ticket https://trac.openmodelica.org/OpenModelica/ticket/5827 from @adrpo

**Comment by casella** [comment]
I guess we should explain this in the User's Guide, as it is probably useful for many people. I would put some words [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/compiler.html#simulation-runtimes). Do you agree?

**Comment by antoine-chupin-jimmy** [comment]
Hello, thank you for your answer and anlysis.
Sorry for my late answer as I was away.

As said by @mahge the two errors while running directly the .exe file are (sorry it is a translation as it is in frenche on my computer)

"Impossible to execute code as libomcgc-1.dll is not found"
and
"Impossible to execute code as libSimulationRuntimeC.dll is not found"

On EDF side we used to run our batches of simulation using a custom python library which use the '-override=' command to run the .exe files with our sets of parameters.

I can confirm that running the .bat file is working correctly.

I am not sufficiently skilful to understand if the override command would work directly on the .bat file but I can try to change our scripts to add the override inside the .bat (should work no?)

On 1.18.1 I do not have the .bat file, but I have it on 1.22.0 dev beta4

**Comment by antoine-chupin-jimmy** [comment]
I have just tried the -override command, either directly on .bat file or inside the .bat.

No success for the moment.

**Comment by mahge** [comment]
> I have just tried the -override command, either directly on .bat file or inside the .bat.

Adding it inside the `.bat` file should work. How are you adding it and what errors do you get? if any.

Another option is to copy and move the two DLLs with your executable. As long as the DLLs are in the same directory as the executable it should work fine. You can also have many simulation executables in the same directory with the DLLs and they should work fine.

**Comment by antoine-chupin-jimmy** [comment]
Hello,

I edited the .bat file
Tried both options.
1. put all my string working usually with .exe
2. just run the .exe (which is the same as using the syntax %CD%/TwoMasses.exe from the original bat file

The #1 gives me an error (translated) : "the syntax of the file, folder or volume is incorrect"

#1

@echo off
SET PATH=;C:/OpenModelica1.22.0-dev.beta.4-64bit/bin/;%PATH%;
SET ERRORLEVEL=
CALL "C:/Users/Antoine/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Thermal.HeatTransfer.Examples.TwoMasses/TwoMasses.exe -inputPath=C:/Users/Antoine/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Thermal.HeatTransfer.Examples.TwoMasses -r=C:/Users/Antoine/AppData/Local/Temp/OpenModelica/OMEdit/ModelicaScripting/tesbatch/Case1.mat -override=mass1.C=20.0,mass2.C=10.0 -port=10234" %*
SET RESULT=%ERRORLEVEL%

EXIT /b %RESULT%


#2

@echo off
SET PATH=;C:/OpenModelica1.22.0-dev.beta.4-64bit/bin/;%PATH%;
SET ERRORLEVEL=
CALL "C:/Users/Antoine/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Thermal.HeatTransfer.Examples.TwoMasses/TwoMasses.exe" %*
SET RESULT=%ERRORLEVEL%

EXIT /b %RESULT%

**Comment by mahge** [comment]
> The https://github.com/OpenModelica/OpenModelica/pull/1 gives me an error (translated) : "the syntax of the file, folder or volume is incorrect"

Try putting each option inside its own quote. That is, the options that would normally be separated by space should all be quoted and put next to the executable string. Something like this:

```bat
CALL "%CD%/Modelica_Electrical_Analog_Examples_CauerLowPassSC.exe" "-override=mass1.C=20.0,mass2.C=10.0" -"port=10234" %*
```

> When moving the two dll files into the folder I have othe errors about other dlls

You have to tell me what the errors are 🙂

**Comment by antoine-chupin-jimmy** [comment]
That works using the quotes " between arguments

**Comment by felix-marsollier2** [comment]
Hello all,

I'm the owner of the issue https://github.com/OpenModelica/OpenModelica/issues/7534 .

I have been contacted by @antoine-chupin-jimmy . Let me explain you the context of our request.
I was working for Electricité De France (EDF). In their quality process, the .exe binaries have to be runnable even after many years (even on a different machine). It was clearly easier to get a static executable (embedding all required dll) rather than keeping over the years a fix environment with all the versions of OpenModelica used during the studies.

I understand than the exe can be static by giving pathes especially for dll in the bat file. That is a good idea ! but it still requires to keep associated versions of OpenModelica and the environment used somewhere other the years.

From my understanding, you can manually add the dlls in the directory where the exe is. That would be possible on our side but we realized that the size of all the dlls copied was clearly greater than the size of the exe with the static option. According to the number of simulation we had stored and we are storing, it could participates to a digital sobriety without lots of efforts.

Moreover, if the user has forgotten to perform the manipulations to copy the dlls or to store which version of OM where used, it could be impossible to run again the .exe. That is problematic for the robustness of the quality process.

Sorry for having specific requests.

**Comment by casella** [comment]
@felix-marsollier2 if you want to discuss the issue of long-term usability of OMC-generated .exe files, I would suggets you open a separate issue or discussion item, because it may be useful to other people.

IMHO the best way to guarantee long-term usability of models is not to use statically linked time capsules, because are going to become obsolete at some point. The obsolescence cycle for a power plant is anything between 20 an 60 years, operating systems become obsolete much faster. 

The best way to do that is to keep the Modelica source code alive, testing it with the latest released version of the tool, e.g. OpenModelica, and making sure there are no regressions. If there are any, they should be fixed right away. Modelica is a mature language, I don't expect that legal Modelica code in 2023 won't be compilable in 2043. I'm not sure Modelica will still be around in 2083, but I won't be around anyway... 😄 

In this way, you can always do whatever you want with those models, including running them on all the operating systems supported by the tool (with all the security updates), exporting FMUs, or whatever.

In any case, if the requirement is long-term usability of executable simulation files, we should open a separate discussion on that topic. I am sure we can get good results in that case also, but it needs to be analyzed carefully, and the story will be different for Windows and Linux, I guess.
