### ISSUE TITLE
Incorrect warning of Boolean connector requiring fixed = true and false value

### ISSUE THREAD

**Issue by mpradovelasco** [OpenModelica/OpenModelica#11138]
The following model shows the code of a single model that connect a zero width pulse to a monostable

```Modelica fold title:WarningInputBoolean 
package WarningInputBoolean

  import Modelica.Blocks.Interfaces.{BooleanOutput,BooleanInput,RealOutput,RealInput};
  import Modelica.Units.SI;
  
  partial block BooleanBlock "Base Symbol for a general Boolean Signal Block"
    annotation(
      Icon(graphics = {Rectangle(extent = {{-70, 50}, {70, -50}})}, coordinateSystem(initialScale = 0.1)));
  end BooleanBlock;

  partial block logicalSISO "Single Input - Single Output Logical block"
    extends BooleanBlock;
  BooleanOutput bo "Connector of Boolean output signals" annotation(
        Placement(visible = true, transformation(origin = {0, 0}, extent = {{100, -10}, {120, 10}}, rotation = 0), iconTransformation(origin = {-30, 0}, extent = {{100, -10}, {120, 10}}, rotation = 0)));
    parameter Boolean hold = false "true if inputs are held constant";
    parameter Boolean biHold = false "bi input value if hold is true"
      annotation(Dialog(enable = hold));
    BooleanInput bi "Connector of Boolean input signals" annotation(
      Placement(visible = not hold, transformation(origin = {-220, 0}, extent = {{100, -10}, {120, 10}}, rotation = 0), iconTransformation(origin = {-190, 0}, extent = {{100, -10}, {120, 10}}, rotation = 0)));
   equation
    if hold then 
      bi = biHold;
    end if;
  annotation(Icon(graphics = {Rectangle(fillColor = {236, 236, 236}, fillPattern = FillPattern.Solid, extent = {{-68, 48}, {68, -48}})}));
 end logicalSISO;

 block mstable "Monostable block with period T"
    extends logicalSISO;
    parameter SI.Time T(final min = 0, displayUnit="min") = 60 "Time of output pulse bo";
  protected
    Boolean fdedge (start = false, fixed = true) "First detected edge";
    SI.Time tstart(start = 0, fixed = true) "time when positive edge is bi is detected";
  equation
    when edge(bi) then
      tstart = time;
      fdedge = true;
    end when;
    bo = fdedge and (time > tstart and time <= tstart + T);
    annotation (
      defaultComponentName="mstable1",
      Icon(coordinateSystem(preserveAspectRatio=true, extent={{-100,-100},{100,
              100}}), graphics={Text(origin = {34, -54}, extent = {{-150, 150}, {150, 110}}, textString = "%name"), Line(origin = {-33, 3}, points = {{-21, -17}, {5, -17}, {5, 17}, {21, 17}}), Line(origin = {36.7105, -13.9803}, points = {{-11, 0}, {-25, 0}}), Line(origin = {40, 3}, points = {{-14, -17}, {-14, 17}, {2, 17}, {2, -17}, {14, -17}, {14, -17}})}));
 end mstable;

 block zpulse "Zero width pulse generator"
    extends logicalSISO(bo(start = false, fixed = true));
  equation
    bo = edge(bi);
    annotation (
      defaultComponentName="zpulse1",
      Icon(coordinateSystem(preserveAspectRatio=true, extent={{-100,-100},{100,100}}), 
      graphics={Text(origin = {34, -54}, extent = {{-150, 150}, {150, 110}}, textString = "%name"), Line(origin = {-33, 3}, points = {{-21, -17}, {5, -17}, {5, 17}, {21, 17}}), Line(origin = {36.7105, -13.9803}, points = {{25, 0}, {-25, 0}}), Line(origin = {36, 3}, points = {{0, 17}, {0, -17}})}));
  end zpulse;

  model test
    zpulse zpulse1 annotation(
      Placement(visible = true, transformation(origin = {-8, 16}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
    mstable mstable1  annotation(
      Placement(visible = true, transformation(origin = {18, 16}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  equation
    zpulse1.bi = if time > 120 then true else false; 
    connect(zpulse1.bo, mstable1.bi) annotation(
	    Line(points = {{0, 16}, {10, 16}}, color = {255, 0, 255}));
  end test;
end WarningInputBoolean;
```

This is the diagram view of the test model:
![Pasted image 20230907193201](https://github.com/OpenModelica/OpenModelica/assets/114144098/f7e61698-9fa7-4bb7-aa79-ead77f5f3527)

The input boolean is governed in the view model with an equation (zpulse1.bi = ...), and the simulation for 10 minutes gives:

![Pasted image 20230907193438](https://github.com/OpenModelica/OpenModelica/assets/114144098/dad35d6c-7765-4e95-8bc6-5f955d98770b)

However, OMEdit gives two warnings:

"Assuming fixed start value for the following 2 variables:
         mstable1.bi:DISCRETE(flow=false fixed = true )  "Connector of Boolean input signals" type: Boolean
         zpulse1.bi:DISCRETE(flow=false fixed = true )  "Connector of Boolean input signals" type: Boolean"

I think these warnings are incorrect, since bi signals are defined as:

-   mstable1.bi is equivalent (trivial equation) zpulse1.bo, which is properly initialized 
-   zpulse1.bi is the expression  `if time > 120 then true else false`, which defines properly the value at the initial time.

Indeed OMEdit seems dot not consider the initialization of bo variable in zpulse block, since start attribute may be removed without any warning. 

I know, these are only warnings, but I think they affect to an important detail (initialization).

Model has been implemented in OMEdit 1.22-dev (26 August) with Enable Instance API = TRUE, on Windows 11.

Thank you in advance for your effort!

**Comment by casella** [comment]
@mpradovelasco I reproduced your issue with this MWE:
```modelica
package MWE
  model Test1
    Boolean b1;
  equation
    b1 = if time < 0.5 then false else true;
  end Test1;
  
  model Test2
    Boolean b1;
    Boolean b2;
  equation
    b1 = if time < 0.5 then false else true;
    b2 = edge(b1);
  end Test2;
end MWE;
```
Test1 gives no warning. Test2, instead, gives the following warning:
```
[1] 17:00:36 Translation Warning
Assuming fixed start value for the following 1 variables:
         b1:DISCRETE(fixed = true ) MWE.Test2 type: Boolean
```
Interestingly, Dymola behaves exactly the same, so I believe this is the correct behaviour.

As I understand, an _equation_ involving a discrete variable `x_d` (outside of a when statement) determines its value `x_d` at all times between StartTime and StopTime, so also at initialization. However, _it does not determine its previous value_ `pre(x_d)` _at initialization_.

In the first case, nobody cares, because `pre(b1)` is not needed to compute the variables of the model. In the second case, instead, the use of `edge(b1)` (which is defined as `b1 and not pre(b1)`)requires the knowledge of `pre(b1)` also during initialization. That is not set by the equation `b1 = if time < 0.5 then false else true`. Hence, it must be set either by setting `b1(fixed = true)` or by adding an initial equation, e.g. `pre(d1) = false`.

**Comment by mpradovelasco** [comment]
Hi @casella ,

Thank you for preparing that interesting MWE. I have performed a minor modification to show that the problem continues.
If the Boolean b1 from Test2 is conected to b1 of Test1, which is well-known, that is:

``` Modelica
model newTest
    model Test1
    connector outputBoolean = output Boolean;
    outputBoolean b1;
  equation
    b1 = if time < 0.5 then false else true;
  end Test1;
  
  model Test2
    connector inputBoolean = input Boolean;
    inputBoolean b1;
    Boolean b2;
  equation
    //b1 = if time < 0.5 then false else true;
    b2 = edge(b1);
  end Test2;
  
  model Test3
    Test1 T1;
    Test2 T2;
  equation
    connect (T1.b1, T2.b1);
  end Test3;
  
  end newTest;
```
However, OMEdit gives the warning:
```
[1] 17:48:43 Translation Warning
Assuming fixed start value for the following 1 variables:
         T2.b1:DISCRETE(flow=false fixed = true )  type: Boolean
```
Could be that the system it is not considering the Equal equations that results from the connect?

**Comment by mpradovelasco** [comment]
Uff, the situation is the same in the second test. Sorry. 

I completely agree then.

Thanks again.

**Comment by casella** [comment]
This is a bit asymmetric w.r.t. the continuous time case.

For continuous variables, if I write `x = <some function of time>` this completely specifies `x` and `der(x)` at all times, _including initialization_. 

For discrete variables instead `b = <some boolean expression of time>` determines `pre(b)` at all event times, _except at initialization_. 

Not 100% sure why the language was designed like that. I guess the reason is that there is an event iteration at initialization (which means an event is triggered at time = StartTime), which is not generated or implied by the boolean expression of time of the equation that determined `b`. So you have to explicitly set `pre(b)` at initialization, either by `fixed = true` or via `initial equation`.

In fact, I was actually not aware of that before looking into your question 😅
