### ISSUE TITLE
start is presented with ShowStartAttribute = false

### ISSUE THREAD

**Issue by mpradovelasco** [OpenModelica/OpenModelica#11150]
Hi,

In the zpulse block of issue #11138  the start attribute keeps in the dialog box despite the showStartAttribute = false annotation. I have also tested this issue with a non connector based variable as bsalida, In the following code, but the result is the same:
``` Modelica fold title:"showStartAttribute = false"
block zpulse "Zero width pulse generator"
    Boolean bsalida(start = false, fixed = true)
      annotation(Dialog(showStartAttribute = false));
  equation
	...
  end zpulse;
```

The following figure shows the start attribute in the dialog box.
![Pasted image 20230908191415](https://github.com/OpenModelica/OpenModelica/assets/114144098/f213e44d-4915-4e9c-aea9-536f0be28d48)

System: OMEdit 1.22 dev (version of august 26) with Enable Instance API ON , on Windows 11.

It could be fantastic if this issue could be fixed for the 1.22 release. 

Thank you again!

**Comment by abuntrock** [comment]
@casella mentioned in a similar ticket created by myself #11059 that OMEdit currently ignores the `showStartAttribute` annotation completely

**Comment by casella** [comment]
@adeas31 is this a quick fix? If so, you can consider adding it to the [1.22.0 project](https://github.com/orgs/OpenModelica/projects/15/views/1).

**Comment by adeas31** [comment]
AFAIR it is a combination of 'showStartAttribute', 'start' and 'fixed' value. If you have any one of them then the variable will be shown.

**Comment by casella** [comment]
> AFAIR it is a combination of `showStartAttribute`, `start` and `fixed` value. If you have any one of them then the variable will be shown.

I confirm that. This is easily checked by double-clicking on m in S in the follwing MWE package:
```modelica
package TestAttributes
  model M
    Real x;
    Real y(start = 2);
    Real z(fixed = true);
    Real w annotation(Dialog(showStartAttribute = true));
  end M;
  model S
    M m annotation(
      Placement(visible = true, 
        transformation(origin = {-28, 22}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end S;
end TestAttributes;
```

@mpradovelasco the [MLS Section 18.7](https://specification.modelica.org/maint/3.6/annotations.html#annotations-for-the-graphical-user-interface) only mandates the behaviour when `showStartAttribute = true`:
> If showStartAttribute = true the dialog should allow the user to set the start- and fixed-attributes for the variable instead of the value of the variable.
>
> [The showStartAttribute = true is primarily intended for non-parameter values and avoids introducing a separate parameter for the start-attribute of the variable.]

So, this annotation (when true) is meant to actually show the start and fixed attributes for variables where it could make sense to set them to non-default values when instantiating the model. The specification doesn't say that if the attribute is false those attributes should not be displayed. 

In fact, what OMEdit does makes sense: if there are modifications on those attributes, they are also displayed in the GUI, so you can handle them from there, instead of needing to switch to the textual view.

So, the current behaviour is intented and in accordance to the Modelica language specification.

**Comment by abuntrock** [comment]
@casella Thanks for your detailed comment. This however basically means that I am not able to "remove" a public parameter (public needed for plotting after simulation) with a start or fixed modifier from the parameter dialog in OMEdit right? 

I would also mention that it might be possible to read the 
> instead of the value of the variable.

part of the Modelica Specification in the way that the value of the variable (and not its start and fixed attributes) should be displayed in the parameter dialog if `showStartAttribute=false` is set.
However, this turns into a Modelica specification issue, which I opened here https://github.com/modelica/ModelicaSpecification/issues/3406 for reference.

**Comment by casella** [comment]
> @casella Thanks for your detailed comment. This however basically means that I am not able to "remove" a public parameter (public needed for plotting after simulation) with a start or fixed modifier from the parameter dialog in OMEdit right?

I guess so.

> I would also mention that it might be possible to read the
> 
> > instead of the value of the variable.
> 
> part of the Modelica Specification in the way that the value of the variable (and not its start and fixed attributes) should be displayed in the parameter dialog if `showStartAttribute=false` is set.

How could you display the value of a time-varying variable in a parameter dialog, particularly when you haven't run the simulation yet?

**Comment by abuntrock** [comment]
Consider the following class and its parameter dialog in v1.22.0-dev-341-gbf24d82543 (64-bit) with Instance API.
```modelica
model TimeVaryingInput
  Real realVariable1 = time annotation(Dialog(group="Time varying inputs"));
  Real realVariable2(start=0.0) = time annotation(Dialog(group="Time varying inputs"), showStartAttribute = false);
  Real realVariable3;

equation
  realVariable3 = realVariable1*realVariable2;

end TimeVaryingInput;
```

This example shows that OMEdit already displays time-varying variables (in this case `realVariable1`) in the parameter dialog if they have a dialog annotation (maybe I was missing this clarification above). 

I would expect that with `showStartAttribute=false` `realVariable2` is shown in the parameter dialogue in the same way as `realVariable1`. This would mean that `realVariable2` and not `realVariable2.start` is displayed.

**Comment by adeas31** [comment]
@abuntrock I agree. I will update accordingly.

**Comment by casella** [comment]
@abuntrock I was actually not aware that you could handle variable bindings with the GUI just by adding the dialog annotations - I always did that by hand 😅 . I also agree with your requests.

**Comment by adeas31** [comment]
@abuntrock sorry I spoke too early. I looked at the code and we check if `showStartAttribute` is not defined and the element is not a parameter then we look if `start` modifier is defined. Since in this example `start` modifier is defined so you see `realVariable2.start` instead of `realVariable2`. If you remove `(start=0.0)` then its listed as `realVariable2` instead of `realVariable2.start`.
