### ISSUE TITLE
LoadEncryptedPackage not working with Command CLI

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11154]
### Description
We are currently testing our encrypted modelica library BRSL in the OMEdit Pro. We can successfully load the BRSL via `File->Load Encrypted Library` and by drag & dropping it into the library browser. However, using `loadEncryptedPackage` in the Command CLI returns `true` as an output but does not add the BRSL to the library browser.
If you cannot replicate this issue with another encrypted library, we can provide you one.

### Steps to Reproduce
The following command is executed in the Command CLI:
`loadEncryptedPackage("C:\Users\bua2ec\BRSL_Versions\Rexroth_BRSL.mol", "C:\temp");getErrorString()`
The output is:
`true
"Error: SetCurrentDirectoryW failed.
"`
And nothing is added to the library browser.

### Expected Behavior
Using `loadEncryptedPackage` in the Command CLI can successfully load packages which can be loaded via `File->Load Encrypted Library`.
If there is an error and the library cannot be loaded to output should be `false` and not `true`.

### Version and OS
 - OpenModelica Version: v1.22.0-dev-255-gdedd489acd (64-bit) PRO with instance API
 - OS: Windows 10, 64 bit

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
@perost can you look into that?

**Comment by perost** [comment]
#11171 should at least fix the return value, but I don't know why it fails in the first place.

The only places where we set the directory seems to be at the start of the call where we set it to the one containing the encrypted library, and then reset it when we're done. So I guess you'd get that error if the path to the file is wrong (I just added a proper error message for that just in case), but I'm not sure if it can go wrong in other ways.

I also don't know why we even do this, everything else is done with full paths so changing the directory doesn't seem to serve any purpose. Maybe @adeas31 has a better clue? I can't really test it myself since I have neither Windows nor OM with encryption support.

**Comment by abuntrock** [comment]
For clarification. It also fails in the same way if I do not specify the working directory as the second argument explicitly.

**Comment by perost** [comment]
> For clarification. It also fails in the same way if I do not specify the working directory as the second argument explicitly.

If the given working directory doesn't exist we just use the current directory instead, so giving an non-existent working directory is the same as giving no directory at all. And that might actually be why we `cd` to the directory containing the file to load, so we can later use `pwd` to get the current directory in that case. But if that's the reason it's still a bit weird to do it that way.

But in my opinion if the user asks for the files to be put in a specific folder we should either put them there or fail instead of just putting them somewhere else. So if the working directory doesn't exist we should try to create it instead.

**Comment by perost** [comment]
I made #11172 that implements my suggestion, i.e. create the working directory if it doesn't exist instead of using a different directory. But I'll need someone else to test it since I can't test it myself. It might not fix the issue here though, but at least it simplifies things a bit.

**Comment by adeas31** [comment]
You cannot mix the CLI with diagram modelling. Operations performed on the CLI not necessarily reflected in OMEdit.

**Comment by abuntrock** [comment]
The `loadEncryptedPackage` command mentioned in this issue also returns `true` way faster than loading the same library but not encrypted with `loadFile`. This also makes me believe that the `loadEncryptedPackage` fails despite returning true. 
As @perost explained, I was expecting that `loadEncryptedPackage` would add the the loaded package to the library browser just like `loadFile` is doing it for not encrypted packages.

**Comment by adeas31** [comment]
@perost is right. We have a special case for `loadEncryptedPackage` in OMEdit, calling it loads the library in browser.

I have successfully tested this now and the command like `loadEncryptedPackage("C:\Users\bua2ec\BRSL_Versions\Rexroth_BRSL.mol", "C:\temp");getErrorString()` works as expected. If the working directory doesn't exist then the package is unzipped in current directory.

Since this works as expected so I am not sure if #11172

**Comment by abuntrock** [comment]
I could test this with the encrypted version corresponding to the OMEdit 1.22 beta 6. My reported issue is now fixed. Thanks a lot.
