### ISSUE TITLE
Incorrect prefix unit for second variable chosen

### ISSUE THREAD

**Issue by scls19fr** [OpenModelica/OpenModelica#11201]
Hello,

Following discussion https://github.com/OpenModelica/OpenModelica/discussions/11200

Simulating this model

![image](https://github.com/OpenModelica/OpenModelica/assets/109167/94b6cd32-0242-4a86-a9c4-b3c86d4feb86)

```modelica
model chariot_portique
  constant Real rpm_max = 1450.0;
  constant Real v_max = 3.0;
  
  Modelica.Mechanics.Rotational.Components.IdealGearR2T idealGearR2T(ratio = (rpm_max*2*Modelica.Constants.pi/60)/v_max)  annotation(
    Placement(visible = true, transformation(origin = {28, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Rotational.Sensors.SpeedSensor speedSensor_moteur annotation(
    Placement(visible = true, transformation(origin = {-52, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Rotational.Components.LossyGear lossyGear(lossTable = [0, 0.8, 0.8, 0, 0], ratio = 1)  annotation(
    Placement(visible = true, transformation(origin = {-6, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Translational.Sensors.SpeedSensor speedSensor_chariot annotation(
    Placement(visible = true, transformation(origin = {72, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Translational.Components.Mass mass(m = 82000)  annotation(
    Placement(visible = true, transformation(origin = {122, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.CombiTimeTable combiTimeTable(extrapolation = Modelica.Blocks.Types.Extrapolation.HoldLastPoint, table = [0, 0; 0, 1520; 4, 1520; 4, 0; 8, 0; 8, -974; 12, -974; 12, 0; 16, 0; 16, -1520; 20, -1520; 20, 0; 24, 0; 24, 974; 28, 974; 28, 0; 32, 0], tableOnFile = false) annotation(
    Placement(visible = true, transformation(origin = {-66, -66}, extent = {{-80, 20}, {-60, 40}}, rotation = 0)));
  Modelica.Mechanics.Rotational.Sources.Torque torque annotation(
    Placement(visible = true, transformation(origin = {-100, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Translational.Sensors.ForceSensor forceSensor_chariot annotation(
    Placement(visible = true, transformation(origin = {90, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Translational.Sensors.PowerSensor powerSensor_chariot annotation(
    Placement(visible = true, transformation(origin = {60, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Rotational.Sensors.PowerSensor powerSensor_moteur annotation(
    Placement(visible = true, transformation(origin = {-68, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Rotational.Sensors.TorqueSensor torqueSensor_moteur annotation(
    Placement(visible = true, transformation(origin = {-36, -36}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(lossyGear.flange_b, idealGearR2T.flangeR) annotation(
    Line(points = {{4, -36}, {18, -36}}));
  connect(speedSensor_chariot.flange, idealGearR2T.flangeT) annotation(
    Line(points = {{62, 0}, {38, 0}, {38, -36}}, color = {0, 127, 0}));
  connect(combiTimeTable.y[1], torque.tau) annotation(
    Line(points = {{-125, -36}, {-112, -36}}, color = {0, 0, 127}));
  connect(forceSensor_chariot.flange_b, mass.flange_a) annotation(
    Line(points = {{100, -36}, {112, -36}}, color = {0, 127, 0}));
  connect(powerSensor_chariot.flange_a, idealGearR2T.flangeT) annotation(
    Line(points = {{50, -36}, {38, -36}}, color = {0, 127, 0}));
  connect(powerSensor_chariot.flange_b, forceSensor_chariot.flange_a) annotation(
    Line(points = {{70, -36}, {80, -36}}, color = {0, 127, 0}));
  connect(torque.flange, powerSensor_moteur.flange_a) annotation(
    Line(points = {{-90, -36}, {-78, -36}}));
  connect(powerSensor_moteur.flange_b, torqueSensor_moteur.flange_a) annotation(
    Line(points = {{-58, -36}, {-46, -36}}));
  connect(lossyGear.flange_a, torqueSensor_moteur.flange_b) annotation(
    Line(points = {{-16, -36}, {-26, -36}}));
  connect(speedSensor_moteur.flange, torque.flange) annotation(
    Line(points = {{-62, 0}, {-90, 0}, {-90, -36}}));
  annotation(
    experiment(StopTime = 32),
    uses(Modelica(version = "4.0.0")),
  Diagram(coordinateSystem(extent = {{-200, -100}, {200, 100}})),
  Icon(coordinateSystem(extent = {{-200, -100}, {200, 100}})),
  version = "");
end chariot_portique;
```

and displaying powerSensor_chariot.power and speedSensor_chariot.speed shows speedSensor_chariot.speed in km/s instead of m/s.

![image](https://github.com/OpenModelica/OpenModelica/assets/109167/cf3f4fa5-bfac-41fb-9eba-ce0b35f7618d)

Kind regards

**Comment by casella** [comment]
@adeas31 of course each plot should have its own prefix scaling. The displayed values are in common, but the prefixes needn't.

**Comment by casella** [comment]
@adeas31 do you think you can fix this easily?

**Comment by adeas31** [comment]
It is not trivial to implement. The current solution is based on reading the lower and upper bounds of the axes and finding the right multiple of 10. If we want each plot to have its own prefix then we need to change quite a lot.

The simplest solution can be that we show unit multiples in a drop down list and then instead of automatically picking a prefix let the user select it explicitly. But I am not sure if @ceraolo agrees with this solution.

**Comment by bilderbuchi** [comment]
> If we want each plot to have its own prefix then we need to change quite a lot.

I proposed an algorithm to achieve (something similar to) that in #11218.

**Comment by ceraolo** [comment]
I think solution as in https://github.com/OpenModelica/OpenModelica/issues/11201#issuecomment-2033307699 would do a good fraction of the job.  I would be pretty much satisfied with it. 
In principle I expect that in the future (don't know how far future) some way to plot combination of variables, included variables multiplied factors and/or translated by offset will be introduced, so if such plan exists, maybe more complicated display is not needed because the user can choose modified variables with factors/offsets to show.

Automatic individual prefixes as in  https://github.com/OpenModelica/OpenModelica/issues/11201#issuecomment-2033694635 would be obviously better than just what in https://github.com/OpenModelica/OpenModelica/issues/11201#issuecomment-2033307699. As usual, one must consider the cost/benefit balance.

**Comment by adeas31** [comment]
> I proposed an algorithm to achieve (something similar to) that in https://github.com/OpenModelica/OpenModelica/issues/11218.

@bilderbuchi we should implement the proposed algorithm and also #11217. However, the current issue can still be solved with only one axis. I will try to first solve this one and then move on to adding another y-axis.

> Automatic individual prefixes as in https://github.com/OpenModelica/OpenModelica/issues/11201#issuecomment-2033694635 would be obviously better than just what in https://github.com/OpenModelica/OpenModelica/issues/11201#issuecomment-2033307699. As usual, one must consider the cost/benefit balance.

@ceraolo I will try to keep the auto prefixing and also add support to explicitly change the display unit.

**Comment by scls19fr** [comment]
Thanks @adeas31

**Comment by adeas31** [comment]
PR #12221 fixes the actual problem reported in this issue. We want this for 1.23 release. @ceraolo you can test it.

We can further improve on it. I opened #12222 so it is possible to manually change the displayUnit.
@bilderbuchi I targeted the #11218 for 1.24 release.

**Comment by adeas31** [comment]
Ported this to maintenance/v1.23 #12223

**Comment by ceraolo** [comment]
I think the fix works as expected.
We do not get a dramatic improvement, because prefixes are quantised by three orders of magnitude.
Here's this ticket plot as is now shown (max speed is 3m/s, and it is therefore hardly visible with the selected vertical trimespan):

![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/92f33156-be7b-4aeb-89e4-3f8b89278caf)

So, it is a first step forward. Twin scales and postprocessing of variables would in the future further incease the "plottability" of inhomogeneous quantities.

**Comment by casella** [comment]
Unit prefix was never meant as a replacement for twin scales 😅 . We also need that.

In fact, a very useful feature for control systems would be to plot a bunch of variables in the same plot by suitably normalizing them. Of course you can do it in Modelica by adding variables such as `Real v_n = v/v_nom;` but in some cases you don't want or cannot change the code, so it would be useful.
