### ISSUE TITLE
The version v1.21.0 refers to the target config-3rdParty that doesn't exist

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#11325]
I am struggling to build v1.21.0 for the FreeBSD port because the target config-3rdParty doesn't exist.

It is only referenced in one gmake command:
```
$ grep -r config-3rdParty *
Makefile.in:    $(MAKE) -C OMSimulator config-3rdParty CERES=OFF "host_short=@host_short@" CC="@CC@" CXX="@CXX@" CFLAGS="@CFLAGS@" CPPFLAGS="@CPPFLAGS@" CXXFLAGS="@CXXFLAGS@" CMAKE=$(CMAKE)
Makefile.omdev.mingw:   $(MAKE) -C OMSimulator config-3rdParty CC="$(CC)" CXX="$(CXX)"
omsimulator.cmake:                                                config-3rdParty
```

But there is no definition of the config-3rdParty target and the build fails:
```
gmake[4]: Entering directory '/usr/ports/science/openmodelica/work/OpenModelica-1.21.0/OMSimulator'
gmake[4]: *** No rule to make target 'config-3rdParty'.  Stop.
```

What is going on with config-3rdParty in v1.21.0 ?

Thanks,
Yuri

**Comment by mahge** [comment]
Make sure your submodules are referring to the correct commit. It looks like your OpenModelica repository is an older commit while the submodule OMSimulator is probably at the tip of master. 

Something like 
```
git submodule update --recursive 
```

should do.

**Comment by mahge** [comment]
I also recommend that you use the [CMake based configuration and build](https://github.com/OpenModelica/OpenModelica/blob/master/README.cmake.md) on FreeBSD if you have no specific reason not to

**Comment by yurivict** [comment]
I use cmake, but cmake seems to run gmake commands.

This problem also exists in the repository that is cloned with 'git clone --recurse-submodules' and then updated to the tag v1.21.0.

**Comment by mahge** [comment]
> that is cloned with 'git clone --recurse-submodules' and then updated to the tag v1.21.0

I think you still need to update the submodules to the correct references. If you just clone as you said and then checkout tag v1.21.0, that will change only the root OpenModelica repository. The submodule references will still point to what the OpenModelica master was referring to instead of what should be at v1.21.0. So just running the submodule update command after checking out the v1.21.0 tag should fix it.

If that does not fix it then there must be something else going wrong and you have to show us how exactly to reproduce the issue.

**Comment by yurivict** [comment]
I've moved on and have updated the FreeBSD port to the latest beta.
