### ISSUE TITLE
OMDev downloading is too slow.

### ISSUE THREAD

**Issue by suyufeng1** [OpenModelica/OpenModelica#11369]
git clone https://openmodelica.org/git/OMDev.git
What's the solution

**Comment by mahge** [comment]
OMDev is a bit too big and it of course will take some time to download. It is basically MSYS2 with all the libraries and tools you need preinstalled. We also have some additional files in there which you would not get through the MSYS2 package manager. 

I think you do not need those extra files for your use cases so you can probably just use MSYS2 directly instead of OMDev. However, I think it will probably take you more time to download and install MSYS2, then install all the compilers, tools and libraries needed to compile OpenModelica.  

If you want to try clean MSYS2 instead of OMDev, then you can follow the instructions in https://github.com/OpenModelica/OpenModelica/issues/9509#issuecomment-1282205766. Let me know if you run into issues.

**Comment by suyufeng1** [comment]
> OMDev is a bit too big and it of course will take some time to download. It is basically MSYS2 with all the libraries and tools you need preinstalled. We also have some additional files in there which you would not get through the MSYS2 package manager.
> 
> I think you do not need those extra files for your use cases so you can probably just use MSYS2 directly instead of OMDev. However, I think it will probably take you more time to download and install MSYS2, then install all the compilers, tools and libraries needed to compile OpenModelica.
> 
> If you want to try clean MSYS2 instead of OMDev, then you can follow the instructions in [#9509 (comment)](https://github.com/OpenModelica/OpenModelica/issues/9509#issuecomment-1282205766). Let me know if you run into issues.

Thank you. I'll just keep waiting

**Comment by mahge** [comment]
🙂Okay. Then I will close this ticket since there is nothing to be done for it.
