### ISSUE TITLE
Modeling an oscillator in Modelica

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#11443]
### Description

The model compiles and simulates fine.  But when I look at the output, there are no voltage drops across the resistors, no current flows and no sign of oscillation.

### Steps to Reproduce

Load and simulate the following model,

```mo
model RC_Relaxation_Oscillators
  Modelica.Electrical.Analog.Basic.Resistor resistor(R(displayUnit = "kOhm") = 15000) annotation(
    Placement(visible = true, transformation(origin = {-14, -42}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Basic.Resistor resistor1(R(displayUnit = "kOhm") = 10000) annotation(
    Placement(visible = true, transformation(origin = {6, 56}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Resistor resistor2(R(displayUnit = "kOhm") = 15000) annotation(
    Placement(visible = true, transformation(origin = {4, -16}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Ground ground annotation(
    Placement(visible = true, transformation(origin = {-40, -22}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Capacitor capacitor(C(displayUnit = "uF") = 0.0001000000000000001) annotation(
    Placement(visible = true, transformation(origin = {-40, 10}, extent = {{10, -10}, {-10, 10}}, rotation = 90)));
  Modelica.Electrical.Analog.Ideal.IdealOpAmpLimited opAmp annotation(
    Placement(visible = true, transformation(origin = {0, 20}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Sources.ConstantVoltage constantVoltage(V = 15) annotation(
    Placement(visible = true, transformation(origin = {58, 10}, extent = {{10, -10}, {-10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Sources.ConstantVoltage constantVoltage1(V = 15) annotation(
    Placement(visible = true, transformation(origin = {56, 56}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Ground ground1 annotation(
    Placement(visible = true, transformation(origin = {112, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Ground ground2 annotation(
    Placement(visible = true, transformation(origin = {108, -20}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Ground ground3 annotation(
    Placement(visible = true, transformation(origin = {-14, -78}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(capacitor.n, ground.p) annotation(
    Line(points = {{-40, 0}, {-40, -12}}, color = {0, 0, 255}));
  connect(resistor.p, resistor2.p) annotation(
    Line(points = {{-14, -32}, {-14, -16}, {-6, -16}}, color = {0, 0, 255}));
  connect(capacitor.p, opAmp.in_n) annotation(
    Line(points = {{-40, 20}, {-40, 26}, {-10, 26}}, color = {0, 0, 255}));
  connect(resistor1.p, opAmp.in_n) annotation(
    Line(points = {{-4, 56}, {-20, 56}, {-20, 26}, {-10, 26}}, color = {0, 0, 255}));
  connect(opAmp.out, resistor2.n) annotation(
    Line(points = {{10, 20}, {24, 20}, {24, -16}, {14, -16}}, color = {0, 0, 255}));
  connect(resistor1.n, opAmp.out) annotation(
    Line(points = {{16, 56}, {24, 56}, {24, 20}, {10, 20}}, color = {0, 0, 255}));
  connect(opAmp.in_p, resistor2.p) annotation(
    Line(points = {{-10, 14}, {-14, 14}, {-14, -16}, {-6, -16}}, color = {0, 0, 255}));
  connect(constantVoltage.n, opAmp.VMin) annotation(
    Line(points = {{48, 10}, {0, 10}}));
  connect(resistor.n, ground3.p) annotation(
    Line(points = {{-14, -52}, {-14, -68}}, color = {0, 0, 255}));
  connect(constantVoltage1.n, ground1.p) annotation(
    Line(points = {{66, 56}, {112, 56}, {112, 40}}, color = {0, 0, 255}));
  connect(constantVoltage.p, ground2.p) annotation(
    Line(points = {{68, 10}, {108, 10}, {108, -10}}, color = {0, 0, 255}));
  connect(opAmp.VMax, constantVoltage1.n) annotation(
    Line(points = {{0, 30}, {36, 30}, {36, 56}, {66, 56}}, color = {0, 0, 255}));
  annotation(
    uses(Modelica(version = "4.0.0")));
end RC_Relaxation_Oscillators;
```

### Expected Behavior

There should be a voltage drop and current flow.

### Version and OS

 - OpenModelica Version: OpenModelica v1.23.0-dev-53-gbf2b968dfe (64-bit)
 - OS: Windows 10, 64 bit

### Additional Context

The model behaves as expected in Dymola.

**Comment by casella** [comment]
Dymola also produces the same result
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/a00e6dd8-f0df-4663-9acc-5f3ee82c6942)

**Comment by casella** [comment]
OK, there are two problems with this model. 

The first is well-know by @ceraolo, whose student had similar issues many times, until he got fed up and asked us to improve the visualization of connections in OMEdit 😅. @adeas31 has been working on this recently.

If you open the model reported above with OpenModelica 1.22.0-dev.beta.6, you get this diagram
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/d861795d-f432-4966-b476-2c8321893979)

So far so good? Not really. If you zoom in on the top right corner, this is what you see:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/6043e928-2e74-4ab5-a3b9-50a5da0d7603)

I guess it is now clear what the problem is: you accidentally connected the `VMax` pin of the op amp not to the positive pin of the `constantVoltage1` voltage source, but to the _negative_ pin, passing over the component. If you right-click on the voltage source component and rotate it counter-clockwise, this is what you get:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/c0720fab-c9cc-4b5e-a07d-211ba0a5633b)

So, basically, the voltage source is dangling (which is perfectly fine in terms of circuit equations) and the op amp `VMax` pin is connected directly to the ground. This is is also apparent from the simulation result:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/a48b5b48-237a-46cb-8f86-317b2df8f025)

So, the first fix to the model is to connect the positive voltage source correctly. Very importantly, you also need to initialize the voltage of the capacitor to some non-equilibrium value, e.g. 1 V, otherwise getting out of the unstable equilibrium in simulation, where there are no random voltage fluctuations to help you doing that, would take forever. 

If you do so, you get the following behaviour of the output voltage:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/67316195-4c15-45b4-9543-cb6d174263a6)

Now the second problem of your model becomes apparent. The output voltage grows exponentially as expected, because of the positive feedback, until it reaches the VMax supply voltage, but at that point the simulation crashes because of a singular system.

The reason of this behaviour is that you are using an _extremely_ idealized op amp model, which is defined by the following equations:
```modelica
  in_p.v - in_n.v = unitVoltage*smooth(0, (if s < -1 then s + 1 else if s > 1  then s - 1 else 0));
  out.v = smooth(0, if s < -1 then VMin.v
                    else if s > 1 then VMax.v 
                    else (VMax.v - VMin.v)*s/2 + (VMax.v + VMin.v)/2);
```
which are similar to those of an ideal diode, using an auxiliary variable `s`. As suggested by the icon, the response curve of this model is infinitely steep: while the voltage output goes from VMin to VMax, the voltage difference between the two input pins remains _exactly_ zero. Additionally, the response of this model is istantaneous. This is simply too idealized to allow solving the circuit equations of this model reliably, causing frustration.  

BTW, my friend @dzimmer gave a really inspired and insightful talk on this topic during his keynote at the Modelica Conference in Aachen a couple of weeks ago. His main point is, we should probably re-think from the very basics how we describe modular models, because if we idealize away too many things, the system models we obtain by modular composition may end up in numerical trouble when situations arise that can only be properly described by the behaviour that was idealized away. 

To make a simple example, considering what happens when you connect two diodes in series: if you do so with the physical diodes, that's a perfectly legitimate piece of circuit, with all voltages and currents well defined. However, if you use idealized models of diodes that assume zero voltage drop when the current flows in the conduction direction, the model becomes singular, because the voltage in-between the two is undetermined. Of course that's not the case if you use a more physical model of the diode, with the exponential voltage-current law.

In general, @dzimmer argues that we should add some crucial dynamics (corresponding to the kinetic energy in a Hamiltonian formulation of the system dynamics) to avoid this problems. In this specific case, that is actually not necessary, as in the previously mention cased of the two diodes. You just need to use the slightly less idealized component model `IdealizedOpAmpLimited`, which has a very steep response (by default an amplification factor of 15000), but not an infinitely steep one. This is enough to get a solvable system of equations when the output voltage reaches the supply limits. 

This is the updated model [RC_Relaxation_Oscillators.zip](https://github.com/OpenModelica/OpenModelica/files/13170518/RC_Relaxation_Oscillators.zip) and this is the simulated output voltage:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/933e4f69-afa0-4d51-a249-50d7d5fbb443)

Et voilà 😄 

Bottom line 1: beware of stray connections.

Bottom line 2: make sure you use the appropriate idealization for a given system behaviour when choosing component models. 

This is of course easier said than done, doing it properly is the essence of the art of modelling. As @dzimmer argued in his keynote, in the future we may want to develop libraries that are safer from this point of view, i.e., actually plug&play. The Modelica Standard library actually isn't. The downside would be, that such libraries would in general lead to more complex models than what is strictly necessary if you know what you are doing.

Hope this helps 😃
