### ISSUE TITLE
FMU exported using CVODE do not find libsundials_cvode.dll

### ISSUE THREAD

**Issue by mdebaGH** [OpenModelica/OpenModelica#11464]
### Description
I am trying to export FMUs in order to call them in other simulation environments (in my case Fortran, but the comment is rather general). The FMU export using explicit euler works properly, but I need more powerful solvers for my purposes so Itried to export it using CVODE. The export procedure works, but then once the FMU is instantiated in the other simulation environment an error arise stating that "a binary file is not found".
Loading the same FMU in dymola and reading there the error I realised that the missing binary file is the libsundials_cvode.dll dynamic library.

To solve the issue I had simply copied the missing library in the execution folder, but I think that should be possible to directly link the library to the exported FMU, ins't it?

### Steps to Reproduce

To reproduce the error you can export the FMU from the .mo file within the attached zip using CVODE as solver and loading somewhere (either in Dymola or in python to make it simple, for example using pyfmi package) trying to instantiate it. 
If you do the same with the FMU extracted using Explicit Euler you'll see that the instantiate procedure will end up correctly.
Then add to the path the location of the libsundials_cvode.dll and you'll get a working instantiation for the CVODE FMU as well.

### Version and OS

 - OpenModelica Version: 1.23 (nightly build)
 - OS: Windows 10, 64 bit
 - Modelica Standard Library 4.0.0

[TestCaseFMI_tofortran.zip](https://github.com/OpenModelica/OpenModelica/files/13179749/TestCaseFMI_tofortran.zip)

Thanks a lot for the support

Marco

**Comment by casella** [comment]
@arun3688, @mahge, can you please comment on that?

**Comment by casella** [comment]
@arun3688 is off until Dec 10 and @mahge can only work on omc sporadically now. @AnHeuermann maybe you can comment on that?

**Comment by AnHeuermann** [comment]
> To solve the issue I had simply copied the missing library in the execution folder, but I think that should be possible to directly link the library to the exported FMU, ins't it?

The CMake FMU build will do exactly that and copy the SUNDIALS libaries into the bin directory. You need to activate [`--fmuRuntimeDepends=modelica`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmuruntimedepends) and of course [`--fmuCMakeBuild=true`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmucmakebuild).
The problem is, that our CMake shipped with OpenModelica is outdated, but #10939 will fix that.

-------------

In the meantime you can copy the runtime dependencies manually.

In theory it is possible to update CMake yourself, but I wouldn't recommend:
Start `C:\Program Files\OpenModelica\tools\msys\msys2.exe`, remove old `cmake` and install [https://packages.msys2.org/package/mingw-w64-x86_64-cmake](mingw-w64-x86_64-cmake).
(Very untested...)

**Comment by BasilioPV** [comment]
@AnHeuermann @mdebaGH Tested with nightly build today and all dependencies are found inside FMU:

![image](https://github.com/user-attachments/assets/52045de9-ce44-4f8d-b6e4-198d5a68a0be)

Several bugs related was corrected, and this issue was solved. Ready to close?

**Comment by casella** [comment]
I guess so. This issue should have been fixed some time ago.
