### ISSUE TITLE
The C compiler is not able to compile a simple test program when build the project in Clion.

### ISSUE THREAD

**Issue by chygithub2020** [OpenModelica/OpenModelica#11482]
#### Os: 
windows 10 home
#### Build:
Cmake and Toolchain in CLion
#### Error  Info:
CMake Error at C:/OMDev/tools/msys/mingw64/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler
    "C:/OMDev/tools/msys/mingw64/bin/gcc.exe"
  is not able to compile a simple test program.
#### Details:
I have build the project by commands correctly and I want to build it in Clion(2023.3.2) so that I can read the source code expediently.But my settings doesn't work.
#### Toolchain Settings:
![image](https://github.com/OpenModelica/OpenModelica/assets/70186881/9bcd45a7-80dd-4e24-beeb-ec10ff4d6d22)

#### Cmake Settings:
![image](https://github.com/OpenModelica/OpenModelica/assets/70186881/e7fdc428-fd97-44f0-b5db-25b938a81236)

**Comment by mahge** [comment]
Sorry I forgot about this. The issue is the `make` executable you are using. You should use  `msys/usr/bin/make.exe` instead of `msys/mingw64/bin/mingw32-make.exe`. You can see this in the config file @AnHeuermann provided you above. 

It can be confusing but one way to think about this is, we want to use the `MinGW` compilers in the `MSYS` environment. This means we need to use the MSYS `make.exe` instead of the `mingw32-make.exe` which is intended to be used from Windows Command Prompt environments.

I also see that you have modified the default toolchain. I recommend you add a new toolchain for `OMDev` and leave the default one as it was originally. I tried the same setting as you (except for the make executable and a new Toolchain) and I can configure OpenModelica.

**Comment by chygithub2020** [comment]
Thank you very much!I have build successfully in Clion. Note that we need to change the debug Timeout in Clion otherwise debug will time out.We also need to change the Target in run configuration to the exe file in the install_cmake directory instead of the default one.

**Comment by dollPrincess** [comment]
> Thank you very much!I have build successfully in Clion. Note that we need to change the debug Timeout in Clion otherwise debug will time out.We also need to change the Target in run configuration to the exe file in the install_cmake directory instead of the default one.

Hello! I am also trying to use clion to build the OpenModelica. 
Could you remember how to configue this? Pleaseee help me with this.

I've set the toolchain & cmake like you did in a project I were using in vs environment for other use, but when I shut it down and opened the OpenModelica in CLion, suddenly the window popped up.

![image](https://github.com/user-attachments/assets/8984a3e3-28eb-4394-918e-3252de4aa7e2)

I've tried all the options listed by clion, but I still can't find which one is the right one to set. I didn't find how to set this one on the web and after reading the official documentation I still don't get it. How did you set this one up, please?
