### ISSUE TITLE
OpenModelica uses the deprecated QWebKit Qt5 component

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#11497]
### Description

QWebKit was deprecated and is being removed.
But configure fails without it:
```
CMake Error at /usr/local/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5WebKitWidgets"
  with any of the following names:

    Qt5WebKitWidgetsConfig.cmake
    qt5webkitwidgets-config.cmake

  Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebKitWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  OMShell/OMShell/OMShellGUI/CMakeLists.txt:6 (find_package)
```

### Version and OS

 - OpenModelica Version: 1.22.0-beta-1
 - OS: FreeBSD 13.2

### Additional Context

QWebKit needs to be replaced with QWebEngine.

**Comment by mahge** [comment]
Yes we need to do this. It is also going to be unavailable on macOS any day now. The only problem is that `QtWebEngine` is not yet available on `MSYS2` on Windows due to Chromium not being available. They are working on it right now and hopefully it will be ready soon. In the meantime, however, we can selectively use `QtWebEngine` or `QtWebKit` based on availability,

There are tickets about this, e.g., https://github.com/OpenModelica/OpenModelica/issues/7260, https://github.com/OpenModelica/OpenModelica/issues/9592. There is also a PR attempting to do this https://github.com/OpenModelica/OpenModelica/pull/9620. I will close this as duplicate and we can continue on the other tickets.
