### ISSUE TITLE
Check for when-clause if using discrete keyword in variable definition 

### ISSUE THREAD

**Issue by MatteoSchiavon** [OpenModelica/OpenModelica#11568]
### Description

Modelica checks that variables defined as discrete appear in LHS of "when" statements. However, as per "Modelica Language Specification (MLS) 3.5" the when-clause can be removed and the variables will be associated with the inferred clock (Chapter 16).

### Steps to Reproduce

The model is:
```modelica
block Integrator "Discrete-time integrator with clocked input and output signals"
  extends Modelica.Clocked.RealSignals.Interfaces.PartialClockedSISO;
  discrete Real x; 
equation
  x = previous(x) + u*interval(u);
  y = x;
end integrator;
```
NOTE: this block must receive a clocked input signal.

### Expected Behavior

If we leave the "**discrete**" keyword the following error message will appear "Following variable is discrete, but does not appear on the LHS of a when-statement: 'x'". The block works fine if I remove the discrete keyword and the FMI variability of the state variable "x" will be indeed discrete. From the MLS it seems not necessary to use a when-clause to define the equation of discrete time variables, and as I mentioned the model works without the discrete keyword and there is no when-clause. Could this be a wrong check on discrete variable definitions?

### Screenshots

NA

### Version and OS

 - OpenModelica Version: 1.23-dev-28-gd1144cfa88 
 - OS: Windows 10, 64 bit

### Additional Context

NA

**Comment by casella** [comment]
@MatteoSchiavon _discrete-time_ variables and _clocked_ variables are two completely different concepts. They are not interchangeable and should not be mixed up. This can be a bit confusing, but has historical reasons. Discrete-time variables were defined very early on in Modelica 1.1 (1998) to describe hybrid systems, and were of course kept for backwards compatibility, while clocked variables were introduced much later in Modelica 3.3 (2012) to describe synchronous systems.

Discrete variables are defined all the time, but they are allowed to change only at events, where they can be subject to event iteration, possibly involving continuous-time variables. Clocked variables are only defined when their clock is active, and are clearly separated by the continuous-time variables by sample() and hold() functions.

The when statement is indeed optional in some cases, when dealing with _clocked_ variables, not discrete-time ones.

Your model should be written like this:
```modelica
block Integrator "Discrete-time integrator with clocked input and output signals"
  extends Modelica.Clocked.RealSignals.Interfaces.PartialClockedSISO;
  Real x; 
equation
  x = previous(x) + u*interval(u);
  y = x;
end Integrator;
```
Since variable `x` is involved in an equation that also involved the clocked variable `u`, it is _automatically inferred_ to be a clocked variable, _with the same clock as `u`_. That's the beauty of synchronous Modelica, clocks are propagated automatically and only need to be defined at one point.

**Comment by casella** [comment]
Not really. There are no such things as discrete variable partitions. Only clocked discrete-time partions and continuous time partitions (that can also contain discrete variables). The concept of clocked variables is orthogonal to continuous time and discrete variables. Please read
- [Section 16](https://specification.modelica.org/maint/3.6/synchronous-language-elements.html)
- the paper introducing Synchronous Modelica http://dx.doi.org/10.3384/ecp1207615
- https://mbe.modelica.university/behavior/discrete/sampling/

**Comment by MatteoSchiavon** [comment]
Thanks! I did not explain myself in a perfect way in the last message but now I am on the same page. Very much appreciated :)

And thanks for the suggestion! However, I have read that article introducing Synchronous Modeluca and that actually tricked me because in the examples they define as "discrete" all the clocked variables (see for instance the model in Chapter 2.2 page 16). Either the ideas of discrete-time and clocked variables have evolved since then or, for me from that paper, it is not clear that the concept of clocked variables (synchronous elements) is orthogonal to continuous-time and discrete-time variability.

On the other hand, I believe that in the Language Specification the orthogonality of "Variability of Expressions" and "Synchronous Elements" is very well pointed out, as well as the difference between "Piecewise-constant variable" and "Clocked variable" within discrete-time expressions in Chapter 16! Moreover, in the MLS the concept of "clocked state variable" is also introduced while in the introduction paper, they talk about "discrete-time state variable" (can be seen in the same model example of 2.2 page 16).

Matteo

**Comment by casella** [comment]
In the end, the text of the language specification prevails. Sometimes it is not particularly user-friendly, but I think Section 16 is almost like a textbook from this point of view.
