### ISSUE TITLE
Stack overflow for illegal matrix inverse

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#11589]
### Description

When writing an illegal Modelica model with a matrix inverse OpenModelica will crash.

### Steps to Reproduce

```modelica
model inverseMatrix
  Real A[2,2] = {{1,2},{3,4}};
  Real B[2,2];
equation
  B = A^(-1);
end inverseMatrix;
```

```
loadFile("InverseMatrix.mo"); getErrorString();
translateModel(InverseMatrix); getErrorString();
```

```
Error: Stack overflow occurred while evaluating translateModel(InverseMatrix):
[bt] #1 /path/to/OpenModelica/build_cmake/install_cmake/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaRuntimeC.so(mmc_setStacktraceMessages_threadData)
[bt] #2 /path/to/OpenModelica/build_cmake/install_cmake/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaRuntimeC.so(mmc_do_stackoverflow)
[bt] #3 /path/to/OpenModelica/build_cmake/install_cmake/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so()
[bt] #4...1024 /path/to/OpenModelica/build_cmake/install_cmake/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(NFExpandExp.expandBinaryPowMatrix2)
[bt] #1025 [...]
```

### Expected Behavior

Throw an error and tell the user, that it's not allowed to write an inverse matrix.
Maybe catch if the exponent is non-positive for a matrix power.

### Version and OS

 - OpenModelica Version: v1.23.0-dev-146-gfce39683e8-cmake
 - OS: Ubuntu Focal

**Comment by perost** [comment]
Do you intend on fixing it yourself, or should I do it?

**Comment by AnHeuermann** [comment]
If you know where to check in the Frontend if the matrix exponent is positive it's probably best if you can do it.

**Comment by perost** [comment]
#11590 at least partially fixes the issue, it should no longer segfault and an error is printed if the rhs is a negative literal (just the generic "cannot resolve type of expression" error, we can add a more specific error if needed).

There are still some things that could be improved though. We only print an error if the lhs is a literal, since evaluating e.g. constants/structural parameters happens later. But that might be good enough as long as we handle it properly in the backend/runtime, the frontend can't catch everything.

But if looks like the code generation doesn't handle matrix exponentation at all, so it only works if the rhs is a known constant such that the expression can be simplified to something else. If the rhs is negative or non-constant we end up with `daeExpBinary:ERR for POW_ARR` in the C code which then of course fails to compile.

**Comment by casella** [comment]
Should we open a separate ticket asking for full support of matrix exponentiation as defined in [Section 10.6.8](https://specification.modelica.org/maint/3.6/arrays.html#scalar-exponentiation-of-matrices)?

**Comment by perost** [comment]
> Should we open a separate ticket asking for full support of matrix exponentiation as defined in [Section 10.6.8](https://specification.modelica.org/maint/3.6/arrays.html#scalar-exponentiation-of-matrices)?

I guess it could be considered a part of  #11275.

**Comment by AnHeuermann** [comment]
Fixed by https://github.com/OpenModelica/OpenModelica/pull/11590
