### ISSUE TITLE
Conditional components (and variables?) And their usage on OM

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11713]
Modelica language specification states that conditional components can be defined but only can be used by connecting them (this excludes the access and use of component internal variables).
By now, OM permits the definition of conditional components and also variables. It's also possible access to component internal variables and use them, with the condition that in any conditional path all equations must be solved (of course...)
For me this is an enhancement from Modelica language specification, but this features raises error on other Modelica tools.
Does OM follow a strict Modelica language implementation? Or OM can provide non-standard enhancements?

**Comment by perost** [comment]
You should at least get a warning if you use a conditional component in a way that's not allowed, or an error if you use the `--strict` flag. The reason why we only give a warning by default is that conditional components have been abused in various creative ways by libraries.

If other tools are more strict nowadays we might consider changing it to be an error by default instead, but we'll have to check how that affects the libraries we support. And even if conditional components are still used incorrectly we might be able to be more restrictive in what we allow.

But if you have any examples of illegal uses of conditional components where you don't even get any warnings, please let us know.

**Comment by casella** [comment]
Referring to conditional components (and variables therein) in the equation sections is forbidden, even though sometimes tools forget to enforce that.

As I understand, there are only two ways to use them in models. One is to connect them to the model, in that case the connection is removed when the conditional component is inactive. The other one is to bind them to the rest of the model through their declaration, e.g.:
```modelica
model M
  Boolean enable;
  Real x;
  Real y = sin(x) if enable;
equation
  x = time;
end M;
```

**Comment by BasilioPV** [comment]
Putting a equation (with time variable "x") in the definition part of a variable ("y") is new for me  :-)

  **Real y = sin(x) if enable;**

This is Modelica language compliant?

Another question: All translation warnings are raised on a Modelica language standard deviation?, There are other types of translation warnings not related with Modelica language standard?
(It would be useful to identify if the warning is a violation of Modelica standard...)

**Comment by casella** [comment]
> Putting a equation (with time variable "x") in the definition part of a variable ("y") is new for me :-)
> 
> **Real y = sin(x) if enable;**
> 
> This is Modelica language compliant?

Of course it is, it's called "[binding equation](https://specification.modelica.org/maint/3.6/equations.html#equation-categories)". 
There are more things in Modelica Horatio, than are dreamt of in your philosophy 😃 

> Another question: All translation warnings are raised on a Modelica language standard deviation?, There are other types of translation warnings not related with Modelica language standard? (It would be useful to identify if the warning is a violation of Modelica standard...)

As a rule, violations of Modelica standard lead to errors, not to warnings. OpenModelica tries to be strict with standard compliance. There are [some flags](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-allownonstandardmodelica) to relax some rules, mostly meant to evaluate if a certain library developed with some other non-strict Modelica tool can work on Modelica. The idea is that if it does, it would be best to make the library compliant and eventually stop using the flag.

Warnings are normally related to potential _usage_ errors. For example, if a parameter has no value, according to the standard it takes the start attribute as a value, but a warning is issued, because most likely you forgot to set it to some meaningful value. Another case is iteration variables of implicit nonlinear systems which have the default start attribute of zero: although this is not prohibited by any means by the standard, it may lead to convergence problems.

Thinks of warnings as things that may _potentially_ reveal issues of your Modelica models, so they should be checked.

**Comment by perost** [comment]
> Putting a equation (with time variable "x") in the definition part of a variable ("y") is new for me :-)
> 
> **Real y = sin(x) if enable;**
> 
> This is Modelica language compliant?

Yes, conditional components can be declared like normal components, and they can also be modified and/or used in connections.

> Another question: All translation warnings are raised on a Modelica language standard deviation?, There are other types of translation warnings not related with Modelica language standard? (It would be useful to identify if the warning is a violation of Modelica standard...)

Any warning that complains about the model should be due to violating the Modelica standard. Then there might be warnings related to the compiler itself, such as invalid command line options, but it should be fairly obvious which is which.

**Comment by BasilioPV** [comment]
Thanks for the answers and to give me the insight of how OM works!
By now, the bad usage of conditional components are raised as a warning into OM, so it is all Ok.
I will close this issue as completed, and fully agree with the working basis of OM. Good job!
