### ISSUE TITLE
Troubles when controlling switches

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11748]
### Description
I have a model for which OM has troubles in controlling a switch. I previously opened #11746, which was an oversimplification of my actual problem, for which @casella correctly observed that the initial steady-state was bi-stable, so two different solutions were possible, and once one way was taken, it lasted forecer.

Here I propose a more complete model showing my issue. It represents the discharge of a battery.
When the battery voltage (cell1.p.v) reaches 3.5 V,  switch sw should open and the circuit current be interrupted. However, OM gets into trouble when 3.5 V is reached, and hangs.

### Steps to Reproduce
1. Load  [Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/13717869/Test.mo.txt)
2. open and run Es2. Simulation hangs when cell1.p.v reaches 3.5 V
 
### Screenshots
Diagram:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/3f0721f3-ffa1-4223-bbe0-b7b28d7a77d9)

### Expected Behavior
I would expect to see the following plot (from Dymola):
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/1b0d67b7-defd-454e-9ea9-5ff449a2439b)

OpenModelica Version: 
 OpenModelica v1.22.0-dev-341

**Comment by casella** [comment]
OK, this is even less trivial than #11746 😅 

The problem here is that there is an algebraic loop involving currents and voltage, but also logic conditions. Additionally, you are using a logic loop breaker `pre1` in parallel to the loop (I guess as a kind of memory block), but you are not using one to actually break that loop, which is one of the intended uses of such blocks.

In this case, the backend tries to use tearing to solve the algebraic loop, by putting the logic or integer variables as torn ones, and hoping that the resulting smaller system is smooth enough that it can be solved by the Newton method. You can check this with the Declarative Debugger:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/0f4086f2-8d61-4259-b8e5-5a07442a7f00)
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/9092e2f6-df37-4587-be10-15cd9e4886cb)

Apparently this doesn't work this time, probably because the system is not smooth enough or something.

I currently have no time to delve deeper into this and figure out exactly what the reason for non-convergence is, maybe this could be an interesting case study for @phannebohm, please have a look. In principle there could be a way to solve the problem as it is posed right now.

But then the modeller in me kicks in and asks one question: is it really reasonable to assume that the switch is activated without _any_ delay, and stubbornly try to solve the resulting mixed system of algebraic equations _simultaneously_? This looks to me more like solving an academic mathematical puzzle than solving a real-life modelling problem. It turns out, in real life _there is no such thing as an instantaneously acting switch_. 

I would then add an infinitesimal delay to the switch command input, which will break the logic feedback loop that makes that algebraic system a mixed one, and rely on event iteration to handle it. After all, if this logic is meant to work in real life, it will have to do so with a bit of delay in the loop. You don't really need to model the time delay accurately, as this is way beyond the level of detail of your model. But modelling non-instantaneous action of this switch control loop, yes, absolutely. 

Infinitely fast control loop are a nice abstraction for system-level modelling, _as long as they work_. When they don't, they should be replaced with something that preserves some causality, as in real life.

If you do so (see the attached updated [Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/13718872/Test.mo.txt)) the mixed algebraic loop is gone you get the result you are looking for without a hiccup:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/a0aac2f2-e86a-44f4-a5e4-0190179989a2)

@ceraolo would this be OK for you as a solution?

**Comment by ceraolo** [comment]
Yes, this is perfect, Thank you.
Please, feel free of closing this ticket of you want.

**Comment by ceraolo** [comment]
Pre  () s necessary to avoid an infinite opening/closing sequence

**Comment by casella** [comment]
Note that 1ms delay will take longer to simulate, because of more detail in the simulation. But I guess that's not a problem with this model. The important point is to break the loops that cause mixed algebraic equations with boolean/integer unknowns.
