### ISSUE TITLE
Simple logic probably mulfunctions

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11746]
### Steps to Reproduce
Consider this model: 
[Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/13713190/Test.mo.txt)

![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/8d0a4158-068d-4b7e-9182-84b543915f2d)

I expect the switch to be initially closed then to open as follows (from Dymola):
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/22c871b5-16db-4917-ac51-da87f4df1f9b)

OM instead considers that switch always open:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/f8eb4dee-0f4a-45d1-8d9a-6b852fd1e1ce)

(The presence of pre-or pair here is redundant; it is however needed in the original model where I discovered this issue, where the voltage source is a battery, instead).

### Expected Behavior
I expected to see the behavour as shown in the plots from Dymola

### Version and OS
OM  v1.23.0-dev-192 Win64

**Comment by casella** [comment]
I am not sure how Dymola obtains that solution, but OpenModelica's solution is perfectly fine. 

The switch `sw` is opened when its input is true, which happens when at least one of the outputs of `pre1` and `lessThreshold` is true. During initialization, a stable condition is established whereby the switch is open, the voltage across the load is negligible, the output of `lessThreshold` is thus active, and it keeps the output of the `or1` block true, which in turn ensures the switch remains open indefinitely.

Of course there is another possible initial stable state, in which the switch is closed, the voltage drop is high, the output of `lessThreshold` is false, and so is the output of the or block, which keeps the switch closed until the voltage drop falls below the threshold. That is the initial state found by Dymola.

However, in which state you end up at initialization is _completely arbitrary_. So, I would argue that this model has an ill-posed initialization problem, as it has two perfectly legitimate initial solutions.

In fact, if you check the initial equation system 17 with the declarative debugger, you can see that it depends on two iteration variables: `load.v` and `sw.s`. Unfortunately, `sw.s` is protected, so you can't change its start value to influence the convergence of the initial solution.

I would suggest to make sure that you get the proper initialization by devising a logic diagram that doesn't have multiple possible solutions at initialization. You could, e.g., obtain that by filtering the switch signal with something like
```modelica
block InitBoolean;
  extends Modelica.Blocks.Interfaces.BooleanSISO;
  parameter Boolean y_start = false;
equation
  y = if initial() then y_start else u;
end Init;
```
This would make sure that the state of the switch computed during initialization is forced to the required value. Then, the block basically becomes transparent during simulation.

**Comment by casella** [comment]
@ceraolo, as a further comment, there are unfortunately many such models around, which have initialization problems that have no unique solution and/or are numerically fragile or ill-conditioned. They are developed using tool X, which happens (more or less by luck or chance) to produce the expected initial solution. Then you try them with tool Y, which gets a different solution, and you blame tool Y for not being good as tool X, while the problem lies, in fact, with the model itself.

The problem is, understanding whether this is actually the case is a non-trivial problem, which cannot be automated and requires somebody with a solid background in modelling and solution methods (a very scarce resource) to analyze it. This is one of the dark sides of equation-based, object-oriented modelling, and a fundamental limit to interoperability among Modelica tools. Unfortunately, this is really a fundamental limitation, stemming from the fact that Modelica models are declarative, not procedural, so there is no a-priori guarantee that a model will be solved in the same way by two tools. **If** there is a unique solution, and *if* two tools find a solution, then it will be the same (unless one of the tools is buggy, or both). But if those conditions are not met, anything can happen.

Now the question is: how can we determine if an initialization problem has a unique solution? In general, this is a very hard problem, and most importantly, it can't be solved automatically. Alas. 

I only see two ways solving this problem. One is by construction, i.e., designing libraries that only produce models with a unique initial solution. The other one, that we are trying to achieve with the Modelica Association to establish some kind of "quality brand" for open-source libraries, is to run the model on as many Modelica tools as possible and see what happens. Of course correct solutions are not determined by majority rules 😅, but at least you can get some insight by looking at the results.

My 2 cts.

**Comment by ceraolo** [comment]
Ok, I oversimplified my actual issue, which regard a battery, and for which the issue does not came at initialisation.
In fact, yes, probably switches in Modelica shoul have a way, at least as an option,  to tell them what the initial state should be, as occurs with other SW. this would eliminate uncertaintes like this. 
I'll close this and reopen another with the actual problem with a battery.
