### ISSUE TITLE
Linux Flatpak cannot build with Corba undefined reference to `Corba_waitForCommand'

### ISSUE THREAD

**Issue by kevinsmia1939** [OpenModelica/OpenModelica#11777]
### Description
Hi,
I am trying to package OpenModelica as Flatpak for Linux. With Flatpak, OpenModelica can be packaged once and distribute to any distro as well as handling software update.
https://www.flatpak.org/

The manifest (contain the build instructions) is here: https://github.com/kevinsmia1939/flathub/tree/org.openmodelica.OpenModelica

Currently, OpenModelica 1.22.1 build and run fine. But I could not build with -DOM_OMC_USE_CORBA=ON
I encounter an error below.
```
[ 50%] Built target OMSimulator
[ 50%] Linking CXX shared library libOMSimulator.so
[ 50%] Built target OMSimulatorLib
[ 50%] Building C object OMSimulator/src/OMSimulatorLua/CMakeFiles/OMSimulatorLua.dir/OMSimulatorLua.c.o
[ 50%] Linking CXX static library libOMSimulatorLua.a
[ 50%] Built target OMSimulatorLua
[ 50%] Linking CXX executable bootstrapped/bin/bomc
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/Corba.c.o: in function `omc_Corba_waitForCommand':
/run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:24: undefined reference to `Corba_waitForCommand'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/Corba.c.o: in function `omc_Corba_haveCorba':
/run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:47: undefined reference to `Corba_haveCorba'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:47: undefined reference to `Corba_haveCorba'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/Corba.c.o: in function `omc_Corba_close':
/run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:12: undefined reference to `Corba_close'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/Corba.c.o: in function `omc_Corba_sendreply':
/run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:17: undefined reference to `Corba_sendreply'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/Corba.c.o: in function `omc_Corba_initialize':
/run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:30: undefined reference to `Corba_initialize'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/Corba.c.o: in function `omc_Corba_setSessionName':
/run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:35: undefined reference to `Corba_setSessionName'
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/Corba.c.o: in function `omc_Corba_setObjectReferenceFilePath':
/run/build/OpenModelica/OMCompiler/Compiler/boot/bomc/bootstrap-sources/build/Corba.c:40: undefined reference to `Corba_setObjectReferenceFilePath'
collect2: error: ld returned 1 exit status
make[2]: *** [OMCompiler/Compiler/boot/CMakeFiles/bomc.dir/build.make:5981: OMCompiler/Compiler/boot/bootstrapped/bin/bomc] Error 1
make[1]: *** [CMakeFiles/Makefile2:7060: OMCompiler/Compiler/boot/CMakeFiles/bomc.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```
The build flags for OpenModelica are
      - -DJava_JAVA_EXECUTABLE=/app/jre/bin/java
      - -DQt5WebKitWidgets_DIR=/app/lib/cmake/Qt5WebKitWidgets
      - -DOM_OMC_USE_CORBA=ON

omniORB
      - --prefix=/app
      - --disable-static

In the Flatpak filesystem, the prefix is /app.
I need OMBootstrapping to be put into OMCompiler/Compiler/boot/bomc/ as specified in OMCompiler/Compiler/boot/CMakeLists.txt.
Since the Flatpak build system does not allow network connection, in the Flatpak manifest, the instructions are,
Download OMBootstrapping and unpack in OMCompiler/Compiler/boot/bomc/
Then start building OpenModelica.
```
          - mkdir -p OMCompiler/Compiler/boot/bomc
          - mv master.tar.gz OMCompiler/Compiler/boot/bomc/sources.tar.gz
          - cd OMCompiler/Compiler/boot/bomc/ && tar xzf sources.tar.gz --strip-components=1
```

### Steps to Reproduce

Clone the repo
`git clone -b org.openmodelica.OpenModelica git@github.com:kevinsmia1939/flathub.git`
install and flatpak and flatpak-builder on your distro
`sudo apt install flatpak flatpak-builder`
Start building
`flatpak-builder build --force-clean --install --user org.openmodelica.OpenModelica.yaml`

### Version and OS
```
cmake version 3.27.7
gcc (GCC) 12.2.0
OpenModelica 1.22.1
omniORB-4.3.1
Flatpak 1.15.6
flatpak-builder 1.2.3

Operating System: openSUSE Tumbleweed 20231225
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.6.6-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 4600H with Radeon Graphics
Memory: 7.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
Manufacturer: LENOVO
Product Name: 82B5
System Version: Lenovo Legion 5 15ARH05
```

**Comment by sjoelund** [comment]
This is using the cmake builds. I have no clue about what those are doing. Use the autoconf build to use the same build system we use for the .deb and .rpm packages (also does not need a network connection to download the sources as far as I know, but the source tarballs such as https://build.openmodelica.org/linux/apt/pool/contrib/openmodelica_1.22.1.orig.tar.xz are not identical to the git repos; they have the version number as a text-file instead of reading it via git).

**Comment by mahge** [comment]
Corba is on the process of being deprecated in OpenModelica. As a result, enabling Corba support is not allowed right now in the OpenModelica CMake configuration. The option is added to the list of options as a migration step to resemble the autoconf build. 

It is [explicitly stated in the documentation](https://github.com/OpenModelica/OpenModelica/blob/master/README.cmake.md#414-other-openmodleica-specific-options) that you should not enable this option. I was not sure why you did not get the error respective messages when you tried to enable Corba support on Linux. https://github.com/OpenModelica/OpenModelica/blob/b890045362c5697477f6317953c3b2b3ed1d06b1/OMCompiler/Compiler/runtime/CMakeLists.txt#L115-L117

Now I see that I used `message(FATAL ...)` instead of `message(FATAL_ERROR ...)` as I was supposed to. Perhaps that is why the message failed to show and configuration continued.

-----------------------------------------------------------------------

That said, if you really have reasons to use Corba with OpenModelica on Linux, it might be possible to implement the CMake support for it yourself and then make a pull request to OpenModelica as well. The main thing needed is a CMake find-module that know how to find the corba libraries and IDL executables on Linux (There is one such implementation [here](https://github.com/titi38/ProjectRC/blob/master/cmake.modules/FindOMNIORB.cmake). There are probably more out all over the web). You can use those and link the libraries to duplicate and adjust what we do for MSYS/MinGW here:
https://github.com/OpenModelica/OpenModelica/blob/b890045362c5697477f6317953c3b2b3ed1d06b1/OMCompiler/Compiler/runtime/CMakeLists.txt#L94-L115

**Comment by kevinsmia1939** [comment]
Hi,
Thank you all for reply. I decide to just not build openmodelica with corba.

**Comment by kevinsmia1939** [comment]
> Hello, are you going to send the PR to FlatHub?

Yes, but first I will submit a pr here which will add desktop file and metainfo which I made for flatpak.
