### ISSUE TITLE
DynamicSelect does not refresh some values if the simulation fails

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#12010]
Steps to reproduce the problem:

1) open OMEdit and load the PowerGrids library
2) open the attached model `All_NewPG_simpli.mo`
3) open and run the model `DynNoReg2`, the simuation fails during initialization, no results are produced, if the dynamic diagram is opened no values are shown, as expected.
![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/e02ce2f4-1082-489e-97e2-32f2df602fcd)

4) open and run the model `PFOnly`, the model simulates correctly and the dynamic values are displayed in the dynamic diagram as expected,
![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/d03a8a85-d1f8-4d9f-a1b3-03c4c271a6b5)

5) come back to the `DynNoReg2` model and re-simulate it, the simulation fails again, no results are produced but some dynamic values of the previous run (`PFOnly` model) are still shown on the dynamic diagram.
![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/3723c2df-3635-4d4c-9ae3-5bea82df4248)

The expected behaviour is that all the dynamic values are erased if no results are produced.

The modelica annotations that implement the DynamicSelect behaviour are the same for the two models and are written in the following classes in the `Icons `package:
`OnePortDynamicText`
`OnePortDynamicTextBus`
`OnePortDynamicTextBusPQ`

and in the following class in the `Electrical.BaseClasses` package:
`TwoPortACVI`

OpenModelica v1.23.0-dev-257-gcfdfeb87e5 (64-bit)
Sysop: Win11 Pro - 64 bit
[All_NewPG_simpli.zip](https://github.com/OpenModelica/OpenModelica/files/14332002/All_NewPG_simpli.zip)

**Comment by AndreaBartolini** [comment]
keep @casella and @ceraolo in copy

**Comment by adeas31** [comment]
This is how the current implementation is suppose to work. The model simulation is not related to the DynamicSelect. As long as there is a result file in the `Variables` view the current model will read values from it for DynamicSelect.

In your case when you first simulated the model `DynNoReg2`, the simulation failed and no result file is loaded so there is no DynamicSelect animation. Then you simulated the model `PFOnly` and a result file is loaded and you see the DynamicSelect animation. At this point, it doesn't matter if you simulate `DynNoReg2` again or not. If you just open its diagram in the `Plotting`view then you will see DynamicSelect values updated since we have a result file in the `Variables` view.

The model and the result file are not linked. You can have several result files but then you mark one of them `Active` so that it can be used with the model for DynamicSelect. See https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#variables-browser

Why we did it this way is because it is possible to load result files from the previous sessions. For example, if you have a result file for model `PFOnly` and you start a new session of OMEdit. Then load the result file in OMEdit, select it as `Active` from the context menu and then load the model diagram in `Plotting` view. Now you will be able to animate the model using the slider at the top of `Variables` view.

We can change this behavior and link the model to result files but then we will not be able to load result files and do animation. If we want to make that change then I suggest we move this issue to 1.23.0 release. I believe this is not a bug and definitely not a critical issue that should be ported to 1.22.3.

**Comment by AndreaBartolini** [comment]
Thanks Adeel for the clear explanation, I agree in general with the current behaviour that allow to show the data from a result file loaded from disk, the only caveat I see is the possibility to use data from simulation of other models (that is what happens here where the data from `PFOnly` is shown on the diagram of `DynNoReg2`).

Maybe a congruence check between model and data should be provided, the most simple can be based on the model name, better could be to verify the matching between the data in the active results and the data requiered by the DynamicSelect, but this is not a bug, is an improovment.

I cannot move the issue to 1.23.0 release (I've not the permissons to do it, I suppose...).

**Comment by casella** [comment]
Milestone set to 1.23.0 (or later, there are simply too many there to be fixed). I think a congruence check could be useful.

**Comment by adeas31** [comment]
PR #12808 fixes this issue. Now the model diagram knows which result file to read the data from. The externally opened result files are not used for DynamicSelect anymore since we don't know to which model they belong.
