### ISSUE TITLE
The thickness attribute is not handled correctly by OMEdit

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12090]
### Steps to Reproduce

Please consider the following MWE:
```modelica
package TestThickness
  model M
  annotation(
      Icon(graphics = {Line(origin = {-80, 0.5}, points = {{0, 99.5}, {0, -100.5}, {0, -98.5}}), Line(origin = {-80, 0.5}, points = {{0, 99.5}, {0, -100.5}, {0, -98.5}}), Line(origin = {-60.6, -0.13}, points = {{0, 99.5}, {0, -100.5}, {0, -98.5}}, thickness = 0.5), Line(origin = {-40.57, 0.18}, points = {{0, 99.5}, {0, -100.5}, {0, -98.5}}, thickness = 1), Line(origin = {-19.9141, -1.07186}, points = {{0, 99.5}, {0, -100.5}, {0, -98.5}}, thickness = 2), Line(origin = {-0.507034, -2.64076}, points = {{0, 99.5}, {0, -100.5}, {0, -98.5}}, thickness = 4), Line(origin = {18.9, -7.64932}, points = {{0, 101.5}, {0, -92.5}, {0, -90.5}}, thickness = 8), Line(origin = {48.6351, -11.4063}, points = {{0, 99.5}, {0, -88.5}, {0, -82.5}}, thickness = 16), Line(origin = {89.62, -12.66}, points = {{0, 89.5}, {0, -80.5}, {0, -76.5}}, color = {255, 0, 0}, thickness = 20)}));
  end M;
  
  model S
  M m annotation(
      Placement(transformation(origin = {-6, 0}, extent = {{-20, -20}, {20, 20}})));
  end S;
end TestThickness;
```
The icon of M looks like this in OMEdit:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/13c0c15f-a63c-46ba-b8d5-a2bcbe0b852e)
Consider that the extent is the default -100, -100, 100, 100, so the grid pitch is 20 units. The thickest black line is 16 units thick, so it should fit inside a grid square with some margin, while in fact it is significantly wider than that. The red line should be exactly as wide as one grid square, but it isn't.

Moreover, if I zoom out, the icon is obviously not invariant
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/4d855d84-07b9-4b97-ad34-9e7a0627882b)
this image looks pretty different from the previous one.

Dymola shows the icon like this:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/884d4192-bad9-4b8a-ba3d-88868e82d54e)
which seems correct to me. It is also invariant with the zooming
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/aa2e3406-3f15-4d87-9914-3702c992c912)

Finally, notice that the vertical alignment of the righmost lines in Dymola looks different from the one in OMEdit, this should also probably be investigated.

### Expected behaviour

The thickness of the icon should actually correspond to the thickness attribute at all zoom factors. Also, the vertical position of the lines should probably correspond to Dymola's, though I did not check that in detail.

This is actually a bug fix, but I would keep it for 1.23.0, because it may actually change how icons built with OMEdit look like, so it's nor really just a patch.

Keeping @gwr69 in the loop.

**Comment by casella** [comment]
@adeas31 any chance you can look into this anytime soon?

**Comment by adeas31** [comment]
I am already working on it. Apparently it is taking more time than what I anticapted. Surprisingly we were using the thickness completely wrong. I have a solution in my working copy and will push it in Monday.

**Comment by adeas31** [comment]
PR #12115 should fix the handling of thickness.

Dymola is using `0` as default value for thickness instead of `0.25` as defined in the Modelica specification.

```Modelica
model M
annotation (Diagram(graphics={Rectangle(
          extent={{-80,80},{-20,20}},
          lineColor={0,0,255},
          fillColor={28,108,200},
          fillPattern=FillPattern.None), Rectangle(
          extent={{20,-20},{80,-80}},
          lineColor={0,0,255},
          fillColor={28,108,200},
          fillPattern=FillPattern.None,
          lineThickness=0.25)}));
end M;
```

If you load the above model in Dymola you will see a thin lined rectangle on top left and slightly thick lined rectangle on the bottom right. However, the both rectangles should be same. The top left rectangle doesn't contain the `lineThickness` attribute and bottom right rectangle has `lineThickness` 0.25. Dymola is using `0` instead of `0.25` when `lineThickness` is missing.

A pen with zero width is a [cosmetic pen](https://doc.qt.io/qt-6/qpen.html#isCosmetic). Since most of the models in MSL does not explicitly define the thickness which means Dymola renders them with cosmetic pen. We tried to match that behavior and went down the wrong road. We were using cosmetic pens for everything and completely wrong handling when thickness is greater than 1.

With PR #12115 the MSL diagrams look slightly different in OMEdit. The change is hardly visible. If you zoom in the diagram in both OMEdit and Dymola you will see the difference in line thickness.

Seems now we get similar results to what WSM produces. @gwr69 this also fixes the diagrams of BusinessSimulation library.

**Comment by casella** [comment]
Great, thanks @adeas31!
