### ISSUE TITLE
Lost experiment annotation when extending

### ISSUE THREAD

**Issue by phannebohm** [OpenModelica/OpenModelica#12124]
### Description

When a model `B` extends another model `A` the annotations in `A` are not carried over to `B`.

### Steps to Reproduce

Simulate model `B`

```modelica
model A
  Real x;
equation
  der(x) = -x;
  annotation(experiment(StopTime = 2.0));
end A;

model B
  extends A;
end B;
```

### Expected Behavior

The [MLS chapter 7.1](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#inheritance-extends-clause) says
>The elements of the flattened base class become elements of the flattened enclosing class, and are added at the place of the extends-clause: specifically components and classes, the equation sections, algorithm sections, optional external-clause, **and the contents of the annotation at the end of the class**, but excluding import-clauses.

So the experiment annotation should also be present in model `B` and it should simulate for 2 seconds instead of the default 1 second.

### Additional Context

Dymola simulates `B` for 2 seconds.

**Comment by perost** [comment]
According to [#2314 for the spec](https://github.com/modelica/ModelicaSpecification/issues/2314) it seems like it's not actually intended that all annotations are inherited, and the specification doesn't really specify how it should work anyway. That issue did result in clarifying the semantics of the [experiment annotation](https://specification.modelica.org/master/annotations.html#annotations-for-simulations) though, but unfortunately that closed the issue without dealing with all the other annotations.

So for now at least we should probably just handle the `experiment` annotation specifically rather than inheriting all annotations.

**Comment by casella** [comment]
@phannebohm in any case this is a very recent addition to MLS 3.7, which is not yet released. This is very welcome, but if you want to keep portability I would not rely on this for another couple of years, just in case 😅

**Comment by phannebohm** [comment]
Yeah, I didn't see the discussion on the spec. The clarification in section 18.4 is indeed very recent.

Still it would be nice if omc could handle that already :slightly_smiling_face:

**Comment by perost** [comment]
#12148 implements inheritance of experiment annotations in the scripting API, such that it works with e.g. `simulate()` or just `-s`. But it doesn't seem like OMEdit picks it up in the simulation options unfortunately. @adeas31, how does OMEdit get the experiment settings from a class?

I'm also not sure why I thought this was a frontend matter, the annotation isn't taken from the flat model but looked up in the Absyn by the scripting API (which involves printing the annotation to a string and then immediately parsing it again...). 

The check for conflicting annotations is also a bit too strict right now since it just checks if two inherited annotations are exactly identical (using `valueEq`) rather than checking if they have conflicting values, but it just prints a warning for that anyway.

**Comment by perost** [comment]
My changes broke most of the simulation tests we have because they use the old frontend, and I'm using `NFApi.getInheritedClasses` to fetch the annotations from the extended classes which doesn't work if the old `ModelicaBuiltin.mo` is loaded. So inheriting `experiment` is now a new frontend only feature.

**Comment by perost** [comment]
#12148 is now merged, please try it out and let me know if you find any issues.

I also fixed the OMEdit issue. OMEdit was checking if a model had an experiment annotation before trying to get it with `getSimulationOptions`, I must have tested it with a model where the experiment annotation was only inherited. I just removed that check since `getSimulationOptions` just returns the default settings anyway if the model doesn't have any annotations.

**Comment by phannebohm** [comment]
> #12148 is now merged, please try it out and let me know if you find any issues.

Works nicely, thanks @perost!
