### ISSUE TITLE
Missing default connection equations for unconnected flow/effort connectors in expandable connectors

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12159]
### Description

Consider this MWE package:
```modelica
package TestExpandableConnectors3
   
  expandable connector C
  end C;

  model ModelA
    C c;
    Modelica.Electrical.Analog.Basic.Ground ground1, ground2, ground3;
  equation
    connect(ground1.p, c.p1);
    connect(ground2.p, c.p2);
    connect(ground3.p, c.p3);
  end ModelA;
  
  model ModelB
    C c;
    Modelica.Electrical.Analog.Basic.Ground ground1;
  equation
    connect(ground1.p, c.p1);
  end ModelB;

  model System
    ModelA m1;
    ModelA m2;
    ModelB m3;
  equation
    connect(m1.c, m2.c);
    connect(m1.c, m3.c);
  end System;
end TestExpandableConnectors3;
```
Checking System gives:
```
Class TestExpandableConnectors3.System has 30 equation(s) and 32 variable(s).
```
Inspection of the flattened model reveals that connector `m3.c` contains all the flow variables obtained by gathering the components of the expandable connectors:
```modelica
  Real m3.c.p1.i "virtual variable in expandable connector";
  Real m3.c.p2.i "virtual variable in expandable connector";
  Real m3.c.p3.i "virtual variable in expandable connector";
```
Unfortunately, only one equation is generated from the `connect(ground1.p, c.p1);` statement in `ModelB`
```modelica
  m3.ground1.p.i - m3.c.p1.i = 0.0;
```
leaving `m3.c.p2.i` and `m3.c.p3.i` orphans of their matched equations.

As I understand, what are missing here are the default equations for unconnected ports in `m3`:
```modelica
  m3.c.p2.i = 0.0;
  m3.c.p3.i = 0.0;
```

**Comment by casella** [comment]
Keeping @albertoleva in the loop

**Comment by casella** [comment]
Possibly related to discussion #12160

**Comment by perost** [comment]
We discussed this issue during the meeting, but afterwards I realised I was still confused about why the model shouldn't be unbalanced since all the flow variables are connected as inside connectors due to the connect equations in `System`.

But it turns out that I'd missed one very crucial thing in the specification (9.2): flow variables added when augmenting expandable connectors should be added as connection sets both as inside _and as outside_. So we need to keep track of what's added during augmentation and add sets with such flow variables as outside too in addition to the usual inside ones.

**Comment by casella** [comment]
@albertoleva tomorrow's nightly build should work fine with expandable connectors.
