### ISSUE TITLE
Render 'each' with 'fill()' when flattening parameters depending on other parameters

### ISSUE THREAD

**Issue by mscuttari** [OpenModelica/OpenModelica#12257]
Consider the following MWE

```modelica
package Test
    model A
        parameter Real p;
    end A;

    model B
        final parameter Real P = 1;    
        A a[4,4,4](each p = P);
    end B;
end Test;
```

When asking for the Base Modelica code of model B with flags

`-i=Test.B --baseModelica -d=nonfScalarize,evaluateAllParameters,vectorizeBindings`

I get

```modelica
package 'B'
    model 'B'
        final parameter Real 'P' = 1.0;
        parameter Real[4, 4, 4] 'a.p' = {{{1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}, {{1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}, {{1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}, {{1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}, {1.0, 1.0, 1.0, 1.0}}};
    end 'B';
end 'B';
```

The problem is similar to #10795.
The assignment to 'a.p' can be made more compact by using the `fill` operator.

```modelica
package 'B'
    model 'B'
        final parameter Real 'P' = 1.0;
        parameter Real[4, 4, 4] 'a.p' = fill(1.0, 4, 4, 4);
    end 'B';
end 'B';
```

The problem does not appear if I change the declaration of `a` to `A a[4,4,4](each p = 1);`.

**Comment by perost** [comment]
#12259 fixes two issues. The first is to avoid expanding the vectorized expression if it's a `fill` or array constructor that doesn't need to be expanded here.

However, that would instead result in `{1.0 for '$a3' in 1:4, '$a2' in 1:4, '$a1' in 1:4}`, so I also changed the vectorization of bindings so that we create `fill` expression instead when the fill argument isn't using the iterators anyway. So now we get the exact output you were looking for.
