### ISSUE TITLE
Flatten all array declarations and equations to scalars for Base Modelica output

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12332]
### Steps to Reproduce

Consider the following MWE:
```modelica
package P
  model M
    Real x[2];
  equation
    x = {1, time};
  end M;
  
  model S
    M m[2];
  end S;
end P;
```
Flattening it with `--BaseModelica` currently gets you
```modelica
package 'S'
  model 'S'
    Real[2] 'm[1].x';
    Real[2] 'm[2].x';
  equation
    'm[1].x' = {1.0, time};
    'm[2].x' = {1.0, time};
  end 'S';
end 'S';

```
From an application standpoint, this hybrid format with half-scalarized arrays is not really very useful.

### Expected results

 If one wants to preserve arrays, setting `--BaseModelica -d=nonfScalarize` gets you
```modelica
package 'S'
  model 'S'
    Real[2, 2] 'm.x';
  equation
    for '$i1' in 1:2 loop
      'm['$i1'].x' = {1.0, time};
    end for;
  end 'S';
end 'S';
```
which is fine. Otherwise, if one only sets `--BaseModelica`, one should get
```modelica
package 'S'
  model 'S'
    Real 'm[1].x[1]';
    Real 'm[1].x[2]';
    Real 'm[2].x[1]';
    Real 'm[2].x[2]';
  equation
    'm[1].x[1]' = 1.0;
    'm[1].x[2]' = time;
    'm[2].x[1]' = 1.0;
    'm[2].x[2]' = time;
  end 'S';
end 'S';
```

**Comment by casella** [comment]
Adding @matteodepascali to the loop

**Comment by perost** [comment]
> @perost can you please update me on the status of this issue? Thanks!

I worked on a bit, but there were so many issues with it that I gave up for the time being. I just moved the dumping of Base Modelica to the end of the instantiation instead of doing it before scalarization, but that broke a lot of things.

There's also some things we need to figure out how to represent in Base Modelica. Subscripting of array variables can probably be handled by creating temporary arrays, or maybe we'll just skip supporting it. Completely getting rid of array variables probably isn't feasibly anyway, since you can have e.g. function parameters that are arrays and can't really be split into scalars. So it might only make sense for simple models.

There's also a similar issue with records, which would have to be split into separate variables since records can contain arrays. That's the complete opposite of what we're doing right now, which makes it a bit complicated to support both. Similar to arrays we'd have also to create temporary record expressions when e.g. passing a record to a function (which doesn't really work with external functions).

So we could probably implement something that supports simple models with limited array and record features fairly easily, but I'm not sure if having the default be to scalarize absolutely everything is really feasible.

**Comment by casella** [comment]
> I worked on a bit, but there were so many issues with it that I gave up for the time being. I just moved the dumping of Base Modelica to the end of the instantiation instead of doing it before scalarization, but that broke a lot of things.

Too bad 😅 
 
> There's also some things we need to figure out how to represent in Base Modelica. Subscripting of array variables can probably be handled by creating temporary arrays

I'm not sure what you mean here by "subscripting of array variables". Do you mean, e.g., slicing? Could you make a concrete example?

> Completely getting rid of array variables probably isn't feasibly anyway, since you can have e.g. function parameters that are arrays and can't really be split into scalars. So it might only make sense for simple models.

I see, and this may be OK for the time being, see below. One option could be to use anonymous array constructors, e.g., `f(x)` is flattened into `'f'({'x[1]', 'x[2]', 'x[3]'})`. Of course this will be inefficient for large arrays, but then if you really want to support them efficiently, you need a more powerful Base Modelica parser/compiler.

> There's also a similar issue with records, which would have to be split into separate variables since records can contain arrays.  That's the complete opposite of what we're doing right now, which makes it a bit complicated to support both. Similar to arrays we'd have also to create temporary record expressions when e.g. passing a record to a function (which doesn't really work with external functions).

OK, for the time being you can forget about handling function calls involving arrays and records, see below.

Later on, one option could be to use anonymous array constructors and record constructors, e.g.
```modelica
'w' = 'f'('R'('r.x', {r.y[1], r.y[2]}));
```
> So we could probably implement something that supports simple models with limited array and record features fairly easily, but I'm not sure if having the default be to scalarize absolutely everything is really feasible.

Agreed. I currently have two industrially-relevant use cases for Base Modelica output, for which I need support ASAP:

1. Importing thermal power generation system models in Pyomo.DAE
2. Importing power grid models in MARCO

Regarding 1., the model needs to be completely scalarized to keep the Python parser as simple as possible (no array syntax and semantics needed), which is the reason why I opened this ticket. On the other hand, these models only use pre-defined or inlined functions and use no records, so there is no need to worry about functions with record/array arguments. If you encounter something involving function, arrays, and records that is not trivial to scalarize, just keep it as it is, it shouldn't hurt for this application. 

Later on I may come up with some application where we need to scalarize records to their Real components (see #12489) but this is not needed now.

Regarding 2., instead, MARCO is a full-fledged Base Modelica compiler. It can't handle model instantiation, connections, inheritance, replaceable classes and so on (so it relies on the OMC NF for that), but it can handle arrays, array subscripting with slicing, records, operator records, functions, and inlining. In this case, I have the exactly opposite requirement, i.e., making sure that we _never_ expand neither arrays nor records, and we let MARCO handle them efficiently, see the first part of #12490.

So, what I need right away (hopefully before the summer break) is
- when `--baseModelica` is selected, fully scalarize simple models - for combinations of function, arrays, and records, don't scalarize them and keep them as they are. This has very high priority and will close this ticket.
- when `--baseModelica -d=nonfScalarize,arrayConnect,combineSubscripts,evaluateAllParameters,vectorizeBindings` or `--baseModelica -d=nonfScalarize,mergeComponents,combineSubscripts,evaluateAllParameters,vectorizeBindings` are selected, avoid expanding arrays and records in declarations and equations. This has high priority and will close #12490.

For anything else, we'll see when we have the application cases, no need to worry now.

Thanks!

**Comment by casella** [comment]
Some added considerations after today's devmeeting. Full scalarization is probably not a good default option, we need a flag to activate that explicitly. I'll modified the proposal in #12333 accordingly.

**Comment by perost** [comment]
Full scalarization is now implemented in #12682 via the flag `--baseModelicaOptions=scalarize`.

Functions should generally work, function arguments will be scalarized and function calls returning arrays will be subscripted. The functions themselves are not scalarized though, since that doesn't really work for functions, so more inlining might be necessary in the future. Also, functions with flexible arrays do not work since their size is unknown and thus can't be scalarized.

Records are split into individual variables for each field, so simple uses should work but passing records in and out of functions won't work and more complex cases might fail. In some cases it might be necessary to access a record field of an expression, which was added to Modelica recently but not yet implemented in omc.

Those are the known issues, but I'm sure there are lots of unknown issues too so let me know how it works for you.

**Comment by casella** [comment]
Thank you @perost! I believe this is more than enough for @matteodepascali, since his model was deliberately written in a Modelica style that avoids those constructs, so it can be easily flattened to scalar DAEs for optimization.

@matteodepascali please check if this works for you ASAP, maybe there is some remaining glitch that @perost can fix before the end of this week.

**Comment by matteodepascali** [comment]
Thank you very much @perost! 
I tried the new flags added both in #12682 and in #12496 and they seem to work fine.
I tested both MWEs and a model from the library I need to translate and I did not notice any error.
I'll implement in the next days the changes needed to process BaseModelica instead of the flattened model in the parser I'm writing and I'll update you if something wrong comes up.
Thanks again!

**Comment by casella** [comment]
@matteodepascali can we close this ticket? Thanks!

**Comment by matteodepascali** [comment]
Yes, I think we can close it: I translated multiple times the model employing all the flags that has been added and I did not notice any issue.

Little *off-topic* comment that is related to baseModelica, but not to these issues: I was pleased to see that the evaluateAllParameters flag does not ignore the Evaluate=false annotation, even if this behavior is not clearly specified in the flag description.

**Comment by casella** [comment]
> Little _off-topic_ comment that is related to baseModelica, but not to these issues: I was pleased to see that the evaluateAllParameters flag does not ignore the Evaluate=false annotation, even if this behavior is not clearly specified in the flag description.

Interesting, I was not aware of that 😄. BTW, this almost implements #4960.

PR #12873 improves the flag description.

**Comment by casella** [comment]
The extended flag description is now [online](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-debug-evaluateallparameters).
