### ISSUE TITLE
how to compile a debug version

### ISSUE THREAD

**Issue by pily1** [OpenModelica/OpenModelica#12405]
I have compiled the OpenModelica with OMDEV MINGW64 on windows platform,I add the cmake param ,cmake -DCMAKE_BUILD_TYPE=Debug,it 
 has compiled success,but it created the release version,not created a debug version,I can find the xxx.dll and xxx.exe,I cann't find the xxxd.dll and xxxd.exe.
how can I compile the debug version?

**Comment by perost** [comment]
The dll and exe files are called the same regardless of build type, changing the build type to Debug just includes the debug symbols in them.

Also, for questions about OM that aren't issues it might be better to use [discussions](https://github.com/OpenModelica/OpenModelica/discussions) instead of opening issues for them.
