### ISSUE TITLE
Exported CSV files error

### ISSUE THREAD

**Issue by luizmac** [OpenModelica/OpenModelica#12450]
### Description

I am doing a simulation with fixed time-step using step sources, however when exporting the results using the CSV export option the generated file has an error on time vector. The time vector has more time points than the specified. Multiple time points are inserted at the time instant of the step.

I tried simulate with different solver and all of them have inserted this additional points.

The time vector for a time step of 0.1 on the CSV file is:

time
--
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1
1.0000000002000888
1.0000000002000888
1.1
1.2
1.3
1.4
1.5
1.6
1.7
1.8
1.9
2
2

As you can see the time vector has two extra points after the 1 second.

### Steps to Reproduce

My script is:

model Test
  Modelica.Blocks.Sources.Step step(startTime = 1)  annotation(
    Placement(transformation(origin = {-44, -8}, extent = {{-10, -10}, {10, 10}})));
equation

annotation(
    uses(Modelica(version = "4.0.0")),
  experiment(StartTime = 0, StopTime = 2, Tolerance = 1e-06, Interval = 0.1),
  __OpenModelica_commandLineOptions = "--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian",
  __OpenModelica_simulationFlags(lv = "LOG_STDOUT,LOG_ASSERT,LOG_STATS", s = "dassl", variableFilter = ".*"));
end Test;

After running the script press Export variables (CSV icon) on the plotting windows.

### Expected Behavior

The CSV exported file should give a time vector with a fixed time-step of 0.1 seconds. 

time
--
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1
1.1
1.2
1.3
1.4
1.5
1.6
1.7
1.8
1.9
2

### Screenshots

![image](https://github.com/OpenModelica/OpenModelica/assets/67111542/70fc6f61-16a2-4f59-b9be-bc41c7c00e77)

### Version and OS

 - OpenModelica Version: OpenModelica 1.24.0~dev-16-gaa27cc1
 - OS: Linux Mint 21.3 Cinnamon

**Comment by phannebohm** [comment]
Do you have an event at `time=1.0000000002000888`?

**Comment by luizmac** [comment]
No. The step is at 1 second.

**Comment by adeas31** [comment]
Have you tried output format CSV instead of exporting to CSV?

**Comment by bilderbuchi** [comment]
> Multiple time points are inserted at the time instant of the step.

As I'm not sure if this iis clear: when there is an event, you get the output values from just before **and** just after the event instant, so having one duplicated time instance, with values of `0` and `1`, respectively, is expected -- this gives you the necessary information about how your system reacts to the event.
What could be argued is if there should be one tick at `1.0` and one at `1.0000000002000888` -- maybe this is a floating-point/comparison/solver inaccuracy?

**Comment by luizmac** [comment]
My intention is to compare a fixed time-step simulation from Simulink with one from modelica. However on modelica this additional points are inserted on the time vector. Is it incorrect expect a time vector with fixed step?

**Comment by casella** [comment]
@luizmac can you please turn on LOG_EVENTS_V and report the log?

**Comment by casella** [comment]
OK, I guess the problem here could be that the communication interval is 1.0, so the continuous-time integration algorithm provides an output point at each multiple of that, computed by interpolating the results of the underlying variable step-size algorithm at those time point. Additionally, a state event is triggered at a time which is theoretically 1.0, but in fact turns out to be slightly afterwards for numerical reasons. So, you get:
- the value at the communication time = 1.0
- the value right before the event at time = 1.00000000002
- the value after the event iterations at time = 1.00000000002

If you only want to see the results at the communication points, you can disable the output of values at events, just deselect Store Variables at Events in the simulation setup
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/3c8b52bd-f238-4997-9825-9b342a013d1b)

I'm not sure if there is any way we can get the double output otherwise.

**Comment by luizmac** [comment]
Thanks! Deselecting the Store Variables at Events the time vector is corrected. Now I can compare the results properly.
