### ISSUE TITLE
Optionally move binding equations of variables to equation section in Base Modelica output

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12496]
As discussed in #12333, the simplest possible Base Modelica output should only contain scalar variable declaration and scalar equations acting on exactly the same symbols. In the case of a flat model output, there is really no added value in keeping binding equations for variables, since they cannot be changed during instantiation. Hence, it should be possible to optionally move those binding equations to the equation section.

This option could be activated by a specific flag, for the name of the flag refer to the discussion in #12333.

Keeping @matteodepascali in the loop.

**Comment by perost** [comment]
Fixed in #12645.

I didn't use the proposed flag name since I wanted it to indicate that it's a Base Modelica option, and instead I went with `--baseModelicaOptions=moveBindings`.

I saw that you proposed using the `--baseModelica` flag for setting options in another issue. I always use `-f` instead of `--baseModelica` so I didn't think of that when adding the flag, but that's an alternative. I'm not sure what I prefer between the explicitness of a separate flag for the options or the convenience of one flag less, maybe you have some opinion?

**Comment by perost** [comment]
> I saw that you proposed using the `--baseModelica` flag for setting options in another issue. I always use `-f` instead of `--baseModelica` so I didn't think of that when adding the flag, but that's an alternative. I'm not sure what I prefer between the explicitness of a separate flag for the options or the convenience of one flag less, maybe you have some opinion?

Actually, given how flags currently work we can't make `--baseModelica` a string list flag because then we wouldn't be able to tell if it was enabled or not if no option is given. So having a separate flag for the options is necessary unless we want to redesign the way flags work.

**Comment by casella** [comment]
@matteodepascali, please try with the next nightly build if this works for you.

The flags to use for the Pyomo should be `--baseModelica --baseModelicaOptions=moveBindings -d=evaluateAllParameters`
