### ISSUE TITLE
Bad OMEdit behaviour with choices and units

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#12756]
### Description
Just changing the unit of measure changes the values when choices is used

### Steps to Reproduce

************************
UPDATE
This description had mistakes. Please consider 
https://github.com/OpenModelica/OpenModelica/issues/12756#issuecomment-2271784638
for a  fixed description
*************************

Code:
```modelica
model a
parameter Modelica.Units.SI.Density rho
  annotation(choices(choice=1.1455 "Air",
                     choice=992.2 "Water"));
equation
end a;
model b
  a a1 annotation(
    Placement(transformation(origin = {-30, 30}, extent = {{-10, -10}, {10, 10}})));
equation
end b;
```
Steps:
0) load a and b
1) open b and double click on a1 icon
2) select 1.1455 for rho (i.e. 1.1455 g/cm3
3) change the unit into kg/m3 (the value is changed into 1145.5 kg/m3
4) Select again 1.1455. The value 1.1455 kg/m3 is displayed  

Here I see three issues:
a) I would expect the choice to remain between the two original values 1.1455 g/cm3 and and 992.2 g/cm3 or their counterpart in kg/m3, not three values
b) the value 1.1455 kg/m3  shown in the list is wrong
c) near the values the textual descrrtipitoin strings "air" and "water" are missing 

### Expected Behavior
- after modification of units of measure the list should enlist still the two original values or their counterpart in kg/m3
- the description strings should be shown along with the numerical values

### Version and OS
OM 1.23.1 Win11

**Comment by casella** [comment]
Interesting case, thanks @ceraolo for reporting!

First of all, the question is, what is the meaning of the values given by the choices annotations? Specifically, what is the corresponding unit? [MLS Section 7.3.4](https://specification.modelica.org/maint/3.6/inheritance-modification-and-redeclaration.html#annotation-choices-for-suggested-redeclarations-and-modifications) says: 

> A declaration can have an annotation choices containing modifiers on choice, where each of them indicates a suitable redeclaration or modifications of the element.

So, the content of the choice annotation is what ends up in the modification, _not necessarily what is shown in the drop-down menu_. So, those numbers refer to the `unit` of the corresponding parameter, no to its `displayUnit`. BTW, a liquid with 999.2 g/cm3 of density would be very dense indeed...

@adeas31 what we should do is to handle those choices exactly in the same way as we handle default modifiers: if they are literal constants, we assume them to have the unit of the parameter and then we show them with the unit conversion mechanism, otherwise we still assume them to have the unit of the parameter but we disable the unit conversion mechanism.

@ceraolo do you agree?

**Comment by ceraolo** [comment]
> if they are literal constants, we assume them to have the unit of the parameter and then we show them with the unit conversion mechanism, otherwise we still assume them to have the unit of the parameter but we disable the unit conversion mechanism.
@ceraolo do you agree?

Ok for me. 
I would also recommend to have a look at how Dymola deals with this, since it is simple and effective.

BTW, this example is rather iconic (as is common to call things these days) since I got it from the wonderful ModelicaByExample online book.

**Comment by ceraolo** [comment]
> if they are literal constants, we assume them to have the unit of the parameter and then we show them with the unit conversion mechanism, otherwise we still assume them to have the unit of the parameter but we disable the unit conversion mechanism.
@ceraolo do you agree?

Ok for me. 
I would also recommend to have a look at how Dymola deals with this, since it is simple and effective.

BTW, this example is rather iconic (as is common to call things these days) since I got it from the wonderful ModelicaByExample online book.

**Comment by adeas31** [comment]
I don't understand what is wrong here.

> 1. open b and double click on a1 icon
> 2. select 1.1455 for rho (i.e. 1.1455 g/cm3

The `displayUnit` of `Modelica.Units.SI.Density` is `g/cm3`.

> 3. change the unit into kg/m3 (the value is changed into 1145.5 kg/m3

This is expected, right?

> 4. Select again 1.1455. The value 1.1455 kg/m3 is displayed

Since you changed the `displayUnit` in step 3 so you get `1.1455 kg/m3`. Why do you expect that the displayUnit reverts back to `g/cm3` when you select `1.1455`? The choice annotation only specifies the value. It doesn't specify what is the displayUnit.

> c) near the values the textual descrrtipitoin strings "air" and "water" are missing

The description string is missing in the instance data. Once @perost comes back from the vacations then we will fix it.

**Comment by ceraolo** [comment]
>I don't understand what is wrong here.

My description had erros, but I still find three issues.
Updated description below.
*****************************************************
Steps:

0) load a and b
1) open b and double click on a1 icon
2) select 1.1455 for rho (OMEdit shows 1.1455 g/cm3)
3) change the unit into kg/m3 (the value is changed into 1145.5 kg/m3
4) Select again 1.1455. The value 1.1455 kg/m3 is displayed  

I think we all agree that the actual value of this density is 1.1455 kg/m3=0.00114455 g/cm3=1.1455 mg/cm3. Don't we?

Here I see three issues:
a) in point 1 the wrong value 1.1455 g/cm3 is shown (either the unit or value is wrong)
b) after point 2 I have a list of three values instead of two, which is bad and misleading
c) near the values the textual descrption strings "air" and "water" are missing 

Regarding point b) playing with units the number of values continues to grow, as per the following screenshot.

![image](https://github.com/user-attachments/assets/a9848916-f0bf-44c8-b62f-b33c86273f5b)

**Comment by casella** [comment]
> I don't understand what is wrong here.
> 
> > 1. open b and double click on a1 icon
> > 2. select 1.1455 for rho (i.e. 1.1455 g/cm3
> 
> The `displayUnit` of `Modelica.Units.SI.Density` is `g/cm3`.

Yes, but the value declared in the choice annotation is meant as the value of the modifier (as per MLS), hence it is expressed in the same unit as the parameter, i.e., kg/m3, not to be the value that is going to be displayed with the displayUnit, which is g/cm3. There are three orders of magnitude in between them.

The way we handle this currently causes the values to be completely wrong. The density for air is 1.1455 **kg/m3**, i.e., 0.0011455 g/cm3, not 1.1455 g/cm3, which is the density of a thick cream, not of a gas like air.

As I wrote in my [comment](https://github.com/OpenModelica/OpenModelica/issues/12756#issuecomment-2258006874), what we need to do when handling choices annotations is to interpret them with the `unit` of the parameter they refer to, and then convert the value to the displayUnit with the usual rules.

I think once this issue is fixed everything else will be OK.

**Comment by adeas31** [comment]
@ceraolo please test this with the latest nightly build.

**Comment by ceraolo** [comment]
Excellent!
Now managing of numbers and units of measure, for me, is exactly as expected.

There is still the issue of the missing descriptive strings, for which I've read we must wait for @perost to return from vacation.
Thanks again.

**Comment by perost** [comment]
> There is still the issue of the missing descriptive strings, for which I've read we must wait for @perost to return from vacation. 

I have it on good authority that he's back.

I've actually been working on it a bit, but encountered the issue that the comments weren't kept during the Absyn->SCode translation. I just opened #12783 that fixes that. I'll make a separate PR for adding the comments to the API, and we'll also need to adapt OMEdit to the changes, but that should be the easy part.

**Comment by adeas31** [comment]
PR #12789 fixes the issue discussed [here](https://github.com/OpenModelica/OpenModelica/pull/12786/files#r1719645663).

**Comment by ceraolo** [comment]
For me 1.1455 "air" is perfect.

The general result is good, even though the management of units of measure of the two example data ("air" and "water") is less flexible than in Dymola.
I'm going to close this ticket.
