### ISSUE TITLE
OMEdit FMU export does not indicate progress

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#12828]
### Description
On OM v1.24.0-dev-238, Windows 10, when I press "Export FMU" on a model in OMEdit, there is an "Exporting model as FMU" indication in the status bar, but no other indication that something is happening. The GUI becomes unresponsive, the window goes gray. 
Coupled with the fact that FMUs sometimes need O(minutes) to generate, this makes for a confusing user experience. Has the process become stuck? Is it crashed? Is OMEdit crashed/frozen? Is the process still progressing? How far along is it?
One can only go for a coffee or do something else until (hopefully) getting the message browser entry pointing to the successfully generated FMU.

### Expected Behavior

It would be a nice enhancement if 
* OMEdit remained _responsive_, so one could continue working on other modelling tasks in the meantime (if that is possible), or at least not be faced with a frozen window.

Also,
* A tab in the messages pane would be added that shows the export commands/progress/output of the FMU export, equivalent to the Compilation tab when running(compiling) Modelica models.
* Failing that, at least frequent Notifications in the Messages pane being added telling about finished sections of the generation or somesuch.

**Comment by casella** [comment]
@arun3688 is now working on it

**Comment by arun3688** [comment]
@bilderbuchi The issue is fixed with this commit bf7f7c64f75d06ce51f27126ba19b5b6d8355249, Now you have the progress bar indicator and the export of fmu behaves the same like simulation process,NOW the export of FMU is split into three parts, 

1. Translating the model 
2. Generating the Target cmake files
3. Building Cmake and Zipping 

The step number 2 and 3 are ran in seperate threads which avoids GUI freezing, however the first step translating model is still not thread safe and the GUI may be frozen for few seconds depending on how big the model is, but in general it is very good improvement of the current fmu export, Please test it from the nightly builds tomorrow (24-09-2024)

**Comment by bilderbuchi** [comment]
@arun3688 awesome work, this is ~ perfect! It's great that one sees the configure step, and the whole compilation output including compiler warnings. That should help troubleshoot issues!

**Comment by bilderbuchi** [comment]
Two remarks:
* There are weird characters in some lines of the build step (Windows 10) -- some spacing chars not understood by the console?  
![image](https://github.com/user-attachments/assets/464d2fe6-fd7b-441b-a53d-c6d82727dafd)
* Now I can see that the configure stage warns me that
```
CMake Warning in CMakeLists.txt:
  The object file directory

    C:/Users/my__user/AppData/Local/Temp/OpenModelica/OMEdit/my_not_that_long_test_model_name_12d2/my_not_that_long_test_model_name_.fmutmp/sources/build_cmake/CMakeFiles/my_not_that_long_test_model_name_.dir/

  has 205 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    simulation/solver/linearSolverTotalPivot.c.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.
```
I'm not sure if that messes with the build? 
There is some duplication here, but it's only the model name, so I'm not sure how to best mitigate this further?
* Drop `OpenModelica` (which is an empty folder) from the temp path? This might not be that attractive, I don't know if other OM tools would put stuff in there?
* use just the hash for the last folder level in `CMakeFiles` -- `CMakeFiles/12d2/`?

Should I report that separately?

**Comment by arun3688** [comment]
@bilderbuchi Thanks for testing, Good that it works as expected, regarding the long path issues I wrote my comments in this issue https://github.com/OpenModelica/OpenModelica/issues/12916 and we can track it from there, If everything works fine from GUI side we can close this issue and try to fix the long path issue separately

**Comment by bilderbuchi** [comment]
> If everything works fine from GUI side we can close this issue

well, only the first remark above with the weird characters in printout is left over, otherwise I would have closed already! ❤️

**Comment by casella** [comment]
If the weird characters can be removed right away, please do so, otherwise I would close this ticket and open a separate one for that. For project management purposes, having a new feature (though not perfect) should be duly recorded 😃.

Thanks!

**Comment by arun3688** [comment]
@bilderbuchi @casella the weird character issue is fixed with this commit c296bbf01ada386d15201d5a6f41cb1ae12ed2e9 , see below screenshot

![image](https://github.com/user-attachments/assets/4e57b32e-9490-4cf1-a4ed-edcf5f870756)

The weird characters popped up due to cmake coloring and in `qt QPlainTextEdit`, the textedit does not support ANSI escape codes and i disable the coloring using `DCMAKE_COLOR_MAKEFILE=OFF` and this produces the expected output, please test it from nightly builds tomorrow (25-9-2024)

**Comment by bilderbuchi** [comment]
>  please test it from nightly builds tomorrow (25-9-2024)

For this, I'll go with just believing you that the issue is fixed :-)
We can always reopen if otherwise.

**Comment by casella** [comment]
Great! This improvement, and previous improvements in 1.23.0 related to using clang instead of gcc and using multiple compiler instances in parallel finally made FMU export in OMEdit a humane experience 😃
