### ISSUE TITLE
No documentation found regarding annotation(__OpenModelica_tearingSelect)

### ISSUE THREAD

**Issue by olivleno** [OpenModelica/OpenModelica#13098]
### Description
The [Release Notes for OpenModelica 1.23.0](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.24/githubreleases.html)
state:

The non-standard annotation(tearingSelect) was deprecated and replaced by annotation(__OpenModelica_tearingSelect)

I could not find any information on this annotation in the documentations.

**Comment by casella** [comment]
Good point. In fact, providing this information was one of the two tasks in #11538. The first was done, the second wasn't, then @phannebohm moved on to other things.

The problem is, we simply don't have enough manpower to take care of all these backend issues, which just keep piling up. We can discuss this in the next OSMC Board meeting.
