### ISSUE TITLE
-d=mergeComponents should also worked in derived classes

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#13110]
Consider this MWE:

```modelica
package TestMergeComponents
  model M
    Real x;
  equation 
    x = 2*time;
  end M;
  
  model S1
    M m1;
    M m2;
  end S1;
  
  model S2
    extends S1;
  end S2;
end TestMergeComponents;
```
If I flatten `S1` with `--newBackend -d=mergeComponents` I get
```modelica
class TestMergeComponents.S1
  Real[2] $M1.x;
equation
  for $i1 in 1:2 loop
    $M1[$i1].x = 2.0 * time;
  end for;
end TestMergeComponents.S1;
```
If I flatten S2, which is identical, I get:
```modelica
class TestMergeComponents.S2
  Real m1.x;
  Real m2.x;
equation
  m1.x = 2.0 * time;
  m2.x = 2.0 * time;
end TestMergeComponents.S2;
```
The desired behaviour is that also S2 is flattened into an array-based model.

**Comment by perost** [comment]
#13117 changes the behaviour so that elements inside the inherited classes are also merged. They're only merged if the extends clause doesn't have any modifiers though, since it doesn't work with modifiers. Each class is also merged separately since the merging is done before instantiation, so elements inherited from different classes won't be merged.

**Comment by casella** [comment]
Thanks @perost! This should change the behaviour of [ScalableTestGrids_NB_SymbolicJacobian](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestGrids_NB_SymbolicJacobian/ScalableTestGrids_NB_SymbolicJacobian.html): currently only the reduced models can actually run, because they are in fact not merged. The next test run should show all of them fail, unless of course #13076 got fixed in the meantime.

**Comment by casella** [comment]
Hmm, indeed they fail, but the extended models do fail in the frontend with [errors](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestGrids_NB_SymbolicJacobian/files/ScalableTestGrids_NB_SymbolicJacobian_ScalableTestGrids.Models.Type1.Type1_reduced_N_1_M_1.err) such as
[ScalableTestGrids 1.1.0-master/Models/Type1/Type1_reduced_N_1_M_1.mo:5:3-5:56:writable] Error:
Variable GEN_1_1.omega not found in scope Type1_reduced_N_1_M_1.

**Comment by perost** [comment]
> Hmm, indeed they fail, but not at runtime as expected, but rather in the frontend, with [errors](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestGrids_NB_SymbolicJacobian/files/ScalableTestGrids_NB_SymbolicJacobian_ScalableTestGrids.Models.Type1.Type1_reduced_N_1_M_1.err) such as
> 
> ```
> [ScalableTestGrids 1.1.0-master/Models/Type1/Type1_reduced_N_1_M_1.mo:5:3-5:56:writable] Error:
> Variable GEN_1_1.omega not found in scope Type1_reduced_N_1_M_1.
> ```
> 
> @perost can you please check?

That's because the model looks like
```Modelica
model Type1_reduced_N_1_M_1
  extends Type1_N_1_M_1;
  output Modelica.SIunits.PerUnit omega = GEN_1_1.omega;
end Type1_reduced_N_1_M_1;
```
That doesn't work with the current implementation since each extends clause is merged individually, without taking other extends clauses or elements into account.

I made some improvements in #13149 so that we use the same name map for all of the extends and then apply it to the binding equations in the root class. That should make this particular case work at least, but more complicated cases will likely need a complete redesign.

**Comment by casella** [comment]
OK, sounds good for the time being. Next year, when we hopefully have working test cases, we'll see if and how we need a redesign.
