### ISSUE TITLE
Set 'each' on extends modification

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#13150]
### Description

Currently it is not possible to set `each` on the extends modifier.

### Steps to Reproduce

```
loadString("package TestArrayModifiers
  model System
    parameter Real r[3];
  end System;
  model SystemVariant1
    extends System;
  end SystemVariant1;
end TestArrayModifiers;");
setExtendsModifierValue(TestArrayModifiers.SystemVariant1, TestArrayModifiers.System, r, $Code((each r = 4)));
```

This produces,

```
model SystemVariant1
 extends System(r(each r = 4));
end SystemVariant1;
```
which is wrong.

### Expected Behavior

How do I get,
```
model SystemVariant1
 extends System(each r = 4);
end SystemVariant1;
```

**Comment by perost** [comment]
I added a new API `setExtendsModifier` in #13151 which lets you set the modifier directly on the extends clause instead of on a specific element in it. The syntax is the same as for `setExtendsModifierValue`, just without the third argument.

It's actually just an alias for `setExtendsModifierValue` internally with the third argument set to `_`, so technically you can now also achieve the same thing with `setExtendsModifierValue`. But that's kind of obscure, so I added a new API call just to make it a bit cleaner.

**Comment by adeas31** [comment]
I will adapt OMEdit accordingly.

**Comment by adeas31** [comment]
I am adding this in OMEdit now but I get the following code and error when I set the value of `r`,

```
model SystemVariant1
 extends System(each r = 3);
end SystemVariant1;
```

`Non-array modification '3' for array component 'r', possibly due to missing 'each'.`.

I tried doing the same in Dymola and WSM, they both produces the same code but gives error on validating/checking the code,

Dymola says,
```
Type inconsistent definition equation:
r = 3;
The left hand side of the following equation is a vector
and the right hand side is a scalar, i.e. it has non-compatible parts:
r = 3;
```

WSM says,
```
Error: TestArrayModifiers.SystemVariant1 [[2:18-2:18]] Incompatible number of dimensions. 3 has type Integer but the expected type is Real[:].
Validation of model TestArrayModifiers.SystemVariant1 completed with 1 error.

```

**Comment by casella** [comment]
@henrikt-ma explained me why this is actually wrong: each is on the "wrong" side.

You can write
```modelica
model M
  model A
    parameter Real p = 1;
  end A;
  
  A a[2](each p = 1);
end M;
```
where you use `each` to apply the scalar `p` in the modifier to all the elements of the array `a[2]`.

But here, we are trying to do the opposite: System is a scalar and r is an array. It doesn't work this way.

You could write
```modelica
extends System(r(each start = 4));
```
but it doesn't work for the value, since we agreed a long time ago that "value" is not really an attribute of Real, see MLS 4.8.1, so we can't really write
```modelica
extends System(r(each value = 4));
```

**Comment by casella** [comment]
So, if `r` is a Real or Integer, you need to write something like
```modelica
package TestArrayModifiers
  model System
    parameter Real r[3];
  end System;
  model SystemVariant1
    extends System(r = 4*ones(size(r, 1)));
  end SystemVariant1;
end TestArrayModifiers;

**Comment by casella** [comment]
Or, if you can fetch the information about the size(s) of the array, you could use fill
```modelica
package TestArrayModifiers
  model System
    parameter Real r[3];
  end System;
  model SystemVariant1
    extends System(r = fill(4, 3));
  end SystemVariant1;
end TestArrayModifiers;
```
This also works for Booleans.
