### ISSUE TITLE
Question: integration on GIT in OMedit?

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#13212]
Dear OM team,

I have found this paper where a GIT integration into OMedit is present:

http://dx.doi.org/10.3384/ecp17132823

![image](https://github.com/user-attachments/assets/5c16bebf-1fe8-4a70-b2de-ef8026aa2849)

@adrpo  @adeas31 @alash325 It will be awesome to have a GIT integration into OMedit, have you considered this?

**Comment by adeas31** [comment]
The feature was not correctly implemented and had issued so we disabled it.

We don't have resources at the moment to work on this. I labelled it for 2.0.0. We will see if we can manage to implement it.

**Comment by casella** [comment]
To be honest, I've been using SVN since 2002 and GIT since 2010 for all my Modelica projects (quite many9 and I never really found a need for this feature. I think people should just use the GIT tools they prefer; in my case, the command line.

I would be hesitant at using a GUI that claims to do stuff on a GIT repo that I don't fully understand.
