### ISSUE TITLE
Submodels are now shown in the diagram as boxes/names

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#13211]
### Description

See the models we got via the OpenModelica mailing list.
![image](https://github.com/user-attachments/assets/54ad5da1-1502-46cb-999b-6afefbbf3d9b)

**Comment by perost** [comment]
`getModelInstance` doesn't trigger any errors and the annotations are there as far as I can determine, so most likely an OMEdit issue.

**Comment by adrpo** [comment]
The difference in json for one that works (older version like 40 commits ago) and the latest that doesn't work:

[omedit-good.json](https://github.com/user-attachments/files/17732468/omedit-good.json)
[omedit-bad.json](https://github.com/user-attachments/files/17732469/omedit-bad.json)

There only seem to be some connections in plus.

**Comment by perost** [comment]
> The difference in json for one that works (older version like 40 commits ago) and the latest that doesn't work:
> 
> [omedit-good.json](https://github.com/user-attachments/files/17732468/omedit-good.json) [omedit-bad.json](https://github.com/user-attachments/files/17732469/omedit-bad.json)
> 
> There only seem to be some connections in plus.

We fixed an issue where inherited connections were sometimes listed, see #13130. Maybe that had some unintended consequences in OMEdit? It's the icons and not the connections that are missing though.

**Comment by adrpo** [comment]
Yes, the icons are missing the connections are there.

**Comment by adeas31** [comment]
Might be related to PR #13177

**Comment by adeas31** [comment]
This is what we use to draw before the fix for #13174 with PR #13177,

![image](https://github.com/user-attachments/assets/7dc28a3f-84fe-4009-b039-45c0c7b86518)

After the fix it looks like this. For me this is the expected output.

![{26AC0EAB-88B0-410E-83FF-D67C67A6AF43}](https://github.com/user-attachments/assets/d0fc382f-5d6d-4688-b091-b7bf8eb82b90)

WSM also does the same as we do know,

![{C3A67E95-A412-4603-BF30-6257A4D508DC}](https://github.com/user-attachments/assets/b069719d-b074-44b5-8a5b-233478c174ea)

Dymola has the same display as we had before.

![{FA9ECFC5-5EB7-465E-91EE-AD2E3419BB30}](https://github.com/user-attachments/assets/17234301-8e0e-4d4e-8074-e6e5bac6d192)

It is up to us what we want. Do we want to have a default grey box when the model has no annotation? With the current master implementation, the grey box is only shown when the component has no icon annotation at all i.e., including its connectors and inherited models, if any if the connector or inherited model has annotation then we don't show the grey box.

@casella any suggestions?

**Comment by casella** [comment]
Somtimes people drag the connector onto the icon canvas, putting it on the borders of the extent area, but they forget to draw at least a square box to give some "boy" to the model. In this case, I would at least draw a default boundary, like Dymola does. The grey box is probably a bit too bold, but having ghost components with floating connectors doesn't really seem a good option to me. I don't see any concrete use case in which one would only like to see the connectors of an objet. BTW, dragging the object in that case would be problematic, because you'd have to grab it from the connectors, which starts a connection by default, unless you disable the connection mode.

BTW, this also raises an issue that I had with some library in the past. If you only show connectors, how can you drag a component? If you drag it by the connector, you get a connection line instead, unless you disable the connection feature. This is a bit annoying.

I would go for a light default boundary (like Dymola) with white background, so you can drag it from any point, not only from the boundary. 

@bilderbuchi, @dietmarw, what would you suggest?

**Comment by casella** [comment]
On the other hand, WSM approach may be the correct one: if there is no icon, you display no icon, and then if you really want it, you add it yourself.

The problem, as usual, is that this behaviour is not standardized, so if people create a library with a tool that displays default icons, they'll think this is the default behaviour with all tools, then you switch tools and the thing looks crazy.

@adeas31 would you mind opening a ticket on the modelica specification issue tracker and pose the problem there?

**Comment by dietmarw** [comment]
I'd prefer the original implementation with the default grey boxes unless an icon is specified. I don't mind the boldness of the grey box since it is en incentive for the lib dev to create proper icons.

**Comment by bilderbuchi** [comment]
> I'd prefer the original implementation with the default grey boxes unless an icon is specified. I don't mind the boldness of the grey box since it is en incentive for the lib dev to create proper icons.

I agree with this, this makes sense. It's also useful that it has the component's name. Floating connectors only is a confusing situation.

**Comment by casella** [comment]
Fine for me

**Comment by casella** [comment]
See modelica/ModelicaSpecification#3613. Feel free to express your opinion there 😃

**Comment by adeas31** [comment]
Fixed with #13215 and ported to maintenance/v1.24 with #13216
