### ISSUE TITLE
downloading previous version

### ISSUE THREAD

**Issue by alikazemian1998** [OpenModelica/OpenModelica#13214]
Hello. I need to install OpenModelica 1.20.0, but I cannot find its download file. I would appreciate if any body can help me.

**Comment by casella** [comment]
For Windows, you can find all the released version installers here: https://build.openmodelica.org/omc/builds/windows/releases/

Is there any specific reason you want to stick to 1.20.0?

We are constantly improving OpenModelica, which is way better now than it was in 1.20.0: faster, more robust, better GUI, improved support of libraries, better FMI export, etc. Our development policy is that we try hard to avoid introducing regressions and backwards-incompatible changes, and in case we do, we try to fix them as soon as possible in patch releases. In principle, everything that worked with 1.20.0 should work with 1.24.0, and beyond. 

The only exception to this policy concerns non-compliance with the [Modelica Language Specification](https://specification.modelica.org/maint/3.6/MLS.html). We strongly believe in the value of open standards, including the Modelica Language, and in the interoperability between OpenModelica and other Modelica tools; hence, we strive to make sure that OpenModelica is always stricly conforming to the latest released Modelica Language Specification.

Hence, whenever we find that something in OpenModelica is not conforming to the standard, we fix it. This could mean that models developed with previous version of OpenModelica may not work with newer versions, because their code was actually not valid Modelica code.

The right approach in this case is not to stick indefinitely with older versions of OpenModelica and with their bugs and shortcomings that have since then been fixed, but rather to fix the Modelica models so they actually conform to the standard.

For many of those cases, see e.g. #10386, we have also provided a complier flag [`--allowNonStandardModelica`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-allownonstandardmodelica), which disables some of the Modelica conformancy checks and allows to use models developed with previous versions of OpenModelica (or  other Modelica tools) using the latest released version of OpenModelica, without fixing the Modelica code. 

In OMEdit, these flags can be set in Tools | Options | Simulation | Additional Translation Flags. 

Using this feature is not recommended, because it hampers the portability of the Modelica code to other tools and because we may no longer support non-standard features in the future, as maintaining them costs additional development effort. However, it can be useful in many cases, e.g. when one does not have time to fix the Modelica code but wants to use a more recent version of OpenModelica, or when one depends on a Modelica library developed by someone else, which has some standard conformancy issue.

BTW, regarding Modelica libraries that are not conforming to the standard, we are currently testing over 80 open-source Modelica libraries on a daily basis; when we discover such problems, we try to get in contact with the library developers and encourage them to fix their Modelica code so that it is conforming to the standard. In the long term, this is the only way to develop a healty Modelica eco-system, which is based on an open standard and promotes interoperability.

Hope this helps.

**Comment by alikazemian1998** [comment]
Dear Francesco.

Thanks a lot for your response. The main reason I wanted to use the 1.20
version is that there's a library called "MosDH", but I can't run it with
the 1.24.02 version.
I would be thankful if you could help me.

Kind regards,
Ali

**Comment by casella** [comment]
Sure. Please provide more details on
- where to find the library (if it is open-source)
- what exactly are the problems you encounter

Please open another ticket for that, as support of MosDH library has nothing to do with downloading previous versions. Ideally, you should allow us to reproduce the problems you are facing, so we can see how to fix them.

Thanks!

**Comment by adrpo** [comment]
https://github.com/MoSDH/MoSDH
