### ISSUE TITLE
Parameter unexpectedly not defined during initialisation

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#13266]
I am designing a generic way to access single- and double channel component variants in a (user)pleasant way. After the previous effort #12842 turned out to be illegal, I found a more cumbersome but seemingly feasible way. However, I am running into puzzling problems of parameter values unexpectedly being undefined: 
```modelica
package ParameterCircus
  model Single "Single-channel component"
    extends Daughter(final N_internal=1); //single channel only needs 1-wide array
    extends PublicInterfaceSingle;
  equation
    counts = counts_internal[1]; // this wires public and internal parameters together
  end Single;

  model PublicInterfaceSingle
    parameter Integer counts "single count"; //users should access this
  end PublicInterfaceSingle;

  model Daughter
    extends Ancestor;
    parameter Integer[N_internal] counts_internal "Generic representation of counts";
  end Daughter;

  model Ancestor
  protected
    parameter Integer N_internal;
  end Ancestor;

  model MWE
    Single s(counts=5);
  end MWE;
end ParameterCircus;
```
Running `MWE` with OpenModelica v1.25.0-dev-174-g92fc808a19 produces 
> [ParameterCircus: 15:5-15:85]: Parameter s.counts_internal has neither value nor start value, and is fixed during initialization (fixed=true).

I don't understand why, though. `s.counts_internal` (inherited via `Daughter`) is of size 1, and has its only element's value defined by the equation in `Single`. `counts` is defined as 5 in the instantiation of `s`. 

# Expected behaviour
`s.counts`is `5`, `s.counts_internal` is `{5}`, `s.N_internal` is `1`.
Why does OM say that `s.counts_internal` has no value?

# Context
The idea is to access in single-channel components via `s.counts = 4` and in multi-channel components via `s.counts = {4,5,6}`, while sharing a common internal implementation (to observe DRY). I left out the multi-channel side here (as well as a load of other details) because it's not necessary for an MWE.

I also tried a couple of other approaches which turned out to be infeasible because I need to be able to set `counts` when instantiating a `Single`, and I need to make sure that the equality between `counts` and `counts_internal[1]` cannot be broken/overridden-by-modifier.

**Comment by bilderbuchi** [comment]
Ah, I was under the wrong impression that an `(initial) equation` would also count towards binding equation for parameters, in absence of others. >.<

The `fixed=false` approach looks suitable!

The second approach of giving a binding equation is something I actually tried first, but with 
```
extends Daughter(final N_internal=1, final counts_internal[1] = counts);
```
I could not get around subscripting being forbidden there. I did not realise that I could use a trivial `fill` as a workaround.

NB: I'm using `final` here so that the equivalence between `counts` and `counts_internal` cannot be broken by a user/ a subsequent modification etc. in the first approach I tried to use an equation for that purpose.

AFAICT now, this should resolve my problem, thanks a lot for the pointers!

**Comment by casella** [comment]
For the record, the initialization problem unknowns are:
- state variables
- state derivatives
- algebraic variables
- discrete variables
- fixed = false parameters

The equations are the collected from 

- equation sections
- algorithm sections
- initial equation sections
- initial algorithm sections
- variables with fixed = true attribute.
- discrete variables with fixed = true attribute

If the sytem is square, it is solved as such. If it is under-determined, there are heuristics to add some extra fixed = true attributes to make it square - note that these are not guaranteed to be invariant w.r.t. to the Modelica tool used, because they are dependent on heuristics.

If the system is over-determined, the backend tries to find redundant but consistent equations and to eliminate them. This is, e.g., what happens if you have index reduction, leading to redundant initial equations. If it doesn't manage to make the problem square, it fails. 

In the past, we also tried approaches to manage overdetermined initialization problems by solving min(sum(f_j(x)^2)) instead of solving f(x) = 0. It worked well on small examples, but it did not really scale up well, because the simple Nelder-Mead algorithm was used. We could reconsider using more scalable gradient-based minimization methods to handle larger models. This could actually be more robust than solving f(x) = 0, at least in some cases. On the other hand, it could end up getting stuck in bad local minima. Global optimization algorithms could also be explored.
