### ISSUE TITLE
Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.Guideline36Winter runs for 400 s and then times out

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#13285]
The model `Buildings.ThermalZones.EnergyPlus_24_2_0.Examples.SmallOffice.Guideline36Winter` runs for 400 s and then times out on the CI. The same model simulates successfully in 308 s on my Win-11 Pro machine (characteristics at the end), herbelow the simulation statistics:

```
### STATISTICS ###
timer
0.271274s reading init.xml
276.836s [ 89.6%] simulation
308.882s [100.0%] total
0.0551303s reading info.xml
0.0029249s [ 0.0%] pre-initialization
4.79574s [ 1.6%] initialization
0.0313369s [ 0.0%] steps
5.79841s [ 1.9%] solver (excl. callbacks)
0.88592s [ 0.3%] creating output-file
20.3186s [ 6.6%] event-handling
0.212946s [ 0.1%] overhead
events
4630 state events
3601 time events
solver: dassl
144951 steps taken
197267 calls of functionODE
84813 evaluations of jacobian
3716 error test failures
294 convergence test failures
260.827s time of jacobian evaluation
The simulation finished successfully.
```

The point is that the model is hard to be solved, as the statistics above show, so the timeout in the CI probably should be increased (at least for this model).

I tried to profile the solver performances with OMEdit on my machine, the non-linear system that seems to dominate the error (49148225 executions) has the dimension of 18x18 and the following six iteration variables:
```
- hvac.VAVBox[1].port_aAir.p
- hvac.fanSup.VMachine_flow
- hvac.splSupRoo[1].res3.m_flow
- hvac.splSupRoo[2].res3.m_flow
- hvac.splSupRoo[3].res3.m_flow
- hvac.splSupRoo[4].res3.m_flow
```

The plot of the iteration variables shows some critical intervals in which the transient is affected by small and quick variations, probably due to the control action.

![image](https://github.com/user-attachments/assets/7148b459-33c0-4e87-8866-09e7f3f2f8d9)

The control system is very complicated so it is very hard to understand the origin of said variations.

OpenModelica v1.25.0-dev-191-g9288a73aaf (64-bit)
Sysop: Win11-Pro (64 bit)
Processor: 12th Gen Intel(R) Core(TM) i9-12900HX   2.30 GHz
RAM: 32,0 GB (31,7 GB usable)

**Comment by casella** [comment]
@AndreaBartolini 49,148,225 executions for a nonlinear systems, given that there are "only" 197,267 calls to functionODE, seem to imply that the Newton solver iterates hundreds of times at each time step. 

This can be be confirmed by turning on the doomsday flag -lv=NLS_LOG_V, also using the [-lv_system](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-lv-system) and [-lv_time](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-lv-time) flags to selectively output information about that system only, over a limited time window. You could also run the simulation with a much lower StopTime to reduce the amount of output (and the run time).

If you indeed see all those iterations in the log, my educated guess is that they will have very small, but not small enough, residuals, due to some numerical ill-conditioning issues. Basically, the Newton solver iterates forever in the attempt of getting the residuals below the tolerance, and it may succeed in doing so after many attempts in a completely random fashion determined by the rounding errors, which are also probably influenced by the operating system. This may explain why the simulation is so much slower on the CI.

At that point, you can try to change [-newtonFTol](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-newtonftol) and [-newtonXTol](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-newtonxtol) to, say, 1e-10 or 1e-9 from their default values of 1e-12 and see if this solves the problem.

If that is indeed the case, then we should investigate why such system is so badly scaled. Maybe using proper nominal values for its iteration variables could help. Or maybe the system is close to singular and we should apply the SVD to the Jacobian to figure out what are the variables and equations involved in the singularity.

**Comment by casella** [comment]
Very good, thanks! We can focus on block 22283, which only has one iteration variable, so it is easy to diagnose. Can you please report a chunk of the log file that shows some iterations leading to nowhere on that block?

**Comment by AndreaBartolini** [comment]
The point is how to found the system that has erratic behavior and limits the step increasing... for example the solver stays around the time 449760 for 538 steps but the iteration variable of the 22283 practically does not change and its Newton converges in one iteration all the steps.
Is there a way to detect such erratic behavior so that to avoid to log all the blocks one by one and do that by hand?

**Comment by AndreaBartolini** [comment]
FYI I attach the log of the 22283 @449760 s
[Guideline36Winter.zip](https://github.com/user-attachments/files/17937540/Guideline36Winter.zip)

**Comment by casella** [comment]
OK, sorry, I was mistaken - in fact, from the profiling block it is clear that many (most?) blocks are ran over 10 million times. And system 22283 always converges very quickly. 

So, it's likely not an issue with the Newton solver, but rather with the ODE solver. BTW, of the 276 s spent by the actual simulation, 260 s are spent computing Jacobians. That's 96%. Quite bad. Not sure if the problem is that Jacobians are re-computed too often (about every 2.5 steps), or if the computation of Jacobians is too inefficient, or both.

@AndreaBartolini can you please try running the simulation with `--generateDynamicJacobian=symbolic`?

**Comment by AndreaBartolini** [comment]
By running the simulation with --generateDynamicJacobian=symbolic the OMC rises the following error:

```
[12] 10:36:04 Translation Error
Jacobian A contains non-linear components. This indicates a singular system or internal generation errors.

[13] 10:36:04 Translation Error
post-optimization module symbolicJacobian (simulation) failed.

```
I tried to see that Jacobian by using the flag `+d=symjacdump` but it returned tons of log... can you help me to find a quick way to reach the target inside them?

**Comment by casella** [comment]
Symbolic jacobians are known to have issues, that's why they are switched off by default. Nice try.

Maybe there is something wrong in the interaction with the external EnergyPlus code.

**Comment by NehaSPatwardhan** [comment]
This model simulating successfully in ubuntu but is crashing in windows. "Assertion is violated, violating min contraint=0" error is on the log file.

**Comment by casella** [comment]
> This model simulating successfully in ubuntu but is crashing in windows. "Assertion is violated, violating min contraint=0" error is on the log file.

Using which version of OMEdit? @AndreaBartolini reports a success

**Comment by NehaSPatwardhan** [comment]
> > This model simulating successfully in ubuntu but is crashing in windows. "Assertion is violated, violating min contraint=0" error is on the log file.
> 
> Using which version of OMEdit? @AndreaBartolini reports a success

 OpenModelica v1.24.2 (64-bit)

**Comment by casella** [comment]
After increasing the timout to 800 s, the [Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Winter.sim](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Winter.sim) simulates successfully.

@Pavanrajrh, please remove UniqueID 21 issues from the issue spreadsheet.

**Comment by Pavanrajhr** [comment]
> After increasing the timout to 800 s, the [Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Winter.sim](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Winter.sim) simulates successfully.
> 
> @Pavanrajrh, please remove UniqueID 21 issues from the issue spreadsheet.

Sure
