### ISSUE TITLE
Issue For addComponent script Api

### ISSUE THREAD

**Issue by onesandineye** [OpenModelica/OpenModelica#13353]
### Description

Use the OMShell call addComponent script api, the api can execute successful, but the format of generated annotation is error.

1. loadString("model test end test;")

2. addComponent(step,Modelica.Blocks.Sources.Step,test,$Expression(()),$Code((startTime = 0.1, offset = 0.1)),"test comment",$Expression(Placement(transformation(extent={{-60,40},{-40,60}}))))

Generated code is following:
`model test
  Modelica.Blocks.Sources.Step step(startTime = 0.1, offset = 0.1) \"test comment\" annotation(
    Placement = transformation(extent = {{-60, 40}, {-40, 60}}));
end test;`

I think the format of the generated annotation is error,  it should be
`model test
  Modelica.Blocks.Sources.Step step(startTime = 0.1, offset = 0.1) \"test comment\" annotation(
    Placement(transformation(extent = {{-60, 40}, {-40, 60}})));
end test;`

 - OpenModelica Version: 1.25-DEV
 - OS: win 11
 - Modelica: 4.0.0

**Comment by perost** [comment]
Fixed with #13360.

It seems the expected way to do this previously was to use `Placement(transformation = transformation(...)))`, which doesn't really make any sense. I guess `Placement(transformation = Transformation(...))` could make sense, but the idiomatic way is to use `Placement(transformation(...))` like in your example.

With my fix all three ways now work the same. I would remove the first one, but I don't want to break any existing scripts unless it's necessary.
