### ISSUE TITLE
Question about library versions

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#13352]
I have two questions about library versions:

¿Can I mix in a model components that use MSL 3.2.3 and others that use MSL 4.0.0 ? I understand that OM only opens a unique version of MSL.

Can I tell inside a model that uses a library with a version equal or greater to a defined version: E.g. uses(Modelica(version >= "4.0.0")))?

**Comment by perost** [comment]
You can't use multiple versions of the same library in a model since it would cause name conflicts, even if loading multiple versions was allowed it wouldn't be possible to determine which version a name refers to.

As for your question about `uses`, being able to specify a version equal or greater wouldn't really work since you don't know if future versions of the library will be compatible or not. It's instead the libraries that specify which versions they are backwards compatible with, e.g. MSL 4.1.0 contains `conversion(noneFromVersion="4.0.0")` to say that it's compatible with MSL 4.0.0 without any need for conversion. So if you load a model that uses 4.0.0 but only have 4.1.0 installed it'll just use 4.1.0 instead.

**Comment by BasilioPV** [comment]
Thanks @perost ! Now it's clear for me.
