### ISSUE TITLE
Check of models with partial Medium packages fails

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#3944]

**Comment by bilderbuchi** [comment]
Original issue: [link](https://trac.openmodelica.org/OpenModelica/ticket/3944)

With the mentioned simple model
```
model check
  inner Modelica.Fluid.System system;
  replaceable package gas = Modelica.Media.Interfaces.PartialMedium;
  Modelica.Fluid.Vessels.ClosedVolume free_volume(
    V = 0.01, use_portsData = false, 
    redeclare package Medium = gas);
end check;
```
this issue is still valid, although the error message has changed again:
> [1] 13:29:54 Translation Error
[Modelica.Media: 4476:7-4479:18]: [Called function ‘check.free_volume.Medium.temperature‘ is partial.]

**Comment by bilderbuchi** [comment]
Related to this: #3304?

**Comment by perost** [comment]
> @perost, when doing checkModel, could we use the default start value and continue?

I'm not convinced that's a good idea. Whenever I reduce models to create MWE and need to replace a binding with something simpler I usually choose 1 rather than 0, because using 0 often creates problem like creating empty arrays where it's not expected.

I implemened the same behaviour we have in the old frontend instead, which is to consider dimensions to be unknown if they can't be evaluated during checkModel. I also made a few other changes to how we evaluate things, since the NF is more thorough in evaluating structural parameters compared to the OF.
