### ISSUE TITLE
Make sure variables which are practically constant are displayed as such in OMEdit

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4232]

**Comment by casella** [comment]
Original trac ticket: https://trac.openmodelica.org/OpenModelica/ticket/4232

**Comment by casella** [comment]
Today I stumbled again on this problem. 
![immagine](https://user-images.githubusercontent.com/4233148/154698740-528557ef-f441-49df-9871-3facf97be65b.png)
This plot makes no sense al all. Those six variables are all 1 +/- 1e-12. They should be displayed as constants equal to one. As @jph-tavella commented in the original ticket, these plots are meant to show physical results, not to debug the solver. I totally agree with that. @max-privato argued that one should indeed see the dirty stuff, because that has educational value; I see his point, but yet IMHO the cons outweigh the pros.

Besides, the current output doesn't even allow to debug the solver, because the labels on the Y axis and the dynamic info shown when hovering with the cursor over the results do not allow to actually figure out what is the amplitude of those numerical fluctuations, nor to understand if their amplitude corresponds to something physically meaningful, or is just numerical noise.

@adeas31, I would suggest to use the following criterion: when plotting a variable v, if `(max(v)-min(v))/max(abs(v)) < 1e-8`, then set the upper and lower limits to `max(abs(v))*(1 + 1e-6)`, `max(abs(v))*(1 - 1e-6)`. I this way one would see a constant plot, and still see different (but very close) labels on the Y axis.

Please note you still have to handle the special case of constant v = 0. The way it is handled currently looks good to me.

All these cases should show a constant value, and show different values on the Y axis:
```modelica
model Test
  Real v1 = 1*(1+ 1e-10*sin(time));
  Real v2 = 1000*(1+ 1e-10*sin(time));
  Real v3 = 1e-5*(1+ 1e-10*sin(time));
  Real v4 = 0;
end Test;
```
