### ISSUE TITLE
OMEdit allows invalid connections

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4337]

**Comment by casella** [comment]
Original trac ticket: https://trac.openmodelica.org/OpenModelica/ticket/4337

**Comment by adeas31** [comment]
We can of course use the instance-based API but maybe its better if we do this in the compiler. @perost what do you think? Perhaps we should have a dedicated API just for checking the connection.

**Comment by perost** [comment]
> We can of course use the instance-based API but maybe its better if we do this in the compiler. @perost what do you think? Perhaps we should have a dedicated API just for checking the connection.

Doing it in the compiler might be tricky, at least without instantiating the whole model. We could cache the connectors from the instance API, but that would instead take a lot of memory. So it's probably easiest to do it in OMEdit instead. I can have a look at it myself if you want.

**Comment by adeas31** [comment]
OK. I am just not sure what to consider when checking if connectors are compatible or not. Like check type of connectors, their causality etc. If you can manage some time then sure take a look at it.

**Comment by casella** [comment]
> #10704 implements some checking of connections in OMEdit using the instance-based API. It does some basic type checking and checks that components with the same direction aren't connected to each other, but it doesn't check that e.g. array dimensions match since that's quite complicated to do.

LGTM

> I'm also not sure how to best handle invalid connections since e.g. #2450 indicates that we probably don't want to just forbid them, so for now I just print an error message but still allow the connection to be created.

I checked #2450. I see two cases mentioned:
- partial classes are connected. This is of course OK in a partial model, but I understand checks on partial classes are lifted already when dealing with the inst-based GUI
- connector with sized depending on parameters are connected, before the parameters are set. This however falls into the already mentioned category of not checking array sizes

I don't really see the point of accepting a connection with wrong types, except for the cases of mismatching array sizes. How could it be possible to fix it later on?

**Comment by adeas31** [comment]
@casella try the latest nightly build. OMEdit now shows an error message for invalid connection but still allows the connection. We can easily change it to not allow when connection is invalid.

**Comment by casella** [comment]
Please check the attached [WrongConnects.mo.txt](https://github.com/OpenModelica/OpenModelica/files/11573581/WrongConnects.mo.txt).

If I connect the components in Test1, I get a "Scripting Error" but the connection is retained. I don't really see the value of doing that, since there is no way this kind of connection could become valid. This only helps confusing beginners, #10733 is a paradigmatic example of that.

I also have the feeling that people tend to overlook the error messages that are shown there, particularly since they are sometimes bogus or inexplicable 😅 

I would suggest not to add the invalid connection, and to issue a pop-up window with the error.

Ditto for Test2

Test3 does not generate any error if I connect the two components, which have incompatible array size. This is OK, as one may want to input the table values afterwards, and that's perfectly legitimate. Of course if I check the model I get an error, but this is also fine.
