### ISSUE TITLE
Put connecting lines above icons surrounded by blank pixels around lines to enhance readability

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4645]

**Comment by adeas31** [comment]
https://trac.openmodelica.org/OpenModelica/ticket/4645

**Comment by max-privato** [comment]
Like every year  I come across this issue every initial period of semesters.
I still consider it to be a big issue.
I understand that the solution requires connections to be on top of components, but this should be Ok (we need to have a look a the outcome, though).
Today a student of mine connected a resistor on the wrong terminal and did not realise it (later I showed it hovering on connections) because the line was under the resistor: the mistake was not visible.

**Comment by casella** [comment]
I agree this is indeed a big deal. It is really too easy to make bad mistakes that are not visible, and in fact Dymola fixed this issue long time ago. We'll try to get this done in 1.21.0

**Comment by ceraolo** [comment]
I would like to change this ticket's name, but I'm not allowed to do so.
The name should be:
_put connecting lines above icons surrounded by blank pixels around lines to enhance readability_

Indeed, as clarified by @adeas31 the major issue is that the connecting lines are below icons and not above.
I did not realise this in the very beginning, since the first time I came across this issue was with diodes, which to not show the actual issue substance.

**Comment by ceraolo** [comment]
@adeas31 Any news on this?
I think this is the most important improvement (along with New API) I can offer to my students this year, but in case I would need to have this in a matter of days.
Thank you

**Comment by casella** [comment]
I'm adding one more example where this feature is essential - I stumbled upon it accidentally a few days ago: [Example.mo.txt](https://github.com/OpenModelica/OpenModelica/files/12574785/Example.mo.txt).

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/4f9aee9d-123e-4904-88a5-7b16f2ecd3f6)

This model produces weird results (no heat flux into the heat port of the bread slice). The reason is that I accidentally connected the ambient source to port_b of heatConvection instead of port_a. This can be understood if I hover on top of the connection:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/52844f82-fdf4-4510-8bff-7d1ab8e2c2dd)
but it's still not immediately understood, because there is no visual clue about which port is port_b.

The actual (wrong) connection becomes appartent if I rotate the heatConduction component:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/c251aac8-52f1-43cf-9e76-c302d0d8ec2b)
Note that this is not a short-circuit of the component itself, but is rather a wrong connection from another component.

This points out that we probably need two features:
1. the connection should not be hidden by the component, but be drawn on top. This is also required to be able to select the wrong connection when it is completely hidden by the component (not in this case)
2. when hovering on a connection, we should not only show the connect statement, but also highlight the two ports in the diagram

**Comment by casella** [comment]
My suggestion for the time being is to draw connections on the top. To avoid spoiling the connectors, we should draw the white boundary not throughout the entire length of the connection, but rather leave the initial and terminal part unscathed, so as to avoid spoiling the connectors. This is a heuristic solution, because we need to guess how large those connectors are.

If you can access the extent of the two connected ports, you can use it to estimate where you should stop drawing the white border. Otherwise you can do something like drawing the white border from 20% to 80% of the connection, or something like that. It will probably be a bit ugly, but it's just meant to highlight stuff that needs to be removed anyway.

**Comment by casella** [comment]
A better solution can be implemented later one while working on advanced visualization. 

As @adrpo correctly pointed out during our meeting, it would be important is to highlight collisions between connection lines and connectors _which are not part of the connect statement_, because it's them that can lead the user into thinking that a certain connection is made, while it's not.

Maybe it would be best if the connection routing algorithm automatically avoids these situations, by detecting a collision between the connection lines and ports that are not involved in the connect statement, and making sure the connection line goes around their extent, to avoid misleading diagrams.

**Comment by casella** [comment]
@ceraolo this completes the first part of the DFD, due for end of August. Please check it ASAP. The Windows nightly builds are now active, the Linux pipeline is still being fixed, please check https://test.openmodelica.org/jenkins/job/LINUX_BUILDS/ to see if that was eventually successful.

**Comment by mahge** [comment]
> The Windows nightly builds are now active, 

 While the last nightly build was built successfully it, unfortunately, was faulty when opening OMEdit.  

You should wait the most recent one which is now being built. It should be ready in about 2 hours.

**Comment by max-privato** [comment]
Installing on Windows is much slower than linux, but this ticket deserves it!
I've just had a look.
The result is quite impressive, and near to what we expected.

However, I note a significant drawback when we wires overlap. Consider the following diagram:
![image](https://github.com/OpenModelica/OpenModelica/assets/37046832/c74134c2-56af-4a0b-8f74-fcce3910b3e6) 
![image]

Here I connected the positive terminal of resistor 1 and resistor 2 to the negative of resistor.
The result is a bit misleading since resistor1 seems unconnected. However, this is still much better than what we had just a few hours ago.

To avoid this, the blank pixels should be added only whenever a wire overlaps a model's icon. 
Can this be implemented easily? Otherwise, maybe, we must wait until when ticket #11115 is addressed.

**Comment by adeas31** [comment]
I also noticed this and thought its better to fix #11115 instead of doing some work around for this.

**Comment by ceraolo** [comment]
> I also noticed this and thought its better to fix #11115 instead of doing some work around for this.

Ok.

Another example, which shows that now #11115 gets higher priority.
This is an inverter.
Old view:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/9895cd50-ddad-4ea0-bbc4-a9eb64f7ccd4)

New view:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/903cf967-835e-438d-b50c-8817b9122509)
 Not sure that the new view is better than the old's.

I'm sure, however, that the new view with the addition of #11115 will change the user experience dramatically in comparison with the old view.

**Comment by adeas31** [comment]
How does these models look like in other tools? Or can you share the code?

**Comment by ceraolo** [comment]
Here's the Dymola's appearence:
 
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/7bd73098-a1cf-41fd-8aa7-a9a0cc581e76)

Here's the code:
[Inverter.mo.txt](https://github.com/OpenModelica/OpenModelica/files/12619401/Inverter.mo.txt)

It's also interesting to see how the dots move dynamically when moving around objects in Dymola. I can supply a short video if this would help.

**Comment by adeas31** [comment]
I already fixed #11115 and here is how is looks in OMEdit now,

![image](https://github.com/OpenModelica/OpenModelica/assets/4007231/bd706d49-0330-4394-8dbd-5f8fe5cbd3f6)

**Comment by ceraolo** [comment]
You reacted increadibly fast!
Your result looks great.
I'm looking forward to seeing it personally, as soon as nightly is available.

**Comment by casella** [comment]
Very good job, nice that we can get this in 1.22.0 😃

**Comment by casella** [comment]
I showed this to @AndreaBartolini, and he noticed two weird things:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/0f04fffd-e769-427d-8956-f3c080f10ab2)
The first is the node shown on the bottom left corner of the connection, which is a bit weird. Dymola correctly doesn't show it.
The second is the dangling connection of the diode second from the left. Which is also dangling in Dymola. Is that unconnected on purpose?

**Comment by casella** [comment]
Last, but not least, I would recommend to make the nodes a bit smaller, currently they are really conspicuous, being the same size of connectors. That shouldn't really be the case.

**Comment by ceraolo** [comment]
I also checked the much-awaited enhancement in #11115 , valid per se, but great in conjunction with this one.
I'm 90% satisfied with the result, and I'll use it this nightly for next semester in my University (I have no more time to wait for further enhancements).

The only glitches I see are exactly those mentioned by @casella  in https://github.com/OpenModelica/OpenModelica/issues/4645#issuecomment-1721573148 and https://github.com/OpenModelica/OpenModelica/issues/4645#issuecomment-1721903541

**Comment by casella** [comment]
@ceraolo your students using Windows can easily install a specific nightly, using the corresponding installer, but not with Linux, which is installed with apt, unless they compile it from sources, which is not trivial.

If you are fine with the current situation, we can make a stable development release 1.22.0-dev.01 on Monday, so you can also install it on Linux.

Further small improvements will end up in the 1.22.0-dev.betaXX betas and in the final 1.22.0 release, available in the next few weeks.

Is that OK for you?

**Comment by ceraolo** [comment]
My students in their personal computers, and the PCs in the classroom use windows.

I could ask IT mantenance guys to install today's nightly (dev-341) or Monday's 1.22-dev01 if available. I have no preference.

As regards Linux, I use it in a virtual box with nightly release branch just to have fast acccess to the latest nightly when in need.

**Comment by casella** [comment]
If you want your students to use exactly the same version, I guess haveing 1.22-dev.01 would be preferrable, so they can also get it if they have Linux on their PCs.

I'll ask @adrpo to proceed with that.

**Comment by adrpo** [comment]
The Linux builds are broken because of the Qt changes that @adeas31 did (I guess for this) :)
https://test.openmodelica.org/jenkins/blue/rest/organizations/jenkins/pipelines/LINUX_BUILDS/runs/2360/nodes/135/steps/387/log/?start=0
When those ar fixed I will branch the master.

**Comment by adeas31** [comment]
I know why Linux builds are broken. I will fix asap.

**Comment by casella** [comment]
I played around with the Inverter model and I identified the issues shown in this diagram:
![immagine](https://user-images.githubusercontent.com/4233148/268345123-0f04fffd-e769-427d-8956-f3c080f10ab2.png)

I would close this ticket, which was mostly accomplished and is becoming way too long, and open another two on the specific remaining issues.
