### ISSUE TITLE
Windows installers fail SmartScreen checks

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4829]
When installing OMC on Windows, the SmartScreen filter identifies the OMC installer as suspicious software from unidentified authors, and requires to give explicit consent to perform a potentially dangerous installation.

This may be ok for hardened hackers that know about the OSMC, but it's not projecting an image of quality and dependability on the sofware, particularly for industrial and corporate use. Looking like potential malware is not a very good marketing strategy :)

I would recommend that from 1.13.0 we start signing the installer with a certificate, so that we avoid this kind of problems. More information on how to do this is found ​[here](https://blogs.msdn.microsoft.com/ie/2011/03/22/smartscreen-application-reputation-building-reputation/).

----------
From https://trac.openmodelica.org/OpenModelica/ticket/4829

**Comment by AnHeuermann** [comment]
> But it's possible to create a self-signed certificate. It shouldn't be any problem to sign the executables.

A [self signed certificate](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing) only works when end users manually install the certificate on their machines. And in an enterprise setting this might not be an option and is not really an improvement.

Currently I can't solve this issue because I can't buy anything for OSMC and I don't know exactly how where we create the Windows installer. @adrpo can you point me to it?

But if someone buys a certificate I can check and update our build scripts. Should not be any harder then running something like
```
SignTool sign /fd SHA256 /a /f signingCert.pfx /p password filepath.appx
```
before uploading to openmodelica.org.
I can try with a self-signed certificate first. Also I would need to get a secret into Jenkins. @sjoelund can probably help me with that.

**Comment by adrpo** [comment]
Here we make the installer: 
https://github.com/OpenModelica/OpenModelicaSetup/blob/master/BuildWindowsRelease.sh#L165
You could add the self sign after that.

**Comment by casella** [comment]
We now have a CS certificate that was used successfully to sign the installer. @adrpo and @adeas31 will look into automating the process for the nightly builds.

**Comment by casella** [comment]
> Should be fixed with: [OpenModelica/OpenModelicaSetup@6132e97](https://github.com/OpenModelica/OpenModelicaSetup/commit/6132e97694330701f474443987d008cef27acde1) Let's see how it works in on the next build.

Unfortunately it [failed](https://test.openmodelica.org/jenkins/job/Windows/job/OM_Win_NIGHTLY_BUILD_64bit/1140/). Not sure if the signature is the problem.
 
> I guess we can also manually sign 1.18.0 and 1.18.1.

Yes, please do.

**Comment by adrpo** [comment]
Last night the 64bit version got signed:
![image](https://user-images.githubusercontent.com/4192979/159121446-29240b0b-0f26-4c35-8c27-8dd57042e2db.png)
but then the program did a login timeout (whatever that means, it could be you need to manually re-login with a new token each NN hours) and the 32bit did not get signed.

**Comment by casella** [comment]
Maybe you could ask to the signature software providers how to deal with this. After all, it's not cheap software by any means...

**Comment by adrpo** [comment]
We did. Is not possible. However from the information they gave us we have some idea on how it could work (I will not write about that here).

**Comment by AnHeuermann** [comment]
@adrpo Can we manually sign the v1.19 official release?
I just checked and SmartScreen is still failing.

**Comment by casella** [comment]
I think @adeas31 can take care of that

**Comment by adrpo** [comment]
We had to run the Jenkins slave as a process instead of a service (to have the same session as the user holding the certificate) to be able to automatically sign the installer. The setup process is now changed to use the new certificate.

I also made a script that signs all the .exe files in: https://build.openmodelica.org/omc/builds/windows/ and started it. 
It will take a while but we should have all executable signed soon. This will also update the .md5sum files as is needed after we sign the executable.

**Comment by sjoelund** [comment]
Maybe this is why the disk space on the backup ran out again :)

**Comment by casella** [comment]
I hope the backup disk space can be restored.

In the meantime I tried the latest nightly and I got a nice message about OpenModelica being kosher.

So, we can finally close this ticket.

**Comment by adrpo** [comment]
Not yet done. The program timeouts if the computer is idle for some time and asks for the password again so is not yet working to automate as we want.

**Comment by adrpo** [comment]
It works now to automatically sign the nightly-builds. Had to put the screen off timeout to never in the power options but now it works fine.
