### ISSUE TITLE
Support for Real x(value=10.0)

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4907]
See also: https://trac.openmodelica.org/OpenModelica/ticket/4907

**Comment by adrpo** [comment]
ClaRa and other libraries uses this pattern:

`Real component(value=someValue)`

instead of

`Real component = someValue`

I think that it was easier to see if you have conditional components, for example:

`Real component(value=if cond then a else b) if someConditional;`

vs.

`Real component = if cond then a else b if someConditional;`

But you could also write it like this:

`Real component = (if cond then a else b) if someConditional;`

@perost, how complicated it would be to add support for this?

**Comment by perost** [comment]
> @perost, how complicated it would be to add support for this?

It will complicate the handling of modifications since you need to merge binding equations and value-modifications (but only if the element you're modifying has a value-attribute), which would also be bad for performance. It also means we need to do a look up of the value attribute for every component of a type that has one when determining their binding equations, leading to even more complications and performance implications.

So it's really not something I'd want to support, particularly since it's now clear that it's not legal Modelica. It would be much better to fix the library instead, since relying on such non-standard extensions will just keep causing issues.

**Comment by adrpo** [comment]
Ok. Good to know for the meeting we will have tomorrow with some of the people that developed libraries that use this pattern. I will ask if they really need this or not.

**Comment by perost** [comment]
I did a quick grep on `ClaRa` and found 78 instances of value-modifiers, 6 of which use an if-expression as binding equation. So fixing the library would be a matter of minutes.

**Comment by adrpo** [comment]
I know, I fixed this several times, but on copies of ClaRa as we never been able to port it back to the original source. The github copy even has my PR with this. Hopefully tomorrow we can make some proper progress on this.

**Comment by perost** [comment]
You might want to point out that the value-attribute has been removed from recent versions of the specification, and since Hans Olsson was the first to say that it shouldn't be allowed it might not be as well supported in future Dymola versions (I doubt they'll remove it completely due to backward compatibility, but it could become less easy to use).

**Comment by casella** [comment]
Yeah, the value modifier is clearly out of the standard, so I would not try to support it, that would apply pressure on exactly the wrong direction.

**Comment by AnHeuermann** [comment]
I checked most of the outputs from https://libraries.openmodelica.org/branches/v1.18/ClaRa_dev/ClaRa_dev.html and this seems to be fixed in ClaRa_dev.

Closing this issue since we all agree that we don't want to support this non-standard way of `x(value=10.0)`.

**Comment by casella** [comment]
The testing for the library with this issue fixed is now up and running, see [ClaRa_dev report](https://libraries.openmodelica.org/branches/master/ClaRa_dev/ClaRa_dev.html). Compared with the [released ClaRa](https://libraries.openmodelica.org/branches/master/ClaRa/ClaRa.html) library, we have 77/142 models passing the frontend, instead of 26/142, and 59/142 models simulating successfully instead of 24/142.

Still some road ahead, but we're finally making tangible progress.
