### ISSUE TITLE
Allow setting each and final prefixes via the API

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5489]

**Comment by adeas31** [comment]
> when changing the unit, the displayUnit modifier should get the each prefix automatically if the parameter is an array, otherwise the model is invalid (https://github.com/OpenModelica/OpenModelica/issues/5395).

With PR #11019 the user can set `each`. OMEdit doesn't automatically add it. We had a discussion about it https://trac.openmodelica.org/OpenModelica/ticket/5405#comment:5 and decided to leave it to user to select it or not.

**Comment by casella** [comment]
> With PR #11019 the user can set `each`. OMEdit doesn't automatically add it. We had a discussion about it https://trac.openmodelica.org/OpenModelica/ticket/5405#comment:5 and decided to leave it to user to select it or not.

I agree that the user should have the freedom to choose. That said, I wonder, could we make some analysis on the input and refuse to accept a wrong modifier right away, instead of accepting it and then getting an error from the compiler later on?

I guess it's a fairly typical error for beginners (and not only for them) to forget `each` when applying a scalar modifier to an array parameter, we should try to prevent this a priori if possible.
