### ISSUE TITLE
Slow performance of 3D animation with repeat

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5695]

**Comment by anotheruserofgithub** [comment]
Original ticket: https://trac.openmodelica.org/OpenModelica/ticket/5695

This has certainly been fixed in [`59ef2a3`](https://github.com/OpenModelica/OpenModelica/pull/9389/commits/59ef2a3796f1227d8330d2b8e7876fa4e42e39cf), the issue being that [`osg::Geode::addDrawable()`](https://github.com/openscenegraph/OpenSceneGraph/blob/OpenSceneGraph-3.2.3/src/osg/Geode.cpp#L53) does not check for already existing drawables, hence duplicated all the [`osg::Shape`](https://github.com/openscenegraph/OpenSceneGraph/blob/OpenSceneGraph-3.2.3/include/osg/Shape)s with every time step (upgrading OSG would not help, see [this commit](https://github.com/openscenegraph/OpenSceneGraph/commit/1cd1ab1c60bf1af639c62cd4df51d3090d418ad4)).

Thanks to the [`osgViewer::StatsHandler`](https://github.com/OpenModelica/OpenModelica/blob/d85e7290b4f2a49afa640256db15473e6eda1a49/OMEdit/OMEditLIB/Animation/ViewerWidget.cpp#L102) you can easily see the difference before and after the fix with some OSG on-screen statistics, which are shown by left-clicking on the animation window to give it the focus, then pressing the S key four consecutive times (and once more to hide them).

@adeas31 Do you remember what model you were using to try replicating the issue, or do you think this ticket can be closed?

**Comment by adeas31** [comment]
You can test any model.

As I remember one of the issue was also that we allocate memory every time we read the values from the result file.

**Comment by casella** [comment]
A nice model for 3D visualization testing is Modelica.Mechanics.MultiBody.Examples.Loops.EngineV6_analytic. It has quite some stuff to display.

**Comment by adeas31** [comment]
@anotheruserofgithub I made some tests and indeed this seems to be fixed now. Thanks!
