### ISSUE TITLE
NF cannot evaluate structural parameter

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5991]

**Comment by casella** [comment]
Good! Can't wait for the library testsuite report 😃

**Comment by perost** [comment]
> Good! Can't wait for the library testsuite report smiley

Sorry for the delay, the `-d=-nfScalarize` test cases are the bane of my existence :)

But it probably won't be as big of an improvement in coverage as we would've liked, a lot of the models still fail in the frontend due to other unrelated issues (mostly some possibly suspect uses of conditional components that I'm looking into).

**Comment by casella** [comment]
> But it probably won't be as big of an improvement in coverage as we would've liked, a lot of the models still fail in the frontend due to other unrelated issues (mostly some possibly suspect uses of conditional components that I'm looking into).

As they say in French, "Un train peut en cacher un autre" (warning at railway crossings, a train could hide another one). At least we'll know why they fail.
