### ISSUE TITLE
Too many events in BRSL PressureValves models

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#6419]
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6419

**Comment by niklwors** [comment]
I checked the model again and it has no time events as well as no state events.

**Comment by AnHeuermann** [comment]
I'll take a look into this on Friday (after I got the test model).

The event handling is starting to create a massive pile of issues that are more and more complicate to fix. Maybe we need to re-make the whole event handling at some point. But that is not an easy task either. But that we are lacking support for time events is a fundamental flaw. But thinking about events from synchronous, delay and spatialDistribution right from the beginning should help.

**Comment by niklwors** [comment]
@AnHeuermann  @sbaetzing  I have tested the related models. 
The model
*Rexroth_Generic_Test.Hydraulics.PressureValves.PressureReducing.PressureReducing_TC04*
 is working fine now
The models 
*Rexroth_Generic_Test.Hydraulics.PressureValves.PressureRelief.PressureRelief_TC04*
*Rexroth_Generic_Test.Hydraulics.PressureValves.PressureReducingThreePort.PressureReducingThreePort_TC04*
still have the same issue:

_assert            | debug   | Simulation terminated due to too many, i.e. 20, event iterations.
|                 | |       | This could either indicate an inconsistent system or an undersized limit of event iterations.
|                 | |       | The limit of event iterations can be specified using the runtime flag '–mei=<value>'.
assert            | info    | simulation terminated by an assertion at initialization_

**Comment by AnHeuermann** [comment]
Then I need to check the models again and see if I can find a better solution.
Maybe I can figure out why that one variable is jumping between `0.0` and `1e-13` and stop it from doing that.

Also my first attempt in #7515  is doomed, because there are some tests from the testsuite that are failing. I guess they use some assert that check if something is smaller/bigger then something which works for equality, but now I changed it a tiny bit so that it can't work in that case any more.

**Comment by AnHeuermann** [comment]
Okay, I think @phannebohm and myself got a lot close to the solution of this one.

We have two observations:
1. The simulation is stuck during initialization because some variables are changing if you call the function DAE `data->callback->functionDAE(data, threadData)` twice in a row.
2. The value of one variable changes ever so slightly in a non-linear system during the solving with Newton
    The example works with `-nls=kinsol`.

**Comment by casella** [comment]
>     1. The simulation is stuck during initialization because some variables are changing if you call the function DAE `data->callback->functionDAE(data, threadData)` twice in a row.

Huh? Is this supposed to be possible, or is it just a bug?

**Comment by phannebohm** [comment]
It looks like bug. Only the mixed solver seems to be affected though

**Comment by phannebohm** [comment]
I have some vague attempt for the mixed solver. But to be honest, I have no idea what is happening there, partly because I don't know the solver well enough. I will try with PR #7568 and see what happens.

**Comment by casella** [comment]
@niklwors, can you please check?

**Comment by niklwors** [comment]
The test examples are working with the Kinsol now. The problem is that they are only test examples, so it would be good if there is also a default solver with which the examples work.

**Comment by casella** [comment]
@niklwors I'm not sure I'm getting your point. Do the examples mentioned in the original ticket work with the default solver now?

**Comment by niklwors** [comment]
yes, the mentioned examples are working. But they are only examples to demonstrate the use of the component- models. 
But the problem can also be caused by other models that use these component models.

**Comment by niklwors** [comment]
We can close the ticket for the moment and we give a recommendation, if the error with too many events occurs, to use the Kinsol solver.

**Comment by casella** [comment]
Seems reasonable to me. In case this is still a problem, we can try some further fixes in a 1.18.1 release later this autumn. As usual, for that we would need some examples that demonstrate the issue.

**Comment by AnHeuermann** [comment]
If @phannebohm doesn't succeed with "fixing" the mixed solver, we can always use the brute force approach by adding some flag to the library that is only valid for OpenModelica and will use a different default solver or will not fail if it reaches the maximum number of allowed retries in this evaluate-residual-until-nothing-changes-loop.

**Comment by casella** [comment]
Why not making this the standard behaviour? I assume something like this can also happen with other libraries. Do you see any downsides to it? I don't.

**Comment by AnHeuermann** [comment]
I don't know exactly where we can add these OpenModelica annotations inside a package, but apparently as of now such annotations are not passed down.

I guess instead of a package with
```modelica
package myMinimalPackage
  model myModel
    Real a(start = 1), b(start = 1);
  equation
    a ^ 2 + b = sin(time);
    a + b^2 = cos(time);
    annotation(__OpenModelica_simulationFlags(nls = "kinsol"));
  end myModel;
end myMinimalPackage;
```
we want to have something like
```
package myMinimalPackage
  annotation(__OpenModelica_simulationFlags(nls = "kinsol"));
  model myModel
    Real a(start = 1), b(start = 1);
  equation
    a ^ 2 + b = sin(time);
    a + b^2 = cos(time);
  end myModel;
end myMinimalPackage;
```

and that every mode that is using `myMinimalPackage.myModel` will automagically get the annotation as well.

Currently this is of course not working. Not sure what we would need to do to pass the annotation to all models in `myMinimalPackage` and models outside of the package. I guess @perost knows how one should do that. But if we want to do this we should start a separate issue for that idea.

**Comment by perost** [comment]
> Currently this is of course not working. Not sure what we would need to do to pass the annotation to all models in `myMinimalPackage` and models outside of the package. I guess @perost knows how one should do that. But if we want to do this we should start a separate issue for that idea.

I don't think we should be passing annotations around, but rather check which packages a model is using and set simulation flags based on that.

Some consideration would need to be given to the situation where there are multiple annotations though, either if the user uses multiple packages or if the user sets their own simulation flags. Also, if we add an annotation to the users model based on which packages are used we might get issues with updating the flags. What happens if the user removes the use of a package from their model? Just removing the flags is not so easy since we don't know where the flags came from in the first place.

**Comment by casella** [comment]
@AnHeuermann, sorry if I insist, but I don't really think we should spend time going down this path. Primarily because it is not standardized. But most importantly because complicated setting setups are not the right solution to the problem.

Please let's continue the discussion in #7672
