### ISSUE TITLE
New frontend fails to compile (but old works fine) 

### ISSUE THREAD

**Issue by filip-jezek** [OpenModelica/OpenModelica#6732]
Hi,

I came across a strange bug in the new frontend with a multi-inheritance model with some binding text-inputs. I tried to prepare a minimal bug case, but inheritance with inputs did work fine, so I am attaching the isolated model packed with all requirements here https://gist.github.com/filip-jezek/4b45dc71e4a9b345562b49b54535cce9

thanks for your attention.

Best,
F/

**Comment by perost** [comment]
Your model uses components from the ADAN_main library that I don't recognize. Please include this package or point us to where it can be downloaded, otherwise it'll be difficult to investigate the issue.

Another option is to use the "Save Total" option in OMEdit to save the complete model with all dependencies to a single file (this will include bits of other libraries though, which could be problematic if the libraries do not allow redistribution).

**Comment by filip-jezek** [comment]
Unable to reproduce now, as the model as changed. I appreciate your response and apologize for holding this issue for so long.
