### ISSUE TITLE
Incorrect argument type in copy_real_array_data function

### ISSUE THREAD

**Issue by hyumo** [OpenModelica/OpenModelica#6806]
Hi, 

I am encountering the issue below, it seems to be a code generation error and I cannot reproduce this issue in a consistent way, unfortunately. I also see similar issues within the 1.17 nightly build version. Thanks in advance if this could be fixed. 

```
<modelname>_02nls.c: In function '<modelname>_eqFunction_974':
<modelname>_02nls.c:38:86: warning: passing argument 2 of 'copy_real_array_data' from incompatible pointer type [-Wincompatible-pointer-types]
   copy_real_array_data(div_alloc_real_array(sub_alloc_real_array(tmp0, tmp1), tmp2), &data->localData[0]->realVars[166] /* <a_variable_name> DUMMY_STATE */);
                                                                                      ^
In file included from D:/OpenModelica1.16.0-dev.03-64bit/include/omc/c/openmodelica_func.h:50:0,
                 from <modelname>_model.h:6,
                 from <modelname>_02nls.c:2:
D:/OpenModelica1.16.0-dev.03-64bit/include/omc/c/util/real_array.h:89:13: note: expected 'real_array_t * {aka struct base_array_s *}' but argument is of type 'modelica_real * {aka double *}'
 extern void copy_real_array_data(const real_array_t source, real_array_t* dest);
             ^
```

**Comment by mahge** [comment]
@hyumo 
We need some more info to investigate this. 
It is just a warning right now. Right? Or do you actually get an error. Either way we would like to fix it.

If it is a compilation error/warning happens once for a specific model it is going to happen always for that model. It is unusual for this kind of errors to appear inconsistently. Of course if you change your OMC version and/or options/flags you use, it can disappear or appear.

Maybe you meant from model to model. In that case, the next time you see the error with a specific model let us know. 

I can see that you have removed the model name from your code snippet above. If that is for proprietary code related reason you can try to duplicate the problematic part in a small equivalent mode and attach that instead.

Otherwise it is going to be difficult to investigate this further.

**Comment by hyumo** [comment]
Thanks for your quick respond, I will try to come up with an example to recreate the issue. 

Meanwhile, here is some additional error info. The executable is generated (with the warning), however, it exited with the following message:
```
src->ndims != dst->ndims, 1!=0

Simulation process failed. Exited with code 3.
```
This error always come along with the warning message I mentioned, and the error seems to be complaining about mismatching memory size.

**Comment by perost** [comment]
The warnings might as well be errors, since they say that we're trying to pass something with the wrong type to the function. In this case it seems like we're trying to treat a scalar as an array.

This usually means that something has gotten the wrong type earlier in the compilation process before the code was generated, but we really need an example model to be able to investigate such issues.

**Comment by hyumo** [comment]
An example model is attached: 
[OMTest.zip](https://github.com/OpenModelica/OpenModelica/files/5343289/OMTest.zip)

The issue could be generated by running `Experiments.Test` with `OpenModelica v1.16.0-dev.03(64-bit)` on windows 10. Please let me know if you are able to see the error or not. Thanks

**Comment by perost** [comment]
I was unable to replicate the issue, the model compiles and simulates successfully for me. Since you're using a version that's a couple of months old there's a high probability that the issue has already been fixed. Please try the latest release of OpenModelica (1.16.0-dev.beta1) and let us know if that solves the issue.

**Comment by hyumo** [comment]
I happen to have `v1.17.0-dev-19-g1a316ea158 (64-bit)` at hand, I don't know if it is good enough. I was able to generate the issue with the following modifications. 

Within the `Contacts.Generic` model, please add a `start` modifier to `delta_0`
```
  Modelica.SIunits.Position delta_0[3](start={0,0,-0.3})
    "Distance vector from wheel center to contact point";
```

**Comment by perost** [comment]
Ok, with the modification I can reproduce the issue. The problem comes from the generated NLS equation:
```Modelica
contact.w = (contact.frame_W.r - {contact.s, 0.0, 0.0}) ./ {0.0, 1.0, 0.0}
```
This is obviously wrong since `contact.w` is a scalar while the equation results in a `Real[3]` array. I'm not sure where this equation is coming from though, I'll see if any of our backend developers can have a look at this.

As a side-note the old frontend does not encounter the same issue, because the corresponding equation becomes:
```Modelica
contact.frame_W.r = VehicleInterfaces.Roads.FlatRoad$road.position(contact.s, contact.w)
```
It seems that the function call is inlined when using the new frontend but not when using the old for some reason.

Here's a total model for easier debugging: [test.mo.zip](https://github.com/OpenModelica/OpenModelica/files/5347569/test.mo.zip)

**Comment by hyumo** [comment]
Thanks a lot for digging into this, I can try to replicate the road model and add an inline annotation to see if it could help the function to be inlined. 

BTW, I am quite new to OM, I am wondering how you were able to see those generated equations or raw `*.c` files? I tried to do such things but I could not find the flag (maybe I should try harder).

**Comment by perost** [comment]
>BTW, I am quite new to OM, I am wondering how you were able to see those generated equations or raw *.c files? I tried to do such things but I could not find the flag (maybe I should try harder).

I used the omc compiler directly instead of using OMEdit, since I'm an OM developer and that's what I usually use. When using OMEdit I think the files end up in a folder in /tmp in Linux and in the users temporary files folder in Windows.

**Comment by AnHeuermann** [comment]
@hyumo 
There are a lot of options for debugging this. There is the flattened Modelica code generated by the Frontend. You can view it in OMEdit with the "Instantiate Model" button on the top (left to the simulate button, a green square with some sort of text as icon).
You can view the generated C code by looking at it with your favorite IDE or text editor (location can be found in OMEdit under Tools->Open Working Directory) or activate the "Show generated files" option at SimulationSetup->Output in OMEdit.

And then there are a lot of debug flags available: https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html

But searching the generated C code for bugs is not really an easy thing to do.

**Comment by AnHeuermann** [comment]
After a bit of searching:

BackendEquation
```
3/3 (3): contact.frame_W.r = AllStuff.Test_total.road.position(contact.s, contact.w)   [dynamic |0|0|0|0|]
```
from the algebraic loop shown below will be solved for `contact.w`.

```bash
########################################

 Algbraic Loops (Initialization): 

########################################

system 528
========================================

################################################################################
 dumpLoops: SORTED COMPONENT 
################################################################################

torn nonlinear Equationsystem:

internal vars (12)
1: contact.frame_W.r[2]:VARIABLE(flow=false unit = "m" )  "Position vector from reference frame to the connector frame origin, resolved in reference frame" type: Real [3]
2: contact.frame_W.r[3]:VARIABLE(flow=false unit = "m" )  "Position vector from reference frame to the connector frame origin, resolved in reference frame" type: Real [3]
3: contact.w:VARIABLE(unit = "m" protected = true )  "Path deviation" type: Real
4: contact.s:VARIABLE(unit = "m" protected = true )  "Path distance" type: Real
5: contact.frame_W.r[1]:VARIABLE(flow=false unit = "m" )  "Position vector from reference frame to the connector frame origin, resolved in reference frame" type: Real [3]
6: contact.e_n_0[1]:VARIABLE(unit = "1" protected = true )  "Unit normal vector of road plane, resolved in world frame" type: Real [3]
7: contact.e_n_0[2]:VARIABLE(unit = "1" protected = true )  "Unit normal vector of road plane, resolved in world frame" type: Real [3]
8: contact.e_n_0[3]:VARIABLE(unit = "1" protected = true )  "Unit normal vector of road plane, resolved in world frame" type: Real [3]
9: contact.e_long_0[1]:VARIABLE(unit = "1" protected = true )  "Unit vector in road plane in longitudinal direction, resolved in world frame" type: Real [3]
10: contact.e_long_0[2]:VARIABLE(unit = "1" protected = true )  "Unit vector in road plane in longitudinal direction, resolved in world frame" type: Real [3]
11: contact.e_long_0[3]:VARIABLE(unit = "1" protected = true )  "Unit vector in road plane in longitudinal direction, resolved in world frame" type: Real [3]
12: contact.delta_0[1]:VARIABLE(start = 0.0 unit = "m" protected = true )  "Distance vector from wheel center to contact point" type: Real [3]

residual vars (2)
1: contact.delta_0[3]:VARIABLE(start = -0.3 unit = "m" protected = true )  "Distance vector from wheel center to contact point" type: Real [3]
2: contact.delta_0[2]:VARIABLE(start = 0.0 unit = "m" protected = true )  "Distance vector from wheel center to contact point" type: Real [3]

internal equations (6)
1/1 (1): contact.delta_0[2] = contact.frame_W.r[2] - contact.frame_C.r[2]   [dynamic |0|0|0|0|]
2/2 (1): contact.delta_0[3] = contact.frame_W.r[3] - contact.frame_C.r[3]   [dynamic |0|0|0|0|]
3/3 (3): contact.frame_W.r = AllStuff.Test_total.road.position(contact.s, contact.w)   [dynamic |0|0|0|0|]
4/6 (3): contact.e_n_0 = AllStuff.Test_total.road.normal(contact.s, contact.w)   [dynamic |0|0|0|0|]
5/9 (3): contact.e_long_0 = smooth(0, if noEvent(sqrt((contact.e_axis_0[2] * contact.e_n_0[3] - contact.e_axis_0[3] * contact.e_n_0[2]) ^ 2.0 + (contact.e_axis_0[3] * contact.e_n_0[1] - contact.e_axis_0[1] * contact.e_n_0[3]) ^ 2.0 + (contact.e_axis_0[1] * contact.e_n_0[2] - contact.e_axis_0[2] * contact.e_n_0[1]) ^ 2.0) >= 1e-13) then {(contact.e_axis_0[2] * contact.e_n_0[3] - contact.e_axis_0[3] * contact.e_n_0[2]) / sqrt((contact.e_axis_0[2] * contact.e_n_0[3] - contact.e_axis_0[3] * contact.e_n_0[2]) ^ 2.0 + (contact.e_axis_0[3] * contact.e_n_0[1] - contact.e_axis_0[1] * contact.e_n_0[3]) ^ 2.0 + (contact.e_axis_0[1] * contact.e_n_0[2] - contact.e_axis_0[2] * contact.e_n_0[1]) ^ 2.0), (contact.e_axis_0[3] * contact.e_n_0[1] - contact.e_axis_0[1] * contact.e_n_0[3]) / sqrt((contact.e_axis_0[2] * contact.e_n_0[3] - contact.e_axis_0[3] * contact.e_n_0[2]) ^ 2.0 + (contact.e_axis_0[3] * contact.e_n_0[1] - contact.e_axis_0[1] * contact.e_n_0[3]) ^ 2.0 + (contact.e_axis_0[1] * contact.e_n_0[2] - contact.e_axis_0[2] * contact.e_n_0[1]) ^ 2.0), (contact.e_axis_0[1] * contact.e_n_0[2] - contact.e_axis_0[2] * contact.e_n_0[1]) / sqrt((contact.e_axis_0[2] * contact.e_n_0[3] - contact.e_axis_0[3] * contact.e_n_0[2]) ^ 2.0 + (contact.e_axis_0[3] * contact.e_n_0[1] - contact.e_axis_0[1] * contact.e_n_0[3]) ^ 2.0 + (contact.e_axis_0[1] * contact.e_n_0[2] - contact.e_axis_0[2] * contact.e_n_0[1]) ^ 2.0)} else {10000000000000.0 * (contact.e_axis_0[2] * contact.e_n_0[3] - contact.e_axis_0[3] * contact.e_n_0[2]), 10000000000000.0 * (contact.e_axis_0[3] * contact.e_n_0[1] - contact.e_axis_0[1] * contact.e_n_0[3]), 10000000000000.0 * (contact.e_axis_0[1] * contact.e_n_0[2] - contact.e_axis_0[2] * contact.e_n_0[1])})   [dynamic |0|0|0|0|]
6/12 (1): contact.delta_0[1] = contact.frame_W.r[1] - contact.frame_C.r[1]   [dynamic |0|0|0|0|]

residual equations (2)
1/1 (1): 0.0 = contact.delta_0[1] * contact.e_long_0[1] + contact.delta_0[2] * contact.e_long_0[2] + contact.delta_0[3] * contact.e_long_0[3]   [dynamic |0|0|0|0|]
2/2 (1): 0.0 = contact.delta_0[1] * contact.e_axis_0[1] + contact.delta_0[2] * contact.e_axis_0[2] + contact.delta_0[3] * contact.e_axis_0[3]   [dynamic |0|0|0|0|]
```

## Why is it solved into this format?

What does function `Test_total.road.position(contact.s, contact.w) ` do?

```modelica
function Test_total.road.position
  input Real s = 0.0 "Roads surface parameter 1 (usually arc length along road)";
  input Real w = 0.0 "Roads surface parameter 2 (usually lateral direction)";
  output Real[3] r_0(quantity = "Length", unit = "m") = {0.0, 0.0, 0.0} "Position vector from world frame to point on road at (s,w), resolved in world frame";
algorithm
  r_0 := {s, w, 0.0};
end Test_total.road.position;
```

So the backend wants to solve for `contact.w`:
```
contact.frame_W.r = {contact.s, contact.w, 0.0}
```
and apparently finds the "solution"
```
598: contact.w=(contact.frame_W.r - {contact.s, 0.0, 0.0}) ./ {0.0, 1.0, 0.0} [Real[3]]
```

So now we need to find the dunction that will do this.

**Comment by mahge** [comment]
Is it not possible to do

```c
contact.w = contact.frame_W.r[2]
```

**Comment by kabdelhak** [comment]
> Is it not possible to do
> 
> ```c
> contact.w = contact.frame_W.r[2]
> ```

That would make the rest underdetermined. You just cannot solve a 3-dimensional equation for a one dimensional variable, you will always lose information.

**Comment by AnHeuermann** [comment]
@hyumo 
As a workaround for now you can use minimal tearing with translation flag  `--tearingMethod=minimalTearing`. Then the equation in question will not be solved for `contact.w`.

**Comment by hyumo** [comment]
@AnHeuermann Awesome, it works now, thanks. I will leave this issue open for now (it seems that the fundamental issue is still there), but feel free to close it anytime you like. Thank you so much! You guys are very helpful.

**Comment by mahge** [comment]
@kabdelhak I was just wondering if there was a practical reason that prevented doing it that way. Yes, in theory it is possible but in practice, considering how the backend works, it might happen to be not so easy.

**Comment by kabdelhak** [comment]
> @kabdelhak I was just wondering if there was a practical reason that prevented doing it that way. Yes, in theory it is possible but in practice, considering how the backend works, it might happen to be not so easy.

It is quite easy, i am working on it rn. 

The basic idea is that the AdjacencyMatrixEnhanced is a little wrong here. The row is computed from the equation by first collecting all appearing crefs and then checking how they appear. For functions we traverse all body statements. We just have to handle functions differently... if we want to solve for function inputs we have to solve for all of them. Furthermore the outputs have to have the same size as the inputs, otherwise the function is not invertible (without losing information that is).

In our case the compiler is decieved by the fact that the body is so simple an linear.

**Comment by mahge** [comment]
I thought the function was inlined by the NF. I guess it is not actually inlined. 

> The basic idea is that the AdjacencyMatrixEnhanced is a little wrong here. The row is computed from the equation by first collecting all appearing crefs and then checking how they appear. For functions we traverse all body statements. We just have to handle functions differently... if we want to solve for function inputs we have to solve for all of them. Furthermore the outputs have to have the same size as the inputs, otherwise the function is not invertible (without losing information that is).

Just out of curiosity, do you mean inverting the function symbolically? If you can "invert" the function it can probably be inlined right? It might be better to check why the function is not inlined in the first place. If you mean invert the function numerically (is that what it is called?) as a NLS, how would that work when you are already inside an algebraic loop? Do you just make it a residual equation?

**Comment by kabdelhak** [comment]
> Just out of curiosity, do you mean inverting the function symbolically? If you can "invert" the function it can probably be inlined right? It might be good to check why the function is not inlined in the first place as well. If you mean invert the function numerically (is that what it is called?) as a NLS, how would that work when you are already inside an algebraic loop? Do you just make it a residual equation?

I am eating my words here a little. It is not as easy as i thought. And yes with inverting i mean what you are describing.
Good question regarding the inlining... but currently the solvability process is fundamentally flawed since it allows some weird stuff. We should have a meeting about that starting next week! The basic problem is that we use differentiation to solve for variables, but we do not respect sizes here. 

In following PR i restricted it to size 1 and it works: #6818 

Unfortunately it now also does not allow scalarized array elements in an array constructor to be solved. E.g. 
```
{w[1], w[2]} = func(...)
```
cannot be solved for `w` anymore. But as i said that whole process does not check if all inputs and outputs can be solved and it does not care for sizes, so i think for now it is better to restrict this to size=1. Keep in mind that this is only for Tearing and StateSelection, so we might end up with slightly less efficient cases sometimes, but it also prevents impossible solving like we see here!

**Comment by mahge** [comment]
> It is not as easy as i thought

I know your pain full and well :). 

Ya I agree the whole solvability analysis process is a bit flawed. It is also not easy to change or fix. Hopefully we do not encounter the shortcoming you mentioned because of other processing we do.

**Comment by kabdelhak** [comment]
My fix works, it is not perfect since it prevents some sensible array cases, but it also prevents bugs like these. I would like postpone better array handling to the new backend, this one even does not seem to be impactful, i did not need to make any changes to the testsuit for my fix.

**Comment by kabdelhak** [comment]
@hyumo It should work now without the tearing method restriction! Feel free to reopen the ticket if something does not work.
