### ISSUE TITLE
NFCeval.evalBinaryAdd failed to evaluate

### ISSUE THREAD

**Issue by dariomangoni** [OpenModelica/OpenModelica#7384]
### Description

The full error code reports:
```
[C:/OM117/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1010:9-1010:67]: Internal error NFCeval.evalBinaryAdd failed to evaluate ‘degree + dim'
```

where 'degree+dim' is the argument of a function called 'factorial' that basically:
- when called by `getMonomesCount` does work
- when called by `getPowerMatrix` that calls `getMonomesCount` stops working

### Steps to Reproduce
Run `getPowerMatrixTest` to replicate the failure: [PowerMatrixPack.txt](https://github.com/OpenModelica/OpenModelica/files/6324032/PowerMatrixPack.txt) (please rename extension to .mo)

BTW, you will notice that in the test there is a commented line in which the `powerTable` dimensions are set with the proper size instead of leaving them `[ : , : ]`. In that case you will se another error:
```
Component powerTable of variability parameter has binding 'PowerMatrixPack.Utilities.PolyFitTools.getPowerMatrix(degree, dim)' of higher variability discrete.
```

I don't have any additional translation flag and I'm using the new frontend. The old one fails as well, but with another error.

### Version and OS
 - OpenModelica Version: v1.17.0 (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 3.2.3

**Comment by dariomangoni** [comment]
@perost I have opened another ticket #7385 that is really close but different from this; please be aware that a fix to this ticket might solve also the other.

**Comment by dariomangoni** [comment]
Oh, btw, since you are working on this, I could suggest even a third bug trigger if it is of any help.
With the same example, if you go into the `getMonomesCount` function and, instead of `degree+dim` you put a consistent constant value (`7`) like this:
```
count := integer(Math.factorial(7) / Math.factorial(dim) / Math.factorial(degree));
```
you should get:
```
[C:/OM117/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 872:11-872:78]: Internal error NFCeval.evalRangeExp got invalid arguments (1, dim)
```
So now also `evalRangeExp` is covered :-)

**Comment by perost** [comment]
Thank you, but failing in NFCeval is in this case just a symptom and not the actual issue. The real issue is that references to input parameters in default arguments are replaced with the actual arguments of the function call, but this is done after the default arguments have already been typed.

So in:
```Modelica
function getPowerMatrix  
  input Integer degree;
  input Integer dim;
  input Integer[:, :] powerMatrix = zeros(PowerMatrixPack.Utilities.PolyFitTools.getMonomesCount(degree, dim), dim);
```
we type the call to `getMonomesCount` while `degree` and `dim` still points to the input parameters defined in the function, which are discrete since Integers are implicitly discrete. The constant evaluation module will not evaluate discrete variables, which causes the errors from NFCeval, and the whole call to `getPowerMatrix` becomes discrete which leads to the variability error.

The fix is to delay the typing of the default arguments until the input arguments have been inserted into them, which also happens to solve several other issues too. But it's the kind of thing that can break things in surprising ways, so I'm being careful and trying to test it thoroughly.
