### ISSUE TITLE
Record component should be able to take the dimensions from the binding equation

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#7413]
### Description

Missing type dimensions should be taken from RHS binding if possible.

### Steps to Reproduce

Consider model RecordIssues.M:
```mo
package RecordIssues

package PB
  record RB
    constant Integer n(min=1);
    parameter Real a[n];
  end RB;
end PB;

package P
  record R
    extends PB.RB(final n=1, final a={1});
  end R;
end P;

model M
  replaceable parameter P.R g;
  PB.RB r = g;
end M;

end RecordIssues;
```

Instantiating the RecordIssues.M should work but it gives an error:
```bash
# omc RecordIssues.mo +i=RecordIssues.M
'Error processing file: RecordIssues.mo
[C:/home/adrpo33/dev/OMTesting/transient/RecordIssues.mo:6:5-6:24:writable] Error: Could not evaluate structural parameter (or constant): r.n which gives dimensions of array: a. Array dimensions must be known at compile time.
```

### Expected Behavior

The model should flatten fine.

### Version and OS

 - OpenModelica v1.18.0-dev-242-g6d0557a077 (64-bit)
 - Windows 10 64bit / msys2/mingw64

**Comment by perost** [comment]
The issue turned out to be that when evaluating `r.n` for the dimension we'd create a component reference for `r` and try to evaluate it to get the binding expression, but since `r` is a continuous variable it would just be skipped. I've changed it so that we now instead fetch the binding of the parent and create the appropriate expression for the field we're looking for, and then try to evaluate that instead.

**Comment by adrpo** [comment]
Thanks! Very good, I will try this as soon as is merged!
