### ISSUE TITLE
Disable old front end upon new installation

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7456]
### Description

We have reports of various errors from frustrated users, which turn out to be due to the option "enable old front end" remaining selected whenever a new version is installed, even though it is no longer appropriate, due to the recent progress of the NF.

Until we finally get rid of this option (I'm not sure 1.18.0 will be good enough to say that tere are zero models around still requiring the NF), we should make sure that when one upgrades to a new version, this option is deselected automatically.

**Comment by adeas31** [comment]
We can have a popup on startup that is only shown if old frontend is selected in the settings.

`You have enabled old frontend for code generation which is not recommended. Do you want to switch to new frontend?` with buttons `Switch to new frontend` and `keep using old frontend`.

This will be annoying to users who still want to use the old frontend for some reasons.
Also will create a cycle in some cases since during the simulation we show a popup that allows to switch from new frontend to old frontend.

So many todo messages in the user interface now because of old frontend like `//! @todo Remove this once new frontend is used as default and old frontend is removed.`
We should kill old frontend asap so we don't waste time on these workarounds.
