### ISSUE TITLE
Default values of parameters which are not displayed in their final unit ends up with rounding problems

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7491]
### Description
Default values of parameters which are not displayed in their final unit (display unit differs the final unit) ends up with rounding problems

### Steps to Reproduce

A definition like

`parameter Modelica.SIunits.Length stroke(displayUnit ="mm") = 0.5; `
will end up in 
![grafik](https://user-images.githubusercontent.com/84787397/119625035-11a66500-be0a-11eb-818c-9c943ad3729b.png)

### Version and OS

OpenModelica v1.18.0-dev-280-g0b76908279 (64-bit)
OMSimulator v2.1.1.post70-gdf73447-mingw
OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3, Bosch Rexroth Simulation Libraries (1.4)

Best wishes

Sven Bätzing

**Comment by casella** [comment]
See discussion in #7465.

**Comment by casella** [comment]
This is already fixed on Windows. On Windows, it will be automatically resolved when we fix #11397.

**Comment by abuntrock** [comment]
@casella  You mean that this is already fixed on Linux right? Is there a timeline until when #11397 will be fixed?

**Comment by casella** [comment]
> @casella You mean that this is already fixed on Linux right?

Yes:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/14b46416-d699-4ab2-91ab-213d627dc276)

> is it there a timeline until when #11397 will be fixed?

It is also already fixed in Windows with the new MSYS2 UCRT64 environment, you can use the special build that you find here:
https://build.openmodelica.org/omc/builds/windows/nightly-builds/PRbuilds/64bit/

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/898ac802-cf90-41dd-a374-b50afd43dd85)

The new environment is currently almost ready in PR #10939 (which was use to create the special build9, it should be merged on master and become available in the nightly builds by the end of this week, if all goes fine.

The fix will be released in 1.23.0 around April 2024.

**Comment by casella** [comment]
The Windows issue #11397 was due to a bug in the old version of gcc we were using. As soon as we update it, thanks to the Ryu library everything will be all right.

**Comment by adeas31** [comment]
Should work fine now since #10939 and #11397 are merged.

**Comment by abuntrock** [comment]
I checked this with the nightly build from last Friday (v1.23.0-dev-316-g3a47d5ed12) and it looks as expected now especially for unit conversions that involve a factor of 10. I found two other issues which might be related to this fix but I will open new tickets for them.
