### ISSUE TITLE
Translation flag -d=backenddaeinfo does not generate torn systems output on Windows v1.17.0

### ISSUE THREAD

**Issue by mjschuh** [OpenModelica/OpenModelica#7517]
When I add the `-d=backenddaeinfo` flag to `Tools -> Options -> Simulation -> "Additional Translation Flags:"` on Linux with version 1.18.0-dev-252-gd66050b, I see `Non-linear torn systems:` output in the `Message Browser -> Notification` tab after running the simulation.

On my Windows 10 64 bit OMEdit v1.17.0 (64-bit) installation with the same `-d=backenddaeinfo` flag set, I don't see any output in the `Message Browser -> Notification` tab after running the simulation.  Do I need to set some additional flag or do something different on the Windows 10 installation to see the `Non-linear torn systems:` output in the `Message Browser -> Notification` tab after running the simulation?

Thanks, 
     Michael

**Comment by adeas31** [comment]
The behavior should be same regardless of the operating system.

Note that if you have simulated the model once then you need to add the flag in `Simulation Setup -> Translation Flags`

**Comment by mjschuh** [comment]
Thanks.  You are right.  Adding the flag in `Simulation Setup -> Translation Flags` and simulating the model again generated the expected `Non-linear torn systems:` output.  After trying a few things, I now understand that after simulation a model one or more times, flags entered in `Tools -> Options -> Simulation -> "Additional Translation Flags:` are not used for future simulations of that model until OMEdit is restarted.  As you pointed out, flags can be added in Simulation Setup -> Translation Flags. It is very helpful to understand this.  I bet this behavior has been giving me trouble for months.  It is good to understand this behavior.

Thanks!
   Michael

**Comment by casella** [comment]
@adeas31, we've discussed this already, but it is still true that the fact that changing Tools|Options is ineffective once you have simulated a system is a bit confusing and not intuitive for many users.

I wonder how we could make this clearer, without adding cumbersome warning messages.

**Comment by mjschuh** [comment]
Perhaps it would be helpful to have a `Messages Browser -> Warnings` message like `Warning Tools -> Options -> Simulation -> "Additional Translation Flags" differ from Simulation Setup -> Translation Flags.  The flags set in Simulation Setup -> Translation Flags will be used.  See http://openmodelica.org/help/Tools|Options for more information.` if OMEdit detects a difference in the settings.

**Comment by mjschuh** [comment]
Maybe the URL for this GItHub issue, https://github.com/OpenModelica/OpenModelica/issues/7517 , could be used for the URL in the above warning text.

**Comment by adeas31** [comment]
#6062 is still open. I don't know what is the best way to fix this. There are several options,

One idea, as suggested in this issue, is to show a warning to user when local and global flags are different. This is useful for some users but might be annoying for users who really want to have different local flags for different models.

We can popup a dialog that says local and global flags are different. Do you want to use local or global flags? And have a "remember my choice" checkbox. This leads us back to the same problem once the user choice is saved.

We can have a button in `Simulation Setup -> Translation Flags` tab that says `Reset to global flags`. This partially works if users simulate through simulation setup instead of direct simulate.

Whenever the global flags are changed. Show a popup that says "Do you want to overwrite the local flags of opened models?". I can possibly show the list of models that have local flags set and user can select which ones to overwrite with global flags. This sounds like the only solution that guarantees that the impact of the change in global flags is obvious to the users.

**Comment by casella** [comment]
> Whenever the global flags are changed. Show a popup that says "Do you want to overwrite the local flags of opened models?". I can possibly show the list of models that have local flags set and user can select which ones to overwrite with global flags. This sounds like the only solution that guarantees that the impact of the change in global flags is obvious to the users.

I think this is the only sensible solution. What is a bit confusing is that one may think changin global flags also affects local flags. This solution makes it explicit.

**Comment by adeas31** [comment]
Sounds good.
@olivleno what do you think?

**Comment by olivleno** [comment]
Interesting to hear that it was not only me stumbling over the current behavior. 

What is the effect of the proposed "overwrite"? - Does it mean the local flags are discarded entirely and replaced with the global ones? 

The stumbling block I see that naturally one expectations that the local flags are applied on top of the global flags. This means the global flags are applied unless altered by the local ones. As discussed earlier this would require some sort of merge mechanism which if I recall correctly is not easily done.

If the proposal is followed then one should think about a crystal clear description of what is meant by overwrite so that there is no doubt about what will happen.

**Comment by casella** [comment]
> Interesting to hear that it was not only me stumbling over the current behavior.

I guess it is fairly commonplace :)

> What is the effect of the proposed "overwrite"? - Does it mean the local flags are discarded entirely and replaced with the global ones?

No, I think we should just apply the diff between the previous and the current global flags to the local flags. That's what I would expect.

> The stumbling block is that naturally one expects that the local flags are applied on top of the global flags. This means the global flags are applied unless altered by the local ones. As discussed earlier this would require some sort of merge mechanism which if I recall correctly is not easily done.

Yeah, I guess it is not trivial, but it is just a diff patch at the end of the day. @adeas31, what do you think?

> If the proposal is followed then one should think about a crystal clear description of what is meant by overwrite so that there is no doubt about what will happen.

Absolutely!

**Comment by adeas31** [comment]
> > Interesting to hear that it was not only me stumbling over the current behavior.
> 
> I guess it is fairly commonplace :)
> 
> > What is the effect of the proposed "overwrite"? - Does it mean the local flags are discarded entirely and replaced with the global ones?
> 
> No, I think we should just apply the diff between the previous and the current global flags to the local flags. That's what I would expect.

No. My proposed "overwrite" is to just discard local flags and replace them with the new global ones.

> 
> > The stumbling block is that naturally one expects that the local flags are applied on top of the global flags. This means the global flags are applied unless altered by the local ones. As discussed earlier this would require some sort of merge mechanism which if I recall correctly is not easily done.
> 
> Yeah, I guess it is not trivial, but it is just a diff patch at the end of the day. @adeas31, what do you think?

Yes we can apply local flags on top of global ones. But that might have unexpected results e.g., if you set `initialization` flag at global level and don't set it in the local level then still it is applied. Now this results in a confusion for the user, since the user might be seeing in the simulation setup that initialization flag is unchecked. Another example is matching algorithm flag, if one set matching algorithm to `PFPlusExt` at global level and `BFSB` at local level then the workflow is to set the global flag first and then override with the local flag. The problem with this example is that user changes the global flag and expects that it is applied.

> 
> > If the proposal is followed then one should think about a crystal clear description of what is meant by overwrite so that there is no doubt about what will happen.
> 
> Absolutely!

As I see most of the issues in this problem are because users are not aware of global and local flags. That is why I suggested the above solution of overwrite so we make it explicit explanation when user changes the global flags. And yes of course we write crystal clear description that local flags will be replaced by the new global ones.

**Comment by olivleno** [comment]
The surprising thing is that the behavior changes after a re-launch. This is suspicious and unexpected.
Overwriting (by discarding all local settings) is a very radical approach. Why not create the same behavior as after a restart?

**Comment by adeas31** [comment]
Local flags are just for one session and they are not preserved across different sessions. Only the global flags are preserved and used across sessions.

**Comment by olivleno** [comment]
Well if that's the case then I see no need for too many headaches on the local settings. One can expect that users still know what they have recently changed locally and are in the worst case able to recover what has been overwritten.

A clean concept of global and local settings that are preserved (as in git) would be a nice to have feature. This would probably require to store them as annotation in the model or somewhere. But this is rather low priority.

Bottom-line: After this clarification I support your proposal. Probably I would phrase it as "Discard" rather than "Overwrite". Also the term "local flags" might not be exactly clear. How about: "flags of simulation session".

Thanks for this good discussion.

**Comment by adeas31** [comment]
> A clean concept of global and local settings that are preserved (as in git) would be a nice to have feature. This would probably require to store them as annotation in the model or somewhere. But this is rather low priority.

We have the option to store the flags as annotation in the model, if user does that then they are preserved as part of the model file. Otherwise the flags are just for the current session.

> Bottom-line: After this clarification I support your proposal. Probably I would phrase it as "Discard" rather than "Overwrite". Also the term "local flags" might not be exactly clear. How about: "flags of simulation session".

Yes, "Discard" is even better.

**Comment by adeas31** [comment]
I will implement my proposal so you can see the thing in action. Then we can have feedback on it.

**Comment by casella** [comment]
A further comment from my side. 

@olivleno, the reason why we introduced local settings that only last throughout the current session (on my request, if I am not mistaken)  was meant to avoid this unpleasant scenario: you are trying to find the best combination of settings for you model, and you need to set four or five different flags for that, so you play around with different combinations to see what happens. Previously, you had to set _all of them_ times and again at each simulation run, which was really annoying and error-prone, because you often forgot one or messed up somehow. 

On the other hand, we thought it would not be a good idea to silently keep these settings between different sessions, because you may re-run a session after a long time, when you have long forgotten which flags you had set the last time you ran the thing, and why you did it. Maybe you were just playing around, but they were not really meant to be permanent. Particularly if you set `LOG `flags, which can generate much output and slow down a simulation significantly. Also, those settings would seemingly come out of nowhere.

So the idea was: while you play around, OMEdit keeps memory of the model settings locally, and when you are happy with them, you can explicitly save them in the model via annotations, to be reused later.

So now we have this concept, that you start a session, the global flags are copied to the local simulation settings, the model annotations are applied on top of them, and off you start. But then, people change the global options and expect this to have some effect on the model they are playing with, which doesn't happen. That is also confusing and needs to be addressed.

I understand from @adeas31 that the concept of "diff" of settings would be hard to implement, so I'm fine with his proposal, that if you change the global settings, any local settings will be overwritten. What is still not 100% clear to me is exactly how the settings saved in annotations will be handled. 

What I understand is that when you start a new session and simulate a model, the global settings are copied into the simulation session settings, and then the flags set in the annotations are applied on top of that. From that point onwards, for the entire duration of the session what matters are the simulation session settings, the annotations are no longer taken into account (even if you change them manually in the simulation code). If you decide to save the current session settings, then the existing annotations are discarded and a new set is generated, which corresponds to the current simulation session settings. This allows to reproduce the same behaviour when you reload the model in a new session later on, or on a different computer.

@adeas31, do I get this right?

The question then is: what does OMEdit do to those annotations when the global settings are changed? I am fine at discarding whatever has been selected during the simulation session, but we should be careful not to accidentally remove crucial annotations that were put in the model by experts and may be essential for good simulation performance, e.g. `--daeMode` or `-nls=kinsol`.

For example, assume that a certain model `M `has an annotation to set `--daeMode`. This is not meant to be the default behaviour of OMEdit, just to be used in this model, so this will never be set in the global options. If I now open Tools|Options and turn on, e.g., evaluate all parameters, what happens to the `--daeMode` setting in the simulation session for `M`? Is it retained or is lost? If it got lost, that would be bad, and it would even be worst if new simulation settings without it are saved into a new annotation, destroying the previous one.

**Comment by casella** [comment]
@adrpo, maybe it's best if we settle this issue before feature freeze?

**Comment by olivleno** [comment]
Is there a way to save the settings in the annotations, or does it have to happen manually?

This means already today must be some mechanism in place that merges the annotations with the local settings?

**Comment by adeas31** [comment]
> What I understand is that when you start a new session and simulate a model, the global settings are copied into the simulation session settings, and then the flags set in the annotations are applied on top of that. From that point onwards, for the entire duration of the session what matters are the simulation session settings, the annotations are no longer taken into account (even if you change them manually in the simulation code). If you decide to save the current session settings, then the existing annotations are discarded and a new set is generated, which corresponds to the current simulation session settings. This allows to reproduce the same behaviour when you reload the model in a new session later on, or on a different computer.

> @adeas31, do I get this right?

Yes, this is what we are doing right now.

> The question then is: what does OMEdit do to those annotations when the global settings are changed? I am fine at discarding whatever has been selected during the simulation session, but we should be careful not to accidentally remove crucial annotations that were put in the model by experts and may be essential for good simulation performance, e.g. --daeMode or -nls=kinsol.

> For example, assume that a certain model M has an annotation to set --daeMode. This is not meant to be the default behaviour of OMEdit, just to be used in this model, so this will never be set in the global options. If I now open Tools|Options and turn on, e.g., evaluate all parameters, what happens to the --daeMode setting in the simulation session for M? Is it retained or is lost? If it got lost, that would be bad, and it would even be worst if new simulation settings without it are saved into a new annotation, destroying the previous one.

When the global settings are changed then basically my idea is to go back as if you are starting a new session i.e., the global settings are copied into the simulation session settings, and then the flags set in the annotations are applied on top of that. So the flags in the annotations are never lost.

**Comment by adeas31** [comment]
> Is there a way to save the settings in the annotations, or does it have to happen manually?

Its manual. There is a checkbox in the simulation setup that says `Save translation flags inside model i.e., __OpenModelica_commandLineOptions annotation`.

> 
> This means already today must be some mechanism in place that merges the annotations with the local settings?

No its not the merge. It is as @casella mentioned,

> What I understand is that when you start a new session and simulate a model, the global settings are copied into the simulation session settings, and then the flags set in the annotations are applied on top of that. From that point onwards, for the entire duration of the session what matters are the simulation session settings, the annotations are no longer taken into account (even if you change them manually in the simulation code). If you decide to save the current session settings, then the existing annotations are discarded and a new set is generated, which corresponds to the current simulation session settings. This allows to reproduce the same behaviour when you reload the model in a new session later on, or on a different computer.

**Comment by olivleno** [comment]
> and then the flags set in the annotations are applied on top of that

What does on top mean? - Isn't that the "mechanism"?

**Comment by adrpo** [comment]
> @adrpo, maybe it's best if we settle this issue before feature freeze?

Sure, I'll wait with the branching of `maintenance/v1.18`

**Comment by casella** [comment]
> When the global settings are changed then basically my idea is to go back as if you are starting a new session i.e., the global settings are copied into the simulation session settings, and then the flags set in the annotations are applied on top of that. So the flags in the annotations are never lost.

OK, sounds good! I understand you are going to do that with all the sessions that are currently open, right?

**Comment by casella** [comment]
> What does on top mean?

As I understand, flags are specified sequentially, both compilation and for simulation. If the same flag is specified more than once with different values, the latest wins. E.g., if the default settings correspond to

`"-d=execstat -n=16 --daeMode --preOptModules-=clockPartitioning"`

and the `__OpenModelica_commandLineOptions` annotation contains

`"-d=noexecstat -n=8 --tearingStrictness=veryStrict"`

Then, as I understand, the end result is the same you would obtain with

`"--daeMode --preOptModules-=clockPartitioning -d=noexecstat -n=8 --tearingStrictness=veryStrict"`

**Comment by casella** [comment]
So, here is my first attempt for the "crystal clear description", to be place inthe OMEdit's user's guide. Let me know what you think of it.

There is a large number of optional settings and flags to influence the way OpenModelica generates the simulation code ([Compiler flags](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html), a.k.a. Translation flags or Command Line Options) and the way the simulation executable is run ([Simulation Flags](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html)).
 
The global default settings can be accessed and changed with the Tools|Options menu. It is also possible to reset them to factory state by clicking on the "Reset" button of the Tools|Options dialog window.
 
When you start OMEdit and you simulate a model for the first time, the model-specific simulation session settings are initialized by copying the global default settings, and then by applying any further settings that are saved in the model within OMC-specific `__OpenModelica_commandLineOptions` and `__OpenModelica_simulationFlags` annotations. Note that the latter may partially override the former, if they give different values to the same flags.
 
You can change those model-specific settings at will with the Simulation Setup window. Any change you make will be remembered until the end of the simulation session, i.e. until you close OMEdit. This is very useful to experiment with different settings and find the optimal ones, or to investigate bugs by turning on logging options, etc. If you check the "Save translation flags" and "Save simulation flags" options in the simulation setup, those settings will be saved in the model within the corresponding OMC-specific annotations, so that you can get the same behaviour when you start a new session later on, or if someone else loads the model on a different computer. Otherwise, all of those changes will be forgotten when you exit OMEdit.
 
If you change the global default settings after running some models, the simulation settings of those models will be reset as if you closed OMEdit and restarted a new session: the new global options will first be applied, and then any further setting saved in the OMC-specific annotations will be applied, possibly overriding the global options if the same flags get different values from the annotations. Any model-specific settings that you may have changed with Simulation Setup up to that point will be lost, unless you saved them in the OMC-specific annotations before changing the global default settings.

**Comment by olivleno** [comment]
This is very clear. It's also providing the necessary context to understand how it works and what it's good for. Thx!
I do also like the proposed behavior. But this is different than what Adeel proposed, right?

**Comment by casella** [comment]
> 
> 
> This is very clear. It's also providing the necessary context to understand how it works and what it's good for. Thx!
> I do also like the proposed behavior. But this is different than what Adeel proposed, right?

I thought this was 100% aligned with what Adeel has in mind. Why shouldn't it be?

**Comment by olivleno** [comment]
You're right. I was referring to the previous proposal with the pop-up window and overwrite. There is a more recent post.
Very good. Looking forward to see this up and running.

**Comment by adeas31** [comment]
@casella and @olivleno I pushed my proposed solution. Try the nightly build tomorrow and let me know what further improvements we can do. In order to test it you need to run OMEdit, open any model and simulate it, then go to the options and change any translation flag and press ok.

@casella I pushed in your description text in the users guide.

**Comment by olivleno** [comment]
This looks good.

The text in the message box is very long. Maybe one could try to shorten it or have a line break to separate the key message from the details.

What I just recognize is that the term "translation flag" is used in OMEdit but not in the references [https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflags-options](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflags-options), where it is referred to as Compiler flags.
Also in the settings dialog the "translation flags" are in the group "simulation", but then there are also "simulation flags" mentioned in the users guide and one can tick on simulationsFlags annotations in the dialog. Hence, it a bit confusing to understand what is a translation flag vs. a simulation flag.

I'd suggest to define a list of terms being used consequently in the users guide and across all tool dialogs.

The other problem I came across when trying to test the functionality is that not all compiler flags are supported, e.g. --flatModelica. This is also very annoying as you always think there is something wrong with the string you defined to set the flag. It should be obvious from the users guide which of these can applied in OMEdit or not. 

Having some example in the uses guide, especially for the submodules, would also help to figure out how to properly use the flags.

Other than that it reads well and works fine for me.
