### ISSUE TITLE
delay not working correctly

### ISSUE THREAD

**Issue by AHaumer** [OpenModelica/OpenModelica#7536]
We're going to implement test models for `Modelica.Electrical.Analog.Lines.TLine` which rely on the delay-operator.
I'm expecting that the output is an exact copy of the input but delayTime later, but in OM it isn't:
The slopes (at the beginning and the end of a pulse) are finite (instead of infinite).
Pls. have a look at the enclosed example. 
OM won't be able to reproduce the comaprison signals of the examples.

OM v1.17.0 (64 bit) on Windows 10 (64 bit) pro
[TestDelay.zip](https://github.com/OpenModelica/OpenModelica/files/6625615/TestDelay.zip)

**Comment by casella** [comment]
Thanks @AHaumer for pointing this out. We just implemented the spatialDistribution operator, see [trac ticket #5281](https://trac.openmodelica.org/OpenModelica/ticket/5281) which should preserve sharp input changes by triggering events when the changes get to the output.

@AnHeuermann, @kabdelhak, do you think porting that solution to `delay` is a simple task? We could also ask @mahge to take care of that, if you can give him the proper hints.

**Comment by casella** [comment]
This is a test model similar to the one I provided for the `spatialDistribution()` operator. It computes the error, which is quite large.
```
model TestDelay
  Real v "Original signal";
  Real aux "Auxiliary variable";
  Real aux_del "Delayed auxiliary variable";
  Real w "Delayed signal (numerical)";
  Real w_exact "Delayed signal (exact)";
  Real err = w - w_exact "Numerical error of delayed signal";
  Real err_int(start = 0, fixed = true);
  parameter Real omega = 20 "Signal frequency";
  parameter Real tau = 0.729 "Time delay";
equation
  aux = sin(omega * time);
  aux_del = sin(omega * (time - tau));
  v = if time < 0.1 then 0 else if aux < 0.5 then aux else 0.5;
  w = delay(v, tau);
  // use noEvent to avoid event generation by the w_exact signal, which is only used for comparison
  // the event should be generated by the delay() operator
  w_exact = noEvent(if time < 0.1 + tau then 0 else if aux_del < 0.5 then aux_del else 0.5);
  der(err_int) = abs(err);
  annotation(
    experiment(StartTime = 0, StopTime = 2, Tolerance = 1e-06, Interval = 0.05));
end TestDelay;
```

**Comment by casella** [comment]
In fact, now that we have a good implementation of `spatialDistribution()` including event handling, we can get a better implementation of `delay()` in the case of fixed (parametric) delay out of the box: just set
```
delay(expr, tau) = 
  spatialDistribution(in0 = expr,
                      in1 = 0, // dummy
                      x = time/tau,
                      positiveVelocity = true,
                      initialValues = {expr.start, expr.start});
```
I guess we shouldn't care of improving the case of variable time delay. As I understand, in most cases that was used as poor man's version of the `spatialDistribution` operator with variable speed before it was actually defined in the spec. I guess it is now mostly obsolete and I wouldn't waste time of that.

The case brought forth by @AHaumer uses a parametric time delay, so it should be fine.

**Comment by AnHeuermann** [comment]
We used delay.c to get an idea on how to implement spatialDistribution.c. Now one could do the opposite and do the reverse to change delay.c to be more similar to the spatialDistribution implementation.

I guess the main differences are the storing and outputting of events. I can't see how it is done for delay.
The important bits for spatialDistribution are:
  - Store events by adding two values at the same position value.
  - Detect output of events because we need to remove two data points with the same position value.

The best approach could be to change the data structure used in delay to a single ended list and then do most of the stuff we are doing in spatialDistribution, but just for forward direction. That would make the two functions more similar and easier to maintain.

**Comment by sjoelund** [comment]
> The best approach could be to change the data structure used in delay to a single ended list and then do most of the stuff we are doing in spatialDistribution, but just for forward direction. That would make the two functions more similar and easier to maintain.

So you mean storing every single value? This is not an option for simulations that run for years. And for a fixed delay there is no need to do this.

**Comment by AnHeuermann** [comment]
But for changing delay it's the only option I can see. And isn't that what is currently done inside the ring buffer?

And of course spatialDistribution has the same problem, that you can eat up all memory because we are storing all values given to the delay. We thought about creating a clean up function that will limit the number of stored data points.

**Comment by casella** [comment]
> But for changing delay it's the only option I can see.

Well, in the case of variable delay, a mandatory delayMax parameter has to be given, so you can indeed discard values after that time.

Maybe we should have two different solutions, one for constant delay and one for variable delay. As I wrote, I think variable delay is now largely obsolete and superseded by spatialDistribution, so supporting it with events and everything is a low-priority task. Supporting events in constant delay is instead top-priority, because that is used in the MSL.

It depends on how much time do you have to spend on this. If we can quickly get a sound implementation of constant delay by simply calling spatialDistribution, I think we should do it right now and have it in 1.18.0. Later on we could have a more efficient specific implementation which is inspired by  spatialDistribution, but is rewritten from scratch.

@AnHeuermann, what do you think?

> And isn't that what is currently done inside the ring buffer?

No, we do eventually discard (i.e. overwrite) values after they leave the [0,1] windows. Once water has flown out of the pipe, memory of its temperature is effectively lost, there is no way to get it back, so there is no need to store it indefinitely.

> And of course spatialDistribution has the same problem, that you can eat up all memory because we are storing all values given to the delay. We thought about creating a clean up function that will limit the number of stored data points.

This is a theoretical possibility in case the velocity asymptotically approaches zero. In practice this never happens, unless e.g. you permanently shut off some pipes in the system, so after a while values can be indeed discarded, because they will leave the active x-window.

**Comment by AnHeuermann** [comment]
>It depends on how much time do you have to spend on this. If we can quickly get a sound implementation of constant delay by simply calling spatialDistribution, I think we should do it right now and have it in 1.18.0. Later on we could have a more efficient specific implementation which is inspired by spatialDistribution, but is rewritten from scratch.
>
> @AnHeuermann, what do you think?

I don't have much time for at the moment. Just calling spatialDistribution for delay sounds easy, I can check if that is an option or if it would be as fast to just do it correctly.

**Comment by casella** [comment]
> I don't have much time for at the moment. Just calling spatialDistribution for delay sounds easy, I can check if that is an option or if it would be as fast to just do it correctly.

Sounds good. We don't care about efficiency at this moment, only about getting correct results with the minimum amount of work.

**Comment by AnHeuermann** [comment]
I'll fix the delay implementation instead of hacking the spatial distribution into this. Should take a similar amount of time but will be more easy to understand.

**Comment by casella** [comment]
Sounds good

**Comment by casella** [comment]
> 
> 
> I'll fix the delay implementation instead of hacking the spatial distribution into this. Should take a similar amount of time but will be more easy to understand.

@AnHeuermann, can you please update what the status is?

**Comment by AnHeuermann** [comment]
I need to start again. I tried something but never got all cases to work at the same time.
I guess I need to check my approach again and discuss with @kabdelhak and @phannebohm if that is the correct idea.

But I guess this is one of the more important run-time tickets, so having this one in 1.19 should be a high priority.

**Comment by AnHeuermann** [comment]
I need to finish the delay zero crossing function / findEvent function. Adding and removing an event to the ring buffer is not yet working exactly how it should.

**Comment by casella** [comment]
@AHaumer, can you please test with the next nightly build and confirm this now works fine for you?
