### ISSUE TITLE
Undeclared identifier __HOM_LAMBDA_ in Cpp runtime

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7539]
A couple of examples of the PowerSystems library fail to compile due to use of undeclared `__HOM_LAMBDA_` in the Jacobian code. See e.g. `PowerSystems.Examples.PowerWorld.Test.HydroPlantTest1`
https://libraries.openmodelica.org/branches/master/PowerSystems_cpp/files/PowerSystems_cpp_PowerSystems.Examples.PowerWorld.Test.HydroPlantTest1.err

Where does this come from? Possibly some new homotopy that is not yet supported by the Cpp runtime?
How shall this be treated?

**Comment by rfranke** [comment]
Same with MSL, see ModelicaTest_3.2.3_cpp https://libraries.openmodelica.org/branches/overview-combined.html. 

The number of compiled models reduced from 547 to 526 from OpenModelica v1.16 to v1.17!

See e.g. `ModelicaTest.Blocks.LimPID` suffering from the same problem:
https://libraries.openmodelica.org/branches/v1.17/ModelicaTest_3.2.3_cpp/files/ModelicaTest_3.2.3_cpp_ModelicaTest.Blocks.LimPID.err

**Comment by rfranke** [comment]
Did this commit by @AnHeuermann possibly break the compilation of many models in the Cpp runtime:
Differentiate homotopy operator with lambda (f8ceac8e1cb025f1efdcc5e5bca76e7b3bd283b0)?

**Comment by AnHeuermann** [comment]
Could be that it is f8ceac8. @rfranke Did you try with a version of OMC before that commit?

But with that commit it is possible to differentiate the homotopy operator and that is going into the Jacobians of the non-linear system. So it is very likely that commit.

My guess would be that the C++ runtime is using some shared code generation or some code generation from the C runtime templates.
`__HOM_LAMBDA_ ` is the lambda from [1,0] that is used to choose between the simplified equation and the actual equation from the `homotopy` operator, see https://build.openmodelica.org/Documentation/ModelicaReference.Operators.%27homotopy()%27.html.

In the C runtime it is saved in `data->simulationInfo->lambda`. We should try to get it working in the C++ runtime as it should improve convergence of non-linear loops during initialization, because the Jacobian should fit the problem. Or at least it should be an improvement when the `homotopy` operator makes sense in the Modelica model.

**Comment by rfranke** [comment]
So far the Cpp runtime implements the trivial version of `homotopy`, see `CodegenCppCommonOld.tpl`:
```
  case CALL(path=IDENT(name="homotopy"),
            expLst={e1,e2},attr=attr as CALL_ATTR(__)) then
    let var1 = daeExp(e1, context, &preExp, &varDecls,simCode , &extraFuncs , &extraFuncsDecl, extraFuncsNamespace, stateDerVectorName, useFlatArrayNotation)
    let var2 = daeExp(e2, context, &preExp, &varDecls,simCode , &extraFuncs , &extraFuncsDecl, extraFuncsNamespace, stateDerVectorName, useFlatArrayNotation)
    '<%var1%>'

  case CALL(path=IDENT(name="homotopyParameter"),
            expLst={},attr=attr as CALL_ATTR(__)) then
     '1.0'
```

When does the code generation use `homotopyParameter` and when `__HOM_LAMBDA_`?

**Comment by AnHeuermann** [comment]
I don't think `__HOM_LAMBDA` should ever be in the generated code but be replaced by `data->simulationInfo->lambda`. See OMCompiler/Compiler/Template/CodegenCFunctions.tpl:

```
/* public */ template cref(ComponentRef cr)
 "Generates C equivalent name for component reference.
  used in Compiler/Template/CodegenFMU.tpl"
::=
  match cr
  case CREF_IDENT(ident = "xloc") then crefStr(cr)
  case CREF_IDENT(ident = "time") then "data->localData[0]->timeValue"
  case CREF_IDENT(ident = "__OMC_DT") then "data->simulationInfo->inlineData->dt"
  case CREF_IDENT(ident = "__HOM_LAMBDA") then "data->simulationInfo->lambda"
  case WILD(__) then ''
  else crefToCStr(cr, 0, false, false)
end cref;
```

It could be enough to add something similar to OMCompiler/Compiler/Template/CodegenCppCommon.tpl. E.g.
```
template cref(ComponentRef cr, Boolean useFlatArrayNotation)
 "Generates C equivalent name for component reference."
::=
  match cr
  case CREF_IDENT(ident = "time") then "_simTime"
  case CREF_IDENT(ident = "__HOM_LAMBDA") then "1.0"
  case WILD(__) then ''
  else "_"+crefToCStr(cr, useFlatArrayNotation)
end cref;
```

**Comment by casella** [comment]
I would recommend that (eventually) the cpp runtime uses homotopy, as well as `--daeMode`, sparse solvers, and all the advanced features that we have introduced in the C runtime during the last 6 years.

While it doesn't, it would probably be best to get rid of homotopy from the start, by using `--replaceHomotopy=actual` when the compilation process is started. This removes homotopy already in the front-end, avoiding unnecessary overhead in the simulation code, caused by the presence of the simplified expressions. I'm not sure that the solution proposed in the previous comment would be as efficient.

**Comment by rfranke** [comment]
The call `homotopyParameter` treated by the Cpp runtime so far appears to not exist. This is why I replaced it with the ident `__HOM_LAMBDA`. The above examples work this way. Let's see the results of more tests ...

**Comment by casella** [comment]
@rfranke, this fix is currently on master, so it will get into 1.18.0. If you want it to be in the 1.17.1 release, it needs to be ported to the [maintenance/v1.17](https://github.com/OpenModelica/OpenModelica/commits/maintenance/v1.17) branch.

Can you please take care of that? Once it's merged in, you can change the milestone again for the record.

Thanks!
