### ISSUE TITLE
BackendDAEEXT.getAssignment failed

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7579]
A moderately large model that we still use with a frozen OpenModelica 1.12 is gradually working less with newer versions.
1.13.2: out-of-memory / crash of 32bit version under Windows
1.14.1: backend fails with new frontend; translates with old frontend but fails to simulate
1.16.1: backend fails with either frontend raising the below error message
1.18-dev: dito
```
[125] 17:41:39 Symbolisch Internal Error
BackendDAEEXT.getAssignment failed because n=1372>arrayLength(ass1)=1372 or m=1390>arrayLength(ass2)=1372

[126] 17:41:39 Übersetzung Fehler
Interner Fehler It is not possible to select continuous time states because Number of Equations 1 greater than number of States 0 to select from.

[127] 17:41:39 Übersetzung Fehler
Interner Fehler - IndexReduction.dynamicStateSelectionWork failed!
```
Is there any flag to get rid of `BackendDAEEXT.getAssignment failed`?

**Comment by sjoelund** [comment]
> Is there any flag to get rid of `BackendDAEEXT.getAssignment failed`?

Maybe DAE mode? Maybe changing index reduction algorithm? You cannot generate code without the matching algorithm succeeding.

**Comment by rfranke** [comment]
Tweaking the index reduction method and selecting the old frontend changes something. But now I encounter a new problem with today's nightly build for Windows. Cpp compilation of any model fails (e.g. Modelica.Blocks.Examples.PID_Controller):
```
g++ -fopenmp=libomp  -Winvalid-pch -O0 -DNDEBUG  -std=c++11 -DBOOST_ALL_DYN_LINK   -DUSE_DGESV -DUSE_LOGGER -DOMC_BUILD -DUSE_THREAD -DSUNDIALS_MAJOR_VERSION=5 -DSUNDIALS_MINOR_VERSION=4 -DPMC_USE_SUNDIALS -I"." -I"C:\PROGRA~2\OPENMO~1.0-D/include/omc/cpp/" -I.  -I"C:\PROGRA~2\OPENMO~1.0-D/include/omc/cpp/3rdParty/boost/gcc/" -I"." -I"C:\PROGRA~2\OPENMO~1.0-D/include/omc/cpp/sundials"     -DMEASURETIME_PROFILEBLOCKS -DUSE_LOGGER  -c -o OMCppPID_ControllerCalcHelperMain.o OMCppPID_ControllerCalcHelperMain.cpp
g++.exe: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
mingw32-make: *** [<builtin>: OMCppPID_ControllerCalcHelperMain.o] Error 1
```
I recall that there was clang selected per default a couple of days ago. I changed it to gcc to get appropriate static linking for FMU expoert. But now clang appears gone again!?

**Comment by casella** [comment]
@rfranke, the only we we have to _structurally_ address this kind of issues is that we set up a private repository of models that are of interest to ABB, on which we run daily regression reports, as we already do with open source libraries. In that way we can kill regressions in the cradle, instead of leaving them to grow like cancer over the years. Otherwise, you end up in impossible situations using old versions that somehow manage to do what you need, but are riddled with many other shortcomings.

I have been proposing for some time that we set up an infrastructure to get this done, which could also bring the OSMC some revenue if we offer this service for a fee, but I understand this is simply not going to happen on anybody's free time. Maybe we should set up a DFD to get this feature implemented, and then ABB gets free service forever in return.

I can personally guarantee that all regressions will be monitored, reported, and addressed as soon as they pop up - if there are any such regressions, the policy will be "revert now, fix later". It won't be enforced strictly by the CI, because we cannot run the whole library testsuite at each commit, but there will be a lot of moral suasion from my side :)

This would guarantee that we have a deadline and we get this done, and, most importantly, it would avoid any further regressions popping up in the future, which is something that has plagued ABB models since the beginning.

@rfranke what do you think?

**Comment by rfranke** [comment]
Yes, this would be an option. The already running tests show though that they don't solve all problems (continuously reduced coverage of Cpp runtime in library tests since 1.13). The biggest change was introduced with the new frontend that improves many things, but also still causes issues in the backend and during code generation. Here additionally a change in the index reduction algorithm causes a problem.
Moreover, the additional issues under Windows are annoying (crashes with stack overflow or endless loops -- that are hopefully fixed now, sudden change of default compiler to clang that breaks static linkage of Cpp FMU export, no compiler working at all in the recent nightly build, ...)

**Comment by adrpo** [comment]
> sudden change of default compiler to clang

@rfranke the change to clang on windows was no sudden at all, it happened in 1.17 and we talked about it a lot of times.
What is the actual problem with clang and static linking? I think we will need to detect which one compiler is used and change the flags a bit (as far as I can tell is an issue with openmp).

**Comment by casella** [comment]
> @rfranke the change to clang on windows was no sudden at all, it happened in 1.17 and we talked about it a lot of times.

Changing to clang and dynamic linking was a major improvements in terms of usability of OMEdit under Windows, because it slashed the turnaround time in the modify-compile-simulate-analyze loop dramatically.

@rfranke, from your comments it seems like OMC has constantly been getting worse since 1.12. That is obviously not the case for most users. The problem is that ABB has slightly off-mainstream requirements that are not routinely tested, so when bugs are introduced (which is inevitable,  this happens all the time) they are not immediately caught and resolved - the discussion starts about them when we are close to the time of the release, which is often too late to handle things properly.

The way forward is not to avoid introducing new features, like clang, when they are badly needed; gcc and static linking under Windows were slow as hell, even a stupid HelloWorld model took 20+ s to compile under Windows, that was not acceptable.

We should instead focus on putting all the features that are critical for ABB under daily automated test, so that we have proper quality assurance. This includes

- coverage of libraries that are intersting for ABB
- coverage of all existing ABB models that run in OMC, also with cpp runtime
- FMU export and testing of generated FMUs, incl. w/ cpp runtime
- GUI

Regarding the latest point, @JKRT is starting a student project with tools to carry out automated GUI testing, we should have something availabe in the near future.

Shall I open an issue where we can collect all your requirements, so that we can formulate a DFD?

**Comment by rfranke** [comment]
@adrpo: the problem is that FMUs compiled with clang have link dependencies and thus cannot be exported. This might stem from CodegenFMUCppOld.tpl, Line 832ff:
```
  # link static libs to avoid dependencies; can't link all static under Linux
  else ifeq ($(findstring gcc,$(CC)),gcc)
    $(eval LIBS=$(LIBS) $(if $(findstring linux,$(PLATFORM)),-static-libstdc++ -static-libgcc,-static))
  endif
```
I had never encountered it until a nightly build of 1.18-dev last week. There seems to be something changing from build to build recently.

**Comment by adrpo** [comment]
@rfranke that should not be the case, it should be possible to link statically with clang with no issues (maybe one issue: https://trac.openmodelica.org/OpenModelica/ticket/6179 some red messages but not error).

**Comment by adrpo** [comment]
I will fix the clang link issue with #7583.

**Comment by rfranke** [comment]
Here we are: the simple example `PowerSystems.Examples.AC1ph_DC.Elementary.Sensor` started to fail with 1.16. Since the bad commits yesterday but one, the error message changed to the title of this issue:
```
Internal error: BackendDAEEXT.setAssignment failed because m=15>12=arrayLength(ass2)
Error: Internal error It is not possible to select continuous time states because Number of Equations 1 greater than number of States 0 to select from.
Error: Internal error - IndexReduction.dynamicStateSelectionWork failed!
```
https://libraries.openmodelica.org/branches/master/PowerSystems/files/PowerSystems_PowerSystems.Examples.AC1ph_DC.Elementary.Sensor.err

**Comment by casella** [comment]
@kabdelhak, can you shed some light on this?

**Comment by rfranke** [comment]
The following examples from PowerSystems suffer from "BackendDAEEXT.setAssignment failed ... IndexReduction.dynamicStateSelectionWork failed"
- `PowerSystems.Examples.AC1ph_DC.Elementary.Sensor`
- `PowerSystems.Examples.AC3ph.Elementary.Sensor`
- `PowerSystems.Examples.Introductory.SimulationSteadyState`
- `PowerSystems.Examples.Introductory.Units`

Those are all rather simple examples that hardly need index reduction.

**Comment by sjoelund** [comment]
There are some similar errors for other libraries, for example Buildings:
```
Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.BalancedStepDown.YD.err:Internal error: BackendDAEEXT.setAssignment failed because m=256>250=arrayLength(ass2)
Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.BalancedStepUp.YD.err:Internal error: BackendDAEEXT.setAssignment failed because m=256>250=arrayLength(ass2)
Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.UnbalancedStepDown.YD.err:Internal error: BackendDAEEXT.setAssignment failed because m=256>250=arrayLength(ass2)
Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Electrical.AC.ThreePhasesUnbalanced.Validation.IEEETests.Test4NodesFeeder.UnbalancedStepUp.YD.err:Internal error: BackendDAEEXT.setAssignment failed because m=256>250=arrayLength(ass2)
```

My guess is that the new frontend preserves arrays better and something in the backend can't handle it. The reason it now fails on setAssignment is due to 9c01e70a5bad trying to catch this earlier (before we had random crashes instead, since C matrices were not allocated enough space).

**Comment by rfranke** [comment]
The four PowerSystems examples mentioned above were failing in the frontend before the recent changes that led to #7596.

**Comment by perost** [comment]
I had a quick look and found that the index reduction seemed to be adding too many dummy variables, and found a case where the comment said it was for variables with StateSelect.Prefer but it checked for StateSelect.Never. I changed the code to do what the comment said, and it fixed the `PowerSystems.Examples.AC1ph_DC.Elementary.Sensor` model at least. It also doesn't break anything in the MSL, but I'll wait for @kabdelhak to review it before I push it in.

**Comment by rfranke** [comment]
Looks very good! The fixes by @adrpo and @perost above solve this issue, as well as the recent frontend work by @mahge on subscripting that solved another problem shadowing this one since release 1.17.

The above mentioned PowerSystems examples simulate now. The given Buildings examples at least improve; now proceed to a later stage (`post-optimization module replaceHomotopyWithSimplified (initialization) failed.`)

**Comment by casella** [comment]
Very good indeed, now PowerSystems is at 94/118=80% success rate, and PowerSystems_cpp at 90/118=76%

**Comment by rfranke** [comment]
Version 1.0.1 of PowerSystems adds experiment annotations to 10 more examples (Precalculations with lots of small matrices). Overall both runtimes (C and Cpp) simulate 98 of 128 models, i.e. 77% now.
https://libraries.openmodelica.org/branches/overview-combined.html
