### ISSUE TITLE
Errors in User's Guide with reinit due to FMI import

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#7591]
### Description

One of our examples with BouncingBall is outdated and needs to be fixed to work with MSL 4.0.

### Steps to Reproduce

See https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/fmitlm.html

### Additional Context

Probably related ticket: https://github.com/OpenModelica/OpenModelica/issues/7522

**Comment by AnHeuermann** [comment]
The problem is the old FMI Import that will create a Modelica model for an FMU which is not compliant with the specification. Apparently it is not working with MSL 4.0.0.

Should we just remove the [FMI Import](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/fmitlm.html#fmi-import) section since it is outdated? But the old / non-working FMI Import is still the fist thing a user will try with OMEdit to import an FMU instead of using OMSimulator by creating a new SSP model.

@lochel We talked about removing the old FMI Import but as of today it is still in OMEdit.
Is removing it for 1.18 a good idea?

**Comment by sjoelund** [comment]
Send an email to @petfr and @casella. I think it should have been removed ages ago. Otherwise, we would need to set it to use the old instantiation, I guess.

**Comment by casella** [comment]
I'm sorry if I repeat myself, but IMHO getting rid of FMI import is a bad idea. I agree that what we have is not good, but I would rather see it improved than removed. We have users that need this feature (e.g. @ceraolo) and would be quite annoyed if we go this way.

OMSimulator _is not a replacement for FMI import in a Modelica model_. Consider this paradigmatic case: model A contains an instance of model B, that contains an instance each of models C and D, each one using an FMI-defined block. As I see it, there is no straightforward way to represent this setup with OMSimulator. This is a representative use case of a Modelica model with some detail represented as an FMI, and I guess it could be quite commonplace.

OMSimulator is a tool to simulate connected FMUS. FMI import is a way to get one (or more) FMUs inside a complex Modelica model. Those are two completely different scenarios with completely different requirements.

Comments?

**Comment by adrpo** [comment]
I agree with @casella since we broke this. We should just give a warning, allow reinit in algorithm sections and go on with our lives.

**Comment by sjoelund** [comment]
> I agree with @casella since we broke this. We should just give a warning, allow reinit in algorithm sections and go on with our lives.

That would be the wrong way to go. Either generate valid Modelica code or require special flags. We could mark the model with the necessary annotations to enable debug flags / etc to make it clear this is not a model that will work in standard Modelica tools.

I should note that also Dymola has difficulties with its FMI import (it failed when importing enumerations last I checked). It's not really an approach that is easy in standard Modelica, which was the dream.

**Comment by petfr** [comment]
Dear All,

I agree with Adrian and Francesco.  This (FMI import) is a valuable feature needed by users. It should be supported.
For user friendliness we should give a warning rather than use flags which are less user friendly.

Regarding Matins comment: For the future:  I think that the Modelica standard might need to be adapted in some way to support this.
That also Dymola has problems supports this view.
An MCP should be created on the topic.  For now, follow Adrian's suggestion.

Best,
Peter




Adrian:

I agree with @casella<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcasella&data=04%7C01%7Cpeter.fritzson%40liu.se%7C48f42b80c2654a64205e08d93536dc28%7C913f18ec7f264c5fa816784fe9a58edd%7C0%7C0%7C637599332002799966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nW3T0EsdsV4HpoyG9Gj7OoWzo4btptk8nKK18ThYBY8%3D&reserved=0> since we broke this. We should just give a warning, allow reinit in algorithm sections and go on with our lives.

Martin Sjölund:

That would be the wrong way to go. Either generate valid Modelica code or require special flags. We could mark the model with the necessary annotations to enable debug flags / etc to make it clear this is not a model that will work in standard Modelica tools.

I should note that also Dymola has difficulties with its FMI import (it failed when importing enumerations last I checked). It's not really an approach that is easy in standard Modelica, which was the dream.

**Comment by lochel** [comment]
@casella Well, let me also repeat myself then 😉 I disagree as everyone should know by now. We should get rid of the FMI import because it doesn't work and instead focus on a proper solution utilizing OMSimulator. I don't think that the mentioned use case requires the Modelica-based FMI import. I suggest a meeting to lay out potential use cases and how those could be handled by the different approaches. Based on such a discussion we can make a discussion and go forward.

**Comment by sjoelund** [comment]
MCP 0017 already exists.We needed to rewrite OMC in order to become a standard Modelica compiler partially because we supported a lot of non-standard things. Why would we do the same mistake again? We have a new good framework for dealing with non-standard things and compatibility for them. We should treat this code the same way we do with libraries developed with Dymola: force a flag to be used.

**Comment by lochel** [comment]
Not exactly sure what you mean @sjoelund. The "old" FMI import should be removed completely. I am pretty sure that we will not get it to work and therefore we shouldn't waste time in semi-supporting it on a special flag. Or what do you think?

**Comment by sjoelund** [comment]
> Not exactly sure what you mean @sjoelund. The "old" FMI import should be removed completely. I am pretty sure that we will not get it to work and therefore we shouldn't waste time in semi-supporting it on a special flag. Or what do you think?

We should as a first step recognize that it isn't standard Modelica and use compatibility flags for it. Probably give a warning when using the API that it's deprecated or not standard Modelica. Just removing it right away might also be possible but upset some users.

**Comment by petfr** [comment]
Hi All,

I agree with Lennart that for the longer perspective we should try to use OMSimulator in some way for this use case.
But it should be made to be easy to use.  A user should be able to include an FMU and connect it together with other Modelica models inside OMEdit.
One should not need to partition the Modelica model into pieces, export each piece as an FMU, and switch to the OMSimulator GUI in order for this to work.
Until this has been done a quick solution as Adrian suggested might be temporary solution.
Best,
Peter

**Comment by lochel** [comment]
I am fine with a deprication warning and fading out the functionality until the 2022.01 (?) release. But we should avoid spending any more resources on the old FMI import.
However, this will require some OMEdit work, and potentially also some OMSimulator work. We need to plan those tasks and ensure that we have funding for it.

**Comment by perost** [comment]
> I agree with @casella since we broke this. We should just give a warning, allow reinit in algorithm sections and go on with our lives.

Just to clarify why we haven't done this yet. It's not as simple as just removing an error check, reinit statements are not implemented at all in the NF since they're not part of Modelica. It wouldn't be terribly hard to add support for them, but it would still take some effort.

**Comment by petfr** [comment]
How much effort appox?
Peter

**Comment by perost** [comment]
> How much effort appox?

A couple of hours perhaps.

**Comment by petfr** [comment]
To me that sounds like it is clearly worth it.
Best,
Peter

**Comment by casella** [comment]
@lochel, I understand you don't agree with me on this. However, the fact that the feature currently doesn't work is not _per se_ a good argument in favour of its removal. Particularly if fixing it is no big deal. The question is: is it needed? From my understanding, the answer is yes.

I also get your point, that maintaining two features is harder than maintaining one. That's why we currently have four runtimes (C, old cpp, omsicpp, realtime) 😄 

Seriously, you haven't yet showed me how you would propose to solve the problem I stated (model A using model B etc.) using OMSimulator. I believe this setup can be useful in a number of applications, and if Dymola is lagging behind supporting it, that could be a selling point for OMC, if it could handle it correctly. Maybe I'm missing something obvious, but using OMSimulator to solve this problem would seem to me like the proverbial tail wagging the dog.

Could you shortly elaborate on that? How would you set up such a model in OMSimulator?

Regarding reinit, this is a low-level technical detail, and if we need an amendment to the Modelica language that has a clear justification, I see no problem with that. The strategy meetings all made clear that the MA supports coordinated open standards, if we need an extension of Modelica to support FMI within Modelica, that's a textbook case.

**Comment by casella** [comment]
> That would be the wrong way to go. Either generate valid Modelica code or require special flags. We could mark the model with the necessary annotations to enable debug flags / etc to make it clear this is not a model that will work in standard Modelica tools.

I agree, but I guess we should issue a warning that this is not standard Modelica and may not work in other tools, and have a flag to suppress the warning, not an error. We already had this discussion regarding the libraries from TUHH.

> I should note that also Dymola has difficulties with its FMI import (it failed when importing enumerations last I checked). It's not really an approach that is easy in standard Modelica, which was the dream.

Nothing is easy in Modelica, and making a compiler is more like a nightmare than a dream, as we all know. The devil in the details, etc. 

But again, if we could do it, it may be a selling point for OMC.

**Comment by perost** [comment]
> Regarding reinit, this is a low-level technical detail, and if we need an amendment to the Modelica language that has a clear justification, I see no problem with that. The strategy meetings all made clear that the MA supports coordinated open standards, if we need an extension of Modelica to support FMI within Modelica, that's a textbook case.

The big question for me is if we really need support for reinit statements to support FMI. I know Adrian made som attempt to get rid of it a while ago, but I don't know if anyone more familiar with the FMI implementation has taken a look. Fixing the generated FMI code would be vastly more preferable to me than having to implement a non-standard extension that we then have to maintain. To be clear, we're talking about a single reinit statement in the generated code here.

**Comment by casella** [comment]
@perost good question, I currently have no idea. I guess it's too late to fix this for 1.18.0, but we can try to get a good solution for 1.19.0.

I understand that for some FMUs this reinit is not necessary (e.g. if they are continuous-time), i.e. there is a class of FMUs that can be currently imported without any problem. I don't see the point of harassing users by suddenly disallowing them to use previously developed models with imported FMUs that used to work fine, and would still work fine.

I am constantly getting feedback from users in industry that are still using old omc versions all the way back to 1.12 because later versions won't run their code for some technical reason. This is of course not good, all of our users should be able to benefit of the latest improvements to the omc codebase, which have been massive in the last couple of years. We should try to keep these regression cases to a minimum, ideally zero, rather than keep growing them.

**Comment by lochel** [comment]
I really would like to have a meeting to discuss this questions. It is not ideal to have the discussion in this issue.

It is doubtful if fixing the reinit would actually solve all the problem with the FMI import. There is probably a reason for why other tools are facing similar issues. I am pretty sure that the implementation wouldn't work well with events for example. And nothing of this is actually needed in my opinion, because we have all the technology we need to simulate those use cases. The only question is how to provide a good user experience.

I see two obvious possible approaches to this problem:

1. Modeling in Modelica

   FMU's can be encapsulated by blocks for the purpose of modeling. The issue with reinit and the runtime only occurs for the simulation. Instead of compiling and simulating, we could automatically generate a SSP that contains a set of FMUs, the parameterization, and also the connection of course. This could then be easily simulated using OMSimulator. And of course you could have all this step on a single click of a button in OMEdit.

2. Modeling in SSP

   Instead of putting precompiled FMUs into the SSP, you could also have the Modelica models directly, either as total model or symbolic link to a library. It is just a matter of tool support to make this a smooth user experience.

**Comment by casella** [comment]
> I really would like to have a meeting to discuss this questions. It is not ideal to have the discussion in this issue.

Could we have it next week after the devmeeting?
 
> It is doubtful if fixing the reinit would actually solve all the problem with the FMI import. There is probably a reason for why other tools are facing similar issues.

Of course it is important to understand if there are _structural_ reasons that do not allow FMI import into Modelica models. After all Modelica is declarative and FMI is procedural, so this could well be. And this is a discussion that we need to carry out within the MA

> I am pretty sure that the implementation wouldn't work well with events for example. And nothing of this is actually needed in my opinion, because we have all the technology we need to simulate those use cases. The only question is how to provide a good user experience.

I'm open to it, if the user experience is good.

> I see two obvious possible approaches to this problem:
> 
>     1. Modeling in Modelica
>        FMU's can be encapsulated by blocks for the purpose of modeling. The issue with reinit and the runtime only occurs for the simulation. Instead of compiling and simulating, we could automatically generate a SSP that contains a set of FMUs, the parameterization, and also the connection of course. This could then be easily simulated using OMSimulator. And of course you could have all this step on a single click of a button in OMEdit.

This could be an option when FMI generation is as good as the current C runtime. It seems we're still quite far from there, e.g. compare the MSL 3.2.3 report with [C runtime](https://libraries.openmodelica.org/branches/master/Modelica_3.2.3/Modelica_3.2.3.html) and with [FMI](https://libraries.openmodelica.org/branches/master-fmi/Modelica_3.2.3/Modelica_3.2.3.html). On the other hand, we have to improve FMI anyway, so that could be a further incentive to do that. What I mean is that there is still a lot of work to be done, and we currently do not have the resources to carry it out, so it's not a solution that can materialize in the next 6-12 months.

It would also require some work in the frontend and backend to carve out the set of equations of the non-FMI Modelica model to be turned into an FMU (the dog wagged by the tail, so to speak). Probably not that difficult.

>     2. Modeling in SSP
>        Instead of putting precompiled FMUs into the SSP, you could also have the Modelica models directly, either as total model or symbolic link to a library. It is just a matter of tool support to make this a smooth user experience.

I don't get this. If I have a complex Modelica model with one or two FMUs in the belly, I'd want to see it as a Modelica model, not as an SSP. And most definitely not as a total model, that's something an end user is ever going to be interacting with directly, e.g. by making modifications. 

Maybe you can provide concrete simple example with a couple diagrams.

**Comment by casella** [comment]
Long story short:
- the existing FMU functionality will be reinstated in #5345 
- future developments will require clarifications from the MA and/or be based on OMSimulator infrastructure
- the [documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/fmitlm.html#fmi-import) is already fixed.
