### ISSUE TITLE
OSError: exception: access violation reading during simulation FMU

### ISSUE THREAD

**Issue by henrylux128** [OpenModelica/OpenModelica#7611]
### Description
FMU CoSimulation with RoomCO2 (OM example inside fluid) generated by OpenModelica and run using fmpy
startValue = 0.0
stopValue = 3600.0
stepSize = 0.01

after 136592 iterations, simulation crashes with exception at doStep call

### Version and OS
 - OpenModelica Version v1.17.0 (64-bit)
 - FMPy 0.3.0
- Python 3.9.2 (same issues for earlier python version)
 - OS: Windows 10, 64 bit
 
### Error message
  File "..........\lib\site-packages\fmpy\fmi2.py", line 575, in doStep
    return self.fmi2DoStep(self.component, currentCommunicationPoint, communicationStepSize, noSetFMUStatePriorToCurrentPoint)
  File ".........\lib\site-packages\fmpy\fmi2.py", line 206, in w
    res = f(*args)
OSError: exception: access violation reading 0x000000000000001A

**Comment by casella** [comment]
@henrylux128, I guess you mean `Modelica.Fluid.Examples.TraceSubstances.RoomCO2`, right?

@lochel, these are colleagues of mine from Politecnico di Torino working on nuclear fusion, we've worked and published together many times in the past 12 years. They are trying to solve the problem of coupling some Modelica models with custom FORTRAN codes, using co-simulation via FMI, which is the proper modern way to do so.

I would appreciate if you could have a look at this issue and help them. 136,000 iterations and counting is quite a large number, but it's not uncommon with co-simulation schemes, where you may need small steps to keep numerical stability.

@henrylux128 if you have Dymola I would suggest you also try this out with a Dymola-generated FMU, to see if FMPy can handle it.

@t-sommer, @chrbertsch, is it possible that FMPy runs into memory management issues when such a large number of steps is executed?

Thanks!

**Comment by t-sommer** [comment]
136k steps does not sound like a lot. What is the memory usage of the process? Did you try to run the FMU with the same settings in the [FMU Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker)?

**Comment by lochel** [comment]
I tested the example using (a) OpenModelica to generate the co-simulation FMU and (b) OMSimulator to simulate it in python. Everything works smoothly. The result file in mat format is with about 2GB big but not unreasonable big. I don't know the model, but at least the results do not seem to be arbitrary garbage.

* OMCompiler v1.18.0-dev.171+gc263934f53
* OMSimulator v2.1.1.post108-g1adcca8

@henrylux128, if you want to reproduce the results then you can simply install OMSimulator using `pip3 install OMSimulator --upgrade`. This is the python code that I was using:
```py
import OMSimulator as oms

print(oms.version)
oms.setCommandLineOption('--stripRoot=true --progressBar=true')

model = oms.newModel('RoomCO2')
root = model.addSystem('root', oms.Types.System.WC)
root.addSubModel('model', 'Modelica.Fluid.Examples.TraceSubstances.RoomCO2.fmu')

model.stopTime = 3600
model.fixedStepSize = 1e-2

model.instantiate()
model.initialize()
model.simulate()
```

Output:
```
OMSimulator v2.1.1.post108-g1adcca8-linux
info:    Result file: RoomCO2_res.mat (bufferSize=10)
info:    Parameter RoomCO2.root.model.traceSource.substanceName will not be stored in the result file, because the signal type is not supported
info:    Parameter RoomCO2.root.model.traceVolume.substanceName will not be stored in the result file, because the signal type is not supported
info:    step WC system [0.000000; 3600.000000] with step size [0.010000; 0.010000; 0.010000]
info:    [===============================================================] 100%
```

**Comment by casella** [comment]
2 GB looks pretty close to the memory space that can be handled by 32-bit processes. I'm not sure how FMPy works from this point of view, is it involving some 32 bit stuff perhaps?

@henrylux128 please check the memory usage while the co-simulation is running, you can use the Windows Process monitor (Gestione Attività)

**Comment by t-sommer** [comment]
Can you share the FMU, ideally with source code, so we can reproduce and debug the issue?

**Comment by lochel** [comment]
I managed to reproduce the problem. It is Windows specific, which is why I couldn't catch it on linux yesterday. I will investigate the problem a bit more.

**Comment by lochel** [comment]
Just a short update on the status: The problem originates from the runtime system that attempts to concatenate two arrays. This works apparently fine for the first 160k steps or so, but then malloc raises a segmentation fault. We are still not sure why though.

**Comment by henrylux128** [comment]
Thanks everyone for the answers.
@lochel 
I tested the example code
`
import OMSimulator as oms

print(oms.version)
oms.setCommandLineOption('--stripRoot=true --progressBar=true')

model = oms.newModel('RoomCO2')
root = model.addSystem('root', oms.Types.System.WC)
root.addSubModel('model', 'Modelica.Fluid.Examples.TraceSubstances.RoomCO2.fmu')

model.stopTime = 3600
model.fixedStepSize = 1e-2

model.instantiate()
model.initialize()
model.simulate()
`
I got the following
![image](https://user-images.githubusercontent.com/44991289/126963442-b9a5e17b-854e-45b9-b78f-b09a64102c34.png)

@casella using Windows Process monitor, the memory usage go from 4.9 GB to 6.8 GB (RAM 8 GB), almost same dimension of mat file. Can I ask if the fmu caches all states in memory, also the states not needed for integration step? I tried to use gc (Python package to handle garbage collector) but I didn't see any performance improvement.

@dietmarw 
now I'm trying to run the following code
`
import OMSimulator as oms

print(oms.version)
oms.setCommandLineOption('--stripRoot=true --progressBar=true')

model = oms.newModel('RoomCO2')
root = model.addSystem('root', oms.Types.System.WC)
root.addSubModel('model', 'RoomCO2Example.fmu')

model.startTime = 0.0
model.stopTime = 3600.0
model.fixedStepSize = 1e-2
model.resultFile = "Result2.mat"

model.instantiate()
model.initialize()

step = 0
while model.time < model.stopTime:
    step += 1
    print(f"Step {step}")
    model.setReal("root.model.massFlowRate", 100.0 / (1.2 * 3600.0) * 5.1)
    model.doStep()

model.terminate()
model.delete()
`

Where I changed massFlowRate as a RealInput before producing fmu, in modelDescription is:
`
<ScalarVariable name="massFlowRate" valueReference="74" causality="input">

<Real start="0.0"/>

</ScalarVariable>
`

And I got the following
![image](https://user-images.githubusercontent.com/44991289/126965580-81879ca8-1a37-4c1a-8ca7-6b0da65ebaa5.png)

**Version**
OMSimulator v2.1.1.post109-g7212988-win

**Comment by casella** [comment]
> @casella using Windows Process monitor, the memory usage go from 4.9 GB to 6.8 GB (RAM 8 GB), almost same dimension of mat file. Can I ask if the fmu caches all states in memory, also the states not needed for integration step? I tried to use gc (Python package to handle garbage collector) but I didn't see any memory usage improvement.

This is for sure an issue. I mean, `Modelica.Fluid.Examples.TraceSubstances.RoomCO2` is a toy example with 228 variables, half of which are aliases. There is no reason why co-simulating such a model should result in such a huge memory allocation. As I understand it, the FMU should allocate a certain amount of memory for the execution _of a single simulation step_, as it happens for standalone simulation executables generated by Dymola or OpenModelica. Given the size of the model, that could amount to a few kilobytes at most. Simulation results should be written directly to mass storage a soon as a simulation step has been accepted, there is no reason why it should be stored in RAM, unless one really wants to hang the computer hard during long simulations.

@henrylux128, it is not clear to me if the large memory allocation you observed was obtained with OMSimulator or with FMPy (or both). Did you refer to your last experiment you reported, i.e. running an OMC-generated FMU of `Modelica.Fluid.Examples.TraceSubstances.RoomCO2` with OMSimulator? If that is the case, then it seems that the problem arises irrespective of what environment (OMSimulator or FMPy) is used to run the FMU.

@lochel, you reported that

>Just a short update on the status: The problem originates from the runtime system that attempts to concatenate two arrays. This works apparently fine for the first 160k steps or so, but then malloc raises a segmentation fault. We are still not sure why though.

By "runtime system" do you mean OMC's runtime? That of course wouldn't be good.

Did we ever check that the memory consumption of OMC-generated FMUs is constant on a large enough number of test cases?

**Comment by lochel** [comment]
From what I can tell, this issue has nothing to do with FMPy or OMSimulator. It is a Windows specific problem of the FMI runtime (which is using a subset of OMC's runtime), and indeed of the memory management to be more specific. I tried to make sense out of the segmentation fault together with @mahge and @arun3688. It is malloc which crashes for whatever reason. Our best guess at the moment is that the GC and memory pool interfere with each other and cause a corrupted heap.

**Comment by casella** [comment]
> 
> 
> From what I can tell, this issue has nothing to do with FMPy or OMSimulator. It is a Windows specific problem of the FMI runtime (which is using a subset of OMC's runtime), and indeed of the memory management to be more specific. I tried to make sense out of the segmentation fault together with @mahge and @arun3688. It is malloc which crashes for whatever reason. Our best guess at the moment is that the GC and memory pool interfere with each other and cause a corrupted heap.

OK, thanks. 

I'm not sure I understand why malloc should be called _at each time step_ though. This would be really terrible performance-wise. Working memory (no matter how allocated) should be re-usable, and results should just be written to mass storage. Why is `malloc()` called during simulation? Do I miss something?

**Comment by lochel** [comment]
@henrylux128 The issue should be solved now. Please try the latest version of OpenModelica and re-export the FMU. The simulation should work fine.

_Note: If you are not compiling OpenModelica yourself, then you have to wait until tomorrow for a new nightly-build installer._

**Comment by casella** [comment]
OK, so the 2 GB limit was indeed enforced by a 32-bit only entity 😄 

@lochel, @mahge, I still don't get why on Earth are we allocating such humongous amounts of memory to simulate a toy example model. I'm scared that as soon as we start handling serious models in terms of size of the individual model and/or of number of FMUs in an SSP simulation, we would soon go into the Terabyte range.

Could you please elaborate a bit about that?

Thanks!

**Comment by mahge** [comment]
> OK, so the 2 GB limit was indeed enforced by a 32-bit only entity 

Ya. You hit the nail in the head with that one.  You should start debugging these things 🙂

>  I still don't get why on Earth are we allocating such humongous amounts of memory to simulate a toy example model. I'm scared that as soon as we start handling serious models in terms of size of the individual model and/or of number of FMUs in an SSP simulation, we would soon go into the Terabyte range.

In a way it is more of a number-of-steps taken instead of just number-of-variables in the model.

OpenModelica FMUs use our own custom memory pool implementation (instead of garbage collection or something like C++ RAII). 

------------------------
In the past this memory pool implementation used to work like a poor-man's stack. It used to mark at the start of a function execution and claim any memory back at the end of the function. Then we switched to Garbage Collection and it fell out of grace.  We stopped generating the relevant code for marking and claiming back in to the generated functions ourselves. 


Then GC had issues with multi-threading for HPCOM project.  Martin updated the memory pool implementation for multi-threaded usage (I assume) and also changed how it works since we can no longer claim in every function. We had removed the code for it. 

-------------------------

I think, the idea was to claim back at the end of every step taken. However, I do not think we are actually doing that right now. It is supposed to claim back after every step but it seems like it is not doing that.

The way the memory pool grows is also the cause here. Right now, if it runs out of available memory, it grows by allocating more but it **allocates a new memory block of at least `x1.5` what it allocated last time**. It starts at 2MB. That accumulates to a lot of memory if it not actually being claimed back. 

_N.B. This might be wrong in some places because I am just trying to understand the code and that is not usually easy_ 

I will try to figure out if we can claim back something and if so why it is not working right now.

**Comment by casella** [comment]
@mahge my question is more fundamental, maybe I am missing something. Why do we need to use _new_ memory at each time step and worry about claiming it back? I mean, unless complicated recursive functions are called, the data structures are always the same. Can't we just re-use _the same_ memory pool to hold variable, residuals, jacobians etc. from step to step? I assumed that was was we were doing, but maybe I was wrong.

So, before trying to claim back memory, I would suggest that you identify for which purpose are we allocating this memory. It is essential that we understand clearly what it is used for and if there aren't ways to avoid that.

**Comment by casella** [comment]
BTW, the regular runtime runs at constant memory allocation during simulation, if I am to believe Windows' resource manager . I'm not sure that happens because the memory is allocated and then reclaimed at each time step, or if it is simply reused. It would seem to me that reusing it wherever possible would be better, since memory allocation is potentially a time consuming operation.

**Comment by henrylux128** [comment]
@lochel 
All scripts (oms, fmpy) using fmu (generated with last OM version) ran correctly. As expected.
I measured the available memory (MB) trends by running the same new FMU for both OMS and FMPY. They look quite similar and therefore independence from the python package is checked. As expected.
Issue is solved.

Available RAM during OMS script (MB)
![oms](https://user-images.githubusercontent.com/44991289/127361535-01a8b666-e79e-441f-8d69-6795df0279f8.PNG)

Available RAM during FMPY script (MB)
![fmpy](https://user-images.githubusercontent.com/44991289/127361698-2367f6a7-7687-44c7-9037-7454bd827fed.PNG)

@casella thank you very much everyone for your availability and thank you for all the Modelica tools you provide.

**Comment by casella** [comment]
All's well that ends well.

I'm still a bit puzzled by all this memory allocation activity. I wonder if we could do without.

**Comment by mahge** [comment]
@casella Sorry I missed the notifications for your comments somehow.

> @mahge my question is more fundamental, maybe I am missing something. Why do we need to use new memory at each time step and worry about claiming it back? I mean, unless complicated recursive functions are called, the data structures are always the same. Can't we just re-use the same memory pool to hold variable, residuals, jacobians etc. from step to step? I assumed that was was we were doing, but maybe I was wrong.

I think the terminology might have made this sound a lot more compilated than it actually is. Let me start again.

In theory the approach is very simple. Here is how it is supposed to work:

The runtime system allocates some large memory. This is the memory pool. Remembers where it is of course. And puts a "marker" there.
```
xMP = malloc(2M);
marker = xMP;
```

Say the first request from the simulation process is for 1MB memory for some monster of an array. The memory pool checks if it has enough memory left (it does) and if it does returns the current `marker` location and updates it afterwards to reflect the change.

```
// some check if we have enough left 
...
loc = marker;
marker = marker + 1MB;
return loc;
```

Now if we get asked for 2MB memory for another array, we have no space left. So the runtime system allocates more memory. But this time it allocates at least ~1.5x more memory (on TOP of what we have!) . We are basically learning from the past and try predict that we will need more. to So we allocate 3MB this time.  

```
xMP2 = malloc(3M);
marker2 = xMP2;
```

_Of course we keep track of both chunks (2MB and 3MB)._ 

That is it and one time-step ended. Now is our chance to claim back. To "claim back", you just move the marker back to where it was before the time-step started. One simple operation. Yes, we still have the 5MB memory, but now it can be reused! So if you do this every time-step you will not go above 5MB. You will not accumulate anything.

The problem seems like we are either not doing that. OR we are doing it but not frequently enough OR there is something else that is accumulating more memory every time step. Because the memory seems to keep going up and up. Sure there are changes between time-steps and we can use a tiny bit more from one step to the other. However, it feels like that is not the case here unless every time step we take somehow has increased need for memory compare to the previous one. 


> BTW, the regular runtime runs at constant memory allocation during simulation, if I am to believe Windows' resource manager . I'm not sure that happens because the memory is allocated and then reclaimed at each time step, or if it is simply reused. It would seem to me that reusing it wherever possible would be better, since memory allocation is potentially a time consuming operation.

The regular simulation uses Garbage Collection 😉. FMUs use the memory pool implementation instead.

**Comment by casella** [comment]
> @casella Sorry I missed the notifications for your comments somehow.

No problem, thanks for the explanation :)
 
> The problem seems like we are either not doing that OR we are doing it but not frequently enough OR there is something else that is accumulating more memory every time step. Because the memory seems to keep going up and up. 

That should not be the case, as far as I understand. So, we should discover which part of the code is doing that. Maybe there is just a plain stupid memory leak somewhere.

> Sure there are changes between time-steps and we can use a tiny bit more from one step to the other.

The only thing that changes between time-steps are the values of the variables, but those should always be written in the same chunk of memory. Normally you keep two arrays, one for the old values and one for the new, and then swap them at each time step and keep rewriting them over and over all the time. There's no need to keep old values in memory, once you have written them down to mass storage. Doing so is not not a good approach for anything but toy models run for very small numbers of time steps.

**Comment by mahge** [comment]
> The only thing that changes between time-steps are the values of the variables, 
True in general. I was just trying to cover the cases where an array size can change, or a loop runs more iterations and allocates more ... It can happen. However, even with that the difference should not be this big. For it to be the case here, it would have to keep growing on every time-step. E.g. A loop in some function does more and more iterations when we do more steps. Say the iteration variable depends indirectly on time.. essentailly causing the time-step to use more memory compared to the previous one. There is just for example and not something that happens often (I hope).  

That said, however, I do not think that is what is happening here. 

> Normally you keep two arrays, one for the old values and one for the new, and then swap them at each time step and keep rewriting them over and over all the time

We do not really try to map everything to the same place across different time steps. It can happen but it is not something we can rely on. All we can do is say "hey the memory pool chunk can be over-written starting from here". And that essentially allows us to reuse the memory and avoid allocating more.

> There's no need to keep old values in memory
We do not keep them in memory. At least not intentionally to keep them. They will be there until something else overwrites over that location. 

_It is like the OS's heap except that our memory pool is simple and strictly linear. You can allocate from the front and deallocate from the front._

**Comment by casella** [comment]
I guess we may want to run this test case with valgrind and figure out where the memory goes.

There are about 200 variables in this test, and it ran for about 130,000 steps. With double precision, this gives 200x130,000x8 bytes = 200 MBytes. In order to get to 2 GB you need a lot more. I really wonder what it is.

**Comment by mahge** [comment]
> There are about 200 variables in this test, and it ran for about 130,000 steps. With double precision, this gives 200x130,000x8 bytes = 200 MBytes. In order to get to 2 GB you need a lot more. I really wonder what it is.

Okay I see the confusion now. You gave back to your Modeler instinct and forgot that  _functions_ exist in Modelica 😉. More importantly, there are arrays in theses functions. Those are not reflected on the number of "model variables".

Most memory for "model variables" is **of course reused as you mentioned above**. What I was refereeing to was mostly about function variables. Arrays in functions are the main reasons of the need for Memory Pools or Garbage Collection.

_I am trying to update OpenModelica's Ipopt to 3.14, right now. As soon as that is finished I will try to figure this memory issue out. No worries. If we are lucky it will be a simple fix._

**Comment by casella** [comment]
> Okay I see the confusion now. You gave back to your Modeler instinct and forgot that _functions_ exist in Modelica 😉. More importantly, there are arrays in theses functions. Those are not reflected on the number of "model variables".

I'm well aware of that ;)

There are indeed function involved in Modelica.Media, and indeed they do use arrays in this case. Most of them should be inlined out, though it is likely that key function call survive as such after backend optimizations.

In this specific case I am 100% sure that we could generate code for them that only uses stack memory for those functions, given that all array sizes are statically known at compile time - no need to use heap for them. We already had this discussion somewhere else, and I understand it won't be trivial in practice, because it would mean rewriting large portions of the code generation. 

I hope the fix is easy and, most importantly, that allocating and (eventually) successfully deallocating memory so many times doesn't bog down the performance significantly. I wonder if there is some way to actually measure this (potential) issue
