### ISSUE TITLE
OMEncrypted does not find libraries in Resources folder

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#7674]
### Description
If an encrypted library. e.g ```MyExample.mol``` uses a Resources folder where e.g. a library for a Modelica external C function is located, the library cannot be found during translation.

### Steps to Reproduce
E.g. for a Model 
```modelica
function myExternalCFunction
  //OUTPUTS
  input Integer  y;
  output Integer u;

  //EXTERNALS
  external "C" myFunction(y, u) annotation(Library="myLibrary");

end myExternalCFunction
```
and the resource folder:

```MyExample\Resources\Library\win64\myLibrary.lib```

The translation stops with a linker error: ```cannot find  myLibrary```

### Version and OS

 - OpenModelica Version: v1.19.0-dev-14-g63df406c47 (64-bit)
 - OS: Windows 10, 64 
 - Versions of used Modelica libraries if applicable

### Additional Context
Please see also https://github.com/OpenModelica/OpenModelica/issues/6242

**Comment by adeas31** [comment]
I think the actual problem is #6242 and is probably have nothing to do with encryption.

**Comment by niklwors** [comment]
yes, but  it is a similar problem and still open.

**Comment by adrpo** [comment]
How did you build the .lib file? Is it with Visual Studio?

**Comment by niklwors** [comment]
Yes, but it has a C- interface and the model C-code works to compile and link with mingw. With the unencrypted library it  works with OMEdit.

**Comment by adrpo** [comment]
Ah, the .lib file is inside the encrypted library? 
Ouch, if that is the case then we will need to unpack it someplace and give that place to the linker. 

I wonder how should the resources (tables, C code, libs) in an encrypted library should be handled, we need to check the specification to see if they say anything about it.

**Comment by niklwors** [comment]
Normal in this folder, only binary files are located.
Her is the part of the specification (3.3, 12.9.4 page 155)
```
The annotation(LibraryDirectory="modelica://LibraryName/Resources/Library"), used
to specify a location for library files. The preceding one is the default and need not be specified; but another
location could be specified by using an URI name for the library directory, see Section 13.2.3. Different
versions of one object library can be provided [e.g. for Windows and for Linux] by providing a “platform”
directory below the “LibraryDirectory”. If no “platform” directory is present, the object library must be
present in the “LibraryDirectory”. The following “platform” names are standardized:
o win32 [Microsoft Windows 32 bit]
o win64 [Microsoft Windows 64 bit]
o linux32 [Linux Intel 32 bit]
o linux64 [Linux Intel 64 bit]
```

**Comment by adrpo** [comment]
Yes, of course we know this, but how do you handle it if the binaries are inside an encrypted mol file?

**Comment by niklwors** [comment]
We can not handle this, that is why the libraries and dependencies cannot be found. I think OMEdit has to unpack these files.

**Comment by niklwors** [comment]
There is a workaround to copy these files to the lib/omc folder. Then the linker will find it.

**Comment by niklwors** [comment]
Also for #6242  is a workaround, to copy the dll's and database to the OMEdit working directory.

**Comment by casella** [comment]
I understand that compiled binaries are safe enough from the point of view of IP protection. That's part of the motivation of the success of FMI. If they are not compiled with debug symbols, that is, but that's none of our business, it is the responsibility of whomever provides the encrypted library to do so.

The only problem I see is if the user has a license to use only parts of a library and we decrypt _all_ the .lib files, because then you'll have access to all of them. Maybe we could figure out selectively which ones are used by the parts of the library that are accessible. But I guess without debug symbols and with no reference Modelica source code, they are not very useful anyway, so I'm not sure we should bother.

As we discussed already, Modelica library encryption is not meant to ensure military-grade security against highly valuable industrial secrets. It is only meant to make it inconvenient to pay the license fees, which are normally not particularly expensive. Why paying an expert hacker 5000 € to get some information out of an encrypted library, when you can buy a license for 1000 €, remaining legal and possibly getting proper assistance?

The big deal is the collective responsibility of the Modelica community, because the security of encrypted libraries is bound to the weakest link of the chain. But that is another story.

**Comment by adrpo** [comment]
To support this, OMEdit would need to unpack the entire library, excluding the .mo files into a temp directory `path/to/temp/LibraryName/everyting_here` and then map the `modelica://LibraryName/inside/lib` to `path/to/temp/LibraryName/inside/lib`.

**Comment by niklwors** [comment]
Maybe we can also write a script that copies all dependencies. The user can call it before he uses the library for the first time. But I don't how to get the paths for OpenModelica installation and the OMEdit working directory.

**Comment by adrpo** [comment]
For the installation path:
https://build.openmodelica.org/Documentation/OpenModelica.Scripting.getInstallationDirectoryPath.html
On Windows we still set OPENMODELICAHOME but not anymore OPENMODELICALIBRARY. 

For the Modelica libraries path (previous it was OPENMODELICALIBRARY, now it returns 2 paths):
https://build.openmodelica.org/Documentation/OpenModelica.Scripting.getModelicaPath.html

**Comment by niklwors** [comment]
We are trying to solve the problem by ourselves and can therefore close the ticket again

**Comment by niklwors** [comment]
I put the Resources folder outside the encrypted library and use the annotation 
```LibraryDirectory="modelica://BRSL/../Resources/Library" ```
 It works for the unencrypted library but for the encrypted version it searches in the temporary model folder:
```-LC:/Users/.../AppData/Local/Temp/OpenModelica/OMEdit/BRSL20210713164249060/BRSL/../Resources/Library/win64" ```
Can we add also the model folder extended with the librarydirector  annotation to the linker path?

**Comment by niklwors** [comment]
We could solve this problem by unzip the mol archive and add the Resources folder in it.
