### ISSUE TITLE
Small additional delay in Modelica.Clocked.Examples.CascadeControlledDrive.SubClocked model

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7852]
Please check the verification results of `Modelica.Clocked.Examples.CascadeControlledDrive.SubClocked` with the [C runtime](https://libraries.openmodelica.org/branches/master/Modelica_trunk/files/Modelica_trunk_Modelica.Clocked.Examples.CascadeControlledDrive.SubClocked.diff.html) and [cpp runtime](https://libraries.openmodelica.org/branches/master/Modelica_trunk_cpp/files/Modelica_trunk_cpp_Modelica.Clocked.Examples.CascadeControlledDrive.SubClocked.diff.html).

The results are identical with the two runtimes, and it appears to be an additional delay of 2 ms of [PI.y](https://libraries.openmodelica.org/branches/master/Modelica_trunk/files/Modelica_trunk_Modelica.Clocked.Examples.CascadeControlledDrive.SubClocked.diff.PI.y.html) with respect to the reference results, which is apparent if you zoom in the first 0.1 s of the simulation results: PI.y starts growing at time = 0.012 instead of 0.01, and then always changes 2 ms later.

What is weird is that I just simulated the same model in OMEdit 1.18.0-beta.2 and this additional delay is not present there. I have no idea what could be different between the simulation I am running manually and the one ran by the test scripts.

@sjoelund, @adrpo, @rfranke, any idea?

**Comment by rfranke** [comment]
It was me who introduced this with commit 573e955a083648a2c96dbb3635d280d22ca12d96 after I had solved a bug with subclock dependencies defined with clock variables with commit 6284e4c227605e0338dc613c36760bb49f2ee0ac.
By chance my simple resolution of a circular subclock relationship lead to the wrong evaluation order for this example ...

**Comment by casella** [comment]
@rfranke, you commit came after branching 1.18.0 and was not cherry-picked, so there's no need to port it to 1.18 maintenance, right?

**Comment by rfranke** [comment]
Right. The two commits mentioned above and #7858 basically fix sub-clock relations for event clocks, along with fixes to their treatment in the Cpp runtime. This makes one more example verify, compared to 1.18: `Modelica.Clocked.Examples.Elementary.ClockSignals.RotationalSample`.

Unfortunately the similar `Modelica.Clocked.Examples.Elementary.ClockSignals.LogicalSample` is still open. With cos() instead of sin() it fulfills an event clock condition at initialization time, triggering the clock in the reference results immediately after initialization. If MA will decide that the reference results set the standard then we might need to extend the initialization of event clocks, see https://github.com/OpenModelica/OpenModelica/issues/7842#issuecomment-911170421.

Anyhow, good that you identified the small delay as reason for the failed verification of `Modelica.Clocked.Examples.CascadeControlledDrive.SubClocked.PI.y`!

**Comment by casella** [comment]
> Unfortunately the similar `Modelica.Clocked.Examples.Elementary.ClockSignals.LogicalSample` is still open. With cos() instead of sin() it fulfills an event clock condition at initialization time, triggering the clock in the reference results immediately after initialization. If MA will decide that the reference results set the standard then we might need to extend the initialization of event clocks, see [#7842 (comment)](https://github.com/OpenModelica/OpenModelica/issues/7842#issuecomment-911170421).

It seems the discussion on that ticket has stalled, and I'm afraid it won't go anywhere. Is there anything I can do to revive it?

**Comment by rfranke** [comment]
I'm afraid you can't do much. MA has stalled as a whole. See also:
- const qualifiers for inputs to external functions https://github.com/modelica/ModelicaStandardLibrary/issues/3839
- max of nothing (ModelicaTest.Math.TestMatrices3) https://github.com/modelica/ModelicaStandardLibrary/issues/3849
- verified result violating specified variable bounds https://github.com/modelica/ModelicaStandardLibrary/issues/3852
- and this one -- an event clock ticking because someone thinks so -- https://github.com/modelica/ModelicaStandardLibrary/issues/3858
