### ISSUE TITLE
Numerical overflow due to replacement of 1/tanh with cosh/sinh

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#8005]
Some load models of the PowerSystems library adapt the load to make it independent of voltage. For instance `PowerSystems.AC3ph.Loads.PQindLoad` states:
```modelica
  der(Z) = (pq/(pq*pq)*v2 * tanh(imax)/tanh(imax/V2_nom*v2) - Z) / tcst;
```
Only `Z` and `v2` are time varying, whereas all other variables are parameters. OpenModelica replaces this with:
```modelica
  der(Z) = (pq/(pq*pq)*v2 * tanh(imax)*cosh(imax/V2_nom*v2)/sinh(imax/V2_nom*v2) - Z) / tcst;
```
During the solution of the example `PowerSystems.Examples.AC3ph.Inverters.InverterToLoad` with DASSL it happens that `v2` takes large values leading to an overflow of `sinh`. [See the respective error message](https://libraries.openmodelica.org/branches/master/PowerSystems_latest/files/PowerSystems_latest_PowerSystems.Examples.AC3ph.Inverters.InverterToLoad.sim) (`sinh(...)` becomes `$cse11`):
```
assert            | debug   | division leads to inf or nan at time 0.00374999, (a=inf) / (b=inf), where divisor b is: (pqLoad.pq[1] ^ 2.0 + pqLoad.pq[2] ^ 2.0) * $cse11
```
The overflow would not happen with `tanh` stated in the model as it is limited by 1. See e.g. https://en.wikipedia.org/wiki/Hyperbolic_functions:
<img src="https://user-images.githubusercontent.com/4224368/137583803-5285d5a8-dee1-454d-8cd4-32284dc2d3ef.png" width=40% height=40%>

**Comment by perost** [comment]
The code responsible for this is (note that the comment on the first line is wrong compared with what the code actually does):
https://github.com/OpenModelica/OpenModelica/blob/28cd7de5b1108da344dde3697bc2c70fcfeb490c/OMCompiler/Compiler/FrontEnd/ExpressionSimplify.mo#L4786-L4792

I'm not sure what the purpose of this simplification rule is since it makes the expression bigger. Perhaps it enables further simplifications in some cases, but not in this case.

**Comment by rfranke** [comment]
This appears to go back to work by @vruge in 2014 first introducing `e1/tanh(e2) => e1*coth(e2)`
(https://github.com/OpenModelica/OMCompiler/commit/aa6621ccb638e3f44f15927ec3b6813f74677e14#diff-ba1b057b0ef11a721e80efc8709c6292974534491031177e8146309998c52648)
and then changing to `e1/tanh(e2) => e1*cosh(e2)/sinh(e2)`
(https://github.com/OpenModelica/OMCompiler/commit/269a95a6989f32b5a4cd28fde97ecd6b105a5b6f#diff-ba1b057b0ef11a721e80efc8709c6292974534491031177e8146309998c52648).

I think that this rule should be removed.

**Comment by sjoelund** [comment]
The first two make a lot of sense though. You remove divisions by zero at least

**Comment by rfranke** [comment]
Commit a2907a19b0be5636771efc31f10a1950c1977c77 fixes the first two.

**Comment by casella** [comment]
I completely agree that the simplification rule` tanh(x) -> sinh(x)/cosh(x)` is not a good idea, because of overflow. sinh(x) and cosh(x) grow exponentialy, while tanh(x) doesn't. Furthermore, tanh(x) is often used as a way to approximate step(x) with a smooth, analytic function, so it is quite likely that its arguments becomes quite large.

I would definitely suggest to remove that rule. @rfranke, can you take care of that?
