### ISSUE TITLE
New feature: obfuscated Save Total

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8067]
We need to support the following use-case, which is going to show up more and more in the future.

Company A is a member of OSMC. Company B is a customer of company A and develops confidential systems models with the help of A. At some point something goes wrong with the compilation or simulation of some of B's confidential models in OpenModelica, and we need OSMC affiliated personnel to look into it for debugging.

Ideally, company A manages to prepare a simple MWE that reproduces the problem, without any confidentiality issues. This can be put in a public ticket, to which OMC's developers have full access. There are no IP or confidentiality issues.

In some cases, however, reproducing the problems with MWEs is not possible, so companies A and B need to share the full confidential model with the OSMC developers to figure out what's wrong with OMC and fix it. Currently, this requires the OSMC to sign an NDA  with company B. This subjects the OSMC to potential liability in case confidential information leaks for any reason.

One strategy to avoid any confidentiality issues is to provide a feature to generate obfuscated models, that allow to reproduce the issue, while making it impossible to reverse-engineer the models and the libraries. This is how I would do that:

1. Use the Save Total feature to get rid of anything that is not strictly necessary up front
2. Remove all the comments from the code
3. Remove all Documentation annotations from the code
4. Remove all graphical annotations from the code
5. Replace all class names and component references with (short) random strings, generating a "Rosetta stone" text file with all correspondences between the original names and the new random names
6. (optional) remove all whitespace

At the end of this treatment, omc can still compile the code and obtain the same runtime code (except for those issues that depend on the lexicographical ordering of variables by their names). However, the obtained code is not human-readable and pretty much useless for any other purpose than debugging the reported issue. To this aim, the bug reporter can point out some specific obfuscated variables or type names that have problems, using the Rosetta-stone file to figure out their names.

In most cases, such code can be safely passed to OSMC personnel directly by company B, without the need for the OSMC to sign an NDA, because company B  understands well that such a code cannot be exploited maliciously for reverse-engineering, at least not with a reasonable effort.

@adrpo, @AndreaBartolini, what do you think? @perost, would this be difficult to implement in the front-end?

**Comment by perost** [comment]
It wouldn't be particularly hard to implement. Stripping things is pretty trivial, and replacing names is easy as long as you don't require that elements with the same name are mapped to different obfuscated identifiers (which would only make it a tiny bit harder to reverse-engineer anyway).

**Comment by AndreaBartolini** [comment]
I think that in order to increase the data protection during the model transfer from/to A/B and OSMC developers it can be useful to provide encription methods to be applied to the files that have to be transmitted.
It has to be investigated how manage the encription keys in a safe way.

**Comment by perost** [comment]
> I think that in order to increase the data protection during the model transfer from/to A/B and OSMC developers it can be useful to provide encription methods to be applied to the files that have to be transmitted. It has to be investigated how manage the encription keys in a safe way.

We have instructions on how to encrypt using PGP [here](https://trac.openmodelica.org/OpenModelica/wiki/PgpInstructions). But I think the issue here is more about possibly avoiding having to sign an NDA rather than the safe transfer of confidential models.

**Comment by casella** [comment]
> It wouldn't be particularly hard to implement. Stripping things is pretty trivial, and replacing names is easy as long as you don't require that elements with the same name are mapped to different obfuscated identifiers (which would only make it a tiny bit harder to reverse-engineer anyway).

That's not required. In fact, we could probably implement this in Python as a post-processing step to be applied to the Save Total model. However, that would require to implement a (tiny) parser, maybe it's faster if you do it on the NF side?

Regarding encryption, I also think this is an orthogonal functionality, there is no need to embed this in OMC.

**Comment by perost** [comment]
I'm working on implementing this, but I wonder whether we should whitelist or blacklist annotations. I'm currently blacklisting, and this is what I have so far:
```Modelica
  function isAllowedAnnotation
    input String name;
    output Boolean allowed;
  algorithm
    allowed := match name
      case "Icon" then false;
      case "Diagram" then false;
      case "Dialog" then false;
      case "IconMap" then false;
      case "DiagramMap" then false;
      case "Placement" then false;
      case "Text" then false;
      case "Line" then false;
      case "defaultComponentName" then false;
      case "defaultComponentPrefixes" then false;
      case "missingInnerMessage" then false;
      case "obsolete" then false;
      case "unassignedMessage" then false;
      case "Protection" then false;
      case "Authorization" then false;
      else true;
    end match;
  end isAllowedAnnotation;
```
The issue with blacklisting is that models might contain proprietary annotations that will not be removed if they're not in the list. Whitelisting instead has the opposite problem that we might remove something that's needed to replicate an issue. I'm not sure which is better, any opinions?

**Comment by adrpo** [comment]
Just blacklist any annotation starting with "__".

**Comment by casella** [comment]
I agree with @adrpo, blacklist everything you wrote in [your comment](https://github.com/OpenModelica/OpenModelica/issues/8067#issuecomment-961981273), plus all annotations starting with `__`. 

If anybody uses nonstandard annotations without the __ prefix, that's their problem 😄 

Thanks!

**Comment by sjoelund** [comment]
Also blacklist __OpenModelica?

**Comment by casella** [comment]
Of course 😄

**Comment by casella** [comment]
Seriously, it depends. It could be annotations that influence the solution process...

**Comment by perost** [comment]
The initial implementation is now done, see #8103. It might need some tweaking, but the basic functionality should be done at least.

I implemented it by adding a new option `obfuscate` to saveTotalModel, so it can be called like for example:
```Modelica
saveTotalModel("BranchingDynamicPipes.mo",
  Modelica.Fluid.Examples.BranchingDynamicPipes, obfuscate = true);
```
This will save the obfuscated model to the given filename, `BranchingDynamicPipes.mo` in this case, and the mapping from original names to obfuscated names in `BranchingDynamicPipes_mapping.json`. I choose JSON since it's as good a format as any for a simple table like this, and having it in JSON format could be useful. It looks like this:
```
{
  "A": "n511",
  "AConBou": "n1516",
  "AConExt": "n1504",
  "AConExtWin": "n1508",
  "AConExtWinFra": "n1682",
  ... and so on
}
```

As for the obfuscation itself I obfuscate pretty much all names except for builtin ones. I also obfuscate assert/terminate message by hashing them (just to get something that's likely unique so one can search for them), so they become e.g.:
```Modelica
assert(n1097, "assert message 7541075014346074783");
```
It would've been nice if we could obfuscate all strings since they often contain details about the models, but we can't know which ones we can change without affecting the model.

Something I think we could remove without affecting the simulation is the quantity/unit/displayUnit attributes, right now it's sometimes pretty obvious what the original element was:
```Modelica
type n589 = Real(final quantity = "Length", final unit = "m");
```
In some cases we might want to keep them though, so I'm not sure what the best way to deal with this is.

We also have external functions, where we currently obfuscate the name of the function itself but not the name of the called external function or things like include directives. This could potentially be quite sensitive information, but the model might also not work without it.

**Comment by perost** [comment]
@adeas31: I guess we should also add support for this in OMEdit. One option is to add another menu option to the File menu, "Save Obfuscated" or something.

Another would be to change "Save Total" from a simple file dialog to a dialog where the user can select the options to use. Besides the new `obfuscate` option we also have `stripAnnotation` and `stripComments`, but I'm not sure how useful those are for users.

**Comment by casella** [comment]
@perost, stripping comments is essential, but I understand this was already supported. What about stripping annotations? We already discussed that we need to get rid of documentation and graphical annotation, but not of experiment or OMC vendor-specific ones. Is that implemented like that already?

In any case, if you really want to obfuscate, you also need to strip annotations and comments, so I guess having all these choices is not that useful. Just Save Total and Save Total Obfuscated might do.

**Comment by perost** [comment]
@casella: Sorry if I was unclear, `stripAnnotations` and `stripComments` are old options for `saveTotalModel` that we've had for years (though I'm probably the only one using them for the purpose of creating MWEs). The `obfuscate` option on the other hand always removes all comments and specific annotations (`stripAnnotations` removes all annotations).

So the obfuscation already does point 1 to 5 that you suggested. I did not implement point 6 (removing whitespace) since that can be trivially defeated by just loading the model and doing a new save total (which prettyprints the classes).

My point was just that if we go with a dialog where the user can choose the options we might as well also show the old options, since there's no way to use those in OMEdit at the moment. But this is not very important since I'm the main user of them, and I don't use OMEdit for that. The File-menu in OMEdit is already quite cluttered though, so it might be nicer to have a separat dialog for save total with the option to obfuscate than to add yet another entry to it for obfuscation.

**Comment by perost** [comment]
Also, my PR is not yet merged due to what seems to be some bootstrapping issue. I'll fix it tomorrow.

**Comment by casella** [comment]
> @casella: Sorry if I was unclear, `stripAnnotations` and `stripComments` are old options for `saveTotalModel` that we've had for years (though I'm probably the only one using them for the purpose of creating MWEs). The `obfuscate` option on the other hand always removes all comments and specific annotations (`stripAnnotations` removes all annotations).

OK, all clear now.

> So the obfuscation already does point 1 to 5 that you suggested.

Good.

> I did not implement point 6 (removing whitespace) since that can be trivially defeated by just loading the model and doing a new save total (which prettyprints the classes).

Sounds reasonable. In fact, we are not try to defend ourselves from sophisticated attacks (we're not talking about nuclear secrets or anything like that), just to provide a reasonable amount of confidentiality and of protection against reverse-engineering.

> My point was just that if we go with a dialog where the user can choose the options we might as well also show the old options, since there's no way to use those in OMEdit at the moment. But this is not very important since I'm the main user of them, and I don't use OMEdit for that. The File-menu in OMEdit is already quite cluttered though, so it might be nicer to have a separate dialog for save total with the option to obfuscate than to add yet another entry to it for obfuscation.

I'm fine with a separate dialog for Save Total, with three checkboxes (all unchecked by default):
- obfuscate output
- strip all annotations
- strip comments

Then we can explain more in detail what they do in the online documentation.

@adeas31 can you please take care of that?

Thanks!

**Comment by perost** [comment]
It took a while due to lots of things going wrong at the same time, but #8103 is now finally merged.

**Comment by casella** [comment]
Great!

@AndreaBartolini please try out and report.

**Comment by casella** [comment]
@perost, we will probably also need this feature in relation to the use of encrypted models. If a model M includes instances of encryped classes, could you selectively obfuscate them during flattening, so that it is not possible to reverse-engineer the models with the debugger or by looking at the C source code?

**Comment by perost** [comment]
> @perost, we will probably also need this feature in relation to the use of encrypted models. If a model M includes instances of encryped classes, could you selectively obfuscate them during flattening, so that it is not possible to reverse-engineer the models with the debugger or by looking at the C source code?

We can easily obfuscate selected models, the tricky bit is changing the references to those models in the rest of the model. That can't be done with a simple string->string table like the obfuscation is using right now, since you typically have elements with the same name in many different scopes. I guess the NF would need to keep a translation table for each encrypted class in order to transform references on the fly while instantiating a model.

**Comment by casella** [comment]
Yes, that was more or less what I had in mind 😃

**Comment by casella** [comment]
I tried the new Obfuscated Save Total on a non-trivial model. Worked like a charm, and the obfuscation seems quite effective. Thanks @perost and @adeas31 for the nice job!
