### ISSUE TITLE
a - floor(a) <0 on a step in a

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#8090]
Hello,

### Description
The problem is that I calculate a - floor(a) when a is the result of a modulo operation. a therefore has steps. On a step, floor(a) does not match the actual a value and the difference a - floor(a) is negative. This is mathematically impossible.

### Steps to reproduce
Plot signals b, c, and d generated with the model below:
Example :
```model testfloor
Real a, b, c ,d;
initial equation
a=-1;
equation
der(a)=10;
b = 2+mod(a-2,4);
c=floor(b);
d=b-floor(b);

end testfloor;
```
The result is:
![image](https://user-images.githubusercontent.com/59084059/140295648-c8ddbbb3-5d41-4b21-8383-5958cd233521.png)

### Expected behavior
Expected behaviour is this, generated with the same model in Dymola:
![image](https://user-images.githubusercontent.com/59084059/140296071-eaeb9169-d395-410b-94d1-8947b1df4c12.png)

### Version and OS
 - OpenModelica Version 1.18.0
 - OS: Windows 10, 64 bit

Best regards,
Paul van der Hulst

**Comment by casella** [comment]
I tried to run the same model but switching off the equidistant time grid output flag
```Modelica
model testfloor
  Real a, b, c ,d;
initial equation
  a=-1;
equation
  der(a)=10;
  b = 2+mod(a-2,4);
  c=floor(b);
  d=b-floor(b);
annotation(
    __OpenModelica_simulationFlags(lv = "LOG_STATS", noEquidistantTimeGrid = "()"));
end testfloor;
```
This is the result:
![immagine](https://user-images.githubusercontent.com/4233148/140585045-ec3896e5-bb79-4988-a917-6a26801636a9.png)

The fact that a data point for `b` at 0.3 is not generated by the equidistant time grid output communication makes it clearer what the problem is: one would expect to see `b` growing until it reaches a value of 6, then being reduced to 2 after the event generated by mod() has been processed. It seems to me that the way we currently handle the events is such that the event triggered by floor() somehow masks it.

@AnHeuermann, @kabdelhak, @phannebohm, what do you think?

**Comment by AnHeuermann** [comment]
>  It seems to me that the way we currently handle the events is such that the event triggered by floor() somehow masks it.

If an event was found we should save the pre-value of `b` in the result file, do the event iteration and than save the value of `b` after that event.
```
LOG_EVENTS        | info    | status of relations at time=0
LOG_EVENTS        | info    | status of zero crossings at time=0
|                 | |       | | [1] (pre:  0) -1 = mod(a - 2.0, 4.0, 0)
|                 | |       | | [2] (pre:  0) -1 = floor(b, 2)
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_EVENTS        | info    | state event at time=0.1
|                 | |       | | [2] floor(b, 2)
LOG_EVENTS        | info    | state event at time=0.2
|                 | |       | | [2] floor(b, 2)
LOG_EVENTS        | info    | state event at time=0.3
|                 | |       | | [2] floor(b, 2)
|                 | |       | | [1] mod(a - 2.0, 4.0, 0)
LOG_EVENTS        | info    | state event at time=0.4
|                 | |       | | [2] floor(b, 2)
LOG_EVENTS        | info    | state event at time=0.5
|                 | |       | | [2] floor(b, 2)
LOG_EVENTS        | info    | state event at time=0.6
|                 | |       | | [2] floor(b, 2)
LOG_EVENTS        | info    | state event at time=0.7
|                 | |       | | [2] floor(b, 2)
|                 | |       | | [1] mod(a - 2.0, 4.0, 0)
LOG_EVENTS        | info    | state event at time=0.8
|                 | |       | | [2] floor(b, 2)
LOG_EVENTS        | info    | state event at time=0.9
|                 | |       | | [2] floor(b, 2)
LOG_EVENTS        | info    | state event at time=1
|                 | |       | | [2] floor(b, 2)
LOG_SUCCESS       | info    | The simulation finished successfully.
```

I guess the problem is that we are not having the pre-value of `m=mod(a-2,4)` even though it is triggering an event.
See for example
```modelica
model pre_modulo
  Real a (start=-1, fixed=true);
  Real m;
equation
  der(a) = 10;
  m = mod(a-2,4);
annotation(
    __OpenModelica_simulationFlags(lv = "LOG_EVENTS", noEquidistantTimeGrid = "()"));
end pre_modulo;
```
![image](https://user-images.githubusercontent.com/38031952/141776151-89e2688c-58a7-42fe-8751-5b083b09e092.png)

**Comment by AnHeuermann** [comment]
Apparently `m` will be changed to be 0 before we find the event. So the pre-value is already 0.

```
m(t=0.298000) = 3.980000
m(t=0.300000) = 4.000000
m(t=0.300000) = 0.000000
LOG_EVENTS        | info    | state event at time=0.3
|                 | |       | | [1] mod(a - 2.0, 4.0, 0)
```

But at the same time we do have the correct value of `m` at time `t=0.3`, but it is not saved as the pre-value, so it won't show up in the result file.
I guess we need to change [_event_mod_real](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/model_help.c#L1435-L1451) to use `_event_floor` instead of `floor`.
