### ISSUE TITLE
Internal error: NFConnection.split got unbalanced connection

### ISSUE THREAD

**Issue by arouhan** [OpenModelica/OpenModelica#8094]
Hello,
while building models with nested Buses (expandable connectors), I often get the following message:
[C:/OM118/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFConnection.mo:57:7-58:91:writable] Error: Internal error NFConnection.split got unbalanced connection.

Attached is a package example "internalError" with a model called "OpPro" which reproduces the error, using OME 1.18.0 and MSL 3.2.3. The package and model "OpPro" check ok under Dymola 2021. The model is incomplete and will not run.
While checking, error message is:

```
Error Buffer: 
[C:/OM118/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFConnection.mo:57:7-58:91:writable] Error: Internal error NFConnection.split got unbalanced connection connect(shSpC.bus, bus) (lhs: 2, rhs: 3) 
```
[InternalError.zip](https://github.com/OpenModelica/OpenModelica/files/7475476/InternalError.zip)

**Comment by casella** [comment]
@arouhan I can't see the attachment, did it get lost somehow?

**Comment by perost** [comment]
@casella: It was accidentally part of the code block, I fixed it.

**Comment by perost** [comment]
The issue could be simplified to this:
```Modelica
connector RealOutput = output Real;

expandable connector EC
  RealOutput x;
end EC;

expandable connector EC2
  EC ec;
end EC2;

expandable connector EC3
  EC2 ec2;
end EC3;

model ExpandableConnector8
  RealOutput x;
  EC3 ec1, ec2;
equation
  connect(ec1.ec2.ec.x, x);
  connect(ec1, ec2);
end ExpandableConnector8;
```
At first I wasn't sure if connecting two expandable connectors should be considered also connecting the expandable connectors in them, but after some debugging I realized we already handled exactly that case.

The actual issue was that we only did it one level instead of recursively, so it didn't work properly when having more than two levels of nested expandable connectors (I guess I didn't consider that anyone would be that crazy :smile:).

**Comment by casella** [comment]
@arouhan could you elaborate on the rationale of having expandable connectors within expandable connectors?

A flat expandable connector to me is a good metaphor for the signal database of a DCS system, which can easily accommodate thousands of signals in real life. Are you trying to go beyond that, so you really need expandability on multiple levels to manage complexity?

**Comment by arouhan** [comment]
@casella sure.  We are building a library of components able to handle complex systems, such a complete ship, including all its systems onboard. We could have used a flat expandable connector (i.e. all signals are all at the same level), then it would have been a mess to find the signals we are looking for, including potential naming conflicts. Using nested expandable connectors, allows to group signals by systems and/or dedicated engineering fields with hierarchical levels. It is far easier then to find the signals we want to look for. 
It is like having all photos in a single folder vs all photos sorted in various thematic folders. Easier to find when the number of photos is high. The depth level of the nested expandable connectors is not too high so that it is manageable to dig into the expandable connectors tree. 

Your thoughts/feedbacks on that topic is welcome.

**Comment by casella** [comment]
> @casella sure. We are building a library of components able to handle complex systems, such a complete ship, including all its systems onboard. 

Interesting.

> We could have used a flat expandable connector (i.e. all signals are all at the same level), then it would have been a mess to find the signals we are looking for, including potential naming conflicts. Using nested expandable connectors, allows to group signals by systems and/or dedicated engineering fields with hierarchical levels. It is far easier then to find the signals we want to look for. It is like having all photos in a single folder vs all photos sorted in various thematic folders. Easier to find when the number of photos is high. The depth level of the nested expandable connectors is not too high so that it is manageable to dig into the expandable connectors tree.

Sounds perfectly reasonable.

> Your thoughts/feedbacks on that topic is welcome.

If this is a requirement for some users of OMC, and since this is allowed by the specification, then we should make sure that we support this feature correctly. If you could supply some simple test cases that we could add to our testsuite, that would be welcome. Both working and problematic test cases are welcome: the former are useful to make sure they don't get broken by updates to the compilers, the latter to fix them.

@arouhan if you plan on using OMC for challenging projects, you may consider joining the [Open Source Modelica Consortium](https://openmodelica.org/home/consortium), to help supporting the tool development and get better support yourself.

@perost, in the meantime you could add the MWE above to the testsuite, if you haven't done it already.

**Comment by perost** [comment]
> @perost, in the meantime you could add the MWE above to the testsuite, if you haven't done it already.

The MWE is one of several new test cases I added.

**Comment by casella** [comment]
@arouhan please check the last comment in #7833
