### ISSUE TITLE
Homotopy CSV files should always be saved in the working directory

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8104]
### Description

After [66c2e0c](https://github.com/OpenModelica/OpenModelica/pull/6814/commits/66c2e0c93126baa105d2f8d3ccd9c581adcad4b5), the CSV file with the homotopy trajectory dump is saved correctly to the working directory when `--homotopyApproach=globalEquidistant` (the default) is selected. 

The same fix should be also applied to the other modes of [--homotopyApproach](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-homotopyapproach), otherwise the file is dumped to an unknown location and cannot be retrieved for inspection.

**Comment by AnHeuermann** [comment]
I'll fix it.

**Comment by AnHeuermann** [comment]
As far as I can see we simply don't generate a CSV file for other types of `--homotopyApproach`, only for equidistant global homotopy.

I'll add a pull request where whenever `LOG_INIT_HOMOTOPY` is activated a CSV file for homotopy will be generated.

**Comment by AnHeuermann** [comment]
Okay, apparently we do generate CSV files for the different approaches, but apparently in a completely different location.

I started unifying the code that generates the CSV files but in the end it takes to much time and just using the correct folder is only a tiny change.

@casella Are you able to test my branch? Otherwise we can merge the PR and if there are still CSV files missing in the working directory I'll finish my unification of the logging code.

**Comment by casella** [comment]
> Okay, apparently we do generate CSV files for the different approaches, but apparently in a completely different location.

Indeed, yesterday I got `TestTornHomotopy_nonlinsys0_adaptive_global_homotopy_pos.csv` in the main working directory.

> I started unifying the code that generates the CSV files but in the end it takes to much time and just using the correct folder is only a tiny change.

Yeah, don't waste too much time on this.

> @casella Are you able to test my branch?

Not really. Please go ahead with merging the PR.

**Comment by AnHeuermann** [comment]
Can we close this issue?

**Comment by casella** [comment]
I'd like to check it on the next OMEdit nightly first. Have you tried that out already? If so, please close it yourself

**Comment by casella** [comment]
I checked `--homotopyApproach=adaptiveGlobal`. The file is correctly saved in the working directory of the specific simulation. However, I had to set the -homotopyOnFirstTry flag to actually get the homotopy-based initialization to work in that case, otherwise it was skipped.

At some point we decided to make `-homotopyOnFirstTry = true` by default, but maybe that was only done for `equidistantGlobal` homotopy?

**Comment by AnHeuermann** [comment]
> At some point we decided to make -homotopyOnFirstTry = true by default, but maybe that was only done for equidistantGlobal homotopy?

To be honest, the code in the homotopy initialization is a total mess. We use so many if cases, boolean switches and pre-processor directives that it is nearly impossible to read.
And that is only part of the code, some is placed in the non-linear homotopy solver. 

So I would say this issue is solved and we should open a new ticket to clean up the homotopy methods used in the runtime.
Reducing the number of options and using some automation to figure out what should be done would be great, but difficult and taking time. We simply have to many options for this to be of any use for any non-hardcore user of OpenModelica.
