### ISSUE TITLE
OMEdit setExtendsModifierValue error for replaceable model

### ISSUE THREAD

**Issue by rvjmaeff** [OpenModelica/OpenModelica#8129]
### Description
When extending a model that has a model that contains a replaceable model, using the parameter dialog to replace the model results in the following error:

`Unable to set the extends modifier value using command setExtendsModifierValue(extendedModel, Model, replaceableModel $Code(=redeclare replaceableModel model))`

### Screenshots
![image](https://user-images.githubusercontent.com/40508824/141665520-9e8fddc6-0416-4589-8129-e31bf64d0f58.png)

### Additional files
[TestExtendsModifierValue.zip](https://github.com/OpenModelica/OpenModelica/files/7533096/TestExtendsModifierValue.zip)

### Version and OS
 - OpenModelica Version 1.18.0~28-g8996052
 - Ubuntu 20.04.3 LTS

### Steps to reproduce
Here is a test package.

```mo
package TestExtendsModifierValue
  partial model baseProperty
    parameter Real density;
  end baseProperty;
  
  model simpleProperty
    extends baseProperty(density=1);
  end simpleProperty;
  
  model propertySettings
    replaceable baseProperty property constrainedby baseProperty annotation(choicesAllMatching=true);
  end propertySettings;
  
  // Can successfully change the baseProperty of settings in parameter dialog.
  partial model partialSystem
    replaceable propertySettings settings annotation(Placement(visible = true, transformation(origin = {-90, 90}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
    Real x;
  initial equation
    x=10;
  equation
    der(x) = -settings.property.density * x;
  end partialSystem;
  
  // Unable to set the extends modifier value using command setExtendsModifierValue(TestExtendsModifierValue.actualSystem, TestExtendsModifierValue.partialSystem, settings.property, $Code(=redeclare TestExtendsModifierValue.simpleProperty property))
  model actualSystemFails
    extends partialSystem;
  end actualSystemFails;
  
  // This is how it should edit the source when selecting the replaceable model in the parameter dialog.
  model actualSystemWorks
    extends partialSystem(settings(redeclare simpleProperty property));
  end actualSystemWorks;
   
end TestExtendsModifierValue;

```

**Comment by abuntrock** [comment]
I am adding my issue here because it is also related to the constrainedby keyword. To show my issue I modified the model "propertySettings" from @rvjmaeff to include a comment like: 

`
model propertySettings
  replaceable baseProperty property constrainedby baseProperty "TestComment" annotation(choicesAllMatching=true);
end propertySettings;
`

This comment is not displayed in the parameter dialog of the model "propertySettings". If i call the method getComponents like

`
getComponents(TestExtendsModifierValue.propertySettings)
`
the output 
`
{{TestExtendsModifierValue.baseProperty, property, "", "public", false, false, false, true, "unspecified", "none", "unspecified", {}}}
`

also indicates an empty comment.
For replaceable declarations without a constrainedBy keyword the comment is correctly shown.

Version and OS
    OpenModelica Version 1.19.2 and 1.21-dev
    Windows 10 64 bit


If i should rather open a new issue regarding the comment please let me know.
Aaron Buntrock

**Comment by abuntrock** [comment]
@casella Should I leave my comment here or would opening up a new issue be better for you?
