### ISSUE TITLE
Empty testmodel creates HUGE FMU

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#8160]
### Description

When testing creation of a simple FMU on Windows I noticed that the exported FMU is **huge** (around 9.5 MB for the zipped FMU and the dll is actually 36 MB). This must be a mistake. 

Just for comparison: on Linux the same FMU is 138kB and the lib file itself 368kB.

### Steps to Reproduce
Here the test source code for FMU generation:

```mo
model SimpleTest
    Modelica.Blocks.Interfaces.RealInput u;
    Modelica.Blocks.Interfaces.RealOutput y;
equation
  connect(u, y);
end SimpleTest;
```
Tested with OpenModelica 1.18 on Windows

**Comment by sjoelund** [comment]
If you use Linux and install mingw, you can create a Windows FMU with a more reasonable size...

**Comment by adrpo** [comment]
Everything is statically linked in Windows so the FMUs are rather large. Maybe you can strip the dll, I don't remember if we already do that.

Do you need to install OpenModelica to be able to run the FMU in other Linux box?

**Comment by sjoelund** [comment]
If we choose static FMU, it's still rather small. The Bouncing ball FMU from the testsuite is statically linked on like 6 platforms, includes the source code for everything and is like 1.5MB?

**Comment by dietmarw** [comment]
Thanks for the mingw hint. I get now the choice of: 
![image](https://user-images.githubusercontent.com/9332/142250657-f5b18fde-8cb5-4685-81de-43e07dedcb44.png)

I wonder what difference the i686 and x_86_64 platform is here.

@adrpo: I'm not looking for workarounds but was actually trying to point out that there is something strange going on with the FMU generation on Windows. Also the whole dynamic vs static linked option don't seem to do any difference (at least on Linux) and it's not really clear how that relates to the FMI standard.

**Comment by sjoelund** [comment]
i686 is 32-bit Windows

**Comment by dietmarw** [comment]
@sjoelund The Bouncing Ball FMU can not even be imported by OMEdit because of (a very old) reinit issue.

**Comment by sjoelund** [comment]
Importing FMUs only work with the old front-end, yes. I voted that it be removed, but others want to keep it... Just use OMSimulator to simulate FMUs

**Comment by dietmarw** [comment]
So you are saying that OMEdit is not fit to import FMIs? The OMSimulator does not seem to have a GUI, right?

**Comment by sjoelund** [comment]
https://www.openmodelica.org/doc/OpenModelicaUsersGuide/1.18/omsimulator.html#graphical-modelling there is a GUI in OMEdit for it

**Comment by dietmarw** [comment]
This is what I'm seeing on the latest nightly on Linux:
![image](https://user-images.githubusercontent.com/9332/142252620-82deae4b-4779-4df3-88e5-b370af9e7beb.png)

**Comment by sjoelund** [comment]
@adeas31 where did you hide OMSimulator? :)

**Comment by dietmarw** [comment]
So the SSP menu is actually the OMSimulator model?

**Comment by sjoelund** [comment]
Maybe. OMSimulator uses the SSP format to describe connections between FMUs. I suppose there documentation needs to be updated

**Comment by adrpo** [comment]
See https://www.openmodelica.org/doc/OMSimulator/master/html/OMEdit.html

**Comment by adrpo** [comment]
The nightly-build generates a 700kb FMU, i guess we fixed some things.

**Comment by dietmarw** [comment]
Looks like the documentation is in need of some synchronisation ;-) I think having a menu called OMSimulator is probably more user friendly than SSP

**Comment by adrpo** [comment]
Seems so, @adeas31, when did we switched from OMSimulator to the SSP menu?
I think is good with the SSP menu. SSP is a standard, OMSimulator is just a tool.
Maybe it should be called SSP/FMI.

**Comment by dietmarw** [comment]
OK so I guess the original issue with the size on Windows is fixed (can't verify since I don't use nightly on Windows). So this ticket can potentially be closed. 

Wrt OMSimulator and SSP there are several other issues.
  1. It is not intuitive to have to create a new SSP model in the "File-> New" menu in order to be able to use the SSP menu. It would make more sense to have the "New SSP Model" entry within the SSP menu
  2. It is **highly** confusing to have the "File --> Import --> FMU" option present if it is not really supported. 
  3. The Linux package of OMSimulator seems to be missing `OMSimulatorServer.py`:
```
/usr/bin/../bin/OMSimulatorPython3 /usr/bin/../share/OMSimulator/scripts/OMSimulatorServer.py --model=/tmp/OpenModelica_dietmarw/OMEdit//Test.ssp --endpoint-pub=tcp://127.0.0.1:41821 --logLevel=0 --option "--suppressPath=true"
python3: can't open file '/usr/bin/../share/OMSimulator/scripts/OMSimulatorServer.py': [Errno 2] No such file or directory
Simulation process failed. Exited with code 2.   
 ```

**Comment by dietmarw** [comment]
and 
 4. "Help --> OpenModelica TLM Simulator Documentation" does not work.

**Comment by dietmarw** [comment]
Actually the first three entries in "Help" don't work either.

**Comment by casella** [comment]
> Wrt OMSimulator and SSP there are several other issues.
> 
>     1. It is not intuitive to have to create a new SSP model in the "File-> New" menu in order to be able to use the SSP menu. It would make more sense to have the "New SSP Model" entry within the SSP menu

The rationale here is that OMEdit is a GUI for two integrated tools: OMC and OMSimulator, that both run in the background, and both can also be accessed through other interfaces, e.g. Python. OMC handles Modelica models, OMSimulator handles SSP model. Both are MA standards. If you are fine with this rationale, it makes perfect sense that you start working on a new SSP model, or load an existing one, from the File menu.

@lochel, maybe we should explain the architecture and rationale of the whole thing in the user's guides. What do you think?

>     2. It is **highly** confusing to have the "File --> Import --> FMU" option present if it is not really supported.

There are two possible ways one can use FMUs.

One is to simulate an individual FMUs, or multiple connected FMUs in an SSP model. The tool that does that is OMSimulator.

The other is to have a structured Modelica model where one (or more) block(s) somewhere are not implemented in Modelica but with a model exchange FMU. Import FMU is meant for that purpose. IMHO this use case is not covered well by OMSimulator, at least if the FMU blocks are not at the top level of the Modelica model. I asked several times to those that want to remove this feature how could OMSimulator solve this use case nicely, but so far I did not get much feedback 😃 

I don't use FMI much myself, but there are OpenModelica users that do need this feature, for whom the current level of support is better than nothing, and for whom OMSimulator is simply not a good substitute.

That said, the import feature has issues, and we should resolve them. This is a matter of time and priorities. @dietmarw if you have some applications where this feature is useful and you'd like better support, please let us know and we'll see what we can do.
 
>     3. The Linux package of OMSimulator seems to be missing `OMSimulatorServer.py`:

This should of course be fixed, see #8163.

@dietmarw, as a general rule, I would really recommend to open one separate ticket for each issue, so that each one can be assigned to somebody and properly tracked. A laundry list of disparate issues on the 20th comment of a ticket with subject "Empty testmodel creates HUGE FMU" has a very low chance of ever being addressed.

> 4. "Help --> OpenModelica TLM Simulator Documentation" does not work.

It works for me, under Windows: my default PDF reader (Sumatra) opens with the guide of TLMSimulator. @dietmarw, maybe there is some problem under Linux with the definition of the default pdf viewer? Would you please mind opening a ticket about that, specifying a bit more details about your installation? 

> Actually the first three entries in "Help" don't work either.

Ditto. Probably also the default .html viewer is not defined properly.

**Comment by dietmarw** [comment]
@casella 
> That said, the import feature has issues, and we should resolve them.

Yes currently OMEdit can not even import the standard bouncing ball example. OMSimulator can. So I assumed that the import function is simply no longer supported in OMEdit and just forgotten to be taken out. 

You might want to think about how to properly display the two FMI options (direct import and SSP) in a way that makes it clear that there are two completely different approaches to it.

> @dietmarw, as a general rule, I would really recommend to open one separate ticket for each issue

I agree and sorry for hijacking this thread. 

> 4. "Help --> ...." does not work

See #8165. Not just a default viewer issue.

**Comment by casella** [comment]
> Yes currently OMEdit can not even import the standard bouncing ball example. OMSimulator can. So I assumed that the import function is simply no longer supported in OMEdit and just forgotten to be taken out.

As far as I understand, one major issue is how to handle reinit. Unfortunately the bouncing ball has it. On the other hand, most actual users of this feature don't need bouncing balls, but rather stuff such as regular nonlinear state-space systems or static input/output nonlinar maps. Those should be fine.
 
> You might want to think about how to properly display the two FMI options (direct import and SSP) in a way that makes it clear that there are two completely different approaches to it.

Absolutely. On the other hand, I'm a bit hesitant at highlighting this feature, since it is not so well supported.

> > @dietmarw, as a general rule, I would really recommend to open one separate ticket for each issue
> 
> I agree and sorry for hijacking this thread.

No problem 😃

**Comment by casella** [comment]
@dietmarw, all that being said, can we close this ticket?

**Comment by dietmarw** [comment]
I don't have the nightly on Windows so I can't really test it. But if @adrpo can confirm that it is fixed, that is good enough for me.

**Comment by dietmarw** [comment]
Just found this ticket from me again. Did the test with 1.21-dev and the size of the binary is now reasonable.
