### ISSUE TITLE
Copy Path with CTRL+C does not work

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OpenModelica#8181]
### Description and Steps to Reproduce

When I double click on a Modelica class in the Library Browser and hit CTRL+C, the fully qualified class name (path) is not copied to the clipboard. This can be checked by inserting the clipboard into a text editor hitting CTRL+V. If I instead make a right click on this class and select **Copy Path**,

![image](https://user-images.githubusercontent.com/4184218/142618946-e5af545b-9ae6-4b6f-8093-1582f7fdb518.png)

the fully qualified class name is copied to the cliopboard.

### Expected Behavior

CTRL+C should also copy the fully qualified class name to the clipboard as the context menu suggests

### Version and OS

- OpenModelica 1.19.0~dev-353-g257a47e
- Linux Mint 20.2 x86_64

This behavior is actually independent of the used library (version)

- MSL 3.2.3
- ElectroMechanicalDrives 2.4.0

**Comment by casella** [comment]
@christiankral, after you've double-clicked, the focus is no longer on the entry in the libraries browser, for some reason. Maybe @adeas31 can comment on why this is the case.

Anyway, if you want to copy and paste the class name, you have to click once on the model name in the libraries browser (so that it gets a blue background) , or click again after double-clicking, to get the focus back. Then, Ctrl-C does its job.

Please reopen if you really think the focus should stay in the Libraries Browser after double-clicking.

**Comment by adeas31** [comment]
> @christiankral, after you've double-clicked, the focus is no longer on the entry in the libraries browser, for some reason. Maybe @adeas31 can comment on why this is the case.

Yes the focus is changed to the opened Diagram view.

**Comment by christiankral** [comment]
OK then. As I now know how CTRL+C is correctly applied, I can live with it.
