### ISSUE TITLE
Public declarations are everywhere in Flat Modelica output

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8227]
Consider this simple example
```Modelica
model TestFlattening
  Real x;
  Real y;
equation
  x+y = 0;
  x- y = 4;
end `TestFlattening;`
```

If I flatten it with `-f`, I get this output:
```Modelica
class 'TestFlattening'
  public Real 'x';
  public Real 'y';
public
equation
  'x' + 'y' = 0.0;
  'x' - 'y' = 4.0;
end 'TestFlattening';
```
There are `public` kewords everwhere in the declaration section. Although they are perfectly legal, they seem to me pretty useless. @perost, is there any specific reason for that?

I cc: @ennioquaglia for his information.

**Comment by perost** [comment]
For the variables it's just the easiest way (because each variable keeps track of its visibility), but it's not really that hard to do it smarter so I can fix that.

The empty public section is a bit more mysterious. It's not a bug, we just print it at the end of the variables for some reason. @sjoelund, any clue what that's about? The only things we print after the variables are equations and algorithms, and those are not affected by public/protected.

**Comment by casella** [comment]
> For the variables it's just the easiest way (because each variable keeps track of its visibility), 

Yeah, that's what I understood.

> but it's not really that hard to do it smarter so I can fix that.

That would be nice, but don't invest too much time on it.

> The empty public section is a bit more mysterious. It's not a bug, we just print it at the end of the variables for some reason. @sjoelund, any clue what that's about? The only things we print after the variables are equations and algorithms, and those are not affected by public/protected.

Seems weird to me as well.

**Comment by sjoelund** [comment]
I'm not sure why that is. Might be some copy-pasta for some empty section of some kind? Maybe just some delimiter in Susan?

**Comment by casella** [comment]
I guess we can safely get rid of that

**Comment by casella** [comment]
Thanks!
