### ISSUE TITLE
Re-simulate interactive simulations (enhancement proposal)

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8303]
### Description
I see that interactive simulations do not allow re-simulating from OMEdit.

I don't understand the difficulties of allowing this. Maybe because all parameters are structural for interactive simulations?

Re-simulating may be useful for interactive simulations because if the simulation interacts with the external world through Modelica_DeviceDrivers (interaction with the user through keyboard or joystick, with the computers via serial or UDP communication, etc), each simulation is different from another. And this without having to change any model parameter.

In case allowing re-simulation also for interactive simulations is easy to implement, I would be glad to have it.

### Expected Behavior
This is an enhancement suggestion, not a bug report. What I expect is to be able to re-simulate interactive simulations from OMEdit 

### Version and OS
OM 1.18.0, Win10 64 bit

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@adeas31 is off, he'll have a look next year.

**Comment by max-privato** [comment]
Any news on this?
Probably it would require just removing a couple of rows of code, the rows that intercept pressing the re-simulate button when doing interactive simulations, and block everything.
In this case, it is just a matter of minutes to fix it.
Thank you!

**Comment by casella** [comment]
@adeas31 is this an easy fix? Thanks!

**Comment by max-privato** [comment]
Has anyone had a look at this?
I use this feature every day, many times per day, and I must continuously recompile the same model (without any modification) just to run it...

**Comment by casella** [comment]
@adeas31 can you please have a look once the 1.19.0 release is done? Thanks!

**Comment by adeas31** [comment]
How do you want re-simulation to work in this case? Since interactive simulation keeps the process running so if we want to do re-simulation then we need to run another instance of the simulation executable which can cause issues because of sharing the same resources (e.g., reading/writing to the same files). So maybe we can allow re-simulation only when the user stops the interactive simulation.

**Comment by adeas31** [comment]
PR #11670 should allow re-simulation of interactive simulations. The only annoying thing is that whenever you try to re-simulate then the already plotted curves are removed. That is because there is no way to preserve the state of the server. We start the interactive simulation again on re-simulate.
