### ISSUE TITLE
Log4J in OpenModelica1.18.0-64bit\share\jEdit4.5_VisualFigaro\jars\

### ISSUE THREAD

**Issue by supajo** [OpenModelica/OpenModelica#8321]
System: Windows 10 x64
Are we now vulnerable by the used Version "log4j-1.2.8.jar"?

**Comment by sjoelund** [comment]
That's log4j version 1, not version 2.

**Comment by supajo** [comment]
I hope you are right, because i have read it several times that it is still a risk in v1
https://snyk.io/blog/log4j-vulnerability-software-supply-chain-security-log4shell/

**Comment by sjoelund** [comment]
Anyway, it's only a problem if you use VisualFigaro, which is not present on Linux installations

**Comment by AnHeuermann** [comment]
Since log4j 1 reached end of live we could just remove VisualFigaro from OpenModelica and add it back once it is patched.

@sjoelund Would it be just removing https://github.com/OpenModelica/OpenModelicaBuildScripts/blob/408efd93354233b14513519fdc22bbdbcd06705d/windows/BuildWindowsRelease.sh#L120-L125 and uploading a new Windows version to https://openmodelica.org/download/download-windows?

@supajo On Windows it seems to be possible to just delete the directory `C:\Program Files\OpenModelica1.18.0-64bit\share\jEdit4.5_VisualFigaro`.
So user that are concerned don't need to wait for us or the VisualFigaro developers to update anything.
Of course export to Figaro won't work, but besides that I couldn't find anything that stopped working (but I didn't searched for long).

**Comment by sjoelund** [comment]
I have no clue about Windows-only stuff. I think @lenaRB or @adeas31 might have more of an idea.

**Comment by adrpo** [comment]
I'll have a look at this even if is not really a problem.

**Comment by adrpo** [comment]
Fixed for windows nightly-builds:
https://github.com/OpenModelica/OpenModelicaSetup/commit/71d28cdc0cbe3aafae02dceec36cbab8fa1507d6

**Comment by adrpo** [comment]
Fixed for windows 1.18:
https://github.com/OpenModelica/OpenModelicaSetup/commit/b2c4697c8c8ec8231f089c4fb58839052928d1a3
I will re-generate the 1.18 release on Windows to have this removed.

**Comment by adrpo** [comment]
This has been solved. The new nightly will not have VisualFigaro, the v1.18 release  has been re-generated without it.

**Comment by AnHeuermann** [comment]
The [stable development installer](https://build.openmodelica.org/omc/builds/windows/releases/1.18/dev.beta1/) was last modified on 2021-07-11 and contains Log4J, the [official release installer](https://build.openmodelica.org/omc/builds/windows/releases/1.18/0/) was last modified on 2021-12-18 but still contains 

I think we should use a new version number `v1.18.1` and add a notification to OMEdit news page and/or send an email over the newsletter to notify users.
And make sure that all version (official, stable, nightly and encrypted) are updated.

@adrpo Can you tell me how we build the Windows installer? Then I could have a look.
