### ISSUE TITLE
How to add new path in OpenModelica?

### ISSUE THREAD

**Issue by Amuri44** [OpenModelica/OpenModelica#8360]
I have an OpenModelica file in arbitrary path “path/to/simpleaddition.mo”, I load the model and simulate it from omshell. But the result files are shown in “C:\Users\user_name\AppData\Local\Temp\OpenModelica\”.

On the other hands, when I open the file “path/to/simpleaddition.mo” and simulate it from the OMEdit, the results are shown in “C:\Users\ user_name \AppData\Local\Temp\OpenModelica\OMEdit\simpleaddition”.

Can I change the path to let the results always shown in the same path of my “.mo” (i.e., “path/to/simpleaddition.mo”)?

**Comment by casella** [comment]
Yes, set the [-outputPath](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-outputpath) simulation flag when you run the simulation.

**Comment by Amuri44** [comment]
@casella 
Thanks for your reply. For example where to add this -outputPath if I run from omshell:
loadFile("path/to/simpleaddition.mo")
simulate(simpleaddition)
and from which tap, if I want to do the same from OMEdit?

**Comment by Amuri44** [comment]
> [-outputPath](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-outputpath)
@casella 
Thanks for your reply. For example where to add this -outputPath if I run from omshell:
loadFile("path/to/simpleaddition.mo")
simulate(simpleaddition, -outputPath="path/to/") # this gives an error
and from which tap, if I want to do the same from OMEdit?

**Comment by casella** [comment]
> > [-outputPath](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-outputpath)
> > @casella
> > Thanks for your reply. For example where to add this -outputPath if I run from omshell:
> > loadFile("path/to/simpleaddition.mo")
> > simulate(simpleaddition, -outputPath="path/to/") # this gives an error

The correct syntax for the simulate() API function is given [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#simulate). Since `-outputPath` is a simulation flag, you should use `simulate(simpleaddition, simflags="-outputPath=path/to/) `. If you have spaces in the path and you need to use quotations, you have to escape them, as in `simulate(simpleaddition, simflags="-outputPath=\"path/to/\"")`

> > and from which tap, if I want to do the same from OMEdit?

In OMEdit, Simulation Setup | Simulation Flags, put -outputPath="path/to/" in the Additional Simulation Flags field. This can be saved as an annotation in the model if you tick the appropriate checkbox
