### ISSUE TITLE
Can the results of system() be shown directly in the workspace of omshell?

### ISSUE THREAD

**Issue by Amuri44** [OpenModelica/OpenModelica#8363]
Hello,
I need to run the executable within for loop (i.e. time-step loop) and the results are needed to change some parameters for the next loop. So, generating the .mat results and reading it (i.e., bring the results into the omshell workspace) will consume sometime. Is there anyway to make running the executable generates the results in the workspace directly rather than in the .mat file?

**Comment by AnHeuermann** [comment]
I'm not sure that I get what you are asking. What do you mean by generating the results directly in the workspace rather than the .mat file?

Do you want to save the result file to a different location then the working directory of omc? In your case to the directory where you are working with omshell?

You can change the result file name (and its location) by adding the [simulation flag -s](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-r) something like
```
simulate(Modelica.Mechanics.Translational.Examples.Damper, simflags="-r=/absolute/path/to/Modelica.Mechanics.Translational.Examples.Damper_res.mat"); getErrorString();
```

-----

Or do you want to not write to disk but keep all results in memory? We have 3 ways to save results: CSV, MAT or TCP/IP.

I'm not sure if [OMPython](https://github.com/OpenModelica/OMPython) / [OMJulia](https://github.com/OpenModelica/OMJulia.jl) are saving the results to disk and then reading them or are actually getting the results directly via ZeroMQ/TCP. But maybe Python or Julia are better for your task.

There is some option to send simulation results via TCP/IP when omc is used interactive, see https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-interactive. So I guess that this is used for OMPython / OMJulia.

**Comment by Amuri44** [comment]
> I'm not sure that I get what you are asking. What do you mean by generating the results directly in the workspace rather than the .mat file?

I mean simulate() allow the results to be in the environment, so I can use val() directly, rather than val(varName, time, "resultFile.mat|csv")

**Comment by AnHeuermann** [comment]
I don't think this is currently possible with val. The [API call val()](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#val) will always read from a result file.
