### ISSUE TITLE
OMEdit Text visualisation glitch

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8383]
### Description

When we use a text box in diagram or icon, we can use the red squares to resize the allowable space. 
Text is expected to stay inside the four red squares. In the example below (file and screenshot), it is truncated in just a fraction of the allowable space (see screenshot below)

### Steps to Reproduce
Open Test.mo and select the text box in diagram view
[Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/7828821/Test.mo.txt)

### Expected Behavior
Text should use the space allowed by the two red squares

### Screenshots

![image](https://user-images.githubusercontent.com/37046832/148544639-58f57498-2a2c-4187-b78d-551ac7503775.png)

### Version and OS
OM 1.18.0 64 bit, Win10 

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@ceraolo, I'm not sure how this text box was set up originally, but if you right-click on it and select Properties, you get this dialog:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/a51821d6-0a0e-436b-bf75-df9858a9bd00)

The font and text style are set to use 10 points characters and left alignment, so that's what you get. If you want the text to fill in the available space, select font size Auto (which is the default when you create a text box), and you get this result:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/34a0d53c-e240-4e9e-8dda-baefaa5fbbcf)

If you resize the box, the text will fill in all the available space, e.g.:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/ca287a5f-92ab-4cc0-a3ba-4a0e0ea6604d)

**Comment by ceraolo** [comment]
> 
> The font and text style are set to use 10 points characters and left alignment, so _that's what you get_. 


I don't agree. As I wrote in the ticket's description, the whole space set by the red boxes should be filled. In the case of this ticket's image, there would be plenty of room to put more 10 pt charaters, instead of having all that empty space.

**Comment by casella** [comment]
No, if you have carriage return characters `\n` in the strings 😃

**Comment by ceraolo** [comment]
> No, if you have carriage return characters `\n` in the strings 😃

1) the third row is cut even though there would be enough space and it does not contain '\n'  (1st screenshot)
2) the second row is cut even when there would be enough space to display it  (2nd screenshot)
3) the third row is missing even if where is enough vertical space (2nd screenshot)

Screenshots: 
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/f66f6a89-fa81-440a-a53b-8eca80601e7d)
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/e824f929-5b72-4ced-a959-d8c3824bc290)

**Comment by adeas31** [comment]
We try to find the elided text and it is not possible to do it for multiline. The algorithm removes the `\n` and then tries to find the elide text on the whole string. Based on this what you get is the correct behavior.

I think we should not try to find the elided text if the string is multiline and font size is fixed.

**Comment by ceraolo** [comment]
good solution.
I personally use frequently multiline text, so this enhancement has a significant impact at least for me.

**Comment by adeas31** [comment]
Ported this to 1.22.1 #11655
