### ISSUE TITLE
apt-key deprecated

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8443]
### Description

`apt-key` is deprecated and will be removed. We are using `apt-key` in the Linux install process, see https://openmodelica.org/download/download-linux.

See https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html for a description on why `apt-key` is deprecated and what is now recommended to use.

From the [OpenModelica forum](https://openmodelica.org/forum/default-topic/3401-linux-install-procedure-apt-key-is-deprecated#p11265).

### Version and OS

 - OS: Linux

**Comment by casella** [comment]
@pierre-haessig reports that eliminating this dependency will be mandatory before at least Ubuntu 22.10.

**Comment by pierre-haessig** [comment]
> @pierre-haessig reports that eliminating this dependency will be mandatory before at least Ubuntu 22.10.

I would rather say that "apt-key will be available in Ubuntu until at least 22.04. It *may* be removed in 22.10 since the its man page says it *will*)". This becomes some kind of propositional logic game!

Following the same logic, apt-key may be removed from Debian testing (future 12 "bookworm") at any time, since Debian 11 "bullseye" was released. 

Source: [man apt-key from Ubuntu 21.10](https://manpages.ubuntu.com/manpages/impish/man8/apt-key.8.html)
>        apt-key(8) will last be available in Debian 11 and Ubuntu 22.04.

**Comment by casella** [comment]
Besides the philosophical digressions, I understand we have time until at least October 2022 to take care of this, right?

**Comment by pierre-haessig** [comment]
At least October 2022, yes. Sorry for digressing ;-)

**Comment by sjoelund** [comment]
Do the instructions on https://openmodelica.org/download/download-linux work now? I believe they should
