### ISSUE TITLE
Can I load Modelica of version 3.2.3. from the installed OpenModelica-v1.18.0-64bit?

### ISSUE THREAD

**Issue by Amuri44** [OpenModelica/OpenModelica#8448]
I have installed OpenModelica-v1.18.0-64bit. I tried to load a package from my colleague, then the below warnings appeared

```modelica
[1] 13:06:29 Scripting Notification
Automatically loaded package Complex 4.0.0 due to uses annotation.

[2] 13:06:29 Scripting Notification
Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.

[3] 13:06:38 Syntax Warning
[C:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/RR/Transformation.mo: 15:26-15:814]: Lexer treating \ as \\, since \d is not a valid Modelica escape sequence.

[4] 13:06:38 Syntax Warning
[C:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/RR/Transformation.mo: 15:26-15:893]: Lexer treating \ as \\, since \d is not a valid Modelica escape sequence.

[5] 13:06:38 Scripting Warning
RR requested package Modelica of version 3.2.3. Modelica 4.0.0 is used instead which states that it is only compatible with a conversion script. OpenModelica currently does not support conversion scripts and will proceed with potential issues as a result.
```
It seems that the package `RR` was built based on package Modelica of version 3.2.3, however, the package Modelica that I have is of version 4.0.0. So, can I load Modelica of version 3.2.3. instead of Modelica 4.0.0 from my installed OpenModelica-v1.18.0-64bit?

**Comment by sjoelund** [comment]
Yes, it should be loaded automatically unless you selected to load MSL 4.0.0 when starting for example OMEdit. Tools -> Options -> Libraries. Change Modelica from `default` or `4.0.0` to `3.2.3`

**Comment by casella** [comment]
Both 3.2.3 and 4.0.0 are **installed**. When you open a package that uses one of them and declares it with a uses annotation, then OMEdit loads the right one. 

The problem is that OMEdit can also automatically **load** and display a certain version of the Modelica Standard Library by default when you start it. If you load 4.0.0 by default, currently it cannot unload it and load 3.2.3, so you get stuck. If you have different projects, some using 3.2.3 and some using 4.0.0, you better avoid loading any by default, and have the loaded automatically when the packages relevant to the project you want to work on are opened.

1.19.0 should hopefully have a much better management; in this case, it would ask you if you want to unload MSL 4.0.0 and load 3.2.3 instead.
