### ISSUE TITLE
Unit multiples in plots should not be used when powers are involved

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8488]
Please run model S from the following MWE package
```modelica
package TestDisplayUnit
  model M
    parameter Modelica.Units.SI.VolumeFlowRate q0;
    Modelica.Units.SI.VolumeFlowRate q(displayUnit = "m3/h");
    Modelica.Units.SI.Length h;
  equation
    q = q0*(1+sin(10*time));
    h = 1-q^2;
  end M;

  model S
  M m(q0 = 1)  annotation(
      Placement(visible = true, transformation(origin = {8, 2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end S;
end TestDisplayUnit;
```
Plot variable `q`, which oscillates between 0 and 7200 m3/h. The values are reported in a derived unit (km3/h), which is of course wrong, as a flow rate of 7200 cubic meters per hour (a small creek or canal) is obviously not equivalent to 7.2 cubic kilometers per hour (maybe the Amazon river during the rain season...).

On the other hand, 7900 m/s (the speed of a circular LEO orbit) could be conveniently rendered as 7.2 km/s, while a speed of 1.2e-3 m/s could become 1.2 mm/s.

We could of course also manage powers correctly, but that is a non-trivial task that requires parsing the units when powers are involved. I would suggest a much simpler solution that yet avoids giving wrong results, namely to disable the automatic setting of multiple units if there are numbers (i.e. powers) in the displayUnit string.

**Comment by bilderbuchi** [comment]
Do you propose to scope this
> namely to disable the automatic setting of multiple units if there are numbers (i.e. powers) in the displayUnit string.

to only apply to the portions/dimensions that actually _have powers_ in the displayUnit string? 
Put differently, would e.g. volumetric quantities like "72000 J/m^3" still (usefully) become "72 kJ/m^3"?

**Comment by max-privato** [comment]
It is not difficult to make a good job:
1) single out the first unit of measure in 72000 J/m^3 it is J, in 7200 m^3/h it is m
2) see if immediately after it we have the "^" symbol (or a digit if m3/h is preferred)
3) use differently the prefix in the two cases. In case we don't have powers, prefixes are used ordinarily; otherwise they are adapted. So 7.2 kJ/m^3. But if, for instance, I have to put on the axis numbers that are in the "biillions of m^3" range, we could use km^3. If millions of m^2 we would use km^2.
This is quality. And does not require a huge effort to implement.

**Comment by casella** [comment]
My proposal:
- short term: disable unit prefixes if there are powers (i.e. numbers) in the unit string, _to avoid getting plain wrong units_. This is easy and should be done at once.
- medium term: re-enable them properly (requires parsing the unit and figuring out if the powers are at the numerator or denominator)

BTW, there are other cases that should be handled. For example, yesterday I simulated a gas turbine with OMEdit, and I got the turbine inlet temperature to be 1.1 k°C, instead of 1100 °C. This looked odd to me, I never saw k°C or M°C in my lifetime.  I'd say that we should disable automatic prefixes for °C

In fact, I would also find a bit weird to see the same temperature in 1.4 kK, i.e. 1400 K, even though this is perfectly legitimate according to the ISO definitions of SI units (note, °C is not an SI unit). I've seen mK though, when discussing extreme cryogenic temperatures for physics experiments.

**Comment by max-privato** [comment]
>(note, °C is not an SI unit)
Exactly so: there are non-IEC units that are widespread and that nobody would give them up. Other examples are  minutes, hours, days. Who talks about Ms?

So we could say that 1.1k°C is a legitimate as 1°C. I' strongly in favour of using it.

**Comment by max-privato** [comment]
>medium term: re-enable them properly (requires parsing the unit and figuring out if the powers are at the numerator or denominator)

BTW the medium term is more complicated than what I mentioned in my previous comment.

Consider a y axis having a span between 10 000 m^3 and 1000 000 m^3. How can one solve This?  Using as unit km^3 is out of the question since 10 000 m^3 is 0.00001  m^3. To make a very good job, in these cases one should use the prefix "da" so if dam^3 is used, the axes labels in these examples would be 10 and 100: ok.
An awkward solution, at a first sight, but also the most reasonable one, the modern symbology offers. I would be strongly in favor of going this way, if something is decided to be done.

But I agree that solving this m^3 case is more a curiosity than a real necessity. So the bottom line is, I think: implementing this dam^3 unit (and similar cases) or not depends on the programmers' curiosity!

If doing these niceties requires (as I suspect) just one day of activity, were I the programmer, I would deal with them. Postponing, for always-busy programmers, might well mean not-doing. But I repeat, there is not at all any strong need of doing it.
