### ISSUE TITLE
Array element assign in when algorithm does not work

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#8492]
## Description

All `tick` elements are -1.

### Steps to Reproduce

Simulate model:
```modelica
model SaveTime
  parameter Integer N = 10;
  Real tick[10](each start=-1, each fixed=true);
  Integer counter(start=1, fixed=true);
  Boolean b(start=false);
algorithm 
  b := sample(1, 2);
  when b then
    tick[counter] := time;
    counter := pre(counter) + 1;
  end when;
end SaveTime;
```

### Expected Behavior

```
tick[1] = 1;
tick[2] = 3;
tick[3] = 5;
...
```

### Version and OS

All.

**Comment by casella** [comment]
Adding @AnHeuermann, since he was involved in most clocked bug fixing recently, so he may have a clue.

**Comment by phannebohm** [comment]
This is not about clocked partitions, it is the normal [operator 3.23](https://modelica.org/documents/MLS.pdf#operatordefinition.3.23) right?

The problem is it's an algorithm where you set part of an array, so according to the [MLS](https://modelica.org/documents/MLS.pdf#subsection.11.1.2) the whole array gets set to its start value on each evaluation. If you want to keep the old values from the previous event, you may want to do something like this:
```modelica
model SaveTime
  parameter Integer N = 10;
  Real tick[10](each start=-1, each fixed=true);
  Integer counter(start=1, fixed=true);
  Boolean b(start=false);
algorithm 
  b := sample(1, 2);
  when b then
    tick := pre(tick); // disable initialization behavior explicitly
    tick[counter] := time;
    counter := pre(counter) + 1;
  end when;
end SaveTime;
```
Algorithms are diabolic.

**Comment by casella** [comment]
@phannebohm, the story is a bit more complicated. [Section 11.1.2](https://specification.modelica.org/maint/3.5/statements-and-algorithm-sections.html#execution-of-an-algorithm-in-a-model) states that continuous-time variables are initialized at their start values (to avoid unwanted memory effects), while discrete-time variables are initialized with their pre-values. However, according to [Section 4.4.4](https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#component-variability-prefixes-discrete-parameter-constant), 
> A Real variable assigned in a when-clause is a discrete-time variable, even though it was not declared
with the prefix discrete.

Hence, the array `tick` should be initialized to its pre-value even if this is not done explicitly in the algorithm.

I guess the backend does not recognize `tick` correctly as a discrete variable when deciding how to initialize it. Please check.

**Comment by phannebohm** [comment]
And here I was thinking I understand what's going on, sorry :sweat_smile:

The problem was in the backend. Right after lowering we detect implicit discrete variables but if it's an array we only set the last element as discrete which is complete nonsense. In fact, if you simulate the original `SaveTime` for longer, the variable `tick[10]` gets the correct value.

**Comment by casella** [comment]
> And here I was thinking I understand what's going on, sorry 😅

Never mind, I wholeheartedly agree with you that algorithms in models are diabolic 😄 

> The problem was in the backend. Right after lowering we detect implicit discrete variables but if it's an array we only set the last element as discrete which is complete nonsense. 

Indeed.

> In fact, if you simulate the original `SaveTime` for longer, the variable `tick[10]` gets the correct value.

Patience and persistence always pay out 😄 

Looking forward to a PR fixing this.
