### ISSUE TITLE
CCCV_Stack in Modelica.Electrical.Batteries.Examples fails

### ISSUE THREAD

**Issue by arouhan** [OpenModelica/OpenModelica#9052]
Hello,
the Modelica.Electrical.Batteries.Examples.CCCV_Stack model of MSL 4.0.0 fails to run under OME v1.19.0 winx64

result is:
```
[1] 17:22:21 Symbolique Erreur
Too few equations, under-determined system. The model has 807 equation(s) and 837 variable(s).

[2] 17:22:21 Symbolique Erreur
[Modelica.Electrical.Batteries.Examples.CCCV_Stack: 62:3-65:22]: [stack.stackBus.cellBus.T = busTranscription.stackBus.cellBus.T has size 1 but 0 variables ()](omeditmessagesbrowser:///Modelica.Electrical.Batteries.Examples.CCCV_Stack?lineNumber=62)
```

The issue has already been reported in v1.18 version: https://github.com/OpenModelica/OpenModelica/issues/7793#issue-976191023

**Comment by casella** [comment]
@arouhan thanks for reporting, we'll look into that ASAP.

**Comment by casella** [comment]
@perost, this is [the test report](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Electrical.Batteries.Examples.CCCV_Stack.err) on the testsuite. Some equations are lost along the road. I don't have any brilliant idea to figure out which they could be, but there is an error mentioning bus variables, maybe you could start looking into that?

**Comment by perost** [comment]
#9199 caused some regressions regarding expandable connectors, see [regression report](https://libraries.openmodelica.org/branches/history/master/2022-07-05%2002:05:05..2022-07-07%2003:53:37.html). The change only revealed an already existing issue though, which might be the cause of why these models doesn't work.

The issue is that we get component references such as `stack.stackBus.cellBus[2, 3].v`, where `cellBus` has the type `CellBus`. This causes a failure when trying to get the full type of the component reference since the subscripts can't be applied to a scalar type. Before #9199 the frontend never actually computed the type of the invalid component reference, so we didn't catch this issue. So at least part of the issue seems to be that some array dimensions are lost somewhere.

I'm going on vacation next week though, so I'm not sure I'll be able to look into this for a while. But at least this gives a good clue on what's going on.

**Comment by casella** [comment]
OK, no problem, it's on the todo list for 1.20.0.

**Comment by perost** [comment]
MWE:
```Modelica
expandable connector CellBus
  Real lossPower;
end CellBus;

expandable connector StackBus
  CellBus[3, 2] cellBus;
end StackBus;

model HeatFlowSensor
  connector RealOutput = output Real;
  RealOutput Q_flow;
end HeatFlowSensor;

model Cell
  HeatFlowSensor heatFlowSensor;
  CellBus cellBus;
equation
  connect(heatFlowSensor.Q_flow, cellBus.lossPower);
end Cell;

model Stack
  replaceable Cell[3, 2] cell;
  StackBus stackBus;
equation
  connect(cell.cellBus, stackBus.cellBus);
end Stack;
```

**Comment by casella** [comment]
> For the `CCCV_StackRC` model I get about 5 million lines of error messages from `BackendEquation.solveEquation`, which seems slightly excessive. 

Now that's a powerful understatement, if I ever saw one 😄 

@kabdelhak any comments?

**Comment by perost** [comment]
It seems something might have improved, at least we're not getting millions of error messages anymore. Now we just get:
```
Notification: It was not possible to check the given initialization system for consistency symbolically, because the relevant equations are part of an algebraic loop. This is not supported yet.
[BackEnd/BackendEquation.mo:2511:7-2511:76:writable] Error: Internal error function solveEquation failed
```

**Comment by casella** [comment]
@perost, before getting there I see:
`
[/home/hudson/saved_omc/libraries/.openmodelica/libraries/Modelica 4.0.0+maint.om/Electrical/Batteries/ParameterRecords/TransientData/CellData.mo:6:3-7:60:writable] Warning:
Parameter stackData.cellData[1,2].nRC has no value, and is fixed during initialization (fixed=true), using available start value (start=0) as default value.
```
I guess setting `nRC = 0` is likely to cause some structural issue. Are you sure that information about those parameter values is not lost by the frontend?

**Comment by perost** [comment]
> @perost, before getting there I see: ` [/home/hudson/saved_omc/libraries/.openmodelica/libraries/Modelica 4.0.0+maint.om/Electrical/Batteries/ParameterRecords/TransientData/CellData.mo:6:3-7:60:writable] Warning: Parameter stackData.cellData[1,2].nRC has no value, and is fixed during initialization (fixed=true), using available start value (start=0) as default value.
> 
> ```
> I guess setting `nRC = 0` is likely to cause some structural issue. Are you sure that information about those parameter values is not lost by the frontend?
> ```

Actually, `nRC` on that line is declared as:
```Modelica
parameter Integer nRC=1;
```
And that's the only declaration of `nRC` in the entire model, so it shouldn't be possible for it to end up with no binding in the flat model. Thanks for pointing that out, I'll have to investigate and see what's going on.

**Comment by perost** [comment]
The issue wasn't that we were losing bindings, but that the binding of `stackData.cellData` was defined as:
```Modelica
{{if anyTrue({ks == kDegraded[i, 1] and kp == kDegraded[i, 2] for i in 1:size(kDegraded, 1)}) then cellDataDegraded else cellDataOriginal for kp in 1:Np} for ks in 1:Ns}
```
We didn't evaluate the if-expression in this binding, which caused us to move the binding to an initial equation:
```Modelica
initial equation
  stackData.cellData[1,1] = if Modelica.Math.BooleanVectors.anyTrue({1 == stackData.kDegraded[1,1] and 1 == stackData.kDegraded[1,2]}) then stackData.cellDataDegraded else stackData.cellDataOriginal;
  stackData.cellData[1,2] = if Modelica.Math.BooleanVectors.anyTrue({1 == stackData.kDegraded[1,1] and 2 == stackData.kDegraded[1,2]}) then stackData.cellDataDegraded else stackData.cellDataOriginal;
  stackData.cellData[2,1] = if Modelica.Math.BooleanVectors.anyTrue({2 == stackData.kDegraded[1,1] and 1 == stackData.kDegraded[1,2]}) then stackData.cellDataDegraded else stackData.cellDataOriginal;
  stackData.cellData[2,2] = if Modelica.Math.BooleanVectors.anyTrue({2 == stackData.kDegraded[1,1] and 2 == stackData.kDegraded[1,2]}) then stackData.cellDataDegraded else stackData.cellDataOriginal;
  stackData.cellData[3,1] = if Modelica.Math.BooleanVectors.anyTrue({3 == stackData.kDegraded[1,1] and 1 == stackData.kDegraded[1,2]}) then stackData.cellDataDegraded else stackData.cellDataOriginal;
  stackData.cellData[3,2] = if Modelica.Math.BooleanVectors.anyTrue({3 == stackData.kDegraded[1,1] and 2 == stackData.kDegraded[1,2]}) then stackData.cellDataDegraded else stackData.cellDataOriginal;
```
It seems the backend didn't like this, so in #10624 I've changed the splitting of record expressions to try to evaluate if-expressions. That causes the bindings to be completely split and no initial equations are generated, and now both the `CCCV_Stack` and `CCCV_StackRC` models simulate.

**Comment by casella** [comment]
Sounds good. Moving bindings to initial equations is not a good idea for structural parameters, which `nRC` definitely is. I wonder if there is a more general strategy to avoid that in the front end.

A reasonable heuristics for that is that all Integer, Enumeration, and Boolean bindings should probably never be moved to the initial equation section.

**Comment by perost** [comment]
> Sounds good. Moving bindings to initial equations is not a good idea for structural parameters, which `nRC` definitely is. I wonder if there is a more general strategy to avoid that in the front end.
> 
> A reasonable heuristics for that is that all Integer, Enumeration, and Boolean bindings should probably never be moved to the initial equation section.

The issue is when you have a parameter record with a binding, in that case we need to split the binding:
```Modelica
record R
  Real x;
  Integer y;
end R;

model M
  parameter R r = R(1.0, 2);
end M;

=> 

model M
  parameter Real r.x = 1.0;
  parameter Integer r.y = 2.0;
end M;
```
But it's not always possible to split the binding, it could for example be an impure external function call. In that case we have to choose between generating "record subscripting" expression (`(some expression).x`), which for functions call can cause the function to be called once for every record field, or moving the binding to an initial equation.

It would be better if we didn't have to split records and could just keep them as they are, but that would likely be a massive amount of work for the old backend. Maybe it'll be easier with the new one, but for now we don't really have any good general way of dealing with record bindings.

**Comment by casella** [comment]
Yeah, I get that. 

From a practical perspective, parameter bindings to records are most likely used to collect several model parameters in a single "datasheet" record entry. Some parameters are related to dimensions or operating points (e.g. a lenght, a surface, or a reference voltage), that may be actually modified at runtime, but some parameters can be related to structural information, e.g. the number of finite volumes in a discretized 1D model, or the number of cells in a stack (as in the case of this ticket), conditionally activated components, and so on. And yes, the datasheet could be read from a file or external database using an impure function.

If the binding does not involve function calls, I guess splitting the record in the frontend is the best option.

If the binding only involves pure function calls, then I understand you can call the function at compile time, so that model `M`
```modelica
record R
  Real x;
  Integer y;
end R;

function f
  output R r;
algorithm
  r.x = 2.0;
  r.y = 3;
end f;

model M
  parameter R r = f();
  Real v[r.y] = ones(size(r.y),1)*r.x;
  Integer z = r.y;
end M;
```
can be transformed by the frontend into

```modelica
model M
  parameter Real r.x = 2.0;
  parameter Integer r.y = 3 ;
  Real v[3];
  Integer z = 3;
equation
  Real v[1] = r.x;
  Real v[2] = r.x;
  Real v[3] = r.x;
end M;
```
Then, of course, the generated code could still allow to change `r.x` at runtime, but of course it won't be possible to change `r.y`, which is structural.

If the binding involves an impure function, any structural information in the external data file must be read at compile time, until we support structural dynamics (which is not happening to OMC anytime soon). I think the best option is then to identify whatever structural parameters are contained in the record, constant-evaluate them at compile time by running the impure function in the frontend, and then pass the whole record down to the backend, which will handle everything else, in the form of initial equations. For example
```modelica
record R
  Real x;
  Integer y;
end R;

impure function f
  output R r;
algorithm
  (r.x, ry) = read_csv();
  // CSV file contains 2.0, 3
end f;

model M
  parameter R r = f();
  Real v[r.y] = ones(size(r.y),1)*r.x;
  Integer z = r.y;
end M;
```
will be transformed by the FE into
```modelica
model M
  parameter R r(fixed = false);
  Real v[3];
  Integer z = 3;
initial equation
  r = f();
equation
  Real v[1] = r.x;
  Real v[2] = r.x;
  Real v[3] = r.x;
end M;
```
Of course if one changes the (structural) value of the integer in the CSV file at runtime, this would be ignored, but that's a fact of life, and we have to live with it, since we don't support runtime structural changes. At least we can change the non-structural parameter values in the CSV file at runtime. This could be useful in a number of cases, e.g. if you want to run a parameter sweep on the non-structural parameters only. I guess that's the best we can do now.

@perost, what do you think?

**Comment by perost** [comment]
> @perost, what do you think?

That's pretty much how it already works, we try various things like inlining or just straight up constant evaluating the bindings in order to split them. The first example is already handled as you say, while in the second we will currently actually evaluate the function call even though it's impure since `r.y` is used as an array dimension (and is thus structural).

**Comment by casella** [comment]
> while in the second we will currently actually evaluate the function call even though it's impure since `r.y` is used as an array dimension (and is thus structural).

That's good enough for the time being. I opened #10626 regarding this future optimization, it's currently not critical.
