### ISSUE TITLE
Linear solver fails

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9118]
### Description

For the model Rexroth_Generic_Test.Mechanics.Rotational.GearNonLinearRotational.GearNonLinearRotational_TC03 from the BRSL library the linear solver fails with error: 
``Failed to solve linear system of equations (no. 273) at time 0.000000, system is singular for U[2, 2].
The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000.``

### Steps to Reproduce
Load the BRSL package: Rexroth_Generic_Test/package.mo
Simulate the model Rexroth_Generic_Test.Mechanics.Rotational.GearNonLinearRotational.GearNonLinearRotational_TC03

### Expected Behavior
The model should simulate for 5s
### Version and OS

 - OpenModelica Version: v1.20.0-dev-119-g4241954151
 - OS: Windows 10, 64 bit
 - MSL 4.0.0
 - BRSL 2.1

**Comment by casella** [comment]
@niklwors this error is likely due to one of two possible causes:
- linear tearing introduces a singularity, see #8935. You can check what happens if you set --tearingMethod=minimalTearing, if the singularity is gone then we have another specimen for the horror museum of #8935.
- unrecognized high-index problem: if the problem has index > 1 but this is not recognized during the analysis phase and symbolic index reduction performed, then the causalized system will be singular, and this will be revealed either by a division by zero (for equations turned into assignments) or by singular A matrix (for linear systems) or Jacobian (for nonlinear implicit systems). In this case we should try to improve the index reduction algorithm

Can you please try running this without tearing and report?

**Comment by niklwors** [comment]
@casella With the translation flag --tearingMethod=minimalTearing the error message is the same.

**Comment by niklwors** [comment]
@casella  with the translation flag --tearingMethod=minimalTearing the error message is still there, but the simulation then finishes.

**Comment by niklwors** [comment]
For some reason, this problem has been fixed.

**Comment by casella** [comment]
Good to hear 😄
