### ISSUE TITLE
Deprecate non-working ODE solvers

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9191]
### Description

There are some ODE solvers that are simply not working or not used or will be replaced by GBODE (see https://github.com/OpenModelica/OpenModelica/pull/9143).
We should deprecate them for 1.20 and remove them in 1.21.

These solvers would be repalced by gbode:

  - heun
  - rungekutta
  - trapezoid
  - imprungekutta
  - irksco
  - rungekuttassc

What about symSolver and symSolverSsc? And what is `qss`?
I'm not sure about the status of these.

### Version and OS

 - OpenModelica Version: v1.20.0-dev-189-gd2b32cda5c

### Additional Context

Comparison for the different solvers.
[DASSL's coverage](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html) of the MSL 4.0.0 is at 483 verified simulations.

![grafik](https://user-images.githubusercontent.com/38031952/177179148-2fde4fdf-9c28-4fcc-b368-af89ea0d42fb.png)
![grafik](https://user-images.githubusercontent.com/38031952/177179243-ac96506e-0dbe-48f1-bc1b-9442f1159ca8.png)

**Comment by casella** [comment]
qss was an early attempt at implementing a QSS solver in OpenModelica. Which is something we should have, but I never managed to get ignition temperature on this task 😅 . 

Rungekuttassc is an interesting algorithm. It was devised by Anton Novikov, a researcher from the Siberian Federal University, who presented it at the 2016 EUROSIM conference. As I understand, they are particular Runge-Kutta algorithms that are designed to obtain high stability for fast eigenvalues, with Re(lambda*h) up to -30. Consider that standard explicit algorithms become unstable for much smaller values or lambda*h (i.e. 2, 3, or similar). 

This seemed to me an interesting possibility to avoid implicit algorithms for systems of medium stiffness. Back then I invited Anton to implement it in OpenModelica, but I understand he did a basic implementation with fixed step size.

@bernhardbachmann I wonder if this class of algorithms could be embedded in your gbode solver. That would be very interesting for me. Could you take care of that?

I'm not sure about symSolver and symSolverSsc. Maybe they are inline integration solvers?

**Comment by casella** [comment]
Here is the link to Anton's paper: http://dx.doi.org/10.3384/ecp17142979

**Comment by bernhardbachmann** [comment]
I just added the Butcher tableau of Anton. The values are from the paper:
Solving Stiff Systems of ODEs by Explicit Methods with Conformed Stability Domains
Anton E. Novikov1     Mikhail V. Rybkov2     Yury V. Shornikov3     Lyudmila V. Knaub4
EUROSIM 2016 & SIMS 2016

I added an embedded version for step size control. The stability region is the following...

**Comment by bernhardbachmann** [comment]
![Screenshot 2022-07-12 182524](https://user-images.githubusercontent.com/12253584/178544178-fa1f5ce4-a792-4774-84ec-9d6ba75b3cda.png)

**Comment by bernhardbachmann** [comment]
Actually it is more ;-)

**Comment by bernhardbachmann** [comment]
Generic Bi-rate ODE solver ("gbode")

percentage of states, which are fast states
-gbratio  (-gbratio = 0 or gbratio=1 => single-rate solver)

Different options and combinations possible: 
outer integration:
singlerate method  		-gbm 						(default = esdirk4)
step size control 		-gbctrl={i,pi,const} 		(default = i <=> IController , pi <=> PIController, const <=> fixed step size)
nonlinear solver		-gbnls={kinsol, newton}		(default = kinsol)
interpolation 			-gbint={linear,hermite,hermite_a,hermite_b,dense_output,hermite_errctrl,dense_output_errctrl)

-gbint is also used for slow state interpolation (with error control on the interpolation error, when last two options are chosen)
if dense_ouput is not available (for most of the integrators!) hermite is chosen.

inner integration:
singlerate solver  		-gbfm			(default same as -gbm)
step size control 		-gbfctrl 		(default same as -gbctrl)
nonlinear solver		-gbfnls			(default same as -gbnls)

inner integrator defaults to outer integrator
only for full implicit methods (i.e. gauss4), which are not supported yet, the inner integrator will be set to esdirk4

logging options:
LOG_SOLVER, LOG_SOLVER_V, LOG_GBODE, LOG_GBODE_V, LOG_GBODE_NLS, LOG_GBODE_NLS_V

and for debugging the birate solution process:
-lv=LOG_GBODE_STATES => file "<modelName>_faststates.txt" is created in OMEdit working directory, usually /tmp/OpenModelica_<userName>/OMEdit

available integrators:
  /* MS_ADAMS_MOULTON */ "adams",
  /* RK_EXPL_EULER */    "expl_euler",
  /* RK_IMPL_EULER */    "impl_euler",
  /* RK_TRAPEZOID */     "trapezoid",
  /* RK_SDIRK2 */        "sdirk2",
  /* RK_SDIRK3 */        "sdirk3",
  /* RK_ESDIRK2 */       "esdirk2",
  /* RK_ESDIRK3 */       "esdirk3",
  /* RK_ESDIRK4 */       "esdirk4",
  /* RK_RADAU_IA_2 */    "radauIA2",
  /* RK_RADAU_IA_3 */    "radauIA3",
  /* RK_RADAU_IA_4 */    "radauIA4",
  /* RK_RADAU_IIA_2 */   "radauIIA2",
  /* RK_RADAU_IIA_3 */   "radauIIA3",
  /* RK_RADAU_IIA_4 */   "radauIIA4",
  /* RK_LOBA_IIIA_3 */   "lobattoIIIA3",
  /* RK_LOBA_IIIA_4 */   "lobattoIIIA4",
  /* RK_LOBA_IIIB_3 */   "lobattoIIIB3",
  /* RK_LOBA_IIIB_4 */   "lobattoIIIB4",
  /* RK_LOBA_IIIC_3 */   "lobattoIIIC3",
  /* RK_LOBA_IIIC_4 */   "lobattoIIIC4",
  /* RK_GAUSS2 */        "gauss2",
  /* RK_GAUSS3 */        "gauss3",
  /* RK_GAUSS4 */        "gauss4",
  /* RK_GAUSS5 */        "gauss5",
  /* RK_GAUSS6 */        "gauss6",
  /* RK_MERSON */        "merson",
  /* RK_HEUN */          "heun",
  /* RK_FEHLBERG12 */    "fehlberg12",
  /* RK_FEHLBERG45 */    "fehlberg45",
  /* RK_FEHLBERG78 */    "fehlberg78",
  /* RK_RK810 */         "rk810",
  /* RK_RK1012 */        "rk1012",
  /* RK_RK1214 */        "rk1214",
  /* RK_DOPRI45 */       "dopri45",
  /* RK_RKSSC */         "rungekuttaSsc"

All integrators have step size control or fixed step size and proper event handling.
Some have alread dense output available. Most of the "old" OMC integrators (see below)
can be emulated by specific settings.

Old OMC integrators and their replacement commands:
old: -s=rungekuttaSsc
new: -s=gbode -gbm=rungekuttaSsc
This is a RK method of order 1 with large stability region

old: -s=euler
new: -s=gbode -gbm=expl_euler -gbctrl=const
Since this routine is used also within the FMI context, it might not be possible to remove it

old: -s=heun
new: -s=gbode -gbm=heun -gbctrl=const

old: -s=impeuler
new: -s=gbode -gbm=impl_euler -gbctrl=const

old: -s=trapezoid
new: -s=gbode -gbm=trapezoid -gbctrl=const

old: -s=imprungekutta
new: -s=gbode -gbm=(one of the lobatto or radau or gauss methods) -gbctrl=const

**Comment by bernhardbachmann** [comment]
old: -s=irksco
new: -s=gbode -gbm=trapezoid

**Comment by casella** [comment]
> ![Screenshot 2022-07-12 182524](https://user-images.githubusercontent.com/12253584/178544178-fa1f5ce4-a792-4774-84ec-9d6ba75b3cda.png)

I never really played seriously with this solver, but it may be quite interesting for mildly stiff models, like in Buildings. I will definitely try it out there.
