### ISSUE TITLE
OMEdit bug with iterationVars flag

### ISSUE THREAD

**Issue by audrey-jardin** [OpenModelica/OpenModelica#9222]
### Description

The list of iteration variables doesn't appear in the log file when the flag "-d=iterationVars" is set in OMEdit.

### Steps to Reproduce

Could be reproduced with the "TestBend" example of ThermoSysPro v4_OSR (see files attached)

### Expected Behavior
Get the list of iteration variables to ease the initialization step for the modeler

### Version and OS

 - OpenModelica Version: OpenModelica v1.19.0 (64-bit)
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries: ThermoSysPro v4 OSR

### Additional Context

Once the flag fixed, would it possible to get the list of iteration variables in the variable browser and set their values from there (or from a .mos file).
[TestBend.log](https://github.com/OpenModelica/OpenModelica/files/9083157/TestBend.log)
[ThermoSysPro-v4.0-OSR.zip](https://github.com/OpenModelica/OpenModelica/files/9083160/ThermoSysPro-v4.0-OSR.zip)
[TestBend.zip](https://github.com/OpenModelica/OpenModelica/files/9083167/TestBend.zip)

**Comment by adrpo** [comment]
Running script: l.mos:
```
loadFile("ThermoSysPro-v4.0-OSR/ThermoSysPro/package.mo"); getErrorString();
loadFile("TestBend.mo"); getErrorString();
buildModel(ThermoSysPro.Examples.SimpleExamples.TestBend); getErrorString();
```
from command line gives:
```
adrpo33@ida-0030 MINGW64 /c/home/adrpo33/dev/OMTesting/bugs/9222
# omc -d=iterationVars l.mos
true
""
true
""
{"C:/home/adrpo33/dev/OMTesting/bugs/9222/ThermoSysPro.Examples.SimpleExamples.TestBend","ThermoSysPro.Examples.SimpleExamples.TestBend_init.xml"}
Warning: The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
Notification: List of all iteration variables (DAE kind: initialization)
Iteration variables of torn nonlinear equation system:
  Bend.Q:VARIABLE(start = 500.0 unit = \"kg/s\" )  \"Mass flow rate\" type: Real
Notification: List of all iteration variables (DAE kind: simulation)
Iteration variables of torn nonlinear equation system:
  Bend.Q:VARIABLE(start = 500.0 unit = \"kg/s\" )  \"Mass flow rate\" type: Real
```

The text about the iteration variables does not appear in the OMEdit translation log.

**Comment by adrpo** [comment]
Seems it is working, if you do this:
- restart OMEdit
- do not load any model
- go: Tools->Options->Simulation and add `-d=iterationVars` and then click Ok
- restart OMEdit
- load your model and simulate

![image](https://user-images.githubusercontent.com/4192979/201149022-dc65026c-6451-44d1-86de-6b056fb6615f.png)

**Comment by adrpo** [comment]
You get this message if you try to edit the global flags with the model open:

![image](https://user-images.githubusercontent.com/4192979/201150646-40893b0f-a210-4bf7-a545-69b9a9d9edb5.png)

which seems really weird as the model does not have any flags in it!?!

**Comment by adeas31** [comment]
All the global flags are propagated to the model when you simulate the model for the first time. From then on the model has the local flags of its own which can be modified via Simulation Setup->Translation Flags. If at that moment you change any global flag then you get a prompt as shown in https://github.com/OpenModelica/OpenModelica/issues/9222#issuecomment-1310552148 which asks you if you want to overwrite the local flag. This is also explained in the users guide https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#simulating-a-model

**Comment by casella** [comment]
@adrpo, it is quite hard to find a logic that is sensible, consistent, easy to explain, and works in all cases. Maybe even impossible 😅 

That said, the current logic is the one @adeas31 explained in [his comment](https://github.com/OpenModelica/OpenModelica/issues/9222#issuecomment-1310576005). We settled on it because many users (including myself) were baffled that sometimes changing the global settings affected the local settings, sometimes it didn't. The reason was that global settings were copied to local settings _the first time you ran a simulation of a certain model during an OMEdit session_  and then retained for the whole session, so if you changed global flag afterwards, it didn't have any effect.

With the latest changes, this no longer happens: if you change global settings while some models previously got some (possibly modified) local settings, you are warned about that, and you're given an option to retain those local settings independently of the new global ones, or to reset them to the new global settings, without restarting OMEdit, which is a pain. This seems very clear and reasonable to me. Maybe we could improve the text in the dialog, which is a bit awkward to read.

What is probably confusing you here is that the model in question got a local `-d=iterationVars` setting _because you set that in the Simulation Setup window_ but _not in the model annotations_. This is perfectly fine, if you decide not to save those settings in annotations.

@adrpo does it make sense to you now?

**Comment by casella** [comment]
@adeas31 I tried to reformulate the text of the dialog to be more user-friendly 😅:

You just changed some global translation flags.

The listed models are currently open in this session and have different local translation flags, that were selected with the Simulation Setup dialog.

Select the models for which you want to discard the local translation flag and apply the new global flags (*). All other models will retain the current local settings until you close OMEdit.

(put the widget with the list here)

(*) If you discard local settings, the new global settings will first be applied, and then any further settings
saved in the model annotations will be applied. This is the same behaviour you would get if you closed OMEdit, restarted it
and reopened all models.

**Comment by audrey-jardin** [comment]
Hi @adrpo, @adeas31 and @casella ,

Thanks for the explanation. This was indeed not so intuitive from the user point of view but it's now clearer to me! 

Best regards,
Audrey

**Comment by casella** [comment]
@audrey-jardin we have improved the explanatory text in the latest nightly build
