### ISSUE TITLE
Fix warning "equality comparison with extraneous parentheses"

### ISSUE THREAD

**Issue by hkiel** [OpenModelica/OpenModelica#9304]
### Description

When building OM, compilation output is cluttered with hundreds of warnings and notes, making it difficult to spot "real" warnings.
```
warning: equality comparison with extraneous parentheses
note: remove extraneous parentheses around the comparison to silence this warning
note: use '=' to turn this equality comparison into an assignment
```

The "problem" are extra parentheses in if conditions, e.g. `if((_flow_dir == ((modelica_integer) -1)))` which are supposed to mark assignments in if conditions. It should be possible to generate only needed parentheses.

**Comment by hkiel** [comment]
@mahge I tried to fix this myself, but using cmake, my modifications to `OMCompiler/Compiler/Template/CodegenCFunctions.tpl` don't seem to take effect.

I added a comment to all occurrences of `if(<%if_conditions%>)` in `CodegenCFunctions.tpl` to distinguish the different places, but the comment never shows up for generated code on a second call of cmake (after touching some OMCompiler/Compiler/NFFrontEnd/*.mo` file to force a rebuild).

**Comment by mahge** [comment]
I have seen them as well. I think some of them come from the bootstrapping code so it is not possible to fix all of them by updating the code generation. 

The easiest way is to just disable that warning if we are using clang. I will make a PR for it.

**Comment by mahge** [comment]
As it turns out we already have silenced these warnings ([here](https://github.com/OpenModelica/OpenModelica/blob/b17e1a0ea1c9e2e8686c568f41e3db40bb409b1b/OMCompiler/Compiler/CMakeLists.txt#L197-L199) and [here](https://github.com/OpenModelica/OpenModelica/blob/b17e1a0ea1c9e2e8686c568f41e3db40bb409b1b/OMCompiler/Compiler/boot/CMakeLists.txt#L18-L20)) for `Clang` but not for `AppleClang`. 

#9305 should hopefully fix it. You might still see these warning in some other places (3rdParty code and some generated parser files) but the large portion (about 90%) of them should be gone now.

**Comment by hkiel** [comment]
@mahge The patch successfully removes the warnings. Thanks!
However, I would keep the ticket open (or open a new one), because `omc` is always rebuilt with bootstrapped `bomc`.
In make-build we have three-pass build of omc (bootstrap from C, build `.mo` with `bomc` and finally build `.mo` with `omc`)

I don't know if we need three passes. But once `omc` is available, it should be used instead of `bomc` to build `omc` itself with `cmake`.

**Comment by casella** [comment]
@hkiel please open a separate one for that. Thanks!
