### ISSUE TITLE
[cmake] omc is always compiled with bootstrapped omc

### ISSUE THREAD

**Issue by hkiel** [OpenModelica/OpenModelica#9314]
### Description

`omc` is always rebuilt with bootstrapped `bomc`.
In make-build we have three-pass build of `omc` (bootstrap from C, build .mo with "bomc" (which is actually omc from bootstrapped sources) and finally build .mo with (non-bootstraped) omc)

I don't know if we really need three passes. But once `omc` is available, it should be used instead of `bomc` to build omc itself with cmake.

**Comment by mahge** [comment]
We can of course replace the bootstrapped `omc` with the compiled `omc` once it is available. However this can leave you in a broken state where you Where you can not compile MetaModelica until you have done a full cleanup (or at least restarted the bootstrapping manually). This used to happen (and still does) with the autoconf build. It happens less and less lately though since we are not updating MetaModelica related things, i.e., the old Front End,  anymore. 

The three step compilation is also probably not a good idea if you ask me. We should avoid it because it:
 - Can leave you in a broken state. 
 - Takes more time to build everything.
 - It does not fit very well with the configure-build-install flow.

What the CMake build should provide instead (which is available in the autoconf build system) is the ability to regenerate the bootstrapped sources for people who need it. However, we are very cautious about updating it frequently. 

One way to think about it is: `bomc` is a `MetaModelica` compiler and `omc `is a `Modelica` compiler (although it can compile MM as well). But to keep things clean we should think of them as separate compilers. It is just that we provide the source code for a  `MetaModelica` compiler together with our sources for our `Modelica` compiler.  

If you really need to use the compiled `omc` instead of the bootstrapped `omc` I can add a separate custom target that can just overwrite the `bomc` executable and the linked shared libraries when explicitly asked.

**Comment by sjoelund** [comment]
The problem with 2-stage is that in the cases where we change something, bomc and omc both will fail to compile and won't be able to bootstrap either. 3-stage however, will work if you make clean and bootstrap again.
