### ISSUE TITLE
Cross build of the FMU using docker

### ISSUE THREAD

**Issue by aditmak** [OpenModelica/OpenModelica#9330]
I am using OpenModelica v1.19.2 (64-bit), OMSimulator v2.1.1.post159-g606161d-mingw under Windows 64bit. I created a fmu and want win64 and linux64 binaries. I ticked on x86_64-linux-gnu docker build and already have docker installed on it.

When I export the FMU, I am getting the following error:

```
Error building simulator. Build log: docker run  --rm -w /fmu -v ...f:/fmu multiarch/crossbuild sh -c "cd "/fmu/model.fmutmp/sources" && ./configure --host='x86_64-linux-gnu' CFLAGS='-Os' CPPFLAGS=-I/fmu/fmiInclude LDFLAGS= && make -j12 nozip":
...
sh: 1: ./configure: not found
```

I think the issue is related to #7458.

**Comment by AnHeuermann** [comment]
I had a similar issue in #7458 and the solution was to use CMake instead of configure+Makefile whenever cross-compoling form Windows. It should be selected automatically, but you can force OpenModelica to use the CMake FMU compilation by adding the compiler flag [`--fmuCMakeBuild=true`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmucmakebuild). If you don't have that your OpenModelica version may be too old. Try again with the nightly build.

Can you give us a minimal working example to reproduce the error? 
The following script fails for me, but because of another issue. I'm using Windows 11, omc (`v1.20.0-dev-89-ge6d4cb0ead`) and Docker.

```Modelica
loadModel(Modelica); getErrorString();
buildModelFMU(Modelica.Electrical.Analog.Examples.Rectifier, platforms={"x86_64-linux-gnu docker run --pull=never multiarch/crossbuild"}); getErrorString();
```
You may need to pull `multiarch/crossbuild` first. We never pull because of the obvious security concerns when pulling random docke rimages from the internet. So the user has to do it.

and run it from a console where omc is in your path:

```bash
$ omc test.mos
```

**Comment by aditmak** [comment]
Thanks  for helping @AnHeuermann. 
Adding the compilation flag for CMake build helped to export the FMU. However, now there are 2 issues. 

1. FMU Export works fine with Explicit Euler solver but with CVode I got the following error.

```
[ 35%] Building C object CMakeFiles/Modelica_Electrical_Analog_Examples_Rectifier.dir/simulation/simulation_omc_assert.c.o
/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources/simulation/simulation_omc_assert.c: In function 'omc_assert_simulation':
/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources/simulation/simulation_omc_assert.c:115:1: warning: 'noreturn' function does return
 } 
 ^
/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources/simulation/simulation_omc_assert.c: In function 'omc_assert_simulation_withEquationIndexes':
/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources/simulation/simulation_omc_assert.c:123:1: warning: 'noreturn' function does return
 } 
 ^
[ 36%] Building C object CMakeFiles/Modelica_Electrical_Analog_Examples_Rectifier.dir/simulation/solver/cvode_solver.c.o
In file included from /fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources/simulation/solver/cvode_solver.c:36:0:
/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources/simulation/solver/cvode_solver.h:35:26: fatal error: omc_config.h: No such file or directory
   #include "omc_config.h" 
                          ^
compilation terminated.
```

2. If I select, Native and x86_64-linux, it is giving me following error. I am using Windows 11 64-bit operating system, x64-based processor. 
```
Error building simulator. Build log: Unknown/unsupported platform "static " for CMake FMU build
```

I am using the OpenModellica 1.19.2 (Stable Release). I want Co-Simulation FMU with version 2.0 in linux64 & win64 binaries. and cvode solver with blackbox filter.

**Comment by AnHeuermann** [comment]
Yeah, I can reproduce the issue on Windows without Docker:

```Modelica
loadModel(Modelica); getErrorString();
setCommandLineOptions("--fmiFlags=s:cvode --fmuCMakeBuild=true"); getErrorString();
buildModelFMU(Modelica.Electrical.Analog.Examples.Rectifier, platforms={"static"}); getErrorString();
```

`omc_config.h` is never included into the FMU and some header files need `OMC_FMI_RUNTIME` defined. There is a stray `"D"` in our CMakeLists.txt.in. and a include directory for sundials missing. Fixing these should resolve the issue.
