### ISSUE TITLE
Modelica.Blocks.Interfaces.RealInput is dumped as Real

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#9374]
### Description

`getModelInstance` api dumps `Modelica.Blocks.Interfaces.RealInput` as type `Real`.

### Steps to Reproduce

```
loadString("model M
  Modelica.Blocks.Interfaces.RealInput u
    annotation (Placement(transformation(extent={{-98,6},{-58,46}})));
  annotation (uses(Modelica(version=\"3.2.3\")));
end M;");
getModelInstance(M, true);
```

### Expected Behavior

The information of class `Modelica.Blocks.Interfaces.RealInput` should be dumped.

**Comment by perost** [comment]
Should be fixed in #9493.

Note that I made some changes to how we dump extends. If the class is a short class definition, i.e. `class A = B`, then the `extends` property in the JSON will be a single object instead of a list of objects like before. This makes the JSON a bit smaller, but also let's us differentiate between the two types of extends if we need to.

The `baseClass` property in an `extends` object may now also be a string instead of an object, which means it's a builtin type (same as we already do for component types).

So e.g. `type RealInput = input Real` is now dumped as:
```json
"type": {
   "name": "RealInput",
   "restriction": "type",
   "prefixes": {
     "direction": "input"
   },
   "extends": {
     "baseClass": "Real"
   },
   "source": ...
}
```
We could potentially shorten the `extends` part to just `"extends": "Real"` in some cases, but I'm not sure it's worth the trouble.
