### ISSUE TITLE
Restrict the width of parameter fields in OMEdit

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9499]
### Description

When opening the parameter dialogue of `G1` in `OpenIPSL.Tests.Machines.PSSE.GEN` 
one is met by a more than screen-wide parameter field due to one of the choices having a series of modifications applied.
 
### Steps to Reproduce

Opening the above-mentioned component one sees:
 
![Peek 2022-10-10 13-25](https://user-images.githubusercontent.com/9332/194855939-87c4971e-36fd-44cc-ba4e-55fd258d23be.gif)

### Expected Behavior

It would be good if the field content could be truncated. 

### Version and OS

 - OpenModelica Version: OpenModelica 1.20.0~dev-336-g8a791ee
 - OS: Ubuntu 22.04.1
 - Versions of used Modelica libraries if applicable: OpenIPSL v3.0.1

**Comment by adeas31** [comment]
This is intentional. We try to use as much space as possible on the visible screen. If the value width is greater than the screen size then we use the maximum screen width and add the scrollbars to the parameters window. The parameters window will never go outside of the screen and the value is always fully visible.

This was implemented as a request feature (I don't remember the ticket number). The motivation was that everyone is using 4k screens nowadays so use as mush space as possible and don't truncate the value.

**Comment by dietmarw** [comment]
OK fair enough.
