### ISSUE TITLE
Ports in a diagram are drawn too large with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9557]
### Description

For some component diagrams of the BRSL library, ports in a diagram are drawn too large.

### Steps to Reproduce

1.  Load the BRSL package: Rexroth_Pumps/package.mo
2. Drag and drop the ```Rexroth_Pumps.AxialPistonUnits.ConstantUnits.A4FO``` on a new sheet.
3. Use ```open class``` from the conetext menu of the ```A4FO``  component
4. The left port is drawn too large, compare picture 1 and 2

### Screenshots
**Picture 1**

<img width="1067" alt="largePorts-1" src="https://user-images.githubusercontent.com/12269776/196899165-ccd63da2-0bc1-4ab7-976f-69bbad0ff737.png">

**Picture 2**
<img width="944" alt="largePorts-2" src="https://user-images.githubusercontent.com/12269776/196899181-f2df5dae-a3ce-43e5-a5f4-4f5e3c68f237.png">

### Version and OS

 - OpenModelica Version: v1.20.0-dev-348-g7cc2ddob5b (64-bit)
 - OS: e.g. Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable
 - MSL 4.0.0
 - BRSL 2.2 dev
### Additional Context

@sbaetzing @abuntrock

**Comment by adeas31** [comment]
First this is happening because you have extra icon annotation with a rectangle and ellipse defined in `Rexroth_Generic.Mechanics.Interfaces.FlangeRotB` which I believe is not supposed to be there.

Secondy, OMEdit uses the diagram annotation for a connector and if there is no diagram annotation then the icon annotation is used. I fixed this now according to the specification,

`For connectors, the icon layer is used to represent a connector when it is shown in the icon layer of the enclosing model. The diagram layer of the connector is used to represent it when shown in the diagram layer of the enclosing model.`

So now we don't use the icon annotation if diagram annotation is not defined.

**Comment by niklwors** [comment]
> Firstly this is happening because you have extra icon annotation with a rectangle and ellipse defined in `Rexroth_Generic.Mechanics.Interfaces.FlangeRotB` which I believe is not supposed to be there.
 
We need this to change the color of the connection
