### ISSUE TITLE
OMEdit with NAPI does not show diagram when a submodel is missing

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9673]
### Steps to Reproduce
load OMEDIT
load [Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/10813047/Test.mo.txt)
open RL_PQ. The diagram is as follows (correct) :
![image](https://user-images.githubusercontent.com/7373030/200734234-88bd3300-3e68-4009-ae0d-97a880eec573.png)

load OMEDIT --NAPI=true
lload Test,mo
open RL_PQ. The diagram is missing:
![image](https://user-images.githubusercontent.com/7373030/200734392-89f9d94f-1a68-42aa-92b8-ad6f1bc03963.png)

### Expected Behavior
the diagram should be visibile, with the red box where the component is missing

### Version and OS

 - OpenModelica Version: 1.21.0 
 - Ubuntu 22.04

**Comment by casella** [comment]
@ceraolo this was a known issue, thanks for actually opening a ticket about it.

**Comment by casella** [comment]
According to @perost during yesterday's devmeeting, he should be able to get a solution for undefined types and connect statements involving them by the end of this week..

**Comment by perost** [comment]
#10382 improves the situation such that the new API now doesn't fail on this model but returns what it can. OMEdit already kind of handles this. It can open the model and display most of the diagram, but instead of a red box it just doesn't draw the component or any connections to it. So @adeas31 will probably need to make some changes to OMEdit if we want the same behaviour as before.

**Comment by casella** [comment]
Yeah, I think a showing a red box would be much better than showing nothing, because it clearly conveys the message that there is something wrong with the model.

**Comment by ceraolo** [comment]
Previously not only red boxes were shown but also connecting lines connecting missing components to each other and with other components. I hope this can be restored.

**Comment by adeas31** [comment]
Yeah the idea is to support everything that old API was doing.

**Comment by casella** [comment]
@ceraolo this issue has been fixed in the meantime. With the latest nightly build we now get:
![immagine](https://user-images.githubusercontent.com/4233148/229541387-a0050805-7071-4362-913e-6ce83e77fb5f.png)
The missing model can be identified as an instance of the (missing) Submodels.QSensor model by hovering with the mouse over it

**Comment by ceraolo** [comment]
Good!
Thank you

**Comment by adeas31** [comment]
That's weird. I will debug that.

**Comment by casella** [comment]
Good, I noticed that but I thought it was no big deal, at the end of the day the important point is to know what are the problematic components, and that was OK 😅

**Comment by ceraolo** [comment]
thie issue is stil present with some models. 
For the following Test model, if we use the old API, the missing object is clearly visibile as a red box; if we use the new one (Tools|Options|Enable instance API), nothing is displaied.
Maybe this ticket has to be reopened?
Tested with 1.22.0-dev-155, on Ubuntu.

[Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/11650893/Test.mo.txt)

**Comment by casella** [comment]
Why is the model missing, because PowerSystems is not loaded?

**Comment by ceraolo** [comment]
Yes, it is missing because PowerSystems is not loaded

**Comment by casella** [comment]
@ceraolo, et voilà, problem solved :cool
