### ISSUE TITLE
The NF should catch uninitialized variables in functions

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9717]
The old frontend was able to catch uninitialized variables in functions. For example, compiling this MWE with the OF
```modelica
model TestUninitialized
  Real y = f(time);
  function f
    input Real x;
    output Real y;
  protected
    Real z;
  algorithm
     y := z + x + y;
     y := y + 1;
  end f;
end TestUninitialized;
```
gave the following warnings:
```
[1] 11:37:58 Translation Warning
[TestUninitialized: 9:6-9:20]: [z was used before it was defined (given a value). Additional such uses may exist for the variable, but some messages were suppressed.](omeditmessagesbrowser:///TestUninitialized?lineNumber=9)

[2] 11:37:58 Translation Warning
[TestUninitialized: 9:6-9:20]: [y was used before it was defined (given a value). Additional such uses may exist for the variable, but some messages were suppressed.](omeditmessagesbrowser:///TestUninitialized?lineNumber=9)
```
This should be ported to the NF as well.

**Comment by perost** [comment]
#9761 adds a check for using uninitialized values in functions, it's not perfect but should be approximately the same as in the OF. #9763 additionally adds a check for uninitialized outputs since the algorithm returns those anyway.

It's a bit inconsistent because the first is just a warning while the second is an error, because that's how they were already defined. Perhaps both should be an error. The specification does say that using an uninitialized variable is an error anyway, and the algorithm is very conservative and shouldn't have any false positives.

**Comment by casella** [comment]
If you are sure that false positives are unlikely, I would make it an error. But we have to be 100% certain about that.

**Comment by perost** [comment]
> If you are sure that false positives are unlikely, I would make it an error. But we have to be 100% certain about that.

It seems we do get one false positive in the library testing, one of the ThermoPower models guards a function from being called with an if-expression. So if we want to allow such functions as long as they're not actually called I guess we need to change it to be a warning instead.
