### ISSUE TITLE
zero delay time creates endless-loop

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9752]
### Description

As shown in https://github.com/OpenModelica/OpenModelica/issues/9131 `delay` with `delayTime=0` is problematic.
The specification is not super clear about this, see https://github.com/modelica/ModelicaSpecification/issues/3287 and https://github.com/modelica/ModelicaSpecification/issues/3245.

With https://github.com/OpenModelica/OpenModelica/pull/9740 the situation improved a bit, but it's still possible to create endless-loops at simulation time.

My suggestion is to stop supporting delay with zero time at runtime (we never supported it) and hope that the next Modelica standard disallows this use of `delay`.

### Steps to Reproduce

For the example from https://github.com/modelica/ModelicaSpecification/issues/3245

```Modelica
model ZeroDelay
  discrete Real delayTime(start = 1.0, fixed = true);
  Real x;
equation
  when time > 2.0 then
    delayTime = 0.0;
  end when;
  x + delay(x^2, delayTime, 1.1) = time;
  annotation(experiment(StopTime = 5.0));
end ZeroDelay;
```

 omc will get stuck in the simulation at `time=2`:

```
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
stdout            | info    | Chattering detected around time 2.0000000003..2.00000000036 (100 state events in a row with a total time delta less than the step size 0.01). This can be a performance bottleneck. Use -lv LOG_EVENTS for more information. The zero-crossing was: delayZeroCrossing(0, 0, x ^ 2.0, delayTime, 1.1) > 0.0
```

### Expected Behavior

Don't get stuck, abort at runtime.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-52-g5f522c32bd-cmake
 - OS: Ubuntu 20.04.5 LTS

**Comment by casella** [comment]
@AnHeuermann maybe completely disallowing zero delay is a bit drastic, see how the discussion in modelica/ModelicaSpecification#3287. IMHO, allowing delayTime to be a zero valued parameter expression is ok, which is exactly what we are supporting now after @perost's last commit.

The case put forth in the above example is interesting, I believe the right solution is to generate a _runtime error_ when delayTime becomes very small or zero. This would still allow to have a zero parameter delayTime, because that will be caught by the NF and will never reach the runtime. On the other hand, if delay makes it to the backend, then it is implicitly assumed that there is a finite nonzero delay and no direct dipendency between input and output of the operator, so this should be checked and generate a proper error if it is not true.

@AnHeuermann, what do you think?

As small value, I'd suggest to take some small positive epsilon (e.g. `eps = 1e-10`) and then assert `delayTime > eps*abs(StopTime - StartTime)` as a threshold for raising this runtime error. This is because there are some simulations in microelectronics with a time span of a few nanoseconds, where a delay of a picosecond would definitely make sense, so a one-fits-all epsilon may not be a good idea.

**Comment by AnHeuermann** [comment]
For now I'll just throw an error at runtime if `delayTime` becomes too small. I'm using the minimum allowed step size (1e-13) for `eps`.

```
assert            | debug   | storeDelayedExpression: delayTime is zero or too small.
|                 | |       | OpenModelica doesn't support delay operator with zero delay time.
```

If we want to support `delayTime=0` we need to have a closer look at our delay implementation again. If nobody needs this feature I would prefer to not spend too much time on this. We can merge my changes and see how many models this affects during the nightly tests.

Also something along
```Modelica
model ZeroDelay
  discrete Real delayTime(start = 1.0, fixed = true);
  Real x;
equation
  when time > 2.0 then
    delayTime = 0.0;
  end when;
  if delayTime <= 0.0 then
    x + x^2 = time;
  else
    x + delay(x^2, delayTime, 1.1) = time;
  end if;
  annotation(experiment(StopTime = 5.0));
end ZeroDelay;
```
seems to work for this example.

**Comment by casella** [comment]
> For now I'll just throw an error at runtime if `delayTime` becomes too small.

LGTM.

>I'm using the minimum allowed step size (1e-13) for `eps`.

I'm fine at using the minimum step size for `eps`. I'm not sure where does 1e-13 come from, though. Could you please check the discussion in the original track ticket #5470? I'm not sure what was the final outcome of that.

We have to make sure that we reasonable values are obtained also in cases such as Modelica.Electrical.Spice3.Examples.Inverter, which has `StopTime=1e-11` and `Interval=5e-15`. If you wanted to add some transmission delay in that model, setting the minimum delay to 1e-13 could not be small enough. 1e-13 seconds is the time it takes to electromagnetic signals to travel 30 micrometers, which is a significant distance in a microchip where the gate size is mesured in a few nanometers. 


> assert            | debug   | storeDelayedExpression: delayTime is zero or too small.
> |                 | |       | OpenModelica doesn't support delay operator with zero delay time.
> ```
> 
> If we want to support `delayTime=0` we need to have a closer look at our delay implementation again. If nobody needs this feature I would prefer to not spend too much time on this. We can merge my changes and see how many models this affects during the nightly tests.
> 
> Also something along
> 
> ```modelica
> model ZeroDelay
>   discrete Real delayTime(start = 1.0, fixed = true);
>   Real x;
> equation
>   when time > 2.0 then
>     delayTime = 0.0;
>   end when;
>   if delayTime <= 0.0 then
>     x + x^2 = time;
>   else
>     x + delay(x^2, delayTime, 1.1) = time;
>   end if;
>   annotation(experiment(StopTime = 5.0));
> end ZeroDelay;
> ```
> 
> seems to work for this example.
