### ISSUE TITLE
Add time to the "Matrix singular!" message

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9811]
### Description
Often OM issues a "Matrix singular!" run-time message, which scares users because does not supply any detail on what this might imply.

I understand that it is difficult to find a way to convey to users, possibly newbies, complicated internal issues.
However, a simple improvement is probably possible: _add to the message the simulation time at which the singular matrix  condition occurs._ 

For instance, it is possible that this message is displayed just once, for t=0 (I suspect this is the case of the example in #9808). In these cases, reading "Singular matrix detected at t=0" gives users more useful information: they can infer that, if the same message does not occur anymore, the simulation results could be correct if they perceive that the singularity at t=0 has not induced significant errors on the initial conditions of the simulation. Or, at least, evaluate what happens at later times, where the effects of possible wrong initial conditions have faded out.
Even in the case in which the message informing that the matrix is singular is displayed several times, having info about the simulation time any of them refers to can at least give a hint on what might be happening.
 

### Version and OS
All versions issued in recent years

**Comment by kabdelhak** [comment]
The relevant files for this are:
`OMCompiler/SimulationRuntime/c/simulation/solver/linearSolverTotalPivot.c:222` 
`OMCompiler/SimulationRuntime/c/simulation/solver/nonlinearSolverHomotopy.c:1156`

There is also a similar message in
`OMCompiler/SimulationRuntime/c/simulation/solver/newtonIteration.c:384`

The time variable is not available at these points, we have to pass them down from the main routine. @AnHeuermann volunteered to do it.

**Comment by casella** [comment]
@ceraolo, upon my request, many years ago we added this message to the runtime output:
```
The initialization finished successfully without homotopy steps / with XX homotopy steps
```
This marks the end of the initialization process. Any message you get _before that_ pertains to initialization, any message _after that_ pertains to simulation. If you set -lv=LOG_INIT, you also get messages marking the various steps of the homotopy transformation, so in case the error is generated during initialization, you can figure out exactly at which point it happens.

I always found "Matrix singular!" (with a Russian-style exclamation mark) a bit frustrating: what's the point of getting this message if I don't know _which_ matrix is singular. But I understood that the low-level linear solver had no clue.

If @AnHeuermann volunteers to improve this, I would suggest to pass down the following information:
- initialization vs. simulation
- value of lambda in case of homotopy-based initialization
- value of time in case of simulation
- number of the linear/nonlinear system involved, as found in the Declarative Debugger

This would make that message far more useful.

**Comment by max-privato** [comment]
Thank you @casella 
So, we already know whether the issue is during initialization or later.

For the rest, any detail could be useful. 
Just "Matrix singular!" seems more like a message from a newly-born program, but now Openmodelica is a mature product. 

If I would ask for just one detail, I would ask for the time at which "matrix "is found singular. My idea is that I should infer from that message that the result obtained at that time could be wrong. Something similar to a lack of convergence. Am I wrong?

Regarding _which matrix_, I imagine that the system under simulation as being represented by a unique n x n matrix, where n is the number of variables and unknowns. So, I never asked myself which matrix is intended to be singular: it is _the_ matrix. Again, Am I wrong?

**Comment by casella** [comment]
> Thank you @casella So, we already know whether the issue is during initialization or later.
> 
> For the rest, any detail could be useful. Just "Matrix singular!" seems more like a message from a newly-born program, but now Openmodelica is a mature product.

Coming of age this year 😄 

> If I would ask for just one detail, I would ask for the time at which "matrix "is found singular. My idea is that I should infer from that message that the result obtained at that time could be wrong. Something having similar effects to a lack of convergence.

Per se getting a singular matrix is not the end of the world. The solver tries a certain step, which may go wrong (e.g. become singular for some reason), but the it can reduce the step size and recover without problems. In other cases, this is not enough and the simulation eventually fails.

> Regarding _which matrix_, I imagine that the system under simulation as being represented by a unique n x n matrix, where n is the number of variables and unknowns. 

Not really. This would be the case if you solved the system with `--daeMode`. Otherwise the solution process is split into two parts: first solving the DAEs for the derivatives, and then using an ODE integration algorithm. The first part (a.k.a "causalization") may require to solve a sequence of multiple algebraic loops of various size. Knowing which one is becoming singular is a crucial piece of information.

**Comment by AnHeuermann** [comment]
> now these messages are identified as warnings (and in omedit will take the warning color, which is more appropriate than the previous red)

It already was a warning. Warnings and errors are displayed red. You can tell if it's only a warning by hovering over it with your mouse. But I guess it should be displayed orange, so I'll open a new issue.
With my changes it will look like this:
![grafik](https://user-images.githubusercontent.com/38031952/205673974-2b6cc622-ea5f-4685-abfe-d5bc6ef9bfb1.png)

> I also wonder whether the sentence "homotopy total pivot", is adequate for the general user or it is something more devoted to programmers and therefore should be visible only when some flag is set.
I'm not sure what understanding is to be supposed for the final user. They probably should be assumed to understand "homotopy", since it is part of Modelica language. The Newton solver also is something maybe is to be assumed to be common culture; regarding "total pivot", it seems more specific to programmers.

There are different places where a matrix could become singular, or a newton iteration us used. I added a method name, so wen find the correct place quicker.

**Comment by casella** [comment]
Thanks @AhHeuermann!
