### ISSUE TITLE
Conditional component with missing variable

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9819]
### Description

If a conditional component uses a undefined variable, but the condition is false, is it still an error?

So for
```modelica
M m(a=a) if false
```
is it an error if `a` is not declared in the scope of that model?

### Steps to Reproduce

```modelica
package MWE
  model M
    parameter Real a = -1.0;
    Real y(start=1, fixed=true);
  equation
    der(y) = a*y;
  end M;

  model CondM
    Real x(start=1, fixed=true);
    //parameter Real a = -10;  // Removed by the library developer
    parameter Boolean useM = false;
    MWE.M m(a=a) if useM;
  equation
    der(x) = -0.5*x;
  end CondM;
end MWE;
```

Simulate `MWE.CondM`:

```
Error: Variable a not found in scope CondM.
```

### Expected Behavior

The component `M` is not part of the model (because `useM=false`) and therefor omc shouldn't care about `a`.
Of course the condition is useless in this case, but maybe there is an additional conditional definition of `a`. Maybe a bit strange but I guess Modelica allows this kind of stuff.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-77-gf539850045-cmake
 - OS: Ubuntu 20.04.5 LTS

### Additional Context

Coming from issue https://github.com/xrg-simulation/SMArtIInt/issues/1.

**Comment by perost** [comment]
It's not entirely clear how valid a deleted component actually has to be, but the specification says: "If the Boolean expression is false the component (including its modifier) is removed from the flattened DAE, and connections to/from the component are removed.".

I interpret that to mean that it should be possible to flatten a conditional component even if it's then deleted, although we do allow some invalid things anyway since libraries use it. Having references to non-existing components is not something we allow though, and it would probably be quite a lot of work to implement support for that.
