### ISSUE TITLE
Strongly non-linear model initialization fails

### ISSUE THREAD

**Issue by matteodepascali** [OpenModelica/OpenModelica#9868]
OpenModelica fails at initializing a strongly non-linear model.
Check with @casella  what may be the issue.

**Comment by casella** [comment]
@matteodepascali, what happened when you tried initializing with a Dymola .mat file solution?

**Comment by matteodepascali** [comment]
I started with the test we were looking at yesterday and if I let OpenModelica resolve the initial equation, initialization fails. If I set also the flag `-iim=false`, the simulation runs smoothly, excluding some assert before concluding initialization regarding molar fractions going below -1e-8 (the limit we set manually to help initialization). 
The same happens for a slightly different configuration (different current generator) which fails initialization if initial equation are solved.

**Comment by casella** [comment]
> I started with the test we were looking at yesterday and if I let OpenModelica resolve the initial equation, initialization fails. If I set also the flag `-iim=false`,

Do you mean  `-iim=none`? The only [allowed values for that flag](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-iim) are `none` and `symbolic`. In that case, it won't be a surprise, because in this case you basically employ the Dymola solution out of the box.

Please try what happens if you don't set `-iim`, so that the imported values are only used as initial guesses but the OMC solver actually runs. It could be interesting to set LOG_NLS_V and see what happens in detail. You should only see one or two iterations.

**Comment by matteodepascali** [comment]
Yes, I confused `none` with `false` while writing the comment!
This is what I tested first: if I just link the result file in the `Equation System Initialization File` option, the initialization fails in the same way as it was failing when we checked it together. It runs 20 iterations, but after 6 of them the value of _error_f_ does not decrease significantly anymore (actually it increases). Below the progression:

Need to damp, error_f =    2.2265551351e+04
Need to damp, error_f =    5.2026864300e+02
Need to damp, error_f =    5.9071384161e+03
Need to damp, error_f =    5.4367274691e+01
Need to damp, error_f =    1.3607369820e+02
Need to damp, error_f =    6.6305032860e+00
Need to damp, error_f =    6.6324275376e+00
Need to damp, error_f =    6.6342948734e+00
Need to damp, error_f =    6.6361089790e+00
Need to damp, error_f =    6.6378731659e+00
Need to damp, error_f =    6.6395904243e+00
Need to damp, error_f =    6.6412634632e+00
Need to damp, error_f =    6.6428947471e+00
Need to damp, error_f =    6.6444865250e+00
Need to damp, error_f =    6.6460408561e+00
Need to damp, error_f =    6.6475596310e+00
Need to damp, error_f =    6.6490445903e+00
Need to damp, error_f =    6.6504973413e+00
Need to damp, error_f =    6.6519193709e+00

**Comment by casella** [comment]
Hmm, this is weird. If you import the start values from the Dymola solution, the first evaluation of the norm of the residual should not be 2.2265551351e+04. Or maybe that's precisely the problem, that there is some error in the generated code, so that a residual that should be close to zero actually isn't. We need to understand where we stand.

Can you compare the values of (a few of the) iteration variables shown by LOG_NLS_V before the first iteration with those of the Dymola result, to check if they match?

**Comment by matteodepascali** [comment]
I further investigated OpenModelica's behavior, turning on also `LOG_INIT_V`.
The log shows in the heading that the `-iff` flag is active with the correct .mat file path. 

Start values are first updated to the ones included with the `start` attributes of the model.
_updated start value: module[9].anodeChannel.Tout(start=1173.15)_

Then after the following line of text:
_import start values file: path_to_res_file.mat_ 
it says
_import real variables_
and it lists all the variable to which it assigns a value from the .mat file.
For example:
_| module[9].anodeChannel.Tout(start=1305.09)_

The new start value is coherent with the one from the .mat file.

When the solver starts with the system that fails initialization, the same variable is not reported with the .mat value:

_initial variable values:_
_module[9].anodeChannel.Tout  = 1173.15 nom = 1000_

When the non-linear solver starts it prints
_module[9].anodeChannel.Tout  =        1173.2167   nom =          1173.15   min =                0   max =   1.7976931e+308_

and then the first iteration happens
_module[9].anodeChannel.Tout  =        1223.6541   step =        50.437427   old =        1173.2167_

This happens also for other temperatures and molar fractions.

A less complicated model, that initializes succesfully with not so accurate start values, shows the same behavior when trying the initialization with its own result file.

**Comment by casella** [comment]
@matteodepascali do you mean that the `-iif` values are basically ignored?

**Comment by casella** [comment]
There are some features that are just fragile, one is profiling, which got broken many times, and the other one is this loading of previous simulation results. I guess we are not testing them enough in the testsuite, so we don't catch commits that break them...

@matteodepascali could you please try go through the example shown in the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/solving.html#importing-initial-values-from-previous-simulations), and check whether the imported value is retained or not?

**Comment by matteodepascali** [comment]
I tested the User's Guide example introducing homotopy:
```modelica
homotopy((v1 - 3)*(v1 + 10)*(v1 - 15), (v1 - 3.3)*(v1 + 10.1)*(v1 - 15.2)) = 0;
```
The solver behaves correctly:
- model M solves $\lambda=0$ initialization, finds v1=15.2 and then goes on until at $\lambda=1$ it converges to v1=15.
- model M2 imports correctly the start values from the .mat files and has v1= 3.3 for $\lambda=0$  and reaches the expected value of v1=3 at $\lambda=1$

So it seems homotopy is not causing any issue, at least for this example.

**Comment by casella** [comment]
@mahge I think we need your help here. I summarize the story for your convenience.
- We have a tough initialization problem for a thermal power generation system model
- Dymola solves it successfully, starting from the given start attributes
- OMC does a first undamped Newton step on it and then ends up stuck in a local minimum of ||f(x)|| from which it cannot escape
- We tried to set the initial guesses of the iteration variables to the solution found by Dymola using`-iif` and `-iim=none`, to check if the residuals are actually zero there, or if we have a problem with code generation that leads to wrong residual C functions; unfortunately, LOG_NSL_V reports the solver starting from the start values instead of the imported values
- The behaviour with `-iif` and `-iim=none` on simple example cases (including ones with homotopy) is the expected one, i.e., the first iteration of Newton's algorithm when solving initial equations starts from the imported values, not from the start values.

At this point the only way to solve this issue is to run the simulation which is not importing the values correctly using gdb, and figure out why it does that. 

BTW, I suspect that something like this could be going on in other tough initialization cases where we are running into trouble in a similar way, so I think it's important that we figure this out.

If @matteodepascali sends you the smallest model he has that shows this unwanted behaviour, could you try doing that and report?

Thanks!

**Comment by piwi447** [comment]
Hello, 
I am a modelica newbie and started wit OpenModelica before to work on convincing my company to buy a dymola licence. I am working on strongly nonlinear model involving gasmixture, heating, cooling, control of molar fractions and volume pressure.

I am able to build my model but Initialisation seems very sensitive and take generally a very long time compared to simulation itself. I tried different solution to avoid inilialisation like resimulate or starting from result saved in a previous simulation, but it does not work. 
 Resimulate from a Time > 0 does not read initial value  from the previous result as i showed it on this link   https://stackoverflow.com/questions/75650137/modelica-hnx-mixing-simulation-initial-mass-fraction-as-input-or-parameter

Last week i also tried saving a result file, rename it as "initial.mat" and declare it in the init file on the OMEdit simulation configuration GUI but without more success. I got some error message ("unable to read value..." for each variable. 

This seems to be link with the case exposed here before? 

I am using the following OM version :  OpenModelica v1.20.0 (64-bit)
Connected to OMSimulator v2.1.1.post188-gaf996ad-mingw

**Comment by casella** [comment]
@piwi447 would you mind opening a separate ticket? This one regarded a specific model. It would be nice if you could also attach some test case that we can reproduce ourselves. 

Regarding using results to initialize a simulation, please check the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/solving.html#importing-initial-values-from-previous-simulations).

Thanks!

**Comment by piwi447** [comment]
I will check how to do this in an interesting form. Regarding the initialization, I applied the user guide but it did not work as expected. Yesterday I tried to reproduce it on a smaller model that I can share easier  but unfortunately, I did not get the same behavior, the result file were read without error message  but the initialize is still not starting from the read values. I will dig more before create an new issue. What is the maximum size of a model to be shared as proof of failure.

**Comment by casella** [comment]
> I will check how to do this in an interesting form. Regarding the initialization, I applied the user guide but it did not work as expected.

One option you have to share a failing model is to do a Save Total with obfuscation. This saves all the bits and pieces of Modelica that are required to build the model in one single .mo file that you can inspect, garbles up variable and parameter names, and removes all comments and documentation information. In most cases this is garbled enough to protect your IP.

>What is the maximum size of a model to be shared as proof of failure.

No limits 😄 

Of course the smaller, the better, but for many initialization problems, the size is a key ingredient, as you have discovered yourself.

**Comment by casella** [comment]
I guess this problem became stale in the meantime, as we have developed further simplifications to avoid getting such huge nonlinear models in the first place.
