### ISSUE TITLE
Problem to use OMC 1.20

### ISSUE THREAD

**Issue by jpducreux** [OpenModelica/OpenModelica#9899]
Hi,

I'm working on Windowds 10 with openmodelica 1.20. The installation does not indicate any problem. 

But when I'm starting OMC from Windows Menu some error messages appear in "All" tab :
```
[1] 17:39:35 Traduction Notification
[D:/OpenModelica1.20.0-64bit/share/omlibrary/cache/index.json: 0:0-0:0]: Cached libraries were found and will be installed into C:/Users/jprdu/AppData/Roaming/.openmodelica/libraries/.

[2] 17:39:35 Erreur
Failed to open file: C:/Users/jprdu/AppData/Roaming/.openmodelica/cache/c11123102e94d4b5acb139331a6d85f45d8adcc0.zip

[3] 17:39:35 Ecriture Notification
After extracting C:/Users/jprdu/AppData/Roaming/.openmodelica/cache/c11123102e94d4b5acb139331a6d85f45d8adcc0.zip, C:/Users/jprdu/AppData/Roaming/.openmodelica/libraries/Complex 4.0.0+maint.om/package.mo does not exist. Removing the failed installation.
```
I can not use any .mo .

Thank you for your help

**Comment by adeas31** [comment]
@perost @sjoelund any idea what is going wrong?

**Comment by jpducreux** [comment]
It seems that no Modelica Library has been loaded

**Comment by casella** [comment]
A colleague of mine (@carlods) reported the same problem today. I suggested to empty the .openmodelica directory `(%APPDATA%/.openmodelica under Windows)` that was probably corrupt, and then everything worked fine. No idea why this happened though, I installed and uninstalled 1.20.0-beta many times with and without pre-installed package manager libraries and never had a problem.

**Comment by perost** [comment]
A possible solution would be to just install the libraries manually using the package manager (File->Manage Libraries->Install Library). OM will only try to install the cached libraries if the user library folder is empty, so the issue should go away once some libraries are installed.

But the `c11123102e94d...` hash is not one of the hashes in the cached package index that we install with the 1.20 release, and it's not in an updated `index.json` either. It seems to be an old hash for a MSL 4.0.0 release.

I checked the code, and we definitely only check for the cached `index.json` file in the `share/omlibrary/cache/` folder. It will also check for the cached zip-files in that same folder but then falls back to checking in the user library folder, so that explains why it points to that folder in the error message.

One possibility would be that the `index.json` file is left over from an older installation, we might have used that hash in one of the beta releases perhaps. But I'm not sure how that could happen. I tried the 1.20 installer for Windows (with Wine on Linux, but shouldn't matter) and it wouldn't let me install again without uninstalling first, and then the `index.json` was deleted as it should.

So I don't know, maybe some issue when updating from a 1.20 beta to the final release, maybe the installer doesn't detect the old installation and overwrites it without replacing the `index.json` file? Seems unlikely, but that's the only thing I can think of.

**Comment by perost** [comment]
I tried installing the nightly build from nov 2 with the expectation that it would be the first one that installs the cached files to the current folder, but it still used the old folders from before the changes by @sjoelund. I guess the Windows installer was updated a bit later.

But even then the `index.json` contained the hashes we still use, so there shouldn't be any Windows installer that contains `c11123102e94d...` and installs the `index.json` to the folder we now use.

**Comment by casella** [comment]
@jpducreux did you try cleaning up the .openmodelica directory?

**Comment by niklwors** [comment]
@casella  We also had that problem and your tip helped us.

**Comment by casella** [comment]
Maybe we should have saved them to do some post-mortem analysis on them. If it happens on some other installations @BR, could you just zip the content of the library and send it to us?

**Comment by benlandg** [comment]
I had the same issue with 1.20 and windows Yesterday. I tried @casella  solution but it did not seem to have effect. 
As suggested by @perost  I installed the Modelica package in OMEdit and after restarting, it works as expected.

**Comment by casella** [comment]
All's well that ends well.

We understand there are probably some glitches left in the whole package management thing. Unfortunately, if we have no way to replicate them, it is difficult to fix them for good. I'm going to close this ticket, we can reopen it in case it happens again and/or we can get enough information to replicate the problem and analyze it on our own.
