### ISSUE TITLE
Build fails: error: pthread: linker input file not found: No such file or directory

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#9903]
[openmodelica-1.20.0.log](https://github.com/OpenModelica/OpenModelica/files/10194400/openmodelica-1.20.0.log)

clang-14
FreeBSD 13.1 STABLE

**Comment by yurivict** [comment]
'pthread' library should be turned on by adding the flag ```-pthread```, not by adding such library as dependency.

**Comment by mahge** [comment]
I suspect this is caused by Fortran compilation in MUMPS (used in coinor-Ipopt) code setting `pthread` instead of `-pthread`. We took it from https://github.com/rjodon/coinor-ipopt-with-cmake/blob/664b2172da0b0985ad909fa60f8e29d594cfa3ec/ThirdParty/CMakeLists_mumps.txt#L291 and adjusted it. 

You can find the relevant code in `OpenModelica/OMCompiler/3rdParty/Ipopt-3.13.4/ThirdParty/MUMPS/CMakeLists.txt` lines 145-150. Maybe you can adjust them and see what happens.

In the meantime it will help if can you give me the system information that cmake dumps for your build directory.

```cmake
cd <build_dir>
cmake --system-information > system_info.txt
```

**Comment by mahge** [comment]
I suggest trying 
```diff
- target_compile_options(coinmumps PUBLIC pthread)
+ target_compile_options(coinmumps PUBLIC ${CMAKE_THREAD_LIBS_INIT})
```

As the original one looks unusually specific.

**Comment by yurivict** [comment]
This helped to get over this error. Thank you.
