### ISSUE TITLE
size of Force Vectors on 1.20.0

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#9949]
### Description
On latest release 1.20.0 the force vectors dont change their size when zooming in the animation 3D view.

### Steps to Reproduce

Select a modelica 4.0.0 example such as Mechanics/MultiBody/Examples/Elementary/ForceAndTorque and zoom into animation window, the force has always the same screen size.

### Expected Behavior

Forces must have the same relative size.

### Screenshots

![image](https://user-images.githubusercontent.com/93596576/207914645-384ef6cf-5c14-47b3-8485-c49a9ebcfd04.png)

![image](https://user-images.githubusercontent.com/93596576/207914726-a6a369b1-206a-48e7-98b0-c2f6be2ab105.png)

### Version and OS

 - OpenModelica Version: 1.20.0
 - OS:  Windows 10, 64 bit
 - Modelica 4.0.0

**Comment by casella** [comment]
@anotheruserofgithub, would you like to take care of this issue? 

Thanks!

**Comment by BasilioPV** [comment]
UPDATE: The behaviour is correct on Modelica Standard Library 3.2.3 using OMedit 1.20.0. But on MSL 4.0.0 does not work.

**Comment by BasilioPV** [comment]
Yes, I raise this Issué :-)

**Comment by anotheruserofgithub** [comment]
Hello @BasilioPV,

Thank you for opening this ticket!
In fact this behavior is intentional.
Please refer to https://github.com/modelica/ModelicaStandardLibrary/issues/3931#issuecomment-1016347058, modelica/ModelicaStandardLibrary#3931, modelica/ModelicaStandardLibrary#3934, modelica/ModelicaStandardLibrary#3991, #9075, #9389, #9428, #9390 so that I do not have to explain all the details here.

For the record: If I am not mistaken, there used to be some parameters to control the display of arrows that MSL 4.0.0 removed or deprecated, in a way that is not very clean nor clear yet.
So now it is up to the Modelica tools to decide how to scale vectors' radius and length.
There are some good reasons for this change, but it also raises two big problems in my opinion:
- Cross-compatibility between tools is deteriorated in this regard, although I understand that this concerns 3D animation for the purpose of displaying vector quantities which do not represent physical length (except for relative position) and thus can be scaled arbitrarily.
But this is the bottom line: Instead of an arbitration by the Modelica standard, it has become an arbitration by the Modelica tools.
- From an implementation point of view: How to determine proper scales so that they will look good for all use cases?
You could argue that there still exist two parameters in the [World](https://github.com/modelica/ModelicaStandardLibrary/blob/maint/4.0.x/Modelica/Mechanics/MultiBody/package.mo#L140-L145) model that can be used at least as default values (although to me they seem to be leftovers), but they only refer to force and torque, thus leaving out the other kinds of [VectorQuantity](https://github.com/modelica/ModelicaStandardLibrary/blob/maint/4.0.x/Modelica/Mechanics/MultiBody/Types/VectorQuantity.mo#L2-L9) anyway (linear/angular velocity/acceleration).

Therefore, not only do tools choose vector scales differently, but also they can never be smart enough to fit any possible use case that might come up, and the user usually has their own opinion or wishes on the matter.
And so you end up with each Modelica tool providing its own custom way to actually let the user specify the scales by themself (at least Dymola and in a near future OpenModelica), because they were removed from the library in the first place—it is a bit silly, is it not?

Now, to get to the point: For OpenModelica I implemented two configurable heuristics for choosing radius and length scales, along with two rendering features, namely zoom-invariant and drawn-on-top vectors.
The latter are the behaviors that you are referring to in this ticket.

My reasoning was more or less as follows:
Vectors are meant to represent physical quantities, hence their value can be appreciated from their length.
In addition, it should be made easy to visually compare vectors between them, meaning, by looking at their relative length.
Therefore it should be required to always be able to see both the head and the tail of every vector, unless it points perpendicular to the screen.
There is also the difficulty that vectors usually change position and length (coordinates) during simulation, and so they may disappear outside the animation window.
All these requirements have been handled at initialization in the heuristic for length scale (again, this would probably need to be customized for each use case).
However, it also means that vectors should remain entirely visible irrespective of the zoom factor, so a vector of constant quantity should keep the same length on screen when zooming.
But zoom invariance is usually not enough since vectors would become smaller than other shapes when zooming in the window, and could thus become invisible behind or inside these shapes (which can also happen without zooming, obviously, but this effect is even more pronounced when zooming).
This has been counteracted by drawing vectors on top of all other shapes.

Of course I am aware that these two behaviors, zoom invariance and drawing on top, are not always intuitive and maybe not desired by some users.
There is also the fact that by drawing vectors on top of everything else, the sense of perspective is kind of lost sometimes.
This is why I plan to introduce vendor-specific annotations in the next release 1.21.0 (hopefully), to let users customize all those things.

But I am still not completely sure what should be the default, though.
In your opinion, does the reasoning above make enough sense to keep the default options as they are now, or do you think we should change something?
I am happily open to suggestions, as long as they can be applicable to the broader audience rather than to a particular user.

If you are not in too much of a hurry, you can just wait for us to add the above-mentioned vendor-specific annotations.
Else if you would like to play around with those settings now and are able to compile the code, you can enable or disable heuristics and features [here](https://github.com/OpenModelica/OpenModelica/blob/maintenance/v1.20/OMEdit/OMEditLIB/Animation/Vector.h#L72-L75), and you can tune parameters for heuristics [here](https://github.com/OpenModelica/OpenModelica/blob/maintenance/v1.20/OMEdit/OMEditLIB/Animation/Visualization.cpp#L742-L749).
Of course I can guide you if the [documentation](https://github.com/OpenModelica/OpenModelica/blob/maintenance/v1.20/OMEdit/OMEditLIB/Animation/Visualization.cpp#L670-L733) is not enough for you to understand how this works, as it is a bit cumbersome.
I can also prepare a commit in a dedicated branch of my fork if you tell me what configuration you would like to try.
If you cannot compile OMEdit by yourself, I can send you the executable if you have a x86 Linux available, otherwise maybe someone could prepare a Windows build for you.

**Comment by BasilioPV** [comment]
Hello @anotheruserofgithub !
Thanks for your explanation, it makes me think on what I want. I will play with some of my models in order to get knowledge about these considerations. By now I will close thus issue and research on this matter.
Thanks for your time and work!

**Comment by anotheruserofgithub** [comment]
Great! Let me know in #9390 if you have particular wishes.

By the way, for comparison you can use a [RelativePosition](https://github.com/modelica/ModelicaStandardLibrary/blob/maint/4.0.x/Modelica/Mechanics/MultiBody/Types/VectorQuantity.mo#L9) vector which behaves like a pre-4.0.0 arrow, without the need to recompile OMEdit.
