### ISSUE TITLE
The NF with --newBackend misses equations in ScalableTestGrids

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9952]
@perost, please check the [newInst-newBackend ScalableTestGrids report](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestGrids_noopt/ScalableTestGrids_noopt.html).

All models fail at the end of the NF because some variables are lost along the road, leading to an unbalanced system with more equations than variables. You can check that on the smallest one, [Type1_N_1_M_1](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestGrids_noopt/files/ScalableTestGrids_noopt_ScalableTestGrids.Models.Type1.Type1_N_1_M_1.err), which fails with
```
Error: Too many equations, over-determined system. The model has 2028 equation(s) and 1416 variable(s).
[/home/hudson/saved_omc/libraries/.openmodelica/libraries/ScalableTestGrids 1.0.0-master/Components.mo:35:5-36:43:writable] 
Error: GEN_1_1.GEN.terminal.v.re = GEN_1_1.terminal.v.re has size 1 but 0 variables ()
```

**Comment by casella** [comment]
The models flatten correctly without --newBackend, see [report](https://libraries.openmodelica.org/branches/master/ScalableTestGrids_noopt/ScalableTestGrids_noopt.html), so it's some issue with array connect handling, I guess.

**Comment by perost** [comment]
It doesn't seem like any variables are lost. I fixed `checkModel` in #9959 which previously assumed every variable had a size of 1, now it counts the variables size instead. With this fix I get 1920 variables, same as when scalarizing, but there are still too many equations (2328 since the size of variable bindings are also taken into account now).

This doesn't change the error from above though, since the backend doesn't use `checkModel` but has its own counting. But at least it clarifies that its the number of equations that's the issue. We should probably fix the backend counting too, but I'm not sure how and it wouldn't fix the actual issue anyway.

I also tried disabling the array connection stuff and just scalarizing everything, but got the same result. So it might not be related to connections at all, but I don't really know where the extra equations are coming from. Please let me know if you find a smaller model with the same issue, it would help a lot to have fewer equations to check.

**Comment by casella** [comment]
Unfortunately it seems there are no other cases in libraries such as MSL or Buildings where this happens.

I will try to remove connected components from Type_1_N_1_M_1 so that you can get the same wrong behaviour with less equations. The resulting model will probably have no solution, but the NF doesn't care about that.

**Comment by casella** [comment]
As a starting point, I tried to run checkModel on PowerGrids.Electrical.Test.OneBusOneLoad with flags `-d=newInst,-frontEndUnitCheck --newBackend`. With the latest nightly I got
```
Check of PowerGrids.Electrical.Test.OneBusOneLoad completed successfully.
Class PowerGrids.Electrical.Test.OneBusOneLoad has 95 equation(s) and 59 variable(s).
46 of these are trivial equation(s).
```
while the output without those flags is
```
Check of PowerGrids.Electrical.Test.OneBusOneLoad completed successfully.
Class PowerGrids.Electrical.Test.OneBusOneLoad has 83 equation(s) and 83 variable(s).
36 of these are trivial equation(s).
```
In fact, #9959 is not yet merged in, so I don't know what the result would be with that. I guess you would get 83 variables but still 95 equations. I guess this would be much easier to debug.

**Comment by casella** [comment]
The flat OneBusOneLoad models seem to be identical with and without `--newBackend`, which is reasonable since there are no arrays involved, so it really just seems an issue with something triggered by `--newBackend`, which is not `-d=nonfScalarize`, which doesn't change anything. Probably something fishy with record equations.

I also have a stripped down version [Type1_N_1_M_1.mo.txt](https://github.com/OpenModelica/OpenModelica/files/10253754/Type1_N_1_M_1.mo.txt)
with 386 equations instead of 1920, but I guess OneBusOneLoad is good enough already for debugging, and it's much smaller.
