### ISSUE TITLE
Slow performance of the NF when flattening ScalableTestGrids models with --newBackend

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9955]
[This report](https://libraries.openmodelica.org/branches/master/ScalableTestGrids_noopt/ScalableTestGrids_noopt.html) shows the performance of the NF on ScalableTestGrids when using scalarized flattening. The time spent flattening the model is roughly proportional to the size. The largest model the CI can handle without running into the CI timeout guillotine has about 210000 equations and takes 75 seconds, so it takes about 0.35 ms per equation on average.

If you now check the [performance with --newBackend](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestGrids_noopt/ScalableTestGrids_noopt.html), the time spent is still roughly proportional to the number of equations, but is now about 0.55 ms per equation on average. BTW, the number of reported equations and variables is wrong, but that's another story, see #9952.

I'm not sure why it should take _more time_ to handle the model when scalarization is not performed. For example, if you check Type1_N_8_M_4, NF.instantiate takes 24 s instead of 18 s, NF.collectFunctions takes 13 s instead of 1.3 s, NF.verifyModel takes 23 s instead of 13 s.

@perost can you please check and report?

Eventually, these models should be passed to the new backend with the -d=mergeComponents,vectorizeBindings feature. The goal will be to handle models that have a few million equations, and for them, we have a total 15 minutes budget to parse them, generate the code and run the simulation, so we can't spend more than about 150 s on the frontend. This requires reducing the time spent by the NF by about one order of magnitude, to about 0.02-0.05 ms per equation. I hope that merging components into arrays allows to drastically reduce the flattening time, since many operations will be carried out once on arrays instead of many times.

I'll try to set up the testing of that feature on the CI ASAP, so we can start to get some feedback on the performance.

**Comment by perost** [comment]
I think that's just variance due to running many models at the same time when doing the library tests, when I try them locally they perform the same at least during the early phases. Which they should, since it's only from `NFFlatten.flatten` and onwards that the scalarized and non-scalarized paths diverge.

The only thing that seem to differ a lot is that `NFVerifyModel.verify` is reported as much slower when using the new backend, but this is actually misleading. The issue is the part before:
https://github.com/OpenModelica/OpenModelica/blob/bd9195fd05372a7d765ff6a492366f85f5d14215/OMCompiler/Compiler/NFFrontEnd/NFInst.mo#L208-L215
I.e. when using the new backend we do some extra processing, but since there's no execStat call for that the time is included in the next call instead which is `NFVerifyModel.verify`. I haven't really looked closely at this code, but maybe it's possible to improve it. Maybe @kabdelhak already knows if there are some things that could be improved.

**Comment by perost** [comment]
> @perost in the meantime could you add and ExecStat item for this extra processing? That would make keeping track of performance easier.

Sure, added in #9957. I added two since I'm not sure what to call the whole thing, `combineBinaries` and `replaceArrayConstructors` (on second thought maybe that wasn't the best name, I guess @kabdelhak can rename them if he can think of better ones). Looks like it's the second one that's the slowest, but they're both a bit slow.

**Comment by casella** [comment]
The issue was clarified with additional reporting by `-d=execstat`, so this ticket can be closed.
