### ISSUE TITLE
Environment issue for Google Colab

### ISSUE THREAD

**Issue by lambtt** [OpenModelica/OpenModelica#9987]
### Description

Howdy, I tried to utilize Google Colab in my workflow.

Since I meet some issue (see https://github.com/OpenModelica/OpenModelica/issues/9330) to use "cross build" in my amd64-windows system, I installed a virtual machine for amd64-linux system, which could succuessfully export the FMU.

I installed PyFMI in Colab and uploaded this amd64-linux FMU file (Modelica_Blocks_Examples_PID_Controller). 

But when I load this FMU, I meet the issue shown in the figure below.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/91109801/209458610-3835efc0-c986-4b35-9ece-437f2dd0f811.png">

I wondered if that's because the link was dynamic. I added a compiler flag "--linkType=static" in the <options-simulation-Additional Translation Flags>.

But the issue still existed.

I tried to upgrade the GLIBC in Google Colab's OS.

Because Colab uses Ubuntu 18 as OS, the newest version of GLIBC could only be 2.27.

I'm wondering if it is necessary to install GLIBC 2.29.

I'm also wondering if there is any option to modify so I could run the FMU in Colab without a version of 2.29. 

### Expected Behavior

The FMU could be simulated in Google Colab.

### Version and OS

 - OpenModelica Version: 1.20.0, stable
 - OS: Ubuntu 18, AMD64
 - Versions of used Modelica libraries if applicable: Modelica_Blocks_Examples_PID_Controller (Modelica Standard Library 4.0.0)

### Additional Context

Options for exporting FMU: 
- Version: 2.0.
- Type: Co-simulation 
- Platforms: Native
- Solver for Co-Simulation: CVODE
- Model Description Filters: None
- Include Modelica based resources via loadResource: Yes
- Include Source Code: No
- Generate Debug Symbols: No

I appreciated any hints, and thanks for your help!

**Comment by AnHeuermann** [comment]
Maybe you where using the stable version instead of the nightly version? Or glibc was updated on the Google machine? Or you used a different image with the matching library version.

In any case the stable version of omc is different with the CMake FMU cross-builds, so no wonder that one is still failing.

**Comment by AnHeuermann** [comment]
In that case you are cross-compiling for a target system (Read Hat) that could be quiet different than the host system (Ubuntu 18). But I'm way out of what I'm usually doing for cross-compilation.

If this works it's fine, but I would recommend to use [`--fmuruntimedepends=all`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmuruntimedepends) if the systems are that different.
This will include all host system libraries used by the FMU, so on the target machine these will be used instead of the target system ones. But expect undesired behavior if something you didn't expected to be different. E.g. if the size of some data types is different on target and host system all sort of things could happen. The easiest approach is probably to use a Docker image with the same OS as on the target machine. Could be difficult for Red Hat, though.

**Comment by AnHeuermann** [comment]
`--fmuruntimedepends=all` is a translation flag, so you need to add it in Options->Simulation->Additional Translation Flags

![grafik](https://user-images.githubusercontent.com/38031952/212045152-4d5fe848-2294-4231-8bf7-b4a060ce52a5.png)

If this flag is useful for more people / the CMake FMU build is used more we will probably add these settings to the GUI.
