### ISSUE TITLE
Unable to load a 3.2.3 file with OM 1.20.0

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9996]
### Description
I have OM 1.20.0 installed, with as default MSL 4.0.0:
![image](https://user-images.githubusercontent.com/7373030/210393219-01ce86ca-c04f-4314-9357-4d471929818f.png)

If I try to load the following file:
[stPSDPkgUpd.mo.txt](https://github.com/OpenModelica/OpenModelica/files/10337933/stPSDPkgUpd.mo.txt)

OMEdit sends this message:
![image](https://user-images.githubusercontent.com/7373030/210392553-7268eb13-b786-41dd-bd6b-87f9f4767bbf.png)
If I click on Unload & reload all, it keeps showing the same message over and over again, and I cannot load the file.

Even if I set as default MSL 3.2.3: 
![image](https://user-images.githubusercontent.com/7373030/210393084-bc7e4832-4bf9-4be7-9a3d-fae5056223a4.png)

I still cannot open that file and get over and over the same message asking reloading!

### Expected Behavior
1) When I set MSL 4.0.0 as default, try to load a file requiring MSL 3.2.3, click on unload and reload, OMEdit should unload MSL 4.0.0, load 3.2.3, then load my file
2) When I set MSL 3.2.3 as default, try to load a file requiring MSL 3.2.3, the message "unload & reload" shoul not appear, and everything should go smoothly

OM version: WIndows, 64 bit.

**Comment by ceraolo** [comment]
The issue is due to the following row:
    uses(Modelica(version = "3.2.3"), EHPTlib(version = "default"), Complex(version = "3.2.3")),
and disappears if I change it into:
    uses(Modelica(version = "3.2.3"),  Complex(version = "3.2.3")),

The behaviour is bad and scary, but I don't think it is significant for the general users, so I'm going to close this ticket.

**Comment by casella** [comment]
@ceraolo I'd like to figure out what is going on here anyway. Can you please post the version annotation of library EHPTlib?

**Comment by ceraolo** [comment]
ok.
Steps to get  the strange behaviour:
1) copy the following file  [EHPTlib 2.1.0.mo.txt](https://github.com/OpenModelica/OpenModelica/files/10340108/EHPTlib.2.1.0.mo.txt)
 (the mo) in C:\Users\USERNAME\AppData\Roaming\.openmodelica\libraries, using the right USERNAME
2) try to load stPSDPkgUpd.mo file I posted today, e.g. dragging it onto OMEdit 1.20.0

**Comment by perost** [comment]
The issue is that the provided model uses MSL 3.2.3 while EHPTlib uses MSL 4.0.0, so regardless of which MSL is loaded it will be wrong. So to solve that issue you'd need to either upgrade your model to 4.0.0 or use an older version of EHPTlib.

However, it seems OMEdit doesn't handle this situation well, I guess it ends up in a loop of switching MSL versions between 3.2.3 and 4.0.0 when trying to satisfy all the dependencies. I'm not sure if that's an OMEdit issue or if there's something the compiler can do, I'll leave it to @adeas31 to investigate.

**Comment by casella** [comment]
@ceraolo, the problem is that the current package loader is greedy, and it just loads what it sees from the uses annotations. If they are inconsistent, it may as well end up in an endless loop.

To avoid that, the loader would have to become much smarter, basically building a dependency graph, checking that it has not inconsistency, and report that if it happens.

I opened #10055 about that, since the issue has much broader impact than this specific example.
